-- R__seed_permissions.sql — canonical RBAC permission catalogue (Flyway REPEATABLE migration).
--
-- WHY REPEATABLE: permissions + their ORG_ADMIN grants are CONVERGENT reference data — the table
-- should always equal this list. A repeatable migration re-runs whenever this file's checksum
-- changes and runs AFTER every versioned migration, so adding/renaming a permission is a one-line
-- edit here that CONVERGES on the next migrate, instead of an append-only Vn migration that can only
-- add rows (the trap that left dead SALES.POS.* codes behind after the V43->V83 fix — now gone).
--
-- SAFE TO BE REPEATABLE (unlike per-company CoA/gl_configs seeds, which are FK'd by later versioned
-- migrations and MUST stay inline): nothing in the schema references a permission row at migrate
-- time. The role_permission FK is satisfied because this file inserts permissions before granting.
--
-- The ORG_ADMIN role row itself is created in V1 (foundational); this file only fills its grants.
INSERT INTO permissions (code, module, description) VALUES
    ('AGENT.MANAGE', 'parties', 'Create, update and archive sales agents'),
    ('AGENT.VIEW', 'parties', 'View and select sales agents'),
    ('AP.BILL.ENTER', 'ap', 'Enter a supplier bill (BILL-####) and edit its draft lines'),
    ('AP.BILL.MATCH', 'ap', 'Run / accept the 3-way match; accept an over-tolerance variance'),
    ('AP.DEBITNOTE', 'ap', 'Raise a debit note / adjustment against an open payable'),
    ('AP.OPENING.SET', 'ap', 'Enter AP opening balances at go-live'),
    ('AP.PAYMENT.RUN', 'ap', 'Pay a single bill and run a payment run (PAYRUN-####)'),
    ('AP.VIEW', 'ap', 'View the AP sub-ledger, balances, ageing, and the reconciliation read'),
    ('APPROVALS.ADMIN', 'approvals', 'Recall/cancel any approval request; override a stuck chain'),
    ('APPROVALS.DECIDE', 'approvals', 'Approve/reject approval-request steps and see the approvals inbox'),
    ('APPROVALS.POLICY.MANAGE', 'approvals', 'Create/edit/deactivate approval policies and their step chains'),
    ('APPROVALS.POLICY.VIEW', 'approvals', 'View approval policies'),
    ('APPROVALS.REQUEST.VIEW', 'approvals', 'View approval requests'),
    ('AR.CREDITNOTE', 'ar', 'Raise a credit note that reduces a customer receivable'),
    ('AR.DISPUTE.MANAGE', 'ar', 'Mark/clear an AR invoice as disputed or on-hold and manage dunning state (D-5)'),
    ('AR.INVOICE.VIEW', 'ar', 'View AR open items (the receivable detail)'),
    ('AR.OPENING.SET', 'ar', 'Enter AR opening balances at go-live'),
    ('AR.RECEIPT.ALLOCATE', 'ar', 'Allocate or re-allocate a receipt across open items'),
    ('AR.RECEIPT.RECORD', 'ar', 'Record a customer receipt (RCT-####) and post its cash leg'),
    ('AR.STATEMENT.VIEW', 'ar', 'View or print a customer statement'),
    ('AR.VIEW', 'ar', 'View the AR sub-ledger, balances, ageing, and the reconciliation read'),
    ('AR.WRITEOFF', 'ar', 'Write off an uncollectable open item (bad debt)'),
    ('AUDIT.VIEW', 'iam', 'View the IAM audit trail'),
    ('BI.CRM.VIEW', 'bi', 'View the CRM panel (pipeline value, win-rate, forecast KPIs)'),
    ('BI.EXPORT', 'bi', 'Export the dashboard to PDF / Excel / CSV'),
    ('BI.FINANCE.VIEW', 'bi', 'View the finance panels (revenue/net-profit trend, AR/AP, cash, working capital)'),
    ('BI.OPS.VIEW', 'bi', 'View the operations panels (inventory value, stock health)'),
    ('BI.VIEW', 'bi', 'View the BI / analytics dashboard (the coarse gate for the dashboard route)'),
    ('BOM.MANAGE', 'products', 'Create, edit drafts, add/remove components, activate, archive and clone BOMs'),
    ('BOM.VIEW', 'products', 'View, list, explode, where-used and cost-roll-up for Bills of Materials'),
    ('BRANCH.ASSIGN', 'iam', 'Assign users to branches and set their default branch'),
    ('BRANCH.MANAGE', 'iam', 'Create, update, set-default and archive branches'),
    ('BRANCH.VIEW', 'iam', 'View branches'),
    ('BUDGETING.BUDGET.APPROVE', 'budgeting', 'Approve or reject a submitted budget version'),
    ('BUDGETING.BUDGET.MANAGE', 'budgeting', 'Create budgets; create/edit versions and lines; seed/re-plan'),
    ('BUDGETING.BUDGET.SUBMIT', 'budgeting', 'Submit a budget version for approval; recall a submitted version'),
    ('BUDGETING.BUDGET.VIEW', 'budgeting', 'List and view budgets, versions, and lines'),
    ('BUDGETING.REPORT.EXPORT', 'budgeting', 'Export variance and departmental reports to CSV'),
    ('BUDGETING.REPORT.VIEW', 'budgeting', 'Run the budget-vs-actual variance report and departmental actuals'),
    ('CASH.ACCOUNT.MANAGE', 'cashbank', 'Create/edit/deactivate a cash/bank account, set its GL link, set the company default'),
    ('CASH.COUNT.MANAGE', 'cashbank', 'Open an end-of-day cash count, record its denomination breakdown, and reconcile the variance'),
    ('CASH.COUNT.VIEW', 'cashbank', 'View end-of-day cash counts and their denomination breakdown'),
    ('CASH.ENTRY.RECORD', 'cashbank', 'Record a direct cash/bank entry (bank charge, interest, sundry)'),
    ('CASH.RECONCILE', 'cashbank', 'Perform a manual bank reconciliation (open/mark-cleared/complete)'),
    ('CASH.TRANSFER', 'cashbank', 'Record an inter-account transfer (CBT-####)'),
    ('CASH.VIEW', 'cashbank', 'View cash/bank accounts, balances, statements, and the GL-reconciliation read'),
    ('CHEQUE.MANAGE', 'cashbank', 'Manage the cheque register (register/clear/cancel)'),
    ('COMPANY.MANAGE', 'iam', 'Create, update and archive companies'),
    ('COMPANY.VIEW', 'iam', 'View companies'),
    ('COSTING.MANAGE', 'costing', 'Maintain dimension values (create/edit/deactivate) and set a dimension mandatory/optional'),
    ('COSTING.TAG', 'costing', 'Pick dimension values on a journal / invoice / bill / adjustment when posting'),
    ('COSTING.VIEW', 'costing', 'View dimensions, dimension values (cost centres / departments), and the dimension-sliced trial balance'),
    ('CRM.ACTIVITY.MANAGE', 'crm', 'Log and complete CRM activities and tasks'),
    ('CRM.ACTIVITY.VIEW', 'crm', 'View CRM activities and tasks'),
    ('CRM.LEAD.MANAGE', 'crm', 'Create and edit CRM leads'),
    ('CRM.LEAD.QUALIFY', 'crm', 'Qualify a CRM lead (link or promote to a Parties customer)'),
    ('CRM.LEAD.VIEW', 'crm', 'View CRM leads'),
    ('CRM.OPPORTUNITY.CONVERT', 'crm', 'Convert a CRM opportunity to a quotation or sales order'),
    ('CRM.OPPORTUNITY.MANAGE', 'crm', 'Create and manage CRM opportunities (advance stage, win, lose)'),
    ('CRM.OPPORTUNITY.VIEW', 'crm', 'View CRM opportunities'),
    ('CRM.PIPELINE.VIEW', 'crm', 'View the CRM pipeline, forecast and KPI report'),
    ('CRM.STAGE.MANAGE', 'crm', 'Manage per-company CRM pipeline stages (add, rename, reorder, deactivate)'),
    ('COMPANY.CURRENCY.CHANGE', 'iam', 'Change the company base (ledger) currency — blocked once GL transactions exist (ADR-0039 OQ-CCY-08)'),
    ('CURRENCY.MANAGE', 'fx', 'Create and maintain currency master and exchange rates'),
    ('CURRENCY.VIEW', 'fx', 'View currencies and exchange rates (read-only)'),
    ('CUSTOMER.MANAGE', 'parties', 'Create, update and archive customers'),
    ('CUSTOMER.IMPORT', 'parties', 'Bulk-import customers from a spreadsheet template (mass create/update)'),
    ('CUSTOMER.VIEW', 'parties', 'View and select customers'),
    ('DOCUMENT.BRANDING.MANAGE', 'documents', 'Edit the company branding profile'),
    ('DOCUMENT.RENDER', 'documents', 'Render / download a document PDF'),
    ('DOCUMENT.TEMPLATE.MANAGE', 'documents', 'Toggle document types active/inactive in the registry'),
    ('DOCUMENT.VIEW', 'documents', 'View the generated-documents render log'),
    ('FA.CATEGORY.MANAGE', 'fixedassets', 'Create and manage fixed asset categories'),
    ('FA.CATEGORY.VIEW', 'fixedassets', 'View fixed asset categories'),
    ('FA.DEPRECIATE', 'fixedassets', 'Preview and post the periodic depreciation run'),
    ('FA.DISPOSE', 'fixedassets', 'Dispose, write-off or revalue a fixed asset'),
    ('FA.REGISTER.MANAGE', 'fixedassets', 'Register, edit, place-in-service and transfer assets'),
    ('FA.VERIFY', 'fixedassets', 'Verify / flag a fixed asset (reserved)'),
    ('FA.VIEW', 'fixedassets', 'View fixed asset register, schedules and reconciliation'),
    ('FISCAL.MANAGE', 'sales', 'Issue, retry and void an EFD/fiscal receipt for a finalised invoice'),
    ('FISCAL.VIEW', 'sales', 'View the fiscal (EFD) receipt / status of an invoice'),
    ('FX.EXPOSURE.VIEW', 'fx', 'View FX exposure report and document FX detail'),
    ('FX.REVALUE', 'fx', 'Preview and post the period-end FX revaluation run'),
    ('GL.MANAGE', 'gl', 'Maintain the chart of accounts and the gl_configs account mapping'),
    ('GL.PERIOD.CLOSE', 'gl', 'Open/close fiscal periods and open a new fiscal year'),
    ('GL.POST', 'gl', 'Post manual journal entries (accruals, adjustments, opening balances)'),
    ('GL.VIEW', 'gl', 'View chart of accounts, posted journals, fiscal periods, and the trial balance'),
    ('GL.YEAR.CLOSE', 'gl', 'Close / reopen a fiscal year — the year-end closing entry + the reopen reversal'),
    ('HR.EMPLOYEE.MANAGE', 'hr', 'Create/update employees, contracts, departments, recurring items (salary data)'),
    ('HR.EMPLOYEE.PAYEE.VIEW', 'hr', 'View sensitive employee payee details (bank account / mobile money) (D-11)'),
    ('HR.EMPLOYEE.VIEW', 'hr', 'View employee, contract, and department records'),
    ('HR.LEAVE.APPROVE', 'hr', 'Approve or reject employee leave requests'),
    ('HR.LEAVE.MANAGE', 'hr', 'Create/manage leave types and balances; submit leave on behalf'),
    ('HR.LEAVE.VIEW', 'hr', 'View leave types, balances, and requests'),
    ('HR.LOAN.MANAGE', 'hr', 'Create and manage employee loans/advances'),
    ('HR.PAYCOMPONENT.MANAGE', 'hr', 'Manage pay-component catalogue (earnings/deduction definitions)'),
    ('HR.PAYROLL.APPROVE', 'hr', 'Approve a calculated payroll run'),
    ('HR.PAYROLL.DISBURSE', 'hr', 'Disburse net wages and statutory payables via Cash & Bank'),
    ('HR.PAYROLL.POST', 'hr', 'Post an approved payroll run to GL'),
    ('HR.PAYROLL.REVERSE', 'hr', 'Reverse a posted payroll run'),
    ('HR.PAYROLL.RUN', 'hr', 'Create payroll runs and trigger calculation'),
    ('HR.PAYROLL.VIEW', 'hr', 'View payroll runs and lines'),
    ('HR.PAYSLIP.VIEW', 'hr', 'View the payslip register and statutory summary (HR/finance scope)'),
    ('HR.SELF.VIEW', 'hr', 'Employee self-service: view own payslips and leave, submit leave requests'),
    ('HR.STATUTORY.MANAGE', 'hr', 'Add effective-dated PAYE band sets and statutory rate sets'),
    ('INVENTORY.BATCH.VIEW', 'stock', 'View batch/lot on-hand, lot numbers, and expiry information'),
    ('INVENTORY.EXPIRY.VIEW', 'stock', 'View the lot expiry / near-expiry report with value at risk'),
    ('INVENTORY.OPENING.SET', 'stock', 'Set the one-time opening inventory valuation (cost/value) for a product'),
    ('INVENTORY.SERIAL.VIEW', 'stock', 'View serial numbers, current status, location, and movement history'),
    ('INVENTORY.VALUATION.VIEW', 'stock', 'View the stock valuation report (qty × avg = value) and the GL reconciliation bar'),
    ('MANUFACTURING.VIEW', 'manufacturing', 'View and list work orders, cost report, WIP recon'),
    ('NOTIFICATION.ADMIN', 'notifications', 'View notification type catalogue, delivery log; enable/disable types per company'),
    ('NOTIFICATION.PREFERENCE.MANAGE', 'notifications', 'Read and set own per-type notification preferences'),
    ('NOTIFICATION.VIEW', 'notifications', 'Read own in-app inbox, unread count, mark-read'),
    ('OTHERPARTY.MANAGE', 'parties', 'Create, update and archive other/misc parties'),
    ('OTHERPARTY.VIEW', 'parties', 'View and select other/misc parties'),
    ('PARTY.BRANCH.ASSIGN', 'parties', 'Associate/dissociate any party with branches of its company'),
    ('PERMISSION.VIEW', 'iam', 'View the permission catalogue'),
    ('PETTY_CASH.MANAGE', 'cashbank', 'Create/edit petty cash funds and record disbursements, replenishments and adjustments'),
    ('PETTY_CASH.VIEW', 'cashbank', 'View petty cash funds and their transactions'),
    ('POS.EXPENSE.RECORD', 'sales', 'Record a categorised expense paid out of the till drawer'),
    ('POS.EXPENSE.VIEW', 'sales', 'View the till-expense report across sessions'),
    ('POS.SALE.AGE_OVERRIDE', 'pos', 'Sell an age-restricted item without an age-verification acknowledgement'),
    ('POS.SALE.CREATE', 'sales', 'Ring a POS sale on an open session'),
    ('POS.SALE.VOID', 'sales', 'Reverse / void a POS sale at the till (refund)'),
    ('POS.SESSION.CLOSE', 'sales', 'Close an open POS cashier session'),
    ('POS.SESSION.OPEN', 'sales', 'Open a POS cashier session on a till'),
    ('POS.SESSION.RECONCILE', 'sales', 'Reconcile a closed POS session (posts variance to GL)'),
    ('POS.SESSION.VIEW', 'sales', 'View POS cashier sessions and X/Z reads'),
    ('POS.TILL.MANAGE', 'sales', 'Create and manage POS tills (registers)'),
    ('POS.TILL.VIEW', 'sales', 'View POS tills (registers)'),
    ('PRICELIST.MANAGE', 'products', 'Create, update, archive price lists'),
    ('PRICELIST.VIEW', 'products', 'View price lists'),
    ('PRODUCT.BRANCH.ASSIGN', 'products', 'Associate/dissociate a product with branches of its company'),
    ('PRODUCT.MANAGE', 'products', 'Create, update, archive products; manage units, barcodes, prices and recipes'),
    ('PRODUCT.IMPORT', 'products', 'Bulk-import products from a spreadsheet template (mass create/update)'),
    ('PRICE.MASS_UPDATE', 'products', 'Bulk-set product prices: spreadsheet price upload and rule-based mass price change'),
    ('PRODUCT.SYMBOLOGY.MANAGE', 'products', 'Manage barcode symbology rules (embedded weight/price barcode decoding)'),
    ('PRODUCT.VIEW', 'products', 'View and select products'),
    ('PROJECTS.COSTING.VIEW', 'projects', 'View the project P&L, WIP, and job-cost roll-up'),
    ('PROJECTS.ISSUE.CREATE', 'projects', 'Issue materials from stock to a project'),
    ('PROJECTS.PROJECT.CREATE', 'projects', 'Create a new project'),
    ('PROJECTS.PROJECT.MANAGE', 'projects', 'Edit a project and change its status (activate/hold/complete/cancel)'),
    ('PROJECTS.PROJECT.VIEW', 'projects', 'View project list and project detail'),
    ('PROJECTS.TAG.MANAGE', 'projects', 'Attach, detach, or re-tag a project dimension on a posting'),
    ('PROJECTS.TASK.MANAGE', 'projects', 'Create, edit, and deactivate project tasks'),
    ('PROJECTS.TASK.VIEW', 'projects', 'View project tasks'),
    ('PROJECTS.TIMESHEET.RECORD', 'projects', 'Record project timesheet hours'),
    ('PROJECTS.TIMESHEET.VIEW', 'projects', 'View project timesheets'),
    ('PURCHASE.GOODS_RECEIPT.VIEW', 'purchases', 'View and list/search goods receipts'),
    ('PURCHASE.LANDEDCOST.MANAGE', 'purchases', 'Create and confirm landed-cost allocations'),
    ('PURCHASE.LANDEDCOST.VIEW', 'purchases', 'View landed-cost documents and allocations'),
    ('PURCHASE.ORDER.APPROVE', 'purchases', 'Approve/reject an over-threshold PO (fallback approval gate, ADR-0027 D-6)'),
    ('PURCHASE.ORDER.CREATE', 'purchases', 'Create and edit draft POs; add/edit/remove ordered lines; place; close'),
    ('PURCHASE.ORDER.VIEW', 'purchases', 'View and list/search purchase orders'),
    ('PURCHASE.ORDER.VOID', 'purchases', 'Void a purchase order'),
    ('PURCHASE.RECEIVE', 'purchases', 'Create a draft GR and receive (finalise) it — pushes stock in'),
    ('PURCHASE.RECEIVE.DIRECT', 'purchases', 'Receive goods straight into stock without a prior LPO (auto-raises the backing PO)'),
    ('PURCHASE.REQUISITION.APPROVE', 'purchases', 'Approve/reject a submitted requisition (fallback approval gate, ADR-0027 D-6)'),
    ('PURCHASE.REQUISITION.CREATE', 'purchases', 'Create, edit, submit, cancel a requisition'),
    ('PURCHASE.REQUISITION.VIEW', 'purchases', 'View and list purchase requisitions'),
    ('PURCHASE.RETURN.CREATE', 'purchases', 'Create and confirm a purchase return'),
    ('PURCHASE.RETURN.VIEW', 'purchases', 'View and list purchase returns'),
    ('PURCHASE.RFQ.MANAGE', 'purchases', 'Create/send RFQs, capture supplier quotes, award'),
    ('PURCHASE.RFQ.VIEW', 'purchases', 'View and list RFQs, supplier quotes, and the quote comparison'),
    ('PURCHASE.SETTINGS.MANAGE', 'purchases', 'Set the PO approval threshold and enable flag'),
    ('PURCHASE.VOID', 'purchases', 'Void a finalised goods receipt — reverses stock-in'),
    ('REPORT.BS.VIEW', 'reporting', 'View the Balance Sheet'),
    ('REPORT.CASHFLOW.VIEW', 'reporting', 'View the Cash-Flow Statement (indirect)'),
    ('REPORT.EXPORT', 'reporting', 'Export any statement / the ledger to PDF / Excel / CSV'),
    ('REPORT.LEDGER.VIEW', 'reporting', 'Drill into the GL account-ledger from a statement line'),
    ('REPORT.PL.VIEW', 'reporting', 'View the Income Statement / Profit & Loss'),
    ('REPORT.VIEW', 'reporting', 'View all financial statements + the account-ledger drill-down (coarse)'),
    ('ROLE.ADMIN', 'iam', 'Create, edit and archive the shared org-wide role catalogue'),
    ('ROLE.MANAGE', 'iam', 'Create and update roles; grant and revoke role assignments'),
    ('ROLE.VIEW', 'iam', 'View roles and their permissions'),
    ('ROUTE.ASSIGN', 'routes', 'Assign/unassign customers and external agents to/from a route; set primary agent'),
    ('ROUTE.MANAGE', 'routes', 'Create, update, archive and restore routes; manage branch associations'),
    ('ROUTE.VIEW', 'routes', 'View, list, search and select routes'),
    ('SALES.BELOW_COST.OVERRIDE', 'sales', 'Finalise a sale with a line priced at or below cost (audited supervisor override)'),
    ('SALES.BLANKET.CLOSE', 'sales', 'Manually close a blanket order'),
    ('SALES.BLANKET.CREATE', 'sales', 'Create blanket orders with committed quantities'),
    ('SALES.BLANKET.MANAGE', 'sales', 'Draw down (call-off) and cancel blanket orders'),
    ('SALES.BLANKET.VIEW', 'sales', 'View blanket orders and call-off draw-down'),
    ('SALES.CREDIT.OVERRIDE', 'sales', 'Finalise a credit sale that exceeds the customer credit limit (audited override)'),
    ('SALES.DELIVERY.CREATE', 'sales', 'Create a delivery against a confirmed sales order (issues stock + COGS)'),
    ('SALES.DELIVERY.VIEW', 'sales', 'View delivery documents'),
    ('SALES.DISCOUNT.OVERRIDE', 'sales', 'Authorise a line discount above the company ceiling (manager step-up)'),
    ('SALES.DROPSHIP.CREATE', 'sales', 'Flag an SO line as drop-ship and trigger the linked PO'),
    ('SALES.DROPSHIP.VIEW', 'sales', 'View drop-ship SO lines and linked supplier POs'),
    ('SALES.INVOICE.CREATE', 'sales', 'Create and edit draft invoices; add/edit/remove lines; finalise'),
    ('SALES.INVOICE.OVERRIDE', 'sales', 'Override a line unit price / non-default discount / default agent'),
    ('SALES.INVOICE.SETTLE', 'sales', 'Take payment / record tenders against an invoice'),
    ('SALES.INVOICE.VIEW', 'sales', 'View and list/search sales invoices'),
    ('SALES.INVOICE.VOID', 'sales', 'Void a finalised invoice'),
    ('SALES.ORDER.CANCEL', 'sales', 'Cancel a sales order (releases reservation)'),
    ('SALES.ORDER.CONFIRM', 'sales', 'Confirm a sales order (reserves stock)'),
    ('SALES.ORDER.CREATE', 'sales', 'Create and edit draft sales orders'),
    ('SALES.ORDER.VIEW', 'sales', 'View sales orders'),
    ('SALES.PRICING.RULE.MANAGE', 'products', 'Create and manage pricing rules (tiers, customer prices, promotions)'),
    ('SALES.PRICING.RULE.VIEW', 'products', 'View pricing rules (tiers, customer prices, promotions)'),
    ('SALES.QUOTE.ACCEPT', 'sales', 'Accept a quotation and convert it to a sales order'),
    ('SALES.QUOTE.CREATE', 'sales', 'Create and edit draft quotations'),
    ('SALES.QUOTE.SEND', 'sales', 'Send a quotation to the customer (allocates QUOTE-####)'),
    ('SALES.QUOTE.VIEW', 'sales', 'View quotations'),
    ('SALES.RETURN.CREATE', 'sales', 'Create a sales return against a delivery (stock back in + credit note)'),
    ('SALES.RETURN.VIEW', 'sales', 'View sales returns / RMA'),
    ('SALES.SETTINGS.MANAGE', 'sales', 'Set the SO approval threshold and enable flag'),
    ('SALES.STANDING.CREATE', 'sales', 'Create standing / recurring orders'),
    ('SALES.STANDING.GENERATE', 'sales', 'Trigger generation of the next child SO from a standing order'),
    ('SALES.STANDING.MANAGE', 'sales', 'Pause/resume/cancel/trigger standing orders'),
    ('SALES.STANDING.VIEW', 'sales', 'View standing / recurring orders'),
    ('STOCK.ADJUST', 'stock', 'Record a manual stock adjustment (+/-) with a reason; set reorder level'),
    ('STOCK.COUNT.CREATE', 'stock', 'Create a stock count, freeze the snapshot, and enter counted quantities'),
    ('STOCK.COUNT.POST', 'stock', 'Post a stock count variance to the books (variance-posting authority)'),
    ('STOCK.COUNT.VIEW', 'stock', 'View stock counts and variance reports'),
    ('STOCK.IMPORT', 'stock', 'Bulk-update on-hand stock levels from a spreadsheet (mass adjustment to a counted level)'),
    ('STOCK.LOCATION.MANAGE', 'stock', 'Create, edit, deactivate locations and set the branch default'),
    ('STOCK.LOCATION.VIEW', 'stock', 'View stock locations within a branch'),
    ('STOCK.OPENING', 'stock', 'Seed an opening-balance on-hand for a never-tracked product at a branch'),
    ('STOCK.TRANSFER.CREATE', 'stock', 'Create and dispatch an inter-location stock transfer'),
    ('STOCK.TRANSFER.RECEIVE', 'stock', 'Receive an in-transit transfer at the destination location'),
    ('STOCK.TRANSFER.VIEW', 'stock', 'View inter-location stock transfers'),
    ('STOCK.VAN_RECON.MANAGE', 'stock', 'Create, enter counts on, reconcile and cancel a van-stock reconciliation worksheet'),
    ('STOCK.VAN_RECON.VIEW', 'stock', 'View van-stock reconciliation worksheets'),
    ('STOCK.VIEW', 'stock', 'View on-hand levels and movement history'),
    ('SUPPLIER.MANAGE', 'parties', 'Create, update and archive suppliers'),
    ('SUPPLIER.IMPORT', 'parties', 'Bulk-import suppliers from a spreadsheet template (mass create/update)'),
    ('SUPPLIER.VIEW', 'parties', 'View and select suppliers'),
    ('TAXRATE.MANAGE', 'sales', 'Maintain company VAT rates'),
    ('TAXRATE.VIEW', 'sales', 'View company VAT rates'),
    ('UOM.MANAGE', 'products', 'Create, update, archive and restore units of measure'),
    ('UOM.VIEW', 'products', 'View units of measure'),
    ('USER.COMPANY.MANAGE', 'iam', 'Assign and remove a user''s company memberships'),
    ('USER.MANAGE', 'iam', 'Create, update, disable and unlock users; set passwords'),
    ('USER.VIEW', 'iam', 'View users'),
    ('VAT.ADJUST', 'tax', 'Add / remove adjustment lines on a DRAFT return'),
    ('VAT.RETURN.FILE', 'tax', 'File a VAT return — the lock + the synchronous GL settlement post'),
    ('VAT.RETURN.PREPARE', 'tax', 'Open / compute / recompute a DRAFT VAT return'),
    ('VAT.VIEW', 'tax', 'View VAT returns (face + band breakdown) and the WHT register'),
    ('WHT.MANAGE', 'tax', 'Manage WHT rates/types; capture WHT on an AP payment / AR receipt; issue certificates'),
    ('WHT.REMIT', 'tax', 'Mark a WHT transaction as remitted to the tax authority (flag-on-row, ADR-0040 D-7)'),
    ('WHT.VIEW', 'tax', 'Read WHT transactions / the WHT register'),
    ('WORKORDER.CLOSE', 'manufacturing', 'Close a completed work order (variance-clear, finance act)'),
    ('WORKORDER.MANAGE', 'manufacturing', 'Create / edit draft / issue / apply-cost / complete / cancel work orders + add operations'),
    ('WORKORDER.QC', 'manufacturing', 'RESERVED — no workflow in v1; hook for future QC workflow'),
    ('WORKORDER.RELEASE', 'manufacturing', 'Release a planned work order (BOM explosion + component plan)'),
    ('PAYMENTTERMS.VIEW', 'parties', 'View payment terms masters'),
    ('PAYMENTTERMS.MANAGE', 'parties', 'Create, update and archive payment terms masters')
ON CONFLICT (code) DO UPDATE
    SET module = EXCLUDED.module, description = EXCLUDED.description;

-- Grant the entire catalogue to the global ORG_ADMIN role (created in V1). CROSS JOIN over the
-- permissions table => ORG_ADMIN always holds every permission, including ones added above later.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM   roles r
CROSS JOIN permissions p
WHERE  r.code = 'ORG_ADMIN'
ON CONFLICT DO NOTHING;


-- ==========================================================================
-- Default operational role bundles (ADR-0057). Org-wide (no company_id),
-- is_system => undeletable (BR-7). Runs AFTER the ORG_ADMIN CROSS JOIN above,
-- so every referenced permission code already exists (FK-safe). Idempotent,
-- additive floor: role rows upsert (name/description converge); grants are
-- ON CONFLICT DO NOTHING (never revoked here). A NEW permission code does NOT
-- auto-flow into any bundle (only ORG_ADMIN absorbs it via its CROSS JOIN) --
-- flowing a capability into a least-privilege bundle is a reviewed edit to the
-- (role_code, perm_code) list below. UIDs are fixed synthetic seed values.
-- ==========================================================================
INSERT INTO roles (uid, code, name, description, is_system) VALUES
  ('00000000000000000000000001', 'SALESPERSON', 'Salesperson', 'Quotes, orders, invoices, deliveries, returns; fiscal receipts.', true),
  ('00000000000000000000000002', 'CASHIER', 'Cashier', 'POS till, customer receipting, cash count, petty cash.', true),
  ('00000000000000000000000003', 'FIELD_SALES_AGENT', 'Field Sales Agent', 'Route/van selling, receipting and van-stock reconciliation.', true),
  ('00000000000000000000000004', 'STOREKEEPER', 'Storekeeper', 'Stock control, counts, transfers, goods receipt.', true),
  ('00000000000000000000000005', 'ACCOUNTANT', 'Accountant', 'GL journals, AR/AP, cash and bank, VAT prep, WHT, reports.', true),
  ('00000000000000000000000006', 'SALES_MANAGER', 'Sales Manager', 'Full sales incl. overrides, pricing, CRM, approvals.', true),
  ('00000000000000000000000007', 'BRANCH_MANAGER', 'Branch Manager', 'Cross-module branch oversight, approvals and sign-offs.', true),
  ('00000000000000000000000008', 'PROCUREMENT_OFFICER', 'Procurement Officer', 'Requisition, RFQ, PO, receive, returns, suppliers.', true),
  ('00000000000000000000000009', 'PROCUREMENT_MANAGER', 'Procurement Manager', 'Procurement officer plus approve, void and settings.', true),
  ('0000000000000000000000000A', 'HR_PAYROLL_MANAGER', 'HR and Payroll Manager', 'Employees, leave, payroll run/approve/post/disburse.', true),
  ('0000000000000000000000000B', 'FINANCE_DIRECTOR', 'Finance Director', 'Accountant plus GL close, VAT file, FA, budgeting, policy.', true),
  ('0000000000000000000000000C', 'PRODUCTION_MANAGER', 'Production Manager', 'Work orders, BOMs, material movements, WIP costing.', true)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_system = true;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id FROM (VALUES
  -- SALESPERSON (36 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('SALESPERSON','SALES.QUOTE.CREATE'),
  ('SALESPERSON','SALES.QUOTE.SEND'),
  ('SALESPERSON','SALES.QUOTE.ACCEPT'),
  ('SALESPERSON','SALES.QUOTE.VIEW'),
  ('SALESPERSON','SALES.ORDER.CREATE'),
  ('SALESPERSON','SALES.ORDER.CONFIRM'),
  ('SALESPERSON','SALES.ORDER.CANCEL'),
  ('SALESPERSON','SALES.ORDER.VIEW'),
  ('SALESPERSON','SALES.INVOICE.CREATE'),
  ('SALESPERSON','SALES.INVOICE.SETTLE'),
  ('SALESPERSON','SALES.INVOICE.VIEW'),
  ('SALESPERSON','SALES.DELIVERY.CREATE'),
  ('SALESPERSON','SALES.DELIVERY.VIEW'),
  ('SALESPERSON','SALES.RETURN.CREATE'),
  ('SALESPERSON','SALES.RETURN.VIEW'),
  ('SALESPERSON','FISCAL.MANAGE'),
  ('SALESPERSON','FISCAL.VIEW'),
  ('SALESPERSON','CUSTOMER.MANAGE'),
  ('SALESPERSON','CUSTOMER.VIEW'),
  ('SALESPERSON','AR.INVOICE.VIEW'),
  ('SALESPERSON','AR.STATEMENT.VIEW'),
  ('SALESPERSON','PRICELIST.VIEW'),
  ('SALESPERSON','SALES.PRICING.RULE.VIEW'),
  ('SALESPERSON','STOCK.VIEW'),
  ('SALESPERSON','ROUTE.VIEW'),
  ('SALESPERSON','AGENT.VIEW'),
  ('SALESPERSON','PRODUCT.VIEW'),
  ('SALESPERSON','UOM.VIEW'),
  ('SALESPERSON','CURRENCY.VIEW'),
  ('SALESPERSON','TAXRATE.VIEW'),
  ('SALESPERSON','PAYMENTTERMS.VIEW'),
  ('SALESPERSON','DOCUMENT.VIEW'),
  ('SALESPERSON','NOTIFICATION.VIEW'),
  ('SALESPERSON','NOTIFICATION.PREFERENCE.MANAGE'),
  ('SALESPERSON','DOCUMENT.RENDER'),
  ('SALESPERSON','BRANCH.VIEW'),
  -- CASHIER (30 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  -- NOTE: POS.SESSION.RECONCILE (Z-read variance → GL) is intentionally NOT granted —
  -- it is a supervisor/back-office step (segregation of duties). Existing DBs that were
  -- seeded before this change keep the grant (additive floor never revokes); revoke it
  -- there manually if the SoD split is required on already-provisioned tenants.
  ('CASHIER','POS.SALE.CREATE'),
  ('CASHIER','POS.SALE.VOID'),
  ('CASHIER','POS.SESSION.OPEN'),
  ('CASHIER','POS.SESSION.CLOSE'),
  ('CASHIER','POS.SESSION.VIEW'),
  -- Kilimanjaro 2026-08-08 (K8): the cashier is the one who pays cash out of the drawer, so they
  -- record the expense. Reading the cross-session expense REPORT is a manager capability
  -- (POS.EXPENSE.VIEW) and is deliberately NOT granted here.
  ('CASHIER','POS.EXPENSE.RECORD'),
  ('CASHIER','POS.TILL.VIEW'),
  ('CASHIER','SALES.INVOICE.SETTLE'),
  ('CASHIER','SALES.INVOICE.VIEW'),
  ('CASHIER','AR.RECEIPT.RECORD'),
  ('CASHIER','AR.RECEIPT.ALLOCATE'),
  ('CASHIER','AR.INVOICE.VIEW'),
  ('CASHIER','AR.VIEW'),
  ('CASHIER','CASH.COUNT.MANAGE'),
  ('CASHIER','CASH.COUNT.VIEW'),
  ('CASHIER','PETTY_CASH.MANAGE'),
  ('CASHIER','PETTY_CASH.VIEW'),
  ('CASHIER','FISCAL.MANAGE'),
  ('CASHIER','FISCAL.VIEW'),
  ('CASHIER','CUSTOMER.VIEW'),
  ('CASHIER','PRODUCT.VIEW'),
  ('CASHIER','UOM.VIEW'),
  ('CASHIER','CURRENCY.VIEW'),
  -- Busy-day-sim fix (2026-07-05): the register needs price/tax/stock reads so the till can show
  -- the VAT-inclusive amount due, vet sellability, and see on-hand before ringing (all read-only).
  ('CASHIER','TAXRATE.VIEW'),
  ('CASHIER','PRICELIST.VIEW'),
  ('CASHIER','STOCK.VIEW'),
  ('CASHIER','DOCUMENT.VIEW'),
  ('CASHIER','NOTIFICATION.VIEW'),
  ('CASHIER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('CASHIER','DOCUMENT.RENDER'),
  ('CASHIER','BRANCH.VIEW'),
  -- FIELD_SALES_AGENT (40 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('FIELD_SALES_AGENT','SALES.QUOTE.CREATE'),
  ('FIELD_SALES_AGENT','SALES.QUOTE.SEND'),
  ('FIELD_SALES_AGENT','SALES.QUOTE.VIEW'),
  ('FIELD_SALES_AGENT','SALES.ORDER.CREATE'),
  ('FIELD_SALES_AGENT','SALES.ORDER.CONFIRM'),
  ('FIELD_SALES_AGENT','SALES.ORDER.VIEW'),
  ('FIELD_SALES_AGENT','SALES.INVOICE.CREATE'),
  ('FIELD_SALES_AGENT','SALES.INVOICE.SETTLE'),
  ('FIELD_SALES_AGENT','SALES.INVOICE.VIEW'),
  ('FIELD_SALES_AGENT','SALES.DELIVERY.CREATE'),
  ('FIELD_SALES_AGENT','SALES.DELIVERY.VIEW'),
  ('FIELD_SALES_AGENT','SALES.RETURN.CREATE'),
  ('FIELD_SALES_AGENT','SALES.RETURN.VIEW'),
  ('FIELD_SALES_AGENT','FISCAL.MANAGE'),
  ('FIELD_SALES_AGENT','FISCAL.VIEW'),
  ('FIELD_SALES_AGENT','AR.RECEIPT.RECORD'),
  ('FIELD_SALES_AGENT','AR.RECEIPT.ALLOCATE'),
  ('FIELD_SALES_AGENT','AR.INVOICE.VIEW'),
  ('FIELD_SALES_AGENT','AR.STATEMENT.VIEW'),
  ('FIELD_SALES_AGENT','AR.VIEW'),
  ('FIELD_SALES_AGENT','STOCK.VAN_RECON.MANAGE'),
  ('FIELD_SALES_AGENT','STOCK.VAN_RECON.VIEW'),
  ('FIELD_SALES_AGENT','STOCK.VIEW'),
  ('FIELD_SALES_AGENT','INVENTORY.BATCH.VIEW'),
  ('FIELD_SALES_AGENT','ROUTE.VIEW'),
  ('FIELD_SALES_AGENT','AGENT.VIEW'),
  ('FIELD_SALES_AGENT','CUSTOMER.MANAGE'),
  ('FIELD_SALES_AGENT','CUSTOMER.VIEW'),
  ('FIELD_SALES_AGENT','PRICELIST.VIEW'),
  ('FIELD_SALES_AGENT','SALES.PRICING.RULE.VIEW'),
  ('FIELD_SALES_AGENT','PRODUCT.VIEW'),
  ('FIELD_SALES_AGENT','UOM.VIEW'),
  ('FIELD_SALES_AGENT','CURRENCY.VIEW'),
  ('FIELD_SALES_AGENT','TAXRATE.VIEW'),
  ('FIELD_SALES_AGENT','PAYMENTTERMS.VIEW'),
  ('FIELD_SALES_AGENT','DOCUMENT.VIEW'),
  ('FIELD_SALES_AGENT','NOTIFICATION.VIEW'),
  ('FIELD_SALES_AGENT','NOTIFICATION.PREFERENCE.MANAGE'),
  ('FIELD_SALES_AGENT','DOCUMENT.RENDER'),
  ('FIELD_SALES_AGENT','BRANCH.VIEW'),
  -- STOREKEEPER (27 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('STOREKEEPER','STOCK.VIEW'),
  ('STOREKEEPER','STOCK.ADJUST'),
  ('STOREKEEPER','STOCK.OPENING'),
  ('STOREKEEPER','STOCK.IMPORT'),
  ('STOREKEEPER','STOCK.COUNT.CREATE'),
  ('STOREKEEPER','STOCK.COUNT.VIEW'),
  ('STOREKEEPER','STOCK.COUNT.POST'),
  ('STOREKEEPER','STOCK.LOCATION.MANAGE'),
  ('STOREKEEPER','STOCK.LOCATION.VIEW'),
  ('STOREKEEPER','STOCK.TRANSFER.CREATE'),
  ('STOREKEEPER','STOCK.TRANSFER.RECEIVE'),
  ('STOREKEEPER','STOCK.TRANSFER.VIEW'),
  ('STOREKEEPER','INVENTORY.BATCH.VIEW'),
  ('STOREKEEPER','INVENTORY.SERIAL.VIEW'),
  ('STOREKEEPER','INVENTORY.EXPIRY.VIEW'),
  ('STOREKEEPER','PURCHASE.RECEIVE'),
  -- Kilimanjaro 2026-08-08 (K3): receive a walk-in / cash purchase with no prior LPO. The service
  -- auto-raises the backing PO, so the storekeeper never authors spend directly; PO approval
  -- thresholds still apply. Held alongside PURCHASE.RECEIVE, which they already have.
  ('STOREKEEPER','PURCHASE.RECEIVE.DIRECT'),
  -- Kilimanjaro 2026-08-11: PURCHASE.RECEIVE.DIRECT is granted to STOREKEEPER and to no other role,
  -- but "Receive Goods Without an Order" opens with a supplier picker backed by GET /suppliers
  -- (SUPPLIER.VIEW). Without this grant a non-root storekeeper got a search box that returned
  -- nothing, with no explanation — the screen was unusable by the only role that owns it. Read-only
  -- lookup of a master they already receive against; it authorises no spend.
  ('STOREKEEPER','SUPPLIER.VIEW'),
  -- Kilimanjaro 2026-08-08 (K9): the shipped stock + valuation reports were unreachable for the very
  -- role that lives in them — the storekeeper could not open the report they are measured on.
  ('STOREKEEPER','INVENTORY.VALUATION.VIEW'),
  ('STOREKEEPER','REPORT.EXPORT'),
  ('STOREKEEPER','PURCHASE.GOODS_RECEIPT.VIEW'),
  ('STOREKEEPER','PURCHASE.ORDER.VIEW'),
  ('STOREKEEPER','PURCHASE.RETURN.CREATE'),
  ('STOREKEEPER','PURCHASE.RETURN.VIEW'),
  ('STOREKEEPER','PRODUCT.VIEW'),
  ('STOREKEEPER','UOM.VIEW'),
  ('STOREKEEPER','DOCUMENT.VIEW'),
  ('STOREKEEPER','NOTIFICATION.VIEW'),
  ('STOREKEEPER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('STOREKEEPER','DOCUMENT.RENDER'),
  ('STOREKEEPER','BRANCH.VIEW'),
  -- ACCOUNTANT (57 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('ACCOUNTANT','GL.VIEW'),
  ('ACCOUNTANT','GL.POST'),
  ('ACCOUNTANT','AR.VIEW'),
  ('ACCOUNTANT','AR.INVOICE.VIEW'),
  ('ACCOUNTANT','AR.RECEIPT.RECORD'),
  ('ACCOUNTANT','AR.RECEIPT.ALLOCATE'),
  ('ACCOUNTANT','AR.CREDITNOTE'),
  ('ACCOUNTANT','AR.WRITEOFF'),
  ('ACCOUNTANT','AR.STATEMENT.VIEW'),
  ('ACCOUNTANT','AR.OPENING.SET'),
  ('ACCOUNTANT','AR.DISPUTE.MANAGE'),
  ('ACCOUNTANT','AP.VIEW'),
  ('ACCOUNTANT','AP.BILL.ENTER'),
  ('ACCOUNTANT','AP.BILL.MATCH'),
  ('ACCOUNTANT','AP.PAYMENT.RUN'),
  ('ACCOUNTANT','AP.DEBITNOTE'),
  ('ACCOUNTANT','AP.OPENING.SET'),
  ('ACCOUNTANT','CASH.VIEW'),
  ('ACCOUNTANT','CASH.ACCOUNT.MANAGE'),
  ('ACCOUNTANT','CASH.ENTRY.RECORD'),
  ('ACCOUNTANT','CASH.RECONCILE'),
  ('ACCOUNTANT','CASH.TRANSFER'),
  ('ACCOUNTANT','CHEQUE.MANAGE'),
  ('ACCOUNTANT','CASH.COUNT.VIEW'),
  ('ACCOUNTANT','PETTY_CASH.VIEW'),
  ('ACCOUNTANT','PETTY_CASH.MANAGE'),
  ('ACCOUNTANT','VAT.VIEW'),
  ('ACCOUNTANT','VAT.RETURN.PREPARE'),
  ('ACCOUNTANT','VAT.ADJUST'),
  ('ACCOUNTANT','WHT.VIEW'),
  ('ACCOUNTANT','WHT.MANAGE'),
  ('ACCOUNTANT','WHT.REMIT'),
  ('ACCOUNTANT','COSTING.VIEW'),
  ('ACCOUNTANT','COSTING.TAG'),
  ('ACCOUNTANT','FX.EXPOSURE.VIEW'),
  ('ACCOUNTANT','FA.VIEW'),
  ('ACCOUNTANT','FA.CATEGORY.VIEW'),
  ('ACCOUNTANT','REPORT.VIEW'),
  ('ACCOUNTANT','REPORT.PL.VIEW'),
  ('ACCOUNTANT','REPORT.BS.VIEW'),
  ('ACCOUNTANT','REPORT.CASHFLOW.VIEW'),
  ('ACCOUNTANT','REPORT.LEDGER.VIEW'),
  ('ACCOUNTANT','REPORT.EXPORT'),
  -- 2026-08-08 (K9): reconciling stock to the GL is core accountant work, but the bundle held
  -- REPORT.EXPORT without INVENTORY.VALUATION.VIEW — so an accountant was refused the stock
  -- reports on screen while still able to download the identical data as a file. Granting the
  -- read closes the gap in the safe direction; the export gate was separately tightened to
  -- require BOTH, so a user who cannot see a report can no longer download it.
  ('ACCOUNTANT','INVENTORY.VALUATION.VIEW'),
  ('ACCOUNTANT','BI.VIEW'),
  ('ACCOUNTANT','BI.FINANCE.VIEW'),
  ('ACCOUNTANT','CUSTOMER.VIEW'),
  ('ACCOUNTANT','SUPPLIER.VIEW'),
  ('ACCOUNTANT','PRODUCT.VIEW'),
  ('ACCOUNTANT','UOM.VIEW'),
  ('ACCOUNTANT','CURRENCY.VIEW'),
  ('ACCOUNTANT','TAXRATE.VIEW'),
  ('ACCOUNTANT','PAYMENTTERMS.VIEW'),
  ('ACCOUNTANT','DOCUMENT.VIEW'),
  ('ACCOUNTANT','NOTIFICATION.VIEW'),
  ('ACCOUNTANT','NOTIFICATION.PREFERENCE.MANAGE'),
  ('ACCOUNTANT','DOCUMENT.RENDER'),
  ('ACCOUNTANT','BRANCH.VIEW'),
  -- SALES_MANAGER (74 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('SALES_MANAGER','SALES.QUOTE.CREATE'),
  ('SALES_MANAGER','SALES.QUOTE.SEND'),
  ('SALES_MANAGER','SALES.QUOTE.ACCEPT'),
  ('SALES_MANAGER','SALES.QUOTE.VIEW'),
  ('SALES_MANAGER','SALES.ORDER.CREATE'),
  ('SALES_MANAGER','SALES.ORDER.CONFIRM'),
  ('SALES_MANAGER','SALES.ORDER.CANCEL'),
  ('SALES_MANAGER','SALES.ORDER.VIEW'),
  ('SALES_MANAGER','SALES.INVOICE.CREATE'),
  ('SALES_MANAGER','SALES.INVOICE.SETTLE'),
  ('SALES_MANAGER','SALES.INVOICE.VIEW'),
  ('SALES_MANAGER','SALES.INVOICE.OVERRIDE'),
  ('SALES_MANAGER','SALES.INVOICE.VOID'),
  ('SALES_MANAGER','SALES.CREDIT.OVERRIDE'),
  ('SALES_MANAGER','SALES.BELOW_COST.OVERRIDE'),
  ('SALES_MANAGER','SALES.DELIVERY.CREATE'),
  ('SALES_MANAGER','SALES.DELIVERY.VIEW'),
  ('SALES_MANAGER','SALES.RETURN.CREATE'),
  ('SALES_MANAGER','SALES.RETURN.VIEW'),
  ('SALES_MANAGER','SALES.DROPSHIP.CREATE'),
  ('SALES_MANAGER','SALES.DROPSHIP.VIEW'),
  ('SALES_MANAGER','SALES.BLANKET.CREATE'),
  ('SALES_MANAGER','SALES.BLANKET.MANAGE'),
  ('SALES_MANAGER','SALES.BLANKET.CLOSE'),
  ('SALES_MANAGER','SALES.BLANKET.VIEW'),
  ('SALES_MANAGER','SALES.STANDING.CREATE'),
  ('SALES_MANAGER','SALES.STANDING.MANAGE'),
  ('SALES_MANAGER','SALES.STANDING.GENERATE'),
  ('SALES_MANAGER','SALES.STANDING.VIEW'),
  ('SALES_MANAGER','SALES.SETTINGS.MANAGE'),
  ('SALES_MANAGER','SALES.PRICING.RULE.MANAGE'),
  ('SALES_MANAGER','SALES.PRICING.RULE.VIEW'),
  ('SALES_MANAGER','PRICELIST.MANAGE'),
  ('SALES_MANAGER','PRICELIST.VIEW'),
  ('SALES_MANAGER','PRICE.MASS_UPDATE'),
  ('SALES_MANAGER','FISCAL.MANAGE'),
  ('SALES_MANAGER','FISCAL.VIEW'),
  ('SALES_MANAGER','CRM.LEAD.MANAGE'),
  ('SALES_MANAGER','CRM.LEAD.QUALIFY'),
  ('SALES_MANAGER','CRM.LEAD.VIEW'),
  ('SALES_MANAGER','CRM.OPPORTUNITY.MANAGE'),
  ('SALES_MANAGER','CRM.OPPORTUNITY.CONVERT'),
  ('SALES_MANAGER','CRM.OPPORTUNITY.VIEW'),
  ('SALES_MANAGER','CRM.ACTIVITY.MANAGE'),
  ('SALES_MANAGER','CRM.ACTIVITY.VIEW'),
  ('SALES_MANAGER','CRM.PIPELINE.VIEW'),
  ('SALES_MANAGER','CRM.STAGE.MANAGE'),
  ('SALES_MANAGER','CUSTOMER.MANAGE'),
  ('SALES_MANAGER','CUSTOMER.VIEW'),
  ('SALES_MANAGER','CUSTOMER.IMPORT'),
  ('SALES_MANAGER','AGENT.MANAGE'),
  ('SALES_MANAGER','AGENT.VIEW'),
  ('SALES_MANAGER','ROUTE.MANAGE'),
  ('SALES_MANAGER','ROUTE.VIEW'),
  ('SALES_MANAGER','ROUTE.ASSIGN'),
  ('SALES_MANAGER','AR.VIEW'),
  ('SALES_MANAGER','AR.INVOICE.VIEW'),
  ('SALES_MANAGER','AR.STATEMENT.VIEW'),
  ('SALES_MANAGER','AR.DISPUTE.MANAGE'),
  ('SALES_MANAGER','STOCK.VIEW'),
  ('SALES_MANAGER','APPROVALS.DECIDE'),
  ('SALES_MANAGER','APPROVALS.REQUEST.VIEW'),
  ('SALES_MANAGER','BI.VIEW'),
  ('SALES_MANAGER','BI.CRM.VIEW'),
  ('SALES_MANAGER','TAXRATE.VIEW'),
  ('SALES_MANAGER','PRODUCT.VIEW'),
  ('SALES_MANAGER','UOM.VIEW'),
  ('SALES_MANAGER','CURRENCY.VIEW'),
  ('SALES_MANAGER','PAYMENTTERMS.VIEW'),
  ('SALES_MANAGER','DOCUMENT.VIEW'),
  ('SALES_MANAGER','NOTIFICATION.VIEW'),
  ('SALES_MANAGER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('SALES_MANAGER','DOCUMENT.RENDER'),
  -- Kilimanjaro 2026-08-08 (K7/K8): the two capabilities a cashier must escalate TO. SALES.DISCOUNT.OVERRIDE
  -- is what the manager step-up verifies against when a discount exceeds the company ceiling;
  -- POS.EXPENSE.VIEW is the cross-session till-expense report the cashier cannot see.
  ('SALES_MANAGER','SALES.DISCOUNT.OVERRIDE'),
  ('SALES_MANAGER','POS.EXPENSE.VIEW'),
  -- 2026-08-08 (K1): the sales manager is the till supervisor — they authorise a Z-read via the
  -- step-up prompt — but did not hold POS.SESSION.VIEW, so they could approve a report they were
  -- then refused permission to read. An approver who cannot see what they approved is an audit
  -- failure, not a security posture.
  ('SALES_MANAGER','POS.SESSION.VIEW'),
  ('SALES_MANAGER','BRANCH.VIEW'),
  -- BRANCH_MANAGER (54 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('BRANCH_MANAGER','SALES.QUOTE.VIEW'),
  ('BRANCH_MANAGER','SALES.ORDER.VIEW'),
  ('BRANCH_MANAGER','SALES.INVOICE.VIEW'),
  ('BRANCH_MANAGER','SALES.INVOICE.OVERRIDE'),
  ('BRANCH_MANAGER','SALES.INVOICE.VOID'),
  ('BRANCH_MANAGER','SALES.CREDIT.OVERRIDE'),
  -- SALES.BELOW_COST.OVERRIDE: the supervisor on the shop floor is who a cashier calls over when a
  -- line prices out at or below cost (V93 APPROVE mode) -- without it the till waits for head office.
  ('BRANCH_MANAGER','SALES.BELOW_COST.OVERRIDE'),
  ('BRANCH_MANAGER','POS.SESSION.VIEW'),
  -- POS.SESSION.CLOSE: a branch manager must be able to close a session a cashier left open
  -- (till stranded by an ended shift / lost device) before reconciling it -- without it CASHIER
  -- was the only bundle holding the code, so a stranded till waited for a cashier to come back.
  ('BRANCH_MANAGER','POS.SESSION.CLOSE'),
  ('BRANCH_MANAGER','POS.SESSION.RECONCILE'),
  ('BRANCH_MANAGER','POS.SALE.VOID'),
  ('BRANCH_MANAGER','POS.SALE.AGE_OVERRIDE'),
  ('BRANCH_MANAGER','POS.TILL.MANAGE'),
  ('BRANCH_MANAGER','POS.TILL.VIEW'),
  ('BRANCH_MANAGER','CASH.COUNT.MANAGE'),
  ('BRANCH_MANAGER','CASH.COUNT.VIEW'),
  ('BRANCH_MANAGER','PETTY_CASH.VIEW'),
  ('BRANCH_MANAGER','CASH.VIEW'),
  ('BRANCH_MANAGER','STOCK.VIEW'),
  ('BRANCH_MANAGER','STOCK.ADJUST'),
  ('BRANCH_MANAGER','STOCK.IMPORT'),
  ('BRANCH_MANAGER','STOCK.COUNT.VIEW'),
  ('BRANCH_MANAGER','STOCK.COUNT.POST'),
  ('BRANCH_MANAGER','STOCK.TRANSFER.VIEW'),
  ('BRANCH_MANAGER','STOCK.LOCATION.VIEW'),
  ('BRANCH_MANAGER','INVENTORY.VALUATION.VIEW'),
  ('BRANCH_MANAGER','INVENTORY.EXPIRY.VIEW'),
  ('BRANCH_MANAGER','PURCHASE.ORDER.VIEW'),
  ('BRANCH_MANAGER','PURCHASE.ORDER.APPROVE'),
  ('BRANCH_MANAGER','PURCHASE.REQUISITION.VIEW'),
  ('BRANCH_MANAGER','PURCHASE.REQUISITION.APPROVE'),
  ('BRANCH_MANAGER','PURCHASE.GOODS_RECEIPT.VIEW'),
  ('BRANCH_MANAGER','AR.VIEW'),
  ('BRANCH_MANAGER','AP.VIEW'),
  ('BRANCH_MANAGER','APPROVALS.DECIDE'),
  ('BRANCH_MANAGER','APPROVALS.REQUEST.VIEW'),
  ('BRANCH_MANAGER','APPROVALS.POLICY.VIEW'),
  ('BRANCH_MANAGER','BI.VIEW'),
  ('BRANCH_MANAGER','BI.OPS.VIEW'),
  ('BRANCH_MANAGER','BI.FINANCE.VIEW'),
  ('BRANCH_MANAGER','REPORT.VIEW'),
  ('BRANCH_MANAGER','REPORT.PL.VIEW'),
  ('BRANCH_MANAGER','REPORT.BS.VIEW'),
  ('BRANCH_MANAGER','REPORT.EXPORT'),
  ('BRANCH_MANAGER','CUSTOMER.VIEW'),
  ('BRANCH_MANAGER','SUPPLIER.VIEW'),
  ('BRANCH_MANAGER','ROUTE.VIEW'),
  ('BRANCH_MANAGER','PRODUCT.VIEW'),
  ('BRANCH_MANAGER','UOM.VIEW'),
  ('BRANCH_MANAGER','DOCUMENT.VIEW'),
  ('BRANCH_MANAGER','NOTIFICATION.VIEW'),
  ('BRANCH_MANAGER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('BRANCH_MANAGER','DOCUMENT.RENDER'),
  ('BRANCH_MANAGER','SALES.DISCOUNT.OVERRIDE'),
  ('BRANCH_MANAGER','POS.EXPENSE.VIEW'),
  ('BRANCH_MANAGER','BRANCH.VIEW'),
  -- PROCUREMENT_OFFICER (25 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('PROCUREMENT_OFFICER','PURCHASE.REQUISITION.CREATE'),
  ('PROCUREMENT_OFFICER','PURCHASE.REQUISITION.VIEW'),
  ('PROCUREMENT_OFFICER','PURCHASE.RFQ.MANAGE'),
  ('PROCUREMENT_OFFICER','PURCHASE.RFQ.VIEW'),
  ('PROCUREMENT_OFFICER','PURCHASE.ORDER.CREATE'),
  ('PROCUREMENT_OFFICER','PURCHASE.ORDER.VIEW'),
  ('PROCUREMENT_OFFICER','PURCHASE.RECEIVE'),
  ('PROCUREMENT_OFFICER','PURCHASE.GOODS_RECEIPT.VIEW'),
  ('PROCUREMENT_OFFICER','PURCHASE.RETURN.CREATE'),
  ('PROCUREMENT_OFFICER','PURCHASE.RETURN.VIEW'),
  ('PROCUREMENT_OFFICER','PURCHASE.LANDEDCOST.MANAGE'),
  ('PROCUREMENT_OFFICER','PURCHASE.LANDEDCOST.VIEW'),
  ('PROCUREMENT_OFFICER','SUPPLIER.MANAGE'),
  ('PROCUREMENT_OFFICER','SUPPLIER.VIEW'),
  ('PROCUREMENT_OFFICER','SUPPLIER.IMPORT'),
  ('PROCUREMENT_OFFICER','PAYMENTTERMS.VIEW'),
  ('PROCUREMENT_OFFICER','STOCK.VIEW'),
  ('PROCUREMENT_OFFICER','PRODUCT.VIEW'),
  -- Kilimanjaro 2026-08-08 (K4): procurement owns product master data (they register the SKUs), but
  -- PRODUCT.MANAGE and UOM.MANAGE were granted to NO operational bundle — only ORG_ADMIN absorbed them
  -- via its CROSS JOIN. Nobody but an org admin could create a pack unit or attach a per-UOM price,
  -- which is why the carton/outer/piece setup was unreachable for the people who needed it.
  ('PROCUREMENT_OFFICER','PRODUCT.MANAGE'),
  ('PROCUREMENT_OFFICER','UOM.MANAGE'),
  ('PROCUREMENT_OFFICER','UOM.VIEW'),
  ('PROCUREMENT_OFFICER','CURRENCY.VIEW'),
  ('PROCUREMENT_OFFICER','DOCUMENT.VIEW'),
  ('PROCUREMENT_OFFICER','NOTIFICATION.VIEW'),
  ('PROCUREMENT_OFFICER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('PROCUREMENT_OFFICER','DOCUMENT.RENDER'),
  ('PROCUREMENT_OFFICER','BRANCH.VIEW'),
  -- PROCUREMENT_MANAGER (34 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('PROCUREMENT_MANAGER','PURCHASE.REQUISITION.CREATE'),
  ('PROCUREMENT_MANAGER','PURCHASE.REQUISITION.VIEW'),
  ('PROCUREMENT_MANAGER','PURCHASE.RFQ.MANAGE'),
  ('PROCUREMENT_MANAGER','PURCHASE.RFQ.VIEW'),
  ('PROCUREMENT_MANAGER','PURCHASE.ORDER.CREATE'),
  ('PROCUREMENT_MANAGER','PURCHASE.ORDER.VIEW'),
  ('PROCUREMENT_MANAGER','PURCHASE.RECEIVE'),
  ('PROCUREMENT_MANAGER','PURCHASE.GOODS_RECEIPT.VIEW'),
  ('PROCUREMENT_MANAGER','PURCHASE.RETURN.CREATE'),
  ('PROCUREMENT_MANAGER','PURCHASE.RETURN.VIEW'),
  ('PROCUREMENT_MANAGER','PURCHASE.LANDEDCOST.MANAGE'),
  ('PROCUREMENT_MANAGER','PURCHASE.LANDEDCOST.VIEW'),
  ('PROCUREMENT_MANAGER','SUPPLIER.MANAGE'),
  ('PROCUREMENT_MANAGER','SUPPLIER.VIEW'),
  ('PROCUREMENT_MANAGER','SUPPLIER.IMPORT'),
  ('PROCUREMENT_MANAGER','PAYMENTTERMS.VIEW'),
  ('PROCUREMENT_MANAGER','STOCK.VIEW'),
  ('PROCUREMENT_MANAGER','PRODUCT.VIEW'),
  ('PROCUREMENT_MANAGER','PRODUCT.MANAGE'),
  ('PROCUREMENT_MANAGER','UOM.MANAGE'),
  ('PROCUREMENT_MANAGER','UOM.VIEW'),
  ('PROCUREMENT_MANAGER','CURRENCY.VIEW'),
  ('PROCUREMENT_MANAGER','DOCUMENT.VIEW'),
  ('PROCUREMENT_MANAGER','PURCHASE.ORDER.APPROVE'),
  ('PROCUREMENT_MANAGER','PURCHASE.REQUISITION.APPROVE'),
  ('PROCUREMENT_MANAGER','PURCHASE.ORDER.VOID'),
  ('PROCUREMENT_MANAGER','PURCHASE.VOID'),
  ('PROCUREMENT_MANAGER','PURCHASE.SETTINGS.MANAGE'),
  ('PROCUREMENT_MANAGER','APPROVALS.DECIDE'),
  ('PROCUREMENT_MANAGER','APPROVALS.REQUEST.VIEW'),
  ('PROCUREMENT_MANAGER','BI.VIEW'),
  ('PROCUREMENT_MANAGER','BI.OPS.VIEW'),
  ('PROCUREMENT_MANAGER','NOTIFICATION.VIEW'),
  ('PROCUREMENT_MANAGER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('PROCUREMENT_MANAGER','DOCUMENT.RENDER'),
  ('PROCUREMENT_MANAGER','BRANCH.VIEW'),
  -- HR_PAYROLL_MANAGER (23 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('HR_PAYROLL_MANAGER','HR.EMPLOYEE.MANAGE'),
  ('HR_PAYROLL_MANAGER','HR.EMPLOYEE.VIEW'),
  ('HR_PAYROLL_MANAGER','HR.EMPLOYEE.PAYEE.VIEW'),
  ('HR_PAYROLL_MANAGER','HR.LEAVE.MANAGE'),
  ('HR_PAYROLL_MANAGER','HR.LEAVE.APPROVE'),
  ('HR_PAYROLL_MANAGER','HR.LEAVE.VIEW'),
  ('HR_PAYROLL_MANAGER','HR.LOAN.MANAGE'),
  ('HR_PAYROLL_MANAGER','HR.PAYCOMPONENT.MANAGE'),
  ('HR_PAYROLL_MANAGER','HR.PAYROLL.RUN'),
  ('HR_PAYROLL_MANAGER','HR.PAYROLL.APPROVE'),
  ('HR_PAYROLL_MANAGER','HR.PAYROLL.POST'),
  ('HR_PAYROLL_MANAGER','HR.PAYROLL.DISBURSE'),
  ('HR_PAYROLL_MANAGER','HR.PAYROLL.REVERSE'),
  ('HR_PAYROLL_MANAGER','HR.PAYROLL.VIEW'),
  ('HR_PAYROLL_MANAGER','HR.PAYSLIP.VIEW'),
  ('HR_PAYROLL_MANAGER','HR.STATUTORY.MANAGE'),
  ('HR_PAYROLL_MANAGER','HR.SELF.VIEW'),
  ('HR_PAYROLL_MANAGER','CURRENCY.VIEW'),
  ('HR_PAYROLL_MANAGER','DOCUMENT.VIEW'),
  ('HR_PAYROLL_MANAGER','NOTIFICATION.VIEW'),
  ('HR_PAYROLL_MANAGER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('HR_PAYROLL_MANAGER','DOCUMENT.RENDER'),
  ('HR_PAYROLL_MANAGER','BRANCH.VIEW'),
  -- FINANCE_DIRECTOR (83 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('FINANCE_DIRECTOR','GL.VIEW'),
  ('FINANCE_DIRECTOR','GL.POST'),
  ('FINANCE_DIRECTOR','AR.VIEW'),
  ('FINANCE_DIRECTOR','AR.INVOICE.VIEW'),
  ('FINANCE_DIRECTOR','AR.RECEIPT.RECORD'),
  ('FINANCE_DIRECTOR','AR.RECEIPT.ALLOCATE'),
  ('FINANCE_DIRECTOR','AR.CREDITNOTE'),
  ('FINANCE_DIRECTOR','AR.WRITEOFF'),
  ('FINANCE_DIRECTOR','AR.STATEMENT.VIEW'),
  ('FINANCE_DIRECTOR','AR.OPENING.SET'),
  ('FINANCE_DIRECTOR','AR.DISPUTE.MANAGE'),
  ('FINANCE_DIRECTOR','AP.VIEW'),
  ('FINANCE_DIRECTOR','AP.BILL.ENTER'),
  ('FINANCE_DIRECTOR','AP.BILL.MATCH'),
  ('FINANCE_DIRECTOR','AP.PAYMENT.RUN'),
  ('FINANCE_DIRECTOR','AP.DEBITNOTE'),
  ('FINANCE_DIRECTOR','AP.OPENING.SET'),
  ('FINANCE_DIRECTOR','CASH.VIEW'),
  ('FINANCE_DIRECTOR','CASH.ACCOUNT.MANAGE'),
  ('FINANCE_DIRECTOR','CASH.ENTRY.RECORD'),
  ('FINANCE_DIRECTOR','CASH.RECONCILE'),
  ('FINANCE_DIRECTOR','CASH.TRANSFER'),
  ('FINANCE_DIRECTOR','CHEQUE.MANAGE'),
  ('FINANCE_DIRECTOR','CASH.COUNT.VIEW'),
  ('FINANCE_DIRECTOR','PETTY_CASH.VIEW'),
  ('FINANCE_DIRECTOR','PETTY_CASH.MANAGE'),
  ('FINANCE_DIRECTOR','VAT.VIEW'),
  ('FINANCE_DIRECTOR','VAT.RETURN.PREPARE'),
  ('FINANCE_DIRECTOR','VAT.ADJUST'),
  ('FINANCE_DIRECTOR','WHT.VIEW'),
  ('FINANCE_DIRECTOR','WHT.MANAGE'),
  ('FINANCE_DIRECTOR','WHT.REMIT'),
  ('FINANCE_DIRECTOR','COSTING.VIEW'),
  ('FINANCE_DIRECTOR','COSTING.TAG'),
  ('FINANCE_DIRECTOR','FX.EXPOSURE.VIEW'),
  ('FINANCE_DIRECTOR','FA.VIEW'),
  ('FINANCE_DIRECTOR','FA.CATEGORY.VIEW'),
  ('FINANCE_DIRECTOR','REPORT.VIEW'),
  ('FINANCE_DIRECTOR','REPORT.PL.VIEW'),
  ('FINANCE_DIRECTOR','REPORT.BS.VIEW'),
  ('FINANCE_DIRECTOR','REPORT.CASHFLOW.VIEW'),
  ('FINANCE_DIRECTOR','REPORT.LEDGER.VIEW'),
  ('FINANCE_DIRECTOR','REPORT.EXPORT'),
  ('FINANCE_DIRECTOR','BI.VIEW'),
  ('FINANCE_DIRECTOR','BI.FINANCE.VIEW'),
  ('FINANCE_DIRECTOR','CUSTOMER.VIEW'),
  ('FINANCE_DIRECTOR','SUPPLIER.VIEW'),
  ('FINANCE_DIRECTOR','PRODUCT.VIEW'),
  ('FINANCE_DIRECTOR','UOM.VIEW'),
  ('FINANCE_DIRECTOR','CURRENCY.VIEW'),
  ('FINANCE_DIRECTOR','TAXRATE.VIEW'),
  ('FINANCE_DIRECTOR','PAYMENTTERMS.VIEW'),
  ('FINANCE_DIRECTOR','DOCUMENT.VIEW'),
  ('FINANCE_DIRECTOR','GL.MANAGE'),
  ('FINANCE_DIRECTOR','GL.PERIOD.CLOSE'),
  ('FINANCE_DIRECTOR','GL.YEAR.CLOSE'),
  ('FINANCE_DIRECTOR','VAT.RETURN.FILE'),
  ('FINANCE_DIRECTOR','FX.REVALUE'),
  ('FINANCE_DIRECTOR','CURRENCY.MANAGE'),
  ('FINANCE_DIRECTOR','FA.CATEGORY.MANAGE'),
  ('FINANCE_DIRECTOR','FA.REGISTER.MANAGE'),
  ('FINANCE_DIRECTOR','FA.DEPRECIATE'),
  ('FINANCE_DIRECTOR','FA.DISPOSE'),
  ('FINANCE_DIRECTOR','FA.VERIFY'),
  ('FINANCE_DIRECTOR','BUDGETING.BUDGET.MANAGE'),
  ('FINANCE_DIRECTOR','BUDGETING.BUDGET.SUBMIT'),
  ('FINANCE_DIRECTOR','BUDGETING.BUDGET.APPROVE'),
  ('FINANCE_DIRECTOR','BUDGETING.BUDGET.VIEW'),
  ('FINANCE_DIRECTOR','BUDGETING.REPORT.VIEW'),
  ('FINANCE_DIRECTOR','BUDGETING.REPORT.EXPORT'),
  ('FINANCE_DIRECTOR','COSTING.MANAGE'),
  ('FINANCE_DIRECTOR','APPROVALS.DECIDE'),
  ('FINANCE_DIRECTOR','APPROVALS.POLICY.MANAGE'),
  ('FINANCE_DIRECTOR','APPROVALS.POLICY.VIEW'),
  ('FINANCE_DIRECTOR','APPROVALS.REQUEST.VIEW'),
  ('FINANCE_DIRECTOR','APPROVALS.ADMIN'),
  ('FINANCE_DIRECTOR','BI.OPS.VIEW'),
  ('FINANCE_DIRECTOR','BI.CRM.VIEW'),
  ('FINANCE_DIRECTOR','COMPANY.CURRENCY.CHANGE'),
  ('FINANCE_DIRECTOR','NOTIFICATION.VIEW'),
  ('FINANCE_DIRECTOR','NOTIFICATION.PREFERENCE.MANAGE'),
  ('FINANCE_DIRECTOR','DOCUMENT.RENDER'),
  ('FINANCE_DIRECTOR','BRANCH.VIEW'),
  -- PRODUCTION_MANAGER (22 perms; incl. baseline NOTIFICATION.*/DOCUMENT.RENDER/BRANCH.VIEW)
  ('PRODUCTION_MANAGER','WORKORDER.MANAGE'),
  ('PRODUCTION_MANAGER','WORKORDER.RELEASE'),
  ('PRODUCTION_MANAGER','WORKORDER.CLOSE'),
  ('PRODUCTION_MANAGER','WORKORDER.QC'),
  ('PRODUCTION_MANAGER','MANUFACTURING.VIEW'),
  ('PRODUCTION_MANAGER','BOM.MANAGE'),
  ('PRODUCTION_MANAGER','BOM.VIEW'),
  ('PRODUCTION_MANAGER','STOCK.VIEW'),
  ('PRODUCTION_MANAGER','STOCK.TRANSFER.CREATE'),
  ('PRODUCTION_MANAGER','STOCK.TRANSFER.RECEIVE'),
  ('PRODUCTION_MANAGER','STOCK.TRANSFER.VIEW'),
  ('PRODUCTION_MANAGER','INVENTORY.BATCH.VIEW'),
  ('PRODUCTION_MANAGER','INVENTORY.VALUATION.VIEW'),
  ('PRODUCTION_MANAGER','COSTING.VIEW'),
  ('PRODUCTION_MANAGER','COSTING.TAG'),
  ('PRODUCTION_MANAGER','PRODUCT.VIEW'),
  ('PRODUCTION_MANAGER','UOM.VIEW'),
  ('PRODUCTION_MANAGER','DOCUMENT.VIEW'),
  ('PRODUCTION_MANAGER','NOTIFICATION.VIEW'),
  ('PRODUCTION_MANAGER','NOTIFICATION.PREFERENCE.MANAGE'),
  ('PRODUCTION_MANAGER','DOCUMENT.RENDER'),
  ('PRODUCTION_MANAGER','BRANCH.VIEW')
) AS g(role_code, perm_code)
JOIN roles r ON r.code = g.role_code
JOIN permissions p ON p.code = g.perm_code
ON CONFLICT DO NOTHING;
