-- R__seed_permissions.sql — canonical RBAC permission catalogue (Flyway REPEATABLE migration).
--
-- WHY REPEATABLE: permissions + their ORG_ADMIN grants are CONVERGENT reference data — the table
-- should always equal this list. A repeatable migration re-runs whenever this file's checksum
-- changes and runs AFTER every versioned migration, so adding/renaming a permission is a one-line
-- edit here that CONVERGES on the next migrate, instead of an append-only Vn migration that can only
-- add rows (the trap that left dead SALES.POS.* codes behind after the V43->V83 fix — now gone).
--
-- SAFE TO BE REPEATABLE (unlike per-company CoA/gl_configs seeds, which are FK'd by later versioned
-- migrations and MUST stay inline): nothing in the schema references a permission row at migrate
-- time. The role_permission FK is satisfied because this file inserts permissions before granting.
--
-- The ORG_ADMIN role row itself is created in V1 (foundational); this file only fills its grants.
INSERT INTO permissions (code, module, description) VALUES
    ('AGENT.MANAGE', 'parties', 'Create, update and archive sales agents'),
    ('AGENT.VIEW', 'parties', 'View and select sales agents'),
    ('AP.BILL.ENTER', 'ap', 'Enter a supplier bill (BILL-####) and edit its draft lines'),
    ('AP.BILL.MATCH', 'ap', 'Run / accept the 3-way match; accept an over-tolerance variance'),
    ('AP.DEBITNOTE', 'ap', 'Raise a debit note / adjustment against an open payable'),
    ('AP.OPENING.SET', 'ap', 'Enter AP opening balances at go-live'),
    ('AP.PAYMENT.RUN', 'ap', 'Pay a single bill and run a payment run (PAYRUN-####)'),
    ('AP.VIEW', 'ap', 'View the AP sub-ledger, balances, ageing, and the reconciliation read'),
    ('APPROVALS.ADMIN', 'approvals', 'Recall/cancel any approval request; override a stuck chain'),
    ('APPROVALS.DECIDE', 'approvals', 'Approve/reject approval-request steps and see the approvals inbox'),
    ('APPROVALS.POLICY.MANAGE', 'approvals', 'Create/edit/deactivate approval policies and their step chains'),
    ('APPROVALS.POLICY.VIEW', 'approvals', 'View approval policies'),
    ('APPROVALS.REQUEST.VIEW', 'approvals', 'View approval requests'),
    ('AR.CREDITNOTE', 'ar', 'Raise a credit note that reduces a customer receivable'),
    ('AR.DISPUTE.MANAGE', 'ar', 'Mark/clear an AR invoice as disputed or on-hold and manage dunning state (D-5)'),
    ('AR.INVOICE.VIEW', 'ar', 'View AR open items (the receivable detail)'),
    ('AR.OPENING.SET', 'ar', 'Enter AR opening balances at go-live'),
    ('AR.RECEIPT.ALLOCATE', 'ar', 'Allocate or re-allocate a receipt across open items'),
    ('AR.RECEIPT.RECORD', 'ar', 'Record a customer receipt (RCT-####) and post its cash leg'),
    ('AR.STATEMENT.VIEW', 'ar', 'View or print a customer statement'),
    ('AR.VIEW', 'ar', 'View the AR sub-ledger, balances, ageing, and the reconciliation read'),
    ('AR.WRITEOFF', 'ar', 'Write off an uncollectable open item (bad debt)'),
    ('AUDIT.VIEW', 'iam', 'View the IAM audit trail'),
    ('BI.CRM.VIEW', 'bi', 'View the CRM panel (pipeline value, win-rate, forecast KPIs)'),
    ('BI.EXPORT', 'bi', 'Export the dashboard to PDF / Excel / CSV'),
    ('BI.FINANCE.VIEW', 'bi', 'View the finance panels (revenue/net-profit trend, AR/AP, cash, working capital)'),
    ('BI.OPS.VIEW', 'bi', 'View the operations panels (inventory value, stock health)'),
    ('BI.VIEW', 'bi', 'View the BI / analytics dashboard (the coarse gate for the dashboard route)'),
    ('BOM.MANAGE', 'products', 'Create, edit drafts, add/remove components, activate, archive and clone BOMs'),
    ('BOM.VIEW', 'products', 'View, list, explode, where-used and cost-roll-up for Bills of Materials'),
    ('BRANCH.ASSIGN', 'iam', 'Assign users to branches and set their default branch'),
    ('BRANCH.MANAGE', 'iam', 'Create, update, set-default and archive branches'),
    ('BRANCH.VIEW', 'iam', 'View branches'),
    ('BUDGETING.BUDGET.APPROVE', 'budgeting', 'Approve or reject a submitted budget version'),
    ('BUDGETING.BUDGET.MANAGE', 'budgeting', 'Create budgets; create/edit versions and lines; seed/re-plan'),
    ('BUDGETING.BUDGET.SUBMIT', 'budgeting', 'Submit a budget version for approval; recall a submitted version'),
    ('BUDGETING.BUDGET.VIEW', 'budgeting', 'List and view budgets, versions, and lines'),
    ('BUDGETING.REPORT.EXPORT', 'budgeting', 'Export variance and departmental reports to CSV'),
    ('BUDGETING.REPORT.VIEW', 'budgeting', 'Run the budget-vs-actual variance report and departmental actuals'),
    ('CASH.ACCOUNT.MANAGE', 'cashbank', 'Create/edit/deactivate a cash/bank account, set its GL link, set the company default'),
    ('CASH.ENTRY.RECORD', 'cashbank', 'Record a direct cash/bank entry (bank charge, interest, sundry)'),
    ('CASH.RECONCILE', 'cashbank', 'Perform a manual bank reconciliation (open/mark-cleared/complete)'),
    ('CASH.TRANSFER', 'cashbank', 'Record an inter-account transfer (CBT-####)'),
    ('CASH.VIEW', 'cashbank', 'View cash/bank accounts, balances, statements, and the GL-reconciliation read'),
    ('CHEQUE.MANAGE', 'cashbank', 'Manage the cheque register (register/clear/cancel)'),
    ('COMPANY.MANAGE', 'iam', 'Create, update and archive companies'),
    ('COMPANY.VIEW', 'iam', 'View companies'),
    ('COSTING.MANAGE', 'costing', 'Maintain dimension values (create/edit/deactivate) and set a dimension mandatory/optional'),
    ('COSTING.TAG', 'costing', 'Pick dimension values on a journal / invoice / bill / adjustment when posting'),
    ('COSTING.VIEW', 'costing', 'View dimensions, dimension values (cost centres / departments), and the dimension-sliced trial balance'),
    ('CRM.ACTIVITY.MANAGE', 'crm', 'Log and complete CRM activities and tasks'),
    ('CRM.ACTIVITY.VIEW', 'crm', 'View CRM activities and tasks'),
    ('CRM.LEAD.MANAGE', 'crm', 'Create and edit CRM leads'),
    ('CRM.LEAD.QUALIFY', 'crm', 'Qualify a CRM lead (link or promote to a Parties customer)'),
    ('CRM.LEAD.VIEW', 'crm', 'View CRM leads'),
    ('CRM.OPPORTUNITY.CONVERT', 'crm', 'Convert a CRM opportunity to a quotation or sales order'),
    ('CRM.OPPORTUNITY.MANAGE', 'crm', 'Create and manage CRM opportunities (advance stage, win, lose)'),
    ('CRM.OPPORTUNITY.VIEW', 'crm', 'View CRM opportunities'),
    ('CRM.PIPELINE.VIEW', 'crm', 'View the CRM pipeline, forecast and KPI report'),
    ('CRM.STAGE.MANAGE', 'crm', 'Manage per-company CRM pipeline stages (add, rename, reorder, deactivate)'),
    ('COMPANY.CURRENCY.CHANGE', 'iam', 'Change the company base (ledger) currency — blocked once GL transactions exist (ADR-0039 OQ-CCY-08)'),
    ('CURRENCY.MANAGE', 'fx', 'Create and maintain currency master and exchange rates'),
    ('CURRENCY.VIEW', 'fx', 'View currencies and exchange rates (read-only)'),
    ('CUSTOMER.MANAGE', 'parties', 'Create, update and archive customers'),
    ('CUSTOMER.VIEW', 'parties', 'View and select customers'),
    ('DOCUMENT.BRANDING.MANAGE', 'documents', 'Edit the company branding profile'),
    ('DOCUMENT.RENDER', 'documents', 'Render / download a document PDF'),
    ('DOCUMENT.TEMPLATE.MANAGE', 'documents', 'Toggle document types active/inactive in the registry'),
    ('DOCUMENT.VIEW', 'documents', 'View the generated-documents render log'),
    ('FA.CATEGORY.MANAGE', 'fixedassets', 'Create and manage fixed asset categories'),
    ('FA.CATEGORY.VIEW', 'fixedassets', 'View fixed asset categories'),
    ('FA.DEPRECIATE', 'fixedassets', 'Preview and post the periodic depreciation run'),
    ('FA.DISPOSE', 'fixedassets', 'Dispose, write-off or revalue a fixed asset'),
    ('FA.REGISTER.MANAGE', 'fixedassets', 'Register, edit, place-in-service and transfer assets'),
    ('FA.VERIFY', 'fixedassets', 'Verify / flag a fixed asset (reserved)'),
    ('FA.VIEW', 'fixedassets', 'View fixed asset register, schedules and reconciliation'),
    ('FX.EXPOSURE.VIEW', 'fx', 'View FX exposure report and document FX detail'),
    ('FX.REVALUE', 'fx', 'Preview and post the period-end FX revaluation run'),
    ('GL.MANAGE', 'gl', 'Maintain the chart of accounts and the gl_configs account mapping'),
    ('GL.PERIOD.CLOSE', 'gl', 'Open/close fiscal periods and open a new fiscal year'),
    ('GL.POST', 'gl', 'Post manual journal entries (accruals, adjustments, opening balances)'),
    ('GL.VIEW', 'gl', 'View chart of accounts, posted journals, fiscal periods, and the trial balance'),
    ('GL.YEAR.CLOSE', 'gl', 'Close / reopen a fiscal year — the year-end closing entry + the reopen reversal'),
    ('HR.EMPLOYEE.MANAGE', 'hr', 'Create/update employees, contracts, departments, recurring items (salary data)'),
    ('HR.EMPLOYEE.PAYEE.VIEW', 'hr', 'View sensitive employee payee details (bank account / mobile money) (D-11)'),
    ('HR.EMPLOYEE.VIEW', 'hr', 'View employee, contract, and department records'),
    ('HR.LEAVE.APPROVE', 'hr', 'Approve or reject employee leave requests'),
    ('HR.LEAVE.MANAGE', 'hr', 'Create/manage leave types and balances; submit leave on behalf'),
    ('HR.LEAVE.VIEW', 'hr', 'View leave types, balances, and requests'),
    ('HR.LOAN.MANAGE', 'hr', 'Create and manage employee loans/advances'),
    ('HR.PAYCOMPONENT.MANAGE', 'hr', 'Manage pay-component catalogue (earnings/deduction definitions)'),
    ('HR.PAYROLL.APPROVE', 'hr', 'Approve a calculated payroll run'),
    ('HR.PAYROLL.DISBURSE', 'hr', 'Disburse net wages and statutory payables via Cash & Bank'),
    ('HR.PAYROLL.POST', 'hr', 'Post an approved payroll run to GL'),
    ('HR.PAYROLL.REVERSE', 'hr', 'Reverse a posted payroll run'),
    ('HR.PAYROLL.RUN', 'hr', 'Create payroll runs and trigger calculation'),
    ('HR.PAYROLL.VIEW', 'hr', 'View payroll runs and lines'),
    ('HR.PAYSLIP.VIEW', 'hr', 'View the payslip register and statutory summary (HR/finance scope)'),
    ('HR.SELF.VIEW', 'hr', 'Employee self-service: view own payslips and leave, submit leave requests'),
    ('HR.STATUTORY.MANAGE', 'hr', 'Add effective-dated PAYE band sets and statutory rate sets'),
    ('INVENTORY.BATCH.VIEW', 'stock', 'View batch/lot on-hand, lot numbers, and expiry information'),
    ('INVENTORY.EXPIRY.VIEW', 'stock', 'View the lot expiry / near-expiry report with value at risk'),
    ('INVENTORY.OPENING.SET', 'stock', 'Set the one-time opening inventory valuation (cost/value) for a product'),
    ('INVENTORY.SERIAL.VIEW', 'stock', 'View serial numbers, current status, location, and movement history'),
    ('INVENTORY.VALUATION.VIEW', 'stock', 'View the stock valuation report (qty × avg = value) and the GL reconciliation bar'),
    ('MANUFACTURING.VIEW', 'manufacturing', 'View and list work orders, cost report, WIP recon'),
    ('NOTIFICATION.ADMIN', 'notifications', 'View notification type catalogue, delivery log; enable/disable types per company'),
    ('NOTIFICATION.PREFERENCE.MANAGE', 'notifications', 'Read and set own per-type notification preferences'),
    ('NOTIFICATION.VIEW', 'notifications', 'Read own in-app inbox, unread count, mark-read'),
    ('OTHERPARTY.MANAGE', 'parties', 'Create, update and archive other/misc parties'),
    ('OTHERPARTY.VIEW', 'parties', 'View and select other/misc parties'),
    ('PARTY.BRANCH.ASSIGN', 'parties', 'Associate/dissociate any party with branches of its company'),
    ('PERMISSION.VIEW', 'iam', 'View the permission catalogue'),
    ('POS.SALE.CREATE', 'sales', 'Ring a POS sale on an open session'),
    ('POS.SALE.VOID', 'sales', 'Reverse / void a POS sale at the till (refund)'),
    ('POS.SESSION.CLOSE', 'sales', 'Close an open POS cashier session'),
    ('POS.SESSION.OPEN', 'sales', 'Open a POS cashier session on a till'),
    ('POS.SESSION.RECONCILE', 'sales', 'Reconcile a closed POS session (posts variance to GL)'),
    ('POS.SESSION.VIEW', 'sales', 'View POS cashier sessions and X/Z reads'),
    ('POS.TILL.MANAGE', 'sales', 'Create and manage POS tills (registers)'),
    ('POS.TILL.VIEW', 'sales', 'View POS tills (registers)'),
    ('PRICELIST.MANAGE', 'products', 'Create, update, archive price lists'),
    ('PRICELIST.VIEW', 'products', 'View price lists'),
    ('PRODUCT.BRANCH.ASSIGN', 'products', 'Associate/dissociate a product with branches of its company'),
    ('PRODUCT.MANAGE', 'products', 'Create, update, archive products; manage units, barcodes, prices and recipes'),
    ('PRODUCT.VIEW', 'products', 'View and select products'),
    ('PROJECTS.COSTING.VIEW', 'projects', 'View the project P&L, WIP, and job-cost roll-up'),
    ('PROJECTS.ISSUE.CREATE', 'projects', 'Issue materials from stock to a project'),
    ('PROJECTS.PROJECT.CREATE', 'projects', 'Create a new project'),
    ('PROJECTS.PROJECT.MANAGE', 'projects', 'Edit a project and change its status (activate/hold/complete/cancel)'),
    ('PROJECTS.PROJECT.VIEW', 'projects', 'View project list and project detail'),
    ('PROJECTS.TAG.MANAGE', 'projects', 'Attach, detach, or re-tag a project dimension on a posting'),
    ('PROJECTS.TASK.MANAGE', 'projects', 'Create, edit, and deactivate project tasks'),
    ('PROJECTS.TASK.VIEW', 'projects', 'View project tasks'),
    ('PROJECTS.TIMESHEET.RECORD', 'projects', 'Record project timesheet hours'),
    ('PROJECTS.TIMESHEET.VIEW', 'projects', 'View project timesheets'),
    ('PURCHASE.GOODS_RECEIPT.VIEW', 'purchases', 'View and list/search goods receipts'),
    ('PURCHASE.LANDEDCOST.MANAGE', 'purchases', 'Create and confirm landed-cost allocations'),
    ('PURCHASE.LANDEDCOST.VIEW', 'purchases', 'View landed-cost documents and allocations'),
    ('PURCHASE.ORDER.APPROVE', 'purchases', 'Approve/reject an over-threshold PO (fallback approval gate, ADR-0027 D-6)'),
    ('PURCHASE.ORDER.CREATE', 'purchases', 'Create and edit draft POs; add/edit/remove ordered lines; place; close'),
    ('PURCHASE.ORDER.VIEW', 'purchases', 'View and list/search purchase orders'),
    ('PURCHASE.ORDER.VOID', 'purchases', 'Void a purchase order'),
    ('PURCHASE.RECEIVE', 'purchases', 'Create a draft GR and receive (finalise) it — pushes stock in'),
    ('PURCHASE.REQUISITION.APPROVE', 'purchases', 'Approve/reject a submitted requisition (fallback approval gate, ADR-0027 D-6)'),
    ('PURCHASE.REQUISITION.CREATE', 'purchases', 'Create, edit, submit, cancel a requisition'),
    ('PURCHASE.REQUISITION.VIEW', 'purchases', 'View and list purchase requisitions'),
    ('PURCHASE.RETURN.CREATE', 'purchases', 'Create and confirm a purchase return'),
    ('PURCHASE.RETURN.VIEW', 'purchases', 'View and list purchase returns'),
    ('PURCHASE.RFQ.MANAGE', 'purchases', 'Create/send RFQs, capture supplier quotes, award'),
    ('PURCHASE.RFQ.VIEW', 'purchases', 'View and list RFQs, supplier quotes, and the quote comparison'),
    ('PURCHASE.SETTINGS.MANAGE', 'purchases', 'Set the PO approval threshold and enable flag'),
    ('PURCHASE.VOID', 'purchases', 'Void a finalised goods receipt — reverses stock-in'),
    ('REPORT.BS.VIEW', 'reporting', 'View the Balance Sheet'),
    ('REPORT.CASHFLOW.VIEW', 'reporting', 'View the Cash-Flow Statement (indirect)'),
    ('REPORT.EXPORT', 'reporting', 'Export any statement / the ledger to PDF / Excel / CSV'),
    ('REPORT.LEDGER.VIEW', 'reporting', 'Drill into the GL account-ledger from a statement line'),
    ('REPORT.PL.VIEW', 'reporting', 'View the Income Statement / Profit & Loss'),
    ('REPORT.VIEW', 'reporting', 'View all financial statements + the account-ledger drill-down (coarse)'),
    ('ROLE.MANAGE', 'iam', 'Create and update roles; grant and revoke role assignments'),
    ('ROLE.VIEW', 'iam', 'View roles and their permissions'),
    ('ROUTE.ASSIGN', 'routes', 'Assign/unassign customers and external agents to/from a route; set primary agent'),
    ('ROUTE.MANAGE', 'routes', 'Create, update, archive and restore routes; manage branch associations'),
    ('ROUTE.VIEW', 'routes', 'View, list, search and select routes'),
    ('SALES.BLANKET.CLOSE', 'sales', 'Manually close a blanket order'),
    ('SALES.BLANKET.CREATE', 'sales', 'Create blanket orders with committed quantities'),
    ('SALES.BLANKET.VIEW', 'sales', 'View blanket orders and call-off draw-down'),
    ('SALES.CREDIT.OVERRIDE', 'sales', 'Finalise a credit sale that exceeds the customer credit limit (audited override)'),
    ('SALES.DELIVERY.CREATE', 'sales', 'Create a delivery against a confirmed sales order (issues stock + COGS)'),
    ('SALES.DELIVERY.VIEW', 'sales', 'View delivery documents'),
    ('SALES.DROPSHIP.CREATE', 'sales', 'Flag an SO line as drop-ship and trigger the linked PO'),
    ('SALES.DROPSHIP.VIEW', 'sales', 'View drop-ship SO lines and linked supplier POs'),
    ('SALES.INVOICE.CREATE', 'sales', 'Create and edit draft invoices; add/edit/remove lines; finalise'),
    ('SALES.INVOICE.OVERRIDE', 'sales', 'Override a line unit price / non-default discount / default agent'),
    ('SALES.INVOICE.SETTLE', 'sales', 'Take payment / record tenders against an invoice'),
    ('SALES.INVOICE.VIEW', 'sales', 'View and list/search sales invoices'),
    ('SALES.INVOICE.VOID', 'sales', 'Void a finalised invoice'),
    ('SALES.ORDER.CANCEL', 'sales', 'Cancel a sales order (releases reservation)'),
    ('SALES.ORDER.CONFIRM', 'sales', 'Confirm a sales order (reserves stock)'),
    ('SALES.ORDER.CREATE', 'sales', 'Create and edit draft sales orders'),
    ('SALES.ORDER.VIEW', 'sales', 'View sales orders'),
    ('SALES.PRICING.RULE.MANAGE', 'products', 'Create and manage pricing rules (tiers, customer prices, promotions)'),
    ('SALES.PRICING.RULE.VIEW', 'products', 'View pricing rules (tiers, customer prices, promotions)'),
    ('SALES.QUOTE.ACCEPT', 'sales', 'Accept a quotation and convert it to a sales order'),
    ('SALES.QUOTE.CREATE', 'sales', 'Create and edit draft quotations'),
    ('SALES.QUOTE.SEND', 'sales', 'Send a quotation to the customer (allocates QUOTE-####)'),
    ('SALES.QUOTE.VIEW', 'sales', 'View quotations'),
    ('SALES.RETURN.CREATE', 'sales', 'Create a sales return against a delivery (stock back in + credit note)'),
    ('SALES.RETURN.VIEW', 'sales', 'View sales returns / RMA'),
    ('SALES.STANDING.CREATE', 'sales', 'Create standing / recurring orders'),
    ('SALES.STANDING.GENERATE', 'sales', 'Trigger generation of the next child SO from a standing order'),
    ('SALES.STANDING.VIEW', 'sales', 'View standing / recurring orders'),
    ('STOCK.ADJUST', 'stock', 'Record a manual stock adjustment (+/-) with a reason; set reorder level'),
    ('STOCK.COUNT.CREATE', 'stock', 'Create a stock count, freeze the snapshot, and enter counted quantities'),
    ('STOCK.COUNT.POST', 'stock', 'Post a stock count variance to the books (variance-posting authority)'),
    ('STOCK.COUNT.VIEW', 'stock', 'View stock counts and variance reports'),
    ('STOCK.LOCATION.MANAGE', 'stock', 'Create, edit, deactivate locations and set the branch default'),
    ('STOCK.LOCATION.VIEW', 'stock', 'View stock locations within a branch'),
    ('STOCK.OPENING', 'stock', 'Seed an opening-balance on-hand for a never-tracked product at a branch'),
    ('STOCK.TRANSFER.CREATE', 'stock', 'Create and dispatch an inter-location stock transfer'),
    ('STOCK.TRANSFER.RECEIVE', 'stock', 'Receive an in-transit transfer at the destination location'),
    ('STOCK.TRANSFER.VIEW', 'stock', 'View inter-location stock transfers'),
    ('STOCK.VIEW', 'stock', 'View on-hand levels and movement history'),
    ('SUPPLIER.MANAGE', 'parties', 'Create, update and archive suppliers'),
    ('SUPPLIER.VIEW', 'parties', 'View and select suppliers'),
    ('TAXRATE.MANAGE', 'sales', 'Maintain company VAT rates'),
    ('TAXRATE.VIEW', 'sales', 'View company VAT rates'),
    ('UOM.MANAGE', 'products', 'Create, update, archive and restore units of measure'),
    ('UOM.VIEW', 'products', 'View units of measure'),
    ('USER.MANAGE', 'iam', 'Create, update, disable and unlock users; set passwords'),
    ('USER.VIEW', 'iam', 'View users'),
    ('VAT.ADJUST', 'tax', 'Add / remove adjustment lines on a DRAFT return'),
    ('VAT.RETURN.FILE', 'tax', 'File a VAT return — the lock + the synchronous GL settlement post'),
    ('VAT.RETURN.PREPARE', 'tax', 'Open / compute / recompute a DRAFT VAT return'),
    ('VAT.VIEW', 'tax', 'View VAT returns (face + band breakdown) and the WHT register'),
    ('WHT.MANAGE', 'tax', 'Manage WHT rates/types; capture WHT on an AP payment / AR receipt; issue certificates'),
    ('WHT.REMIT', 'tax', 'Mark a WHT transaction as remitted to the tax authority (flag-on-row, ADR-0040 D-7)'),
    ('WHT.VIEW', 'tax', 'Read WHT transactions / the WHT register'),
    ('WORKORDER.CLOSE', 'manufacturing', 'Close a completed work order (variance-clear, finance act)'),
    ('WORKORDER.MANAGE', 'manufacturing', 'Create / edit draft / issue / apply-cost / complete / cancel work orders + add operations'),
    ('WORKORDER.QC', 'manufacturing', 'RESERVED — no workflow in v1; hook for future QC workflow'),
    ('WORKORDER.RELEASE', 'manufacturing', 'Release a planned work order (BOM explosion + component plan)'),
    ('PAYMENTTERMS.VIEW', 'parties', 'View payment terms masters'),
    ('PAYMENTTERMS.MANAGE', 'parties', 'Create, update and archive payment terms masters')
ON CONFLICT (code) DO UPDATE
    SET module = EXCLUDED.module, description = EXCLUDED.description;

-- Grant the entire catalogue to the global ORG_ADMIN role (created in V1). CROSS JOIN over the
-- permissions table => ORG_ADMIN always holds every permission, including ones added above later.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM   roles r
CROSS JOIN permissions p
WHERE  r.code = 'ORG_ADMIN'
ON CONFLICT DO NOTHING;
