-- V10 — General Ledger module: companies.base_currency + chart_of_accounts + fiscal_years +
-- fiscal_periods + journal_batches + journal_entries + journal_lines + gl_configs + permissions +
-- TZ CoA seed + fiscal-year/period seed + gl_configs seed.
-- Additive only. V1–V9 are FROZEN.
-- Order per ADR-0013 D-16: base_currency → CoA → fiscal_years → fiscal_periods →
-- journal_batches → journal_entries → journal_lines → gl_configs → indexes →
-- permission seed → CoA seed → fiscal seed → gl_configs seed.

-- ============================================================================
-- (1) ADD companies.base_currency — closing ADR-0005 D-4 (OWNER-RESOLVED D-9)
-- Additive ALTER; DEFAULT 'TZS' backfills all existing rows.
-- ============================================================================
ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS base_currency VARCHAR(3) NOT NULL DEFAULT 'TZS';

-- ============================================================================
-- (2) chart_of_accounts (per-company master, ADR-0013 D-2a)
-- ============================================================================
CREATE TABLE chart_of_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)     NOT NULL,
    company_id       BIGINT          NOT NULL,
    account_code     VARCHAR(20)     NOT NULL,
    name             VARCHAR(160)    NOT NULL,
    account_type     VARCHAR(20)     NOT NULL,  -- ASSET|LIABILITY|EQUITY|INCOME|EXPENSE
    normal_balance   VARCHAR(10)     NOT NULL,  -- DEBIT|CREDIT; stored, derived-from-type at write
    parent_id        BIGINT,                    -- self-FK; reserved for later grouping; NULL in v1
    is_active        BOOLEAN         NOT NULL DEFAULT true,
    allow_manual_posting BOOLEAN     NOT NULL DEFAULT true,
    status           VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    currency         VARCHAR(3),                 -- P2-M1: locks account to one currency (NULL = multi-currency)
    -- P2-D4 (ADR-0041): per-account dimension-requirement flags. When true, a MANUAL journal line
    -- to this account must carry the corresponding dimension value (enforced in GLPostingServiceImpl,
    -- MANUAL-only — system/event-driven posters are exempt, mirroring the Step-3 mandatory-slot rule).
    require_cost_centre  BOOLEAN     NOT NULL DEFAULT false,
    require_department   BOOLEAN     NOT NULL DEFAULT false,
    require_project      BOOLEAN     NOT NULL DEFAULT false,
    -- P3: convenience/reporting columns (all nullable, additive).
    default_tax_code VARCHAR(30),                -- default tax tag suggested when posting to this account
    effective_from   DATE,                       -- account availability window (NULL = always)
    effective_to     DATE,
    description      VARCHAR(255),               -- free-text account description / notes
    version          BIGINT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,

    CONSTRAINT uq_chart_of_account_uid          UNIQUE (uid),
    CONSTRAINT uq_chart_of_account_company_code UNIQUE (company_id, account_code),
    CONSTRAINT fk_chart_of_account_company      FOREIGN KEY (company_id)
        REFERENCES companies (id),
    CONSTRAINT fk_chart_of_account_parent       FOREIGN KEY (parent_id)
        REFERENCES chart_of_accounts (id),
    control_type     VARCHAR(24),                -- D-1: NULL = ordinary account; non-null = control

    CONSTRAINT chk_chart_of_account_type        CHECK (
        account_type IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
    CONSTRAINT chk_chart_of_account_normal_balance CHECK (
        normal_balance IN ('DEBIT','CREDIT')),
    CONSTRAINT chk_chart_of_account_control_type CHECK (
        control_type IS NULL OR control_type IN (
            'AR','AP','BANK','CASH','INVENTORY','TAX','PAYROLL_CLEARING','FX_CLEARING'))
);

-- ============================================================================
-- (3) fiscal_years (per-company master, ADR-0013 D-2b)
-- ============================================================================
CREATE TABLE fiscal_years (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid          VARCHAR(26)     NOT NULL,
    company_id   BIGINT          NOT NULL,
    year_code    VARCHAR(12)     NOT NULL,
    name         VARCHAR(120),                   -- P3: human label (e.g. "Fiscal Year 2026"); nullable
    start_month  INTEGER         NOT NULL,
    start_date   DATE            NOT NULL,
    end_date     DATE            NOT NULL,
    status       VARCHAR(20)     NOT NULL DEFAULT 'OPEN',
    version      BIGINT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT,
    reopened_at  TIMESTAMPTZ,                    -- P2-M1: reopen audit trail (last reopen action)
    reopened_by  BIGINT,                         -- P2-M1: app_users.id of the reopening actor

    CONSTRAINT uq_fiscal_year_uid              UNIQUE (uid),
    CONSTRAINT uq_fiscal_year_company_code     UNIQUE (company_id, year_code),
    CONSTRAINT fk_fiscal_year_company          FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_fiscal_year_start_month     CHECK (start_month BETWEEN 1 AND 12),
    CONSTRAINT chk_fiscal_year_status          CHECK (status IN ('OPEN','CLOSED'))
);

-- ============================================================================
-- (4) fiscal_periods (child of fiscal_years, ADR-0013 D-2b)
-- ============================================================================
CREATE TABLE fiscal_periods (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid            VARCHAR(26)     NOT NULL,
    company_id     BIGINT          NOT NULL,
    fiscal_year_id BIGINT          NOT NULL,
    period_no      INTEGER         NOT NULL,
    name           VARCHAR(60),                  -- P3: human label (e.g. "Jan 2026"); nullable
    start_date     DATE            NOT NULL,
    end_date       DATE            NOT NULL,
    status         VARCHAR(20)     NOT NULL DEFAULT 'OPEN',
    closed_at      TIMESTAMPTZ,
    closed_by      BIGINT,
    reopened_at    TIMESTAMPTZ,                  -- P3: reopen audit trail (mirror fiscal_years); last reopen action
    reopened_by    BIGINT,                       -- P3: app_users.id of the reopening actor
    version        BIGINT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,

    CONSTRAINT uq_fiscal_period_uid      UNIQUE (uid),
    CONSTRAINT uq_fiscal_period_year_no  UNIQUE (fiscal_year_id, period_no),
    CONSTRAINT fk_fiscal_period_company  FOREIGN KEY (company_id)     REFERENCES companies (id),
    CONSTRAINT fk_fiscal_period_year     FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_years (id),
    CONSTRAINT fk_fiscal_period_closed_by FOREIGN KEY (closed_by)     REFERENCES app_users (id),
    CONSTRAINT chk_fiscal_period_no      CHECK (period_no BETWEEN 1 AND 12),
    CONSTRAINT chk_fiscal_period_status  CHECK (status IN ('OPEN','CLOSED')),
    CONSTRAINT chk_fiscal_period_dates   CHECK (end_date >= start_date)
);

-- ============================================================================
-- (5) journal_batches (numbered container, ADR-0013 D-2c)
-- No updated_* columns — append-only (BR-GL-02).
-- ============================================================================
CREATE TABLE journal_batches (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           VARCHAR(26)     NOT NULL,
    company_id    BIGINT          NOT NULL,
    branch_id     BIGINT,
    batch_number  VARCHAR(30)     NOT NULL,
    source_type   VARCHAR(20)     NOT NULL,
    description   VARCHAR(255),
    posted_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    posted_by     BIGINT,
    version       BIGINT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by    BIGINT,
    total_debit   NUMERIC(19,4),                 -- P2-M1: denormalised control totals (populated on post)
    total_credit  NUMERIC(19,4),
    reversed_by_batch_id BIGINT,                  -- P3: self soft-FK to the batch that reverses THIS one (batch-level reversal linkage)

    CONSTRAINT uq_journal_batch_uid            UNIQUE (uid),
    CONSTRAINT uq_journal_batch_company_number UNIQUE (company_id, batch_number),
    CONSTRAINT fk_journal_batch_company        FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_journal_batch_branch         FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT fk_journal_batch_posted_by      FOREIGN KEY (posted_by)  REFERENCES app_users (id),
    CONSTRAINT fk_journal_batch_reversed_by    FOREIGN KEY (reversed_by_batch_id) REFERENCES journal_batches (id),
    CONSTRAINT chk_journal_batch_source_type   CHECK (
        source_type IN ('MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE'))
);

-- ============================================================================
-- (6) journal_entries (one balanced transaction, ADR-0013 D-2c)
-- No updated_* columns — append-only (BR-GL-02).
-- ============================================================================
CREATE TABLE journal_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)     NOT NULL,
    company_id       BIGINT          NOT NULL,
    branch_id        BIGINT,
    batch_id         BIGINT          NOT NULL,
    entry_no         INTEGER         NOT NULL DEFAULT 1,
    posting_date     DATE            NOT NULL,
    fiscal_period_id BIGINT          NOT NULL,
    description      VARCHAR(255)    NOT NULL,
    source_type      VARCHAR(20)     NOT NULL,
    source_ref       VARCHAR(60),
    reversal_of_id   BIGINT,
    posted_at        TIMESTAMPTZ     NOT NULL DEFAULT now(),
    posted_by        BIGINT,
    version          BIGINT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,
    reversed_by_entry_id BIGINT,                 -- P2-M1: self-ref id of the entry that reversed THIS one
    reversed         BOOLEAN         NOT NULL DEFAULT false,  -- P2-M1: denormalised "has been reversed" flag
    header_currency  VARCHAR(3),                 -- P2-M1: informational source-doc currency (ledger stays base-only)
    total_debit      NUMERIC(19,4),              -- P2-M1: denormalised control totals
    total_credit     NUMERIC(19,4),
    -- P3: classification / convenience columns (all nullable, additive).
    entry_type       VARCHAR(20),                -- GENERAL|ADJUSTING|REVERSING|OPENING|CLOSING|ACCRUAL (informational; CHECK below)
    value_date       DATE,                       -- business value/effective date (distinct from posting_date)
    external_ref     VARCHAR(60),                -- external system / document reference
    attachment_ref   VARCHAR(255),               -- link/uid to a supporting attachment

    CONSTRAINT uq_journal_entry_uid        UNIQUE (uid),
    CONSTRAINT uq_journal_entry_batch_no   UNIQUE (batch_id, entry_no),
    -- Idempotency backstop: one SALES/SALES_REVERSAL entry per (company, source_ref) partial unique.
    -- NULLs in source_ref are distinct so MANUAL/OPENING_BALANCE (often NULL source_ref) coexist.
    CONSTRAINT uq_journal_entry_sales_source UNIQUE (company_id, source_type, source_ref)
        DEFERRABLE INITIALLY DEFERRED,
    -- Note: the partial unique below replaces the above with a WHERE clause for correctness.
    CONSTRAINT fk_journal_entry_company    FOREIGN KEY (company_id)       REFERENCES companies (id),
    CONSTRAINT fk_journal_entry_branch     FOREIGN KEY (branch_id)        REFERENCES branches (id),
    CONSTRAINT fk_journal_entry_batch      FOREIGN KEY (batch_id)         REFERENCES journal_batches (id),
    CONSTRAINT fk_journal_entry_period     FOREIGN KEY (fiscal_period_id) REFERENCES fiscal_periods (id),
    CONSTRAINT fk_journal_entry_reversal_of FOREIGN KEY (reversal_of_id)  REFERENCES journal_entries (id),
    CONSTRAINT fk_journal_entry_posted_by  FOREIGN KEY (posted_by)        REFERENCES app_users (id),
    CONSTRAINT chk_journal_entry_source_type CHECK (
        source_type IN ('MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE')),
    CONSTRAINT chk_journal_entry_entry_type CHECK (
        entry_type IS NULL OR entry_type IN (
            'GENERAL','ADJUSTING','REVERSING','OPENING','CLOSING','ACCRUAL'))
);

-- Drop the overly broad unique and replace with a proper partial unique (ADR-0013 D-2c).
ALTER TABLE journal_entries DROP CONSTRAINT IF EXISTS uq_journal_entry_sales_source;
CREATE UNIQUE INDEX uq_journal_entry_sales_source
    ON journal_entries (company_id, source_type, source_ref)
    WHERE source_type IN ('SALES','SALES_REVERSAL');

-- ============================================================================
-- (7) journal_lines (one leg of an entry, ADR-0013 D-2c)
-- No updated_* columns — append-only (BR-GL-02).
-- ============================================================================
CREATE TABLE journal_lines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid            VARCHAR(26)     NOT NULL,
    company_id     BIGINT          NOT NULL,
    branch_id      BIGINT,
    entry_id       BIGINT          NOT NULL,
    line_no        INTEGER         NOT NULL,
    account_id     BIGINT          NOT NULL,
    debit_amount   NUMERIC(19,4)   NOT NULL DEFAULT 0,
    credit_amount  NUMERIC(19,4)   NOT NULL DEFAULT 0,
    currency       VARCHAR(3)      NOT NULL,
    line_memo      VARCHAR(255),
    version        BIGINT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by     BIGINT,
    tax_code       VARCHAR(30),                  -- P2-M1: informational tax tag (does not drive posting)
    tax_amount     NUMERIC(19,4),
    -- P3: statistical quantity postings + GL reconciliation marker (all nullable, additive).
    statistical_quantity NUMERIC(19,4),          -- non-monetary quantity carried on the line (e.g. headcount, units)
    statistical_uom      VARCHAR(20),            -- unit for statistical_quantity
    reconciliation_marker VARCHAR(40),           -- GL reconciliation/clearing group marker
    cleared              BOOLEAN     NOT NULL DEFAULT false,  -- reconciliation cleared flag

    CONSTRAINT uq_journal_line_uid      UNIQUE (uid),
    CONSTRAINT uq_journal_line_entry_no UNIQUE (entry_id, line_no),
    CONSTRAINT fk_journal_line_company  FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_journal_line_branch   FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT fk_journal_line_entry    FOREIGN KEY (entry_id)   REFERENCES journal_entries (id),
    CONSTRAINT fk_journal_line_account  FOREIGN KEY (account_id) REFERENCES chart_of_accounts (id),
    -- Single-row half of the double-entry invariant (BR-GL-08):
    CONSTRAINT chk_journal_line_one_side CHECK (
        (debit_amount > 0 AND credit_amount = 0)
        OR (credit_amount > 0 AND debit_amount = 0)
    ),
    CONSTRAINT chk_journal_line_nonneg CHECK (
        debit_amount >= 0 AND credit_amount >= 0
    )
);

-- ============================================================================
-- (8) gl_configs (account mapping per company, key/value, ADR-0013 D-2d)
-- ============================================================================
CREATE TABLE gl_configs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)     NOT NULL,
    company_id  BIGINT          NOT NULL,
    config_key  VARCHAR(40)     NOT NULL,
    account_id  BIGINT          NOT NULL,
    version     BIGINT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,

    CONSTRAINT uq_gl_config_uid         UNIQUE (uid),
    CONSTRAINT uq_gl_config_company_key UNIQUE (company_id, config_key),
    CONSTRAINT fk_gl_config_company     FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_gl_config_account     FOREIGN KEY (account_id) REFERENCES chart_of_accounts (id),
    CONSTRAINT chk_gl_config_key        CHECK (
        config_key IN (
            'SALES_REVENUE','VAT_PAYABLE','ACCOUNTS_RECEIVABLE','CASH',
            'INVENTORY','COGS','ACCOUNTS_PAYABLE'
        ))
);

-- ============================================================================
-- (9) Indexes (ADR-0013 D-2a/b/c/d)
-- ============================================================================

-- chart_of_accounts
CREATE INDEX ix_chart_of_accounts_company
    ON chart_of_accounts (company_id);
CREATE INDEX ix_chart_of_accounts_company_type
    ON chart_of_accounts (company_id, account_type);
CREATE INDEX ix_chart_of_accounts_active
    ON chart_of_accounts (company_id) WHERE is_active = true;
CREATE INDEX ix_chart_of_accounts_control
    ON chart_of_accounts (company_id, control_type) WHERE control_type IS NOT NULL;

-- fiscal_years
CREATE INDEX ix_fiscal_years_company
    ON fiscal_years (company_id);

-- fiscal_periods
CREATE INDEX ix_fiscal_periods_company_dates
    ON fiscal_periods (company_id, start_date, end_date);
CREATE INDEX ix_fiscal_periods_year
    ON fiscal_periods (fiscal_year_id, period_no);

-- journal_batches
CREATE INDEX ix_journal_batches_company
    ON journal_batches (company_id);

-- journal_entries
CREATE INDEX ix_journal_entries_company_period
    ON journal_entries (company_id, fiscal_period_id);
CREATE INDEX ix_journal_entries_company_date
    ON journal_entries (company_id, posting_date);
CREATE INDEX ix_journal_entries_source
    ON journal_entries (company_id, source_type, source_ref);
CREATE INDEX ix_journal_entries_reversal_of
    ON journal_entries (reversal_of_id)
    WHERE reversal_of_id IS NOT NULL;

-- journal_lines
CREATE INDEX ix_journal_lines_company_account
    ON journal_lines (company_id, account_id);
CREATE INDEX ix_journal_lines_entry
    ON journal_lines (entry_id);
CREATE INDEX ix_journal_lines_company_branch
    ON journal_lines (company_id, branch_id);

-- gl_configs
CREATE INDEX ix_gl_configs_company
    ON gl_configs (company_id);

-- ============================================================================
-- (10) Permission seed + ORG_ADMIN grant (ADR-0013 D-14; mirror V7/V9 pattern)
-- ============================================================================


-- ============================================================================
-- (11) CoA seed — standard TZ small-business chart of accounts, per existing company
-- (ADR-0013 D-15). Deterministic seed UIDs. All accounts is_active = true.
-- The migrate seeds the CURRENT companies; new companies are seeded by ChartOfAccountSeeder.
-- ============================================================================
INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'SEED' || lpad(c.id::text, 6, '0') || a.code AS uid,
    c.id,
    a.code,
    a.name,
    a.account_type,
    a.normal_balance,
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
CROSS JOIN (VALUES
    ('1000', 'Cash',                    'ASSET',     'DEBIT'),
    ('1100', 'Bank',                    'ASSET',     'DEBIT'),
    ('1200', 'Accounts Receivable',     'ASSET',     'DEBIT'),
    ('1300', 'Inventory',               'ASSET',     'DEBIT'),
    ('2100', 'Accounts Payable',        'LIABILITY', 'CREDIT'),
    ('2200', 'VAT Payable',             'LIABILITY', 'CREDIT'),
    ('3000', 'Owner''s Equity / Capital', 'EQUITY',  'CREDIT'),
    ('3900', 'Retained Earnings',       'EQUITY',    'CREDIT'),
    ('4100', 'Sales Revenue',           'INCOME',    'CREDIT'),
    ('5100', 'Cost of Goods Sold',      'EXPENSE',   'DEBIT'),
    ('5200', 'Rent Expense',            'EXPENSE',   'DEBIT'),
    ('5300', 'Salaries & Wages',        'EXPENSE',   'DEBIT'),
    ('5400', 'Utilities',               'EXPENSE',   'DEBIT')
) AS a(code, name, account_type, normal_balance)
ON CONFLICT (company_id, account_code) DO NOTHING;

-- D-1 (ADR-0040): classify the seeded sub-ledger control accounts. CASH/BANK are classified yet
-- stay manually postable (reconciled via the cash/bank module + bank reconciliation, which expect
-- manual journals for bank charges/interest/corrections); the genuine reconciliation controls
-- (AR/AP/INVENTORY/TAX) block direct manual journals. Mirrors ChartOfAccountServiceImpl.seedDefaults
-- so the migrate-seeded path and the new-company path agree. (No-op on a fresh DB with no companies.)
UPDATE chart_of_accounts SET
    control_type = CASE account_code
        WHEN '1000' THEN 'CASH'
        WHEN '1100' THEN 'BANK'
        WHEN '1200' THEN 'AR'
        WHEN '1300' THEN 'INVENTORY'
        WHEN '2100' THEN 'AP'
        WHEN '2200' THEN 'TAX'
    END,
    allow_manual_posting = CASE
        WHEN account_code IN ('1200','1300','2100','2200') THEN false
        ELSE allow_manual_posting
    END
WHERE account_code IN ('1000','1100','1200','1300','2100','2200');

-- ============================================================================
-- (12) Fiscal year + 12 period seed — current FY per existing company (ADR-0013 D-4/D-16)
-- Uses start_month = 1 (January) default. The year covers the current calendar year.
-- ============================================================================
INSERT INTO fiscal_years (
    uid, company_id, year_code, start_month,
    start_date, end_date, status, version, created_at
)
SELECT
    'FYSD' || lpad(c.id::text, 10, '0') AS uid,
    c.id,
    'FY' || extract(year FROM now())::text,
    1,
    (extract(year FROM now())::text || '-01-01')::date,
    (extract(year FROM now())::text || '-12-31')::date,
    'OPEN',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, year_code) DO NOTHING;

-- Seed 12 periods for each just-seeded fiscal year (generate_series 1..12)
INSERT INTO fiscal_periods (
    uid, company_id, fiscal_year_id, period_no,
    start_date, end_date, status, version, created_at
)
SELECT
    'FPSD' || lpad(fy.company_id::text, 8, '0') || lpad(p.period_no::text, 2, '0') AS uid,
    fy.company_id,
    fy.id,
    p.period_no,
    -- start: first day of the month (period_no months offset from Jan of the FY year)
    (extract(year FROM fy.start_date)::text
        || '-' || lpad(p.period_no::text, 2, '0') || '-01')::date,
    -- end: last day of that month
    ((extract(year FROM fy.start_date)::text
        || '-' || lpad(p.period_no::text, 2, '0') || '-01')::date
        + interval '1 month' - interval '1 day')::date,
    'OPEN',
    0,
    now()
FROM fiscal_years fy
CROSS JOIN generate_series(1, 12) AS p(period_no)
WHERE fy.year_code = 'FY' || extract(year FROM now())::text
ON CONFLICT (fiscal_year_id, period_no) DO NOTHING;

-- ============================================================================
-- (13) gl_configs default mapping seed per existing company (ADR-0013 D-15)
-- Resolves account_id by joining the just-seeded chart_of_accounts on (company_id, account_code).
-- ============================================================================
INSERT INTO gl_configs (uid, company_id, config_key, account_id, version, created_at)
SELECT
    -- <=26-char uid: prefix + 6-digit company + 12-hex md5(key). Concatenating the raw
    -- config_key overflowed uid VARCHAR(26) for long keys (e.g. ACCOUNTS_RECEIVABLE) when this
    -- seed runs on a DB that already has companies (keep-data upgrade) -- ISSUES-REGISTER #12.
    'GC' || lpad(coa.company_id::text, 6, '0') || substr(md5(m.config_key), 1, 12) AS uid,
    coa.company_id,
    m.config_key,
    coa.id,
    0,
    now()
FROM (VALUES
    ('SALES_REVENUE',      '4100'),
    ('VAT_PAYABLE',        '2200'),
    ('ACCOUNTS_RECEIVABLE','1200'),
    ('CASH',               '1000'),
    ('INVENTORY',          '1300'),
    ('COGS',               '5100'),
    ('ACCOUNTS_PAYABLE',   '2100')
) AS m(config_key, account_code)
JOIN chart_of_accounts coa ON coa.account_code = m.account_code
ON CONFLICT (company_id, config_key) DO NOTHING;
