-- V11 — Accounts Receivable module (ADR-0014): ar_invoices, ar_receipts,
-- ar_receipt_allocations, ar_credit_notes, ar_write_offs; CoA seed (5500, 3100);
-- gl_configs CHECK widen + BAD_DEBT_EXPENSE / OPENING_BALANCE_EQUITY keys;
-- journal source-type CHECK widen (AR_RECEIPT, AR_WRITEOFF, AR_CREDIT_NOTE);
-- permissions seed + ORG_ADMIN grant.
-- Additive only. V1–V10 are FROZEN.
-- Order per ADR-0014 D-14: ar_invoices → ar_receipts → ar_receipt_allocations →
-- ar_credit_notes → ar_write_offs → indexes → CoA seed → gl_configs → source-type →
-- permission seed.

-- ============================================================================
-- (1) ar_invoices — the open items (the sub-ledger detail behind GL 1200)
-- ============================================================================
CREATE TABLE ar_invoices (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)     NOT NULL,
    company_id           BIGINT          NOT NULL,
    branch_id            BIGINT,
    customer_id          BIGINT          NOT NULL,
    source               VARCHAR(20)     NOT NULL,
    source_invoice_uid   VARCHAR(26),
    document_no          VARCHAR(30),
    original_amount      NUMERIC(19,4)   NOT NULL,
    outstanding_amount   NUMERIC(19,4)   NOT NULL,
    currency             VARCHAR(3)      NOT NULL,
    invoice_date         DATE            NOT NULL,
    due_date             DATE            NOT NULL,
    status               VARCHAR(20)     NOT NULL DEFAULT 'OPEN',
    version              BIGINT          NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,

    CONSTRAINT uq_ar_invoice_uid        UNIQUE (uid),
    CONSTRAINT fk_ar_invoice_company    FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_ar_invoice_branch     FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_ar_invoice_customer   FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT chk_ar_invoice_source    CHECK (source IN ('SALE','OPENING_BALANCE')),
    CONSTRAINT chk_ar_invoice_status    CHECK (status IN ('OPEN','PARTIAL','PAID','WRITTEN_OFF')),
    CONSTRAINT chk_ar_invoice_amounts   CHECK (
        original_amount > 0
        AND outstanding_amount >= 0
        AND outstanding_amount <= original_amount),
    CONSTRAINT chk_ar_invoice_dates     CHECK (due_date >= invoice_date)
);

-- Partial unique: one open item per source invoice per company (FR-AR-04, BR-AR-08)
CREATE UNIQUE INDEX uq_ar_invoice_source_sale
    ON ar_invoices (company_id, source_invoice_uid)
    WHERE source = 'SALE';

-- ============================================================================
-- (2) ar_receipts — money received (RCT-####)
-- ============================================================================
CREATE TABLE ar_receipts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT,
    customer_id         BIGINT          NOT NULL,
    receipt_number      VARCHAR(30)     NOT NULL,
    receipt_date        DATE            NOT NULL,
    amount              NUMERIC(19,4)   NOT NULL,
    unallocated_amount  NUMERIC(19,4)   NOT NULL,
    currency            VARCHAR(3)      NOT NULL,
    tender_type         VARCHAR(20)     NOT NULL,
    bank_reference      VARCHAR(80),
    gl_entry_uid        VARCHAR(26),
    status              VARCHAR(20)     NOT NULL DEFAULT 'UNALLOCATED',
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_ar_receipt_uid            UNIQUE (uid),
    CONSTRAINT uq_ar_receipt_company_number UNIQUE (company_id, receipt_number),
    CONSTRAINT fk_ar_receipt_company        FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_ar_receipt_branch         FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_ar_receipt_customer       FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT chk_ar_receipt_amount        CHECK (amount > 0),
    CONSTRAINT chk_ar_receipt_unallocated   CHECK (
        unallocated_amount >= 0 AND unallocated_amount <= amount),
    CONSTRAINT chk_ar_receipt_tender        CHECK (
        tender_type IN ('CASH','BANK_TRANSFER','MOBILE_MONEY')),
    CONSTRAINT chk_ar_receipt_status        CHECK (
        status IN ('UNALLOCATED','PARTIAL','ALLOCATED'))
);

-- ============================================================================
-- (3) ar_receipt_allocations — junction: receipt ↔ open item (singular per convention)
-- ============================================================================
CREATE TABLE ar_receipt_allocations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT          NOT NULL,
    receipt_id       BIGINT          NOT NULL,
    ar_invoice_id    BIGINT          NOT NULL,
    allocated_amount NUMERIC(19,4)   NOT NULL,
    allocated_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    allocated_by     BIGINT,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,

    CONSTRAINT uq_ar_receipt_allocation_pair UNIQUE (receipt_id, ar_invoice_id),
    CONSTRAINT fk_ar_receipt_allocation_company FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT fk_ar_receipt_allocation_receipt FOREIGN KEY (receipt_id)    REFERENCES ar_receipts (id),
    CONSTRAINT fk_ar_receipt_allocation_invoice FOREIGN KEY (ar_invoice_id) REFERENCES ar_invoices (id),
    CONSTRAINT chk_ar_receipt_allocation_amount CHECK (allocated_amount > 0)
);

-- ============================================================================
-- (4) ar_credit_notes — reduce a receivable (CRN-####)
-- ============================================================================
CREATE TABLE ar_credit_notes (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                   VARCHAR(26)     NOT NULL,
    company_id            BIGINT          NOT NULL,
    branch_id             BIGINT,
    customer_id           BIGINT          NOT NULL,
    credit_note_number    VARCHAR(30)     NOT NULL,
    ar_invoice_id         BIGINT,
    note_date             DATE            NOT NULL,
    amount                NUMERIC(19,4)   NOT NULL,
    net_amount            NUMERIC(19,4)   NOT NULL,
    vat_amount            NUMERIC(19,4)   NOT NULL DEFAULT 0,
    currency              VARCHAR(3)      NOT NULL,
    reason                VARCHAR(255)    NOT NULL,
    origin                VARCHAR(20)     NOT NULL DEFAULT 'STANDALONE',
    gl_entry_uid          VARCHAR(26),
    -- D-6: unapplied tracking + base capture + FX rate (ADR-0040 D-6, receipt parity)
    unapplied_amount      NUMERIC(19,4)   NOT NULL DEFAULT 0,
    base_amount           NUMERIC(19,4),
    base_unapplied_amount NUMERIC(19,4),
    fx_rate               NUMERIC(19,8)   NOT NULL DEFAULT 1,
    rate_at               TIMESTAMPTZ,
    status                VARCHAR(20)     NOT NULL DEFAULT 'UNAPPLIED',
    version               BIGINT          NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ,
    updated_by            BIGINT,

    CONSTRAINT uq_ar_credit_note_uid            UNIQUE (uid),
    CONSTRAINT uq_ar_credit_note_company_number UNIQUE (company_id, credit_note_number),
    CONSTRAINT fk_ar_credit_note_company        FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT fk_ar_credit_note_branch         FOREIGN KEY (branch_id)     REFERENCES branches (id),
    CONSTRAINT fk_ar_credit_note_customer       FOREIGN KEY (customer_id)   REFERENCES customers (id),
    CONSTRAINT fk_ar_credit_note_invoice        FOREIGN KEY (ar_invoice_id) REFERENCES ar_invoices (id),
    CONSTRAINT chk_ar_credit_note_amount        CHECK (
        amount > 0 AND net_amount >= 0 AND vat_amount >= 0),
    CONSTRAINT chk_ar_credit_note_origin        CHECK (
        origin IN ('STANDALONE','SALE_VOID')),
    CONSTRAINT chk_ar_credit_note_unapplied     CHECK (
        unapplied_amount >= 0 AND unapplied_amount <= amount),
    CONSTRAINT chk_ar_credit_note_status        CHECK (
        status IN ('UNAPPLIED','PARTIAL','APPLIED'))
);

-- ============================================================================
-- (4b) ar_credit_note_allocations — junction: CN ↔ open item (ADR-0040 D-6)
--      No uid (junction convention, mirrors ar_receipt_allocations).
--      Append-only; reapply = delete + re-insert; posting nothing to GL (only FX plug).
-- ============================================================================
CREATE TABLE ar_credit_note_allocations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            BIGINT          NOT NULL,
    credit_note_id        BIGINT          NOT NULL,
    ar_invoice_id         BIGINT          NOT NULL,
    allocated_amount      NUMERIC(19,4)   NOT NULL,
    base_allocated_amount NUMERIC(19,4),
    settlement_rate       NUMERIC(19,8),
    allocated_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    allocated_by          BIGINT,
    created_at            TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by            BIGINT,

    CONSTRAINT uq_ar_credit_note_allocation_pair    UNIQUE (credit_note_id, ar_invoice_id),
    CONSTRAINT fk_ar_cn_allocation_company          FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT fk_ar_cn_allocation_credit_note      FOREIGN KEY (credit_note_id) REFERENCES ar_credit_notes (id),
    CONSTRAINT fk_ar_cn_allocation_invoice          FOREIGN KEY (ar_invoice_id)  REFERENCES ar_invoices (id),
    CONSTRAINT chk_ar_cn_allocation_amount          CHECK (allocated_amount > 0)
);

-- ============================================================================
-- (5) ar_write_offs — bad debt removal
-- ============================================================================
CREATE TABLE ar_write_offs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid            VARCHAR(26)     NOT NULL,
    company_id     BIGINT          NOT NULL,
    branch_id      BIGINT,
    customer_id    BIGINT          NOT NULL,
    ar_invoice_id  BIGINT          NOT NULL,
    write_off_date DATE            NOT NULL,
    amount         NUMERIC(19,4)   NOT NULL,
    currency       VARCHAR(3)      NOT NULL,
    reason         VARCHAR(255)    NOT NULL,
    gl_entry_uid   VARCHAR(26),
    version        BIGINT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,

    CONSTRAINT uq_ar_write_off_uid       UNIQUE (uid),
    CONSTRAINT fk_ar_write_off_company   FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT fk_ar_write_off_branch    FOREIGN KEY (branch_id)     REFERENCES branches (id),
    CONSTRAINT fk_ar_write_off_customer  FOREIGN KEY (customer_id)   REFERENCES customers (id),
    CONSTRAINT fk_ar_write_off_invoice   FOREIGN KEY (ar_invoice_id) REFERENCES ar_invoices (id),
    CONSTRAINT chk_ar_write_off_amount   CHECK (amount > 0)
);

-- ============================================================================
-- (6) Indexes (ADR-0014 D-2)
-- ============================================================================

-- ar_invoices
CREATE INDEX ix_ar_invoices_company
    ON ar_invoices (company_id);
CREATE INDEX ix_ar_invoices_company_customer
    ON ar_invoices (company_id, customer_id);
CREATE INDEX ix_ar_invoices_open
    ON ar_invoices (company_id, customer_id, due_date)
    WHERE status IN ('OPEN','PARTIAL');
CREATE INDEX ix_ar_invoices_company_due
    ON ar_invoices (company_id, due_date);

-- ar_receipts
CREATE INDEX ix_ar_receipts_company
    ON ar_receipts (company_id);
CREATE INDEX ix_ar_receipts_company_customer
    ON ar_receipts (company_id, customer_id);
CREATE INDEX ix_ar_receipts_company_date
    ON ar_receipts (company_id, receipt_date);
CREATE INDEX ix_ar_receipts_onaccount
    ON ar_receipts (company_id, customer_id)
    WHERE unallocated_amount > 0;

-- ar_receipt_allocations
CREATE INDEX ix_ar_receipt_allocations_receipt
    ON ar_receipt_allocations (receipt_id);
CREATE INDEX ix_ar_receipt_allocations_invoice
    ON ar_receipt_allocations (ar_invoice_id);
CREATE INDEX ix_ar_receipt_allocations_company
    ON ar_receipt_allocations (company_id);

-- ar_credit_notes
CREATE INDEX ix_ar_credit_notes_company
    ON ar_credit_notes (company_id);
CREATE INDEX ix_ar_credit_notes_company_customer
    ON ar_credit_notes (company_id, customer_id);
CREATE INDEX ix_ar_credit_notes_invoice
    ON ar_credit_notes (ar_invoice_id)
    WHERE ar_invoice_id IS NOT NULL;
-- D-6: open CN lookup for balance netting (ADR-0040 D-6)
CREATE INDEX ix_ar_credit_notes_open
    ON ar_credit_notes (company_id, customer_id)
    WHERE unapplied_amount > 0;

-- ar_credit_note_allocations
CREATE INDEX ix_ar_credit_note_allocations_credit_note
    ON ar_credit_note_allocations (credit_note_id);
CREATE INDEX ix_ar_credit_note_allocations_invoice
    ON ar_credit_note_allocations (ar_invoice_id);
CREATE INDEX ix_ar_credit_note_allocations_company
    ON ar_credit_note_allocations (company_id);

-- ar_write_offs
CREATE INDEX ix_ar_write_offs_company
    ON ar_write_offs (company_id);
CREATE INDEX ix_ar_write_offs_invoice
    ON ar_write_offs (ar_invoice_id);

-- ============================================================================
-- (7) CoA seed — add 5500 Bad Debt Expense + 3100 Opening Balance Equity
-- per existing company (CROSS JOIN; deterministic seed-uid; V10 pattern).
-- ============================================================================
INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'ARSD' || lpad(c.id::text, 6, '0') || a.code AS uid,
    c.id,
    a.code,
    a.name,
    a.account_type,
    a.normal_balance,
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
CROSS JOIN (VALUES
    ('5500', 'Bad Debt Expense',        'EXPENSE', 'DEBIT'),
    ('3100', 'Opening Balance Equity',  'EQUITY',  'CREDIT')
) AS a(code, name, account_type, normal_balance)
ON CONFLICT (company_id, account_code) DO NOTHING;

-- ============================================================================
-- (8) gl_configs CHECK constraint — widen to admit BAD_DEBT_EXPENSE and
-- OPENING_BALANCE_EQUITY (additive ALTER; never editing V10 DDL).
-- ============================================================================
ALTER TABLE gl_configs
    DROP CONSTRAINT IF EXISTS chk_gl_config_key;

ALTER TABLE gl_configs
    ADD CONSTRAINT chk_gl_config_key CHECK (
        config_key IN (
            'SALES_REVENUE','VAT_PAYABLE','ACCOUNTS_RECEIVABLE','CASH',
            'INVENTORY','COGS','ACCOUNTS_PAYABLE',
            'BAD_DEBT_EXPENSE','OPENING_BALANCE_EQUITY'
        ));

-- Seed BAD_DEBT_EXPENSE → 5500 and OPENING_BALANCE_EQUITY → 3100 per company.
INSERT INTO gl_configs (uid, company_id, config_key, account_id, version, created_at)
SELECT
    -- <=26-char uid (ISSUES-REGISTER #12): raw config_key (e.g. OPENING_BALANCE_EQUITY) overflowed
    -- uid VARCHAR(26) when seeding a DB that already has companies. md5(key) keeps it bounded.
    'ARC' || lpad(coa.company_id::text, 6, '0') || substr(md5(m.config_key), 1, 12) AS uid,
    coa.company_id,
    m.config_key,
    coa.id,
    0,
    now()
FROM (VALUES
    ('BAD_DEBT_EXPENSE',       '5500'),
    ('OPENING_BALANCE_EQUITY', '3100')
) AS m(config_key, account_code)
JOIN chart_of_accounts coa ON coa.account_code = m.account_code
ON CONFLICT (company_id, config_key) DO NOTHING;

-- ============================================================================
-- (9) journal source-type CHECK widen — add AR_RECEIPT, AR_WRITEOFF, AR_CREDIT_NOTE
-- (additive ALTER on journal_batches + journal_entries; V10 DDL untouched).
-- ============================================================================
ALTER TABLE journal_batches
    DROP CONSTRAINT IF EXISTS chk_journal_batch_source_type;

ALTER TABLE journal_batches
    ADD CONSTRAINT chk_journal_batch_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE'
        ));

ALTER TABLE journal_entries
    DROP CONSTRAINT IF EXISTS chk_journal_entry_source_type;

ALTER TABLE journal_entries
    ADD CONSTRAINT chk_journal_entry_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE'
        ));
