-- V12 — Accounts Payable module (ADR-0015): supplier_bills, supplier_bill_lines,
-- bill_match, ap_payments, ap_payment_allocations, ap_debit_notes;
-- ap_settings (tolerance config); CoA seed (5150 Purchases);
-- gl_configs CHECK widen + PURCHASES key seed; journal source-type CHECK widen
-- (AP_BILL, AP_PAYMENT, AP_DEBIT_NOTE); permissions seed + ORG_ADMIN grant.
-- Additive only. V1–V11 are FROZEN.
-- Order per ADR-0015 D-14:
--   supplier_bills → supplier_bill_lines → bill_match →
--   ap_payments → ap_payment_allocations → ap_debit_notes → ap_settings →
--   indexes → CoA seed → gl_configs CHECK + key seed →
--   journal source-type CHECK widen → permission seed.

-- ============================================================================
-- (1) supplier_bills — the payables (the sub-ledger detail behind GL 2100)
-- ============================================================================
CREATE TABLE supplier_bills (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)     NOT NULL,
    company_id           BIGINT          NOT NULL,
    branch_id            BIGINT,
    supplier_id          BIGINT          NOT NULL,
    bill_number          VARCHAR(30),
    supplier_invoice_no  VARCHAR(60)     NOT NULL,
    source               VARCHAR(20)     NOT NULL,
    purchase_order_uid   VARCHAR(26),
    bill_date            DATE            NOT NULL,
    due_date             DATE            NOT NULL,
    net_amount           NUMERIC(19,4)   NOT NULL,
    vat_amount           NUMERIC(19,4)   NOT NULL DEFAULT 0,
    gross_amount         NUMERIC(19,4)   NOT NULL,
    outstanding_amount   NUMERIC(19,4)   NOT NULL,
    currency             VARCHAR(3)      NOT NULL,
    status               VARCHAR(25)     NOT NULL DEFAULT 'DRAFT',
    posted_gl_entry_uid  VARCHAR(26),
    matched_at           TIMESTAMPTZ,
    matched_by           BIGINT,
    supplier_bank_account_uid VARCHAR(26),    -- captured beneficiary (soft ref, no FK — ADR-0040 D-4)
    -- D-7: WHT plan/snapshot at bill entry (non-posting; captured on payment) — ADR-0040 D-7
    wht_type_id          BIGINT,             -- scalar, no FK (cross-module soft ref)
    wht_taxable_base     NUMERIC(19,4),      -- taxable base for WHT calculation
    wht_amount           NUMERIC(19,4),      -- planned/snapshot WHT amount
    version              BIGINT          NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,

    CONSTRAINT uq_supplier_bill_uid            UNIQUE (uid),
    CONSTRAINT uq_supplier_bill_company_number UNIQUE (company_id, bill_number),
    CONSTRAINT uq_supplier_bill_supplier_invoice UNIQUE (company_id, supplier_id, supplier_invoice_no),
    CONSTRAINT fk_supplier_bill_company        FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_supplier_bill_branch         FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_supplier_bill_supplier       FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT chk_supplier_bill_source        CHECK (source IN ('BILL','OPENING_BALANCE')),
    CONSTRAINT chk_supplier_bill_status        CHECK (status IN (
        'DRAFT','MATCHED','HELD','APPROVED','PARTIALLY_PAID','PAID')),
    CONSTRAINT chk_supplier_bill_amounts       CHECK (
        net_amount >= 0
        AND vat_amount >= 0
        AND gross_amount >= 0
        AND outstanding_amount >= 0
        AND outstanding_amount <= gross_amount),
    CONSTRAINT chk_supplier_bill_dates         CHECK (due_date >= bill_date),
    CONSTRAINT chk_supplier_bill_number_when_posted CHECK (
        (status = 'DRAFT' AND bill_number IS NULL)
        OR (status <> 'DRAFT' AND bill_number IS NOT NULL)),
    CONSTRAINT chk_supplier_bill_wht_amount    CHECK (wht_amount IS NULL OR wht_amount >= 0)
);

-- ============================================================================
-- (2) supplier_bill_lines — children of supplier_bills
-- ============================================================================
CREATE TABLE supplier_bill_lines (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)     NOT NULL,
    supplier_bill_id BIGINT          NOT NULL,
    company_id       BIGINT          NOT NULL,
    branch_id        BIGINT,
    line_no          SMALLINT        NOT NULL,
    product_id       BIGINT,
    po_line_uid      VARCHAR(26),
    gr_line_uid      VARCHAR(26),
    description      VARCHAR(200)    NOT NULL,
    billed_qty       NUMERIC(19,6)   NOT NULL,
    unit_cost_amount NUMERIC(19,4)   NOT NULL,
    line_net_amount  NUMERIC(19,4)   NOT NULL,
    -- D-8: per-line VAT (ADR-0040 D-8) — reuses products.VatStatus enum values
    vat_status       VARCHAR(20),            -- STANDARD | ZERO_RATED | EXEMPT; null = inherit from product
    vat_rate         NUMERIC(9,4),           -- rate snapshot at bill entry (e.g. 0.1800 for 18%)
    line_vat_amount  NUMERIC(19,4)   NOT NULL DEFAULT 0,   -- lineNetAmount × vatRate; 0 if no VAT
    -- D-8: optional per-line GL account override for service / non-stock lines
    gl_account_id    BIGINT,                 -- intra-DB FK → chart_of_accounts(id); null = use PURCHASES config key
    currency         VARCHAR(3)      NOT NULL,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,

    CONSTRAINT uq_supplier_bill_line_uid    UNIQUE (uid),
    CONSTRAINT uq_supplier_bill_line_no     UNIQUE (supplier_bill_id, line_no),
    CONSTRAINT fk_supplier_bill_line_bill   FOREIGN KEY (supplier_bill_id)  REFERENCES supplier_bills (id),
    CONSTRAINT fk_supplier_bill_line_company FOREIGN KEY (company_id)        REFERENCES companies (id),
    CONSTRAINT fk_supplier_bill_line_branch  FOREIGN KEY (branch_id)         REFERENCES branches (id),
    CONSTRAINT fk_supplier_bill_line_product FOREIGN KEY (product_id)        REFERENCES products (id),
    CONSTRAINT fk_supplier_bill_line_gl_acct FOREIGN KEY (gl_account_id)     REFERENCES chart_of_accounts (id),
    CONSTRAINT chk_supplier_bill_line_qty   CHECK (billed_qty > 0),
    CONSTRAINT chk_supplier_bill_line_cost  CHECK (unit_cost_amount >= 0 AND line_net_amount >= 0),
    CONSTRAINT chk_supplier_bill_line_vat_status CHECK (
        vat_status IS NULL OR vat_status IN ('STANDARD','ZERO_RATED','EXEMPT')),
    CONSTRAINT chk_supplier_bill_line_vat_amount CHECK (line_vat_amount >= 0)
);

-- ============================================================================
-- (3) bill_match — per-line 3-way match result (one row per bill line)
-- ============================================================================
CREATE TABLE bill_match (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT          NOT NULL,
    supplier_bill_id       BIGINT          NOT NULL,
    supplier_bill_line_id  BIGINT          NOT NULL,
    po_unit_cost_amount    NUMERIC(19,4),
    gr_received_qty        NUMERIC(19,6),
    billed_qty             NUMERIC(19,6)   NOT NULL,
    price_variance_amount  NUMERIC(19,4)   NOT NULL DEFAULT 0,
    price_variance_pct     NUMERIC(9,4)    NOT NULL DEFAULT 0,
    qty_variance           NUMERIC(19,6)   NOT NULL DEFAULT 0,
    match_status           VARCHAR(25)     NOT NULL,
    tolerance_pct          NUMERIC(9,4),
    tolerance_abs_amount   NUMERIC(19,4),
    accepted_by            BIGINT,
    accepted_at            TIMESTAMPTZ,
    matched_at             TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_at             TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by             BIGINT,

    CONSTRAINT uq_bill_match_line           UNIQUE (supplier_bill_line_id),
    CONSTRAINT fk_bill_match_company        FOREIGN KEY (company_id)            REFERENCES companies (id),
    CONSTRAINT fk_bill_match_bill           FOREIGN KEY (supplier_bill_id)      REFERENCES supplier_bills (id),
    CONSTRAINT fk_bill_match_line           FOREIGN KEY (supplier_bill_line_id) REFERENCES supplier_bill_lines (id),
    CONSTRAINT fk_bill_match_accepted_by    FOREIGN KEY (accepted_by)           REFERENCES app_users (id),
    CONSTRAINT chk_bill_match_status        CHECK (match_status IN (
        'MATCHED','HELD_PRICE_VARIANCE','HELD_QTY_VARIANCE','VARIANCE_ACCEPTED'))
);

-- ============================================================================
-- (4) ap_payments — single payment or payment run (PAYRUN-####)
-- ============================================================================
CREATE TABLE ap_payments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)     NOT NULL,
    company_id       BIGINT          NOT NULL,
    branch_id        BIGINT,
    supplier_id      BIGINT,
    payment_number   VARCHAR(30)     NOT NULL,
    kind             VARCHAR(20)     NOT NULL,
    payment_date     DATE            NOT NULL,
    amount           NUMERIC(19,4)   NOT NULL,
    currency         VARCHAR(3)      NOT NULL,
    tender_type      VARCHAR(20)     NOT NULL,
    bank_reference   VARCHAR(80),
    gl_entry_uid     VARCHAR(26),
    supplier_bank_account_uid VARCHAR(26),    -- captured beneficiary (soft ref, no FK — ADR-0040 D-4)
    -- D-7: WHT withheld on payment header (ADR-0040 D-7)
    wht_amount           NUMERIC(19,4),      -- withheld amount (null = no WHT on this payment)
    wht_transaction_uid  VARCHAR(26),        -- scalar ref to wht_transactions.uid; no FK (cross-module soft ref)
    -- D-9: on-account (prepayment) tracking (ADR-0040 D-9)
    unallocated_amount   NUMERIC(19,4)   NOT NULL DEFAULT 0,   -- on-account remainder; starts == amount for prepayments
    status               VARCHAR(20)     NOT NULL DEFAULT 'ALLOCATED',  -- UNALLOCATED|PARTIAL|ALLOCATED
    cheque_uid           VARCHAR(26),        -- scalar ref to cheques.uid; no FK (cross-module soft ref)
    version          BIGINT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,

    CONSTRAINT uq_ap_payment_uid            UNIQUE (uid),
    CONSTRAINT uq_ap_payment_company_number UNIQUE (company_id, payment_number),
    CONSTRAINT fk_ap_payment_company        FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_ap_payment_branch         FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_ap_payment_supplier       FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT chk_ap_payment_amount        CHECK (amount > 0),
    CONSTRAINT chk_ap_payment_kind          CHECK (kind IN ('SINGLE','PAYMENT_RUN')),
    CONSTRAINT chk_ap_payment_tender        CHECK (tender_type IN ('CASH','BANK_TRANSFER','MOBILE_MONEY')),
    CONSTRAINT chk_ap_payment_wht_amount    CHECK (wht_amount IS NULL OR wht_amount > 0),
    CONSTRAINT chk_ap_payment_unallocated   CHECK (unallocated_amount >= 0 AND unallocated_amount <= amount),
    CONSTRAINT chk_ap_payment_status        CHECK (status IN ('UNALLOCATED','PARTIAL','ALLOCATED'))
);

-- ============================================================================
-- (5) ap_payment_allocations — junction: payment ↔ bill (singular per convention)
-- ============================================================================
CREATE TABLE ap_payment_allocations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT          NOT NULL,
    ap_payment_id    BIGINT          NOT NULL,
    supplier_bill_id BIGINT          NOT NULL,
    allocated_amount NUMERIC(19,4)   NOT NULL,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,

    CONSTRAINT uq_ap_payment_allocation_pair UNIQUE (ap_payment_id, supplier_bill_id),
    CONSTRAINT fk_ap_payment_allocation_company  FOREIGN KEY (company_id)      REFERENCES companies (id),
    CONSTRAINT fk_ap_payment_allocation_payment  FOREIGN KEY (ap_payment_id)   REFERENCES ap_payments (id),
    CONSTRAINT fk_ap_payment_allocation_bill     FOREIGN KEY (supplier_bill_id) REFERENCES supplier_bills (id),
    CONSTRAINT chk_ap_payment_allocation_amount  CHECK (allocated_amount > 0)
);

-- ============================================================================
-- (6) ap_debit_notes — reduce a payable (DBN-####)
-- ============================================================================
CREATE TABLE ap_debit_notes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT,
    supplier_id         BIGINT          NOT NULL,
    debit_note_number   VARCHAR(30)     NOT NULL,
    supplier_bill_id    BIGINT,
    note_date           DATE            NOT NULL,
    amount              NUMERIC(19,4)   NOT NULL,
    net_amount          NUMERIC(19,4)   NOT NULL,
    vat_amount          NUMERIC(19,4)   NOT NULL DEFAULT 0,
    currency            VARCHAR(3)      NOT NULL,
    reason              VARCHAR(255)    NOT NULL,
    gl_entry_uid        VARCHAR(26),
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_ap_debit_note_uid            UNIQUE (uid),
    CONSTRAINT uq_ap_debit_note_company_number UNIQUE (company_id, debit_note_number),
    CONSTRAINT fk_ap_debit_note_company        FOREIGN KEY (company_id)     REFERENCES companies (id),
    CONSTRAINT fk_ap_debit_note_branch         FOREIGN KEY (branch_id)      REFERENCES branches (id),
    CONSTRAINT fk_ap_debit_note_supplier       FOREIGN KEY (supplier_id)    REFERENCES suppliers (id),
    CONSTRAINT fk_ap_debit_note_bill           FOREIGN KEY (supplier_bill_id) REFERENCES supplier_bills (id),
    CONSTRAINT chk_ap_debit_note_amount        CHECK (
        amount > 0 AND net_amount >= 0 AND vat_amount >= 0)
);

-- ============================================================================
-- (7) ap_settings — per-company tolerance config (OQ-AP-01)
-- ============================================================================
CREATE TABLE ap_settings (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            BIGINT          NOT NULL,
    price_tolerance_pct   NUMERIC(9,4)    NOT NULL DEFAULT 2.0000,
    price_tolerance_abs   NUMERIC(19,4)   NOT NULL DEFAULT 0.0000,
    created_at            TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ,

    CONSTRAINT uq_ap_settings_company UNIQUE (company_id),
    CONSTRAINT fk_ap_settings_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- Seed default tolerance settings for existing companies
INSERT INTO ap_settings (company_id, price_tolerance_pct, price_tolerance_abs, created_at)
SELECT id, 2.0000, 0.0000, now()
FROM   companies
ON CONFLICT (company_id) DO NOTHING;

-- ============================================================================
-- (8) Indexes
-- ============================================================================

-- supplier_bills
CREATE INDEX ix_supplier_bills_company
    ON supplier_bills (company_id);
CREATE INDEX ix_supplier_bills_company_supplier
    ON supplier_bills (company_id, supplier_id);
CREATE INDEX ix_supplier_bills_status
    ON supplier_bills (company_id, status);
CREATE INDEX ix_supplier_bills_open
    ON supplier_bills (company_id, supplier_id, due_date)
    WHERE status IN ('MATCHED','APPROVED','PARTIALLY_PAID');
CREATE INDEX ix_supplier_bills_po
    ON supplier_bills (company_id, purchase_order_uid);

-- supplier_bill_lines
CREATE INDEX ix_supplier_bill_lines_bill
    ON supplier_bill_lines (supplier_bill_id);
CREATE INDEX ix_supplier_bill_lines_company
    ON supplier_bill_lines (company_id);
CREATE INDEX ix_supplier_bill_lines_po_line
    ON supplier_bill_lines (po_line_uid);

-- D-8: partial index on supplier_bill_lines.gl_account_id when set
CREATE INDEX ix_supplier_bill_lines_gl_account
    ON supplier_bill_lines (gl_account_id)
    WHERE gl_account_id IS NOT NULL;

-- bill_match
CREATE INDEX ix_bill_match_bill
    ON bill_match (supplier_bill_id);
CREATE INDEX ix_bill_match_company
    ON bill_match (company_id);
CREATE INDEX ix_bill_match_held
    ON bill_match (company_id)
    WHERE match_status IN ('HELD_PRICE_VARIANCE','HELD_QTY_VARIANCE');

-- ap_payments
CREATE INDEX ix_ap_payments_company
    ON ap_payments (company_id);
CREATE INDEX ix_ap_payments_company_supplier
    ON ap_payments (company_id, supplier_id);
CREATE INDEX ix_ap_payments_company_date
    ON ap_payments (company_id, payment_date);
-- D-9: on-account remainder query (supplier balance netting)
CREATE INDEX ix_ap_payments_onaccount
    ON ap_payments (company_id, supplier_id)
    WHERE unallocated_amount > 0;
-- D-9: cheque back-link
CREATE INDEX ix_ap_payments_cheque
    ON ap_payments (cheque_uid)
    WHERE cheque_uid IS NOT NULL;

-- ap_payment_allocations
CREATE INDEX ix_ap_payment_allocations_payment
    ON ap_payment_allocations (ap_payment_id);
CREATE INDEX ix_ap_payment_allocations_bill
    ON ap_payment_allocations (supplier_bill_id);
CREATE INDEX ix_ap_payment_allocations_company
    ON ap_payment_allocations (company_id);

-- ap_debit_notes
CREATE INDEX ix_ap_debit_notes_company
    ON ap_debit_notes (company_id);
CREATE INDEX ix_ap_debit_notes_company_supplier
    ON ap_debit_notes (company_id, supplier_id);
CREATE INDEX ix_ap_debit_notes_bill
    ON ap_debit_notes (supplier_bill_id)
    WHERE supplier_bill_id IS NOT NULL;

-- ============================================================================
-- (9) CoA seed — add 5150 Purchases (EXPENSE/DEBIT) per existing company
-- (CROSS JOIN; deterministic seed-uid; mirrors V11 pattern).
-- ============================================================================
INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'APSD' || lpad(c.id::text, 6, '0') || '5150' AS uid,
    c.id,
    '5150',
    'Purchases',
    'EXPENSE',
    'DEBIT',
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, account_code) DO NOTHING;

-- Also ensure OPENING_BALANCE_EQUITY (3100) exists (seeded by V11; idempotent if AP lands first).
INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'APOB' || lpad(c.id::text, 6, '0') || '3100' AS uid,
    c.id,
    '3100',
    'Opening Balance Equity',
    'EQUITY',
    'CREDIT',
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, account_code) DO NOTHING;

-- ============================================================================
-- (10) gl_configs CHECK constraint — widen to admit PURCHASES
-- (additive ALTER; never editing V10/V11 DDL).
-- ============================================================================
ALTER TABLE gl_configs
    DROP CONSTRAINT IF EXISTS chk_gl_config_key;

ALTER TABLE gl_configs
    ADD CONSTRAINT chk_gl_config_key CHECK (
        config_key IN (
            'SALES_REVENUE','VAT_PAYABLE','ACCOUNTS_RECEIVABLE','CASH',
            'INVENTORY','COGS','ACCOUNTS_PAYABLE',
            'BAD_DEBT_EXPENSE','OPENING_BALANCE_EQUITY',
            'PURCHASES'
        ));

-- Seed PURCHASES → 5150 per company (and OPENING_BALANCE_EQUITY → 3100 if not done by V11).
INSERT INTO gl_configs (uid, company_id, config_key, account_id, version, created_at)
SELECT
    -- <=26-char uid (ISSUES-REGISTER #12): bound the seed uid via md5(key), as V10/V11.
    'APC' || lpad(coa.company_id::text, 6, '0') || substr(md5(m.config_key), 1, 12) AS uid,
    coa.company_id,
    m.config_key,
    coa.id,
    0,
    now()
FROM (VALUES
    ('PURCHASES',              '5150'),
    ('OPENING_BALANCE_EQUITY', '3100')
) AS m(config_key, account_code)
JOIN chart_of_accounts coa ON coa.account_code = m.account_code
ON CONFLICT (company_id, config_key) DO NOTHING;

-- ============================================================================
-- (11) journal source-type CHECK widen — add AP_BILL, AP_PAYMENT, AP_DEBIT_NOTE
-- (additive ALTER on journal_batches + journal_entries; V10/V11 DDL untouched).
-- ============================================================================
ALTER TABLE journal_batches
    DROP CONSTRAINT IF EXISTS chk_journal_batch_source_type;

ALTER TABLE journal_batches
    ADD CONSTRAINT chk_journal_batch_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE'
        ));

ALTER TABLE journal_entries
    DROP CONSTRAINT IF EXISTS chk_journal_entry_source_type;

ALTER TABLE journal_entries
    ADD CONSTRAINT chk_journal_entry_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE'
        ));
