-- V13 — Cash & Bank module (ADR-0016): cash_bank_accounts, bank_reconciliations,
-- cash_transactions, cash_transfers, cheques;
-- AR/AP additive nullable ALTER (cash_bank_account_id);
-- journal source-type CHECK widen (CASH_TRANSFER, CASH_DIRECT);
-- default cash/bank account seed per company (gl_configs.CASH → default account);
-- permissions seed + ORG_ADMIN grant.
-- Additive only. V1–V12 are FROZEN.
-- Order per ADR-0016 D-14:
--   cash_bank_accounts → bank_reconciliations → cash_transactions →
--   cash_transfers → cheques → indexes →
--   AR/AP additive ALTERs → journal source-type CHECK widen →
--   default cash/bank account seed → permission seed.

-- ============================================================================
-- (1) cash_bank_accounts — the money locations (master, per company)
-- ============================================================================
CREATE TABLE cash_bank_accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT,
    code                VARCHAR(30)     NOT NULL,
    name                VARCHAR(120)    NOT NULL,
    account_type        VARCHAR(10)     NOT NULL,
    bank_name           VARCHAR(120),
    bank_account_no     VARCHAR(60),
    bank_branch         VARCHAR(120),
    currency            VARCHAR(3)      NOT NULL,
    gl_account_id       BIGINT          NOT NULL,
    is_default          BOOLEAN         NOT NULL DEFAULT FALSE,
    active              BOOLEAN         NOT NULL DEFAULT TRUE,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_cash_bank_account_uid             UNIQUE (uid),
    CONSTRAINT uq_cash_bank_account_company_code    UNIQUE (company_id, code),
    CONSTRAINT uq_cash_bank_account_gl              UNIQUE (company_id, gl_account_id),
    CONSTRAINT fk_cash_bank_account_company         FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT fk_cash_bank_account_branch          FOREIGN KEY (branch_id)     REFERENCES branches (id),
    CONSTRAINT fk_cash_bank_account_gl_account      FOREIGN KEY (gl_account_id) REFERENCES chart_of_accounts (id),
    CONSTRAINT chk_cash_bank_account_type           CHECK (account_type IN ('CASH','BANK')),
    CONSTRAINT chk_cash_bank_account_bank_details   CHECK (
        (account_type = 'BANK')
        OR (bank_name IS NULL AND bank_account_no IS NULL AND bank_branch IS NULL))
);

-- Partial unique: at most one default per company (BR-CASH-09)
CREATE UNIQUE INDEX uq_cash_bank_account_default
    ON cash_bank_accounts (company_id)
    WHERE is_default = TRUE;

-- ============================================================================
-- (2) bank_reconciliations — before cash_transactions (FK from transactions → recon)
-- ============================================================================
CREATE TABLE bank_reconciliations (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)     NOT NULL,
    company_id                  BIGINT          NOT NULL,
    branch_id                   BIGINT,
    cash_bank_account_id        BIGINT          NOT NULL,
    reconciliation_number       VARCHAR(30)     NOT NULL,
    statement_date              DATE            NOT NULL,
    statement_closing_balance   NUMERIC(19,4)   NOT NULL,
    cleared_book_balance        NUMERIC(19,4),
    status                      VARCHAR(10)     NOT NULL DEFAULT 'DRAFT',
    reconciled_by               BIGINT,
    completed_at                TIMESTAMPTZ,
    version                     BIGINT          NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,

    CONSTRAINT uq_bank_reconciliation_uid               UNIQUE (uid),
    CONSTRAINT uq_bank_reconciliation_company_number    UNIQUE (company_id, reconciliation_number),
    CONSTRAINT fk_bank_reconciliation_company           FOREIGN KEY (company_id)           REFERENCES companies (id),
    CONSTRAINT fk_bank_reconciliation_branch            FOREIGN KEY (branch_id)            REFERENCES branches (id),
    CONSTRAINT fk_bank_reconciliation_account           FOREIGN KEY (cash_bank_account_id) REFERENCES cash_bank_accounts (id),
    CONSTRAINT chk_bank_reconciliation_status           CHECK (status IN ('DRAFT','COMPLETED'))
);

-- ============================================================================
-- (3) cash_transactions — the cash/bank ledger (append-only)
-- ============================================================================
CREATE TABLE cash_transactions (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)     NOT NULL,
    company_id                  BIGINT          NOT NULL,
    branch_id                   BIGINT,
    cash_bank_account_id        BIGINT          NOT NULL,
    txn_number                  VARCHAR(30)     NOT NULL,
    txn_date                    DATE            NOT NULL,
    direction                   VARCHAR(3)      NOT NULL,
    amount                      NUMERIC(19,4)   NOT NULL,
    currency                    VARCHAR(3)      NOT NULL,
    txn_type                    VARCHAR(20)     NOT NULL,
    source_ref                  VARCHAR(26),
    counter_gl_account_id       BIGINT,
    journal_entry_ref           VARCHAR(26),
    cleared                     BOOLEAN         NOT NULL DEFAULT FALSE,
    cleared_in_reconciliation_id BIGINT,
    memo                        VARCHAR(255),
    version                     BIGINT          NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,

    CONSTRAINT uq_cash_transaction_uid              UNIQUE (uid),
    CONSTRAINT uq_cash_transaction_company_number   UNIQUE (company_id, txn_number),
    CONSTRAINT fk_cash_transaction_company          FOREIGN KEY (company_id)           REFERENCES companies (id),
    CONSTRAINT fk_cash_transaction_branch           FOREIGN KEY (branch_id)            REFERENCES branches (id),
    CONSTRAINT fk_cash_transaction_account          FOREIGN KEY (cash_bank_account_id) REFERENCES cash_bank_accounts (id),
    CONSTRAINT fk_cash_transaction_counter_gl       FOREIGN KEY (counter_gl_account_id) REFERENCES chart_of_accounts (id),
    CONSTRAINT fk_cash_transaction_reconciliation   FOREIGN KEY (cleared_in_reconciliation_id) REFERENCES bank_reconciliations (id),
    CONSTRAINT chk_cash_transaction_direction       CHECK (direction IN ('IN','OUT')),
    CONSTRAINT chk_cash_transaction_type            CHECK (txn_type IN (
        'AR_RECEIPT','AP_PAYMENT','TRANSFER_IN','TRANSFER_OUT','DIRECT_ENTRY')),
    CONSTRAINT chk_cash_transaction_amount          CHECK (amount > 0),
    CONSTRAINT chk_cash_transaction_counter_gl      CHECK (
        (txn_type = 'DIRECT_ENTRY' AND counter_gl_account_id IS NOT NULL)
        OR (txn_type <> 'DIRECT_ENTRY')),
    CONSTRAINT chk_cash_transaction_cleared         CHECK (
        (cleared = FALSE AND cleared_in_reconciliation_id IS NULL)
        OR (cleared = TRUE AND cleared_in_reconciliation_id IS NOT NULL))
);

-- ============================================================================
-- (4) cash_transfers — the inter-account transfer header (CBT-####)
-- ============================================================================
CREATE TABLE cash_transfers (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    branch_id               BIGINT,
    transfer_number         VARCHAR(30)     NOT NULL,
    source_account_id       BIGINT          NOT NULL,
    destination_account_id  BIGINT          NOT NULL,
    transfer_date           DATE            NOT NULL,
    amount                  NUMERIC(19,4)   NOT NULL,
    currency                VARCHAR(3)      NOT NULL,
    reference               VARCHAR(255),
    out_txn_id              BIGINT          NOT NULL,
    in_txn_id               BIGINT          NOT NULL,
    journal_entry_ref       VARCHAR(26),
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_cash_transfer_uid             UNIQUE (uid),
    CONSTRAINT uq_cash_transfer_company_number  UNIQUE (company_id, transfer_number),
    CONSTRAINT fk_cash_transfer_company         FOREIGN KEY (company_id)             REFERENCES companies (id),
    CONSTRAINT fk_cash_transfer_branch          FOREIGN KEY (branch_id)              REFERENCES branches (id),
    CONSTRAINT fk_cash_transfer_source          FOREIGN KEY (source_account_id)      REFERENCES cash_bank_accounts (id),
    CONSTRAINT fk_cash_transfer_destination     FOREIGN KEY (destination_account_id) REFERENCES cash_bank_accounts (id),
    CONSTRAINT fk_cash_transfer_out_txn         FOREIGN KEY (out_txn_id)             REFERENCES cash_transactions (id),
    CONSTRAINT fk_cash_transfer_in_txn          FOREIGN KEY (in_txn_id)              REFERENCES cash_transactions (id),
    CONSTRAINT chk_cash_transfer_amount         CHECK (amount > 0),
    CONSTRAINT chk_cash_transfer_distinct       CHECK (source_account_id <> destination_account_id)
);

-- ============================================================================
-- (5) cheques — the cheque register (BANK accounts only)
-- ============================================================================
CREATE TABLE cheques (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    branch_id               BIGINT,
    cash_bank_account_id    BIGINT          NOT NULL,
    cheque_number           VARCHAR(40)     NOT NULL,
    payee                   VARCHAR(160)    NOT NULL,
    amount                  NUMERIC(19,4)   NOT NULL,
    currency                VARCHAR(3)      NOT NULL,
    issue_date              DATE            NOT NULL,
    value_date              DATE            NOT NULL,
    status                  VARCHAR(12)     NOT NULL DEFAULT 'ISSUED',
    ap_payment_uid          VARCHAR(26),
    cash_transaction_uid    VARCHAR(26),
    cleared_at              TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_cheque_uid                UNIQUE (uid),
    CONSTRAINT uq_cheque_bank_number        UNIQUE (cash_bank_account_id, cheque_number),
    CONSTRAINT fk_cheque_company            FOREIGN KEY (company_id)           REFERENCES companies (id),
    CONSTRAINT fk_cheque_branch             FOREIGN KEY (branch_id)            REFERENCES branches (id),
    CONSTRAINT fk_cheque_account            FOREIGN KEY (cash_bank_account_id) REFERENCES cash_bank_accounts (id),
    CONSTRAINT chk_cheque_status            CHECK (status IN ('ISSUED','CLEARED','CANCELLED')),
    CONSTRAINT chk_cheque_amount            CHECK (amount > 0),
    CONSTRAINT chk_cheque_dates             CHECK (value_date >= issue_date)
);

-- ============================================================================
-- (6) Indexes
-- ============================================================================

-- cash_bank_accounts
CREATE INDEX ix_cash_bank_accounts_company
    ON cash_bank_accounts (company_id);
CREATE INDEX ix_cash_bank_accounts_company_active
    ON cash_bank_accounts (company_id, active);
CREATE INDEX ix_cash_bank_accounts_gl
    ON cash_bank_accounts (company_id, gl_account_id);

-- bank_reconciliations
CREATE INDEX ix_bank_reconciliations_company
    ON bank_reconciliations (company_id);
CREATE INDEX ix_bank_reconciliations_account
    ON bank_reconciliations (cash_bank_account_id);
CREATE INDEX ix_bank_reconciliations_account_date
    ON bank_reconciliations (cash_bank_account_id, statement_date);

-- cash_transactions
CREATE INDEX ix_cash_transactions_company
    ON cash_transactions (company_id);
CREATE INDEX ix_cash_transactions_account_date
    ON cash_transactions (cash_bank_account_id, txn_date, id);
CREATE INDEX ix_cash_transactions_account_balance
    ON cash_transactions (cash_bank_account_id);
CREATE INDEX ix_cash_transactions_uncleared
    ON cash_transactions (cash_bank_account_id)
    WHERE cleared = FALSE;
CREATE INDEX ix_cash_transactions_source
    ON cash_transactions (company_id, source_ref);

-- cash_transfers
CREATE INDEX ix_cash_transfers_company
    ON cash_transfers (company_id);
CREATE INDEX ix_cash_transfers_source
    ON cash_transfers (source_account_id);
CREATE INDEX ix_cash_transfers_destination
    ON cash_transfers (destination_account_id);
CREATE INDEX ix_cash_transfers_company_date
    ON cash_transfers (company_id, transfer_date);

-- cheques
CREATE INDEX ix_cheques_company
    ON cheques (company_id);
CREATE INDEX ix_cheques_account
    ON cheques (cash_bank_account_id);
CREATE INDEX ix_cheques_status
    ON cheques (company_id, status);
CREATE INDEX ix_cheques_ap_payment
    ON cheques (ap_payment_uid);

-- ============================================================================
-- (7) AR/AP additive ALTERs — nullable cash_bank_account_id + FK (D-8)
-- ============================================================================
ALTER TABLE ar_receipts
    ADD COLUMN IF NOT EXISTS cash_bank_account_id BIGINT;

ALTER TABLE ar_receipts
    ADD CONSTRAINT fk_ar_receipt_cash_bank_account
        FOREIGN KEY (cash_bank_account_id) REFERENCES cash_bank_accounts (id);

ALTER TABLE ap_payments
    ADD COLUMN IF NOT EXISTS cash_bank_account_id BIGINT;

ALTER TABLE ap_payments
    ADD CONSTRAINT fk_ap_payment_cash_bank_account
        FOREIGN KEY (cash_bank_account_id) REFERENCES cash_bank_accounts (id);

-- ============================================================================
-- (8) journal source-type CHECK widen — add CASH_TRANSFER, CASH_DIRECT
-- (additive ALTER; V10/V11/V12 DDL untouched; builds on V12's IN-list)
-- ============================================================================
ALTER TABLE journal_batches
    DROP CONSTRAINT IF EXISTS chk_journal_batch_source_type;

ALTER TABLE journal_batches
    ADD CONSTRAINT chk_journal_batch_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT'
        ));

ALTER TABLE journal_entries
    DROP CONSTRAINT IF EXISTS chk_journal_entry_source_type;

ALTER TABLE journal_entries
    ADD CONSTRAINT chk_journal_entry_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT'
        ));

-- ============================================================================
-- (9) Default cash/bank account seed per company (D-10/D-13)
-- Each existing company gets one default CASH account whose gl_account_id is
-- the company's gl_configs CASH-mapped account (so unchanged AR/AP callers
-- keep posting to the same GL account they always did — zero behaviour change).
-- deterministic seed-uid: 'CBSD' + lpad(company_id,6,'0') + 'CASH'
-- ============================================================================
INSERT INTO cash_bank_accounts (
    uid, company_id, code, name, account_type, currency,
    gl_account_id, is_default, active, version, created_at
)
SELECT
    'CBSD' || lpad(c.id::text, 6, '0') || 'CASH' AS uid,
    c.id                                           AS company_id,
    'CB-0001'                                      AS code,
    'Default Cash Account'                         AS name,
    'CASH'                                         AS account_type,
    COALESCE(c.base_currency, 'TZS')               AS currency,
    coa.id                                         AS gl_account_id,
    TRUE                                           AS is_default,
    TRUE                                           AS active,
    0                                              AS version,
    now()                                          AS created_at
FROM companies c
JOIN gl_configs gc  ON gc.company_id = c.id AND gc.config_key = 'CASH'
JOIN chart_of_accounts coa ON coa.id = gc.account_id
ON CONFLICT (company_id, code) DO NOTHING;

-- ============================================================================
-- (10) Permission seed + ORG_ADMIN grant (ADR-0016 D-13; mirror V11/V12 pattern)
-- ============================================================================
INSERT INTO permissions (code, module, description) VALUES
    ('CASH.VIEW',           'cashbank', 'View cash/bank accounts, balances, statements, and the GL-reconciliation read'),
    ('CASH.ACCOUNT.MANAGE', 'cashbank', 'Create/edit/deactivate a cash/bank account, set its GL link, set the company default'),
    ('CASH.TRANSFER',       'cashbank', 'Record an inter-account transfer (CBT-####)'),
    ('CASH.ENTRY.RECORD',   'cashbank', 'Record a direct cash/bank entry (bank charge, interest, sundry)'),
    ('CASH.RECONCILE',      'cashbank', 'Perform a manual bank reconciliation (open/mark-cleared/complete)'),
    ('CHEQUE.MANAGE',       'cashbank', 'Manage the cheque register (register/clear/cancel)')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM   roles r
CROSS JOIN permissions p
WHERE  r.code   = 'ORG_ADMIN'
AND    p.code IN (
    'CASH.VIEW','CASH.ACCOUNT.MANAGE','CASH.TRANSFER',
    'CASH.ENTRY.RECORD','CASH.RECONCILE','CHEQUE.MANAGE'
)
ON CONFLICT DO NOTHING;
