-- V14 — VAT Return & Withholding Tax module (ADR-0017):
-- vat_returns, vat_return_bands, vat_adjustments, wht_types, wht_transactions;
-- CoA seed (1400 VAT Input, 1500 WHT Receivable, 2300 VAT Due, 2400 WHT Payable);
-- gl_configs CHECK widen + 4 key seeds (VAT_INPUT, VAT_DUE, WHT_PAYABLE, WHT_RECEIVABLE);
-- journal source-type CHECK widen (VAT_RETURN);
-- permission seed + ORG_ADMIN grant.
-- Additive only. V1–V13 are FROZEN.
-- Order per ADR-0017 D-12:
--   vat_returns → vat_return_bands → vat_adjustments →
--   wht_types → wht_transactions → indexes →
--   CoA seed → gl_configs CHECK widen + key seeds →
--   journal source-type CHECK widen → permission seed.

-- ============================================================================
-- (1) vat_returns — the monthly return master (one per company per month)
-- ============================================================================
CREATE TABLE vat_returns (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    return_number       VARCHAR(30)     NOT NULL,
    period_year         SMALLINT        NOT NULL,
    period_month        SMALLINT        NOT NULL,
    period_start        DATE            NOT NULL,
    period_end          DATE            NOT NULL,
    due_date            DATE            NOT NULL,
    status              VARCHAR(10)     NOT NULL DEFAULT 'DRAFT',
    output_vat          NUMERIC(19,4)   NOT NULL DEFAULT 0,
    input_vat           NUMERIC(19,4)   NOT NULL DEFAULT 0,
    adjustments_total   NUMERIC(19,4)   NOT NULL DEFAULT 0,
    opening_credit      NUMERIC(19,4)   NOT NULL DEFAULT 0,
    net_vat             NUMERIC(19,4)   NOT NULL DEFAULT 0,
    closing_credit      NUMERIC(19,4)   NOT NULL DEFAULT 0,
    prior_return_id     BIGINT,
    filing_reference    VARCHAR(80),
    filing_date         DATE,
    posted_journal_uid  VARCHAR(26),
    filed_at            TIMESTAMPTZ,
    filed_by            BIGINT,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    paid_at             TIMESTAMPTZ,             -- P2-M1: VAT remittance (cash settlement to authority)
    paid_amount         NUMERIC(19,4),
    payment_reference   VARCHAR(80),
    sales_turnover      NUMERIC(19,4),           -- P2-M1: statutory turnover figures for the return face form
    purchases_turnover  NUMERIC(19,4),
    zero_rated_sales    NUMERIC(19,4),
    exempt_sales        NUMERIC(19,4),
    amended_return_id   BIGINT,                  -- P2 D7: self soft-FK → the original return this amends
    is_amendment        BOOLEAN         NOT NULL DEFAULT false,  -- P2 D7: this is an amended/revised return
    penalty_amount      NUMERIC(19,4),           -- P2 D7: late-filing/payment penalty assessed
    interest_amount     NUMERIC(19,4),           -- P2 D7: interest assessed on overdue VAT

    CONSTRAINT uq_vat_return_uid                UNIQUE (uid),
    CONSTRAINT uq_vat_return_company_number     UNIQUE (company_id, return_number),
    CONSTRAINT uq_vat_return_company_period     UNIQUE (company_id, period_year, period_month),
    CONSTRAINT fk_vat_return_company            FOREIGN KEY (company_id)      REFERENCES companies (id),
    CONSTRAINT fk_vat_return_prior              FOREIGN KEY (prior_return_id) REFERENCES vat_returns (id),
    CONSTRAINT fk_vat_return_amended            FOREIGN KEY (amended_return_id) REFERENCES vat_returns (id),
    CONSTRAINT fk_vat_return_filed_by           FOREIGN KEY (filed_by)        REFERENCES app_users (id),
    CONSTRAINT chk_vat_return_status            CHECK (status IN ('DRAFT','FILED')),
    CONSTRAINT chk_vat_return_period_month      CHECK (period_month BETWEEN 1 AND 12),
    CONSTRAINT chk_vat_return_period_year       CHECK (period_year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_vat_return_dates             CHECK (period_end >= period_start),
    CONSTRAINT chk_vat_return_credits           CHECK (opening_credit >= 0 AND closing_credit >= 0),
    -- A DRAFT carries no filing fields. A FILED return carries filing_reference + filing_date;
    -- posted_journal_uid is set when the period had VAT movement to settle, but is NULL for a
    -- legal nil-activity return (no output, no input → no settlement journal posted — ADR-0017 D-8).
    CONSTRAINT chk_vat_return_filed_fields      CHECK (
        (status = 'DRAFT'
            AND filing_reference IS NULL
            AND filing_date IS NULL
            AND posted_journal_uid IS NULL)
        OR (status = 'FILED'
            AND filing_reference IS NOT NULL
            AND filing_date IS NOT NULL))
);

-- ============================================================================
-- (2) vat_return_bands — output breakdown by tax band (child of vat_returns)
-- ============================================================================
CREATE TABLE vat_return_bands (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vat_return_id   BIGINT          NOT NULL,
    company_id      BIGINT          NOT NULL,
    tax_band        VARCHAR(20)     NOT NULL,
    taxable_base    NUMERIC(19,4)   NOT NULL DEFAULT 0,
    output_vat      NUMERIC(19,4)   NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      BIGINT,

    CONSTRAINT uq_vat_return_band                   UNIQUE (vat_return_id, tax_band),
    CONSTRAINT fk_vat_return_band_return            FOREIGN KEY (vat_return_id) REFERENCES vat_returns (id),
    CONSTRAINT fk_vat_return_band_company           FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT chk_vat_return_band                  CHECK (tax_band IN ('STANDARD','ZERO_RATED','EXEMPT')),
    CONSTRAINT chk_vat_return_band_amounts          CHECK (taxable_base >= 0 AND output_vat >= 0)
);

-- ============================================================================
-- (3) vat_adjustments — manual adjustment lines on a DRAFT return
-- ============================================================================
CREATE TABLE vat_adjustments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)     NOT NULL,
    vat_return_id   BIGINT          NOT NULL,
    company_id      BIGINT          NOT NULL,
    reason          VARCHAR(30)     NOT NULL,
    sign            VARCHAR(10)     NOT NULL,
    amount          NUMERIC(19,4)   NOT NULL,
    narrative       VARCHAR(255),
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_vat_adjustment_uid            UNIQUE (uid),
    CONSTRAINT fk_vat_adjustment_return         FOREIGN KEY (vat_return_id) REFERENCES vat_returns (id),
    CONSTRAINT fk_vat_adjustment_company        FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT chk_vat_adjustment_reason        CHECK (reason IN (
        'BAD_DEBT_RELIEF','PRIOR_PERIOD_CORRECTION','CREDIT_NOTE_VAT','DEBIT_NOTE_VAT','OTHER')),
    CONSTRAINT chk_vat_adjustment_sign          CHECK (sign IN ('INCREASE','DECREASE')),
    CONSTRAINT chk_vat_adjustment_amount        CHECK (amount > 0)
);

-- ============================================================================
-- (4) wht_types — lean WHT rate/type master (per company)
-- ============================================================================
CREATE TABLE wht_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)     NOT NULL,
    company_id  BIGINT          NOT NULL,
    code        VARCHAR(30)     NOT NULL,
    name        VARCHAR(120)    NOT NULL,
    kind        VARCHAR(20)     NOT NULL,
    rate_pct    NUMERIC(9,4)    NOT NULL,
    active      BOOLEAN         NOT NULL DEFAULT TRUE,
    version     BIGINT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,

    CONSTRAINT uq_wht_type_uid              UNIQUE (uid),
    CONSTRAINT uq_wht_type_company_code     UNIQUE (company_id, code),
    CONSTRAINT fk_wht_type_company          FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_wht_type_kind            CHECK (kind IN ('WHT_ON_PAYMENT','WHT_ON_RECEIPT')),
    CONSTRAINT chk_wht_type_rate            CHECK (rate_pct >= 0)
);

-- ============================================================================
-- (5) wht_transactions — WHT register + certificate (one row per withholding event)
-- ============================================================================
CREATE TABLE wht_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT,
    wht_number          VARCHAR(30)     NOT NULL,
    wht_type_id         BIGINT          NOT NULL,
    kind                VARCHAR(20)     NOT NULL,
    party_kind          VARCHAR(10)     NOT NULL,
    party_id            BIGINT          NOT NULL,
    party_name          VARCHAR(160)    NOT NULL,
    source_ref          VARCHAR(26)     NOT NULL,
    taxable_base        NUMERIC(19,4)   NOT NULL,
    wht_amount          NUMERIC(19,4)   NOT NULL,
    currency            VARCHAR(3)      NOT NULL,
    certificate_date    DATE            NOT NULL,
    journal_entry_ref   VARCHAR(26),
    -- D-7: TIN snapshot + rate snapshot + remittance tracking (ADR-0040 D-7)
    tin                 VARCHAR(40),            -- party tax-id snapshot at capture time
    rate_pct            NUMERIC(9,4),           -- WHT rate snapshot (e.g. 5.0000 for 5%); guards against type rate changes
    remitted            BOOLEAN         NOT NULL DEFAULT FALSE,
    remittance_period   VARCHAR(7),             -- YYYY-MM format; set when remitted
    remittance_ref      VARCHAR(80),            -- TRA/authority reference number; set when remitted
    remitted_at         TIMESTAMPTZ,            -- timestamp of remittance action
    remitted_by         BIGINT,                 -- app_users.id of the actor who remitted
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_wht_transaction_uid               UNIQUE (uid),
    CONSTRAINT uq_wht_transaction_company_number    UNIQUE (company_id, wht_number),
    CONSTRAINT fk_wht_transaction_company           FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_wht_transaction_branch            FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_wht_transaction_type              FOREIGN KEY (wht_type_id) REFERENCES wht_types (id),
    CONSTRAINT chk_wht_transaction_kind             CHECK (kind IN ('WHT_ON_PAYMENT','WHT_ON_RECEIPT')),
    CONSTRAINT chk_wht_transaction_party_kind       CHECK (party_kind IN ('SUPPLIER','CUSTOMER')),
    CONSTRAINT chk_wht_transaction_amounts          CHECK (taxable_base >= 0 AND wht_amount > 0),
    -- D-7: remittance integrity: unremitted rows carry no ref/timestamp; remitted rows require both
    CONSTRAINT chk_wht_transaction_remittance CHECK (
        (NOT remitted AND remittance_ref IS NULL AND remitted_at IS NULL)
        OR (remitted AND remittance_ref IS NOT NULL AND remitted_at IS NOT NULL))
);

-- ============================================================================
-- (6) Indexes
-- ============================================================================

-- vat_returns
CREATE INDEX ix_vat_returns_company
    ON vat_returns (company_id);
CREATE INDEX ix_vat_returns_company_period
    ON vat_returns (company_id, period_year, period_month);
CREATE INDEX ix_vat_returns_status
    ON vat_returns (company_id, status);

-- vat_return_bands
CREATE INDEX ix_vat_return_bands_return
    ON vat_return_bands (vat_return_id);

-- vat_adjustments
CREATE INDEX ix_vat_adjustments_return
    ON vat_adjustments (vat_return_id);
CREATE INDEX ix_vat_adjustments_company
    ON vat_adjustments (company_id);

-- wht_types
CREATE INDEX ix_wht_types_company
    ON wht_types (company_id);

-- wht_transactions
CREATE INDEX ix_wht_transactions_company
    ON wht_transactions (company_id);
CREATE INDEX ix_wht_transactions_company_period
    ON wht_transactions (company_id, certificate_date);
CREATE INDEX ix_wht_transactions_kind
    ON wht_transactions (company_id, kind);
CREATE INDEX ix_wht_transactions_source
    ON wht_transactions (company_id, source_ref);
CREATE INDEX ix_wht_transactions_party
    ON wht_transactions (company_id, party_kind, party_id);
-- D-7: remittance query index (find unremitted / by period)
CREATE INDEX ix_wht_transactions_remittance
    ON wht_transactions (company_id, remitted, remittance_period);

-- ============================================================================
-- (7) CoA seed — add 4 new accounts per existing company
-- Seeds: 1400 VAT Input (ASSET/DEBIT), 1500 WHT Receivable (ASSET/DEBIT),
--        2300 VAT Due (LIABILITY/CREDIT), 2400 WHT Payable (LIABILITY/CREDIT).
-- Deterministic seed-uid uses account_code suffix (≤14 chars).
-- ============================================================================
INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'VATC' || lpad(c.id::text, 6, '0') || '1400' AS uid,
    c.id,
    '1400',
    'VAT Input (Recoverable)',
    'ASSET',
    'DEBIT',
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, account_code) DO NOTHING;

INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'VATC' || lpad(c.id::text, 6, '0') || '1500' AS uid,
    c.id,
    '1500',
    'WHT Receivable',
    'ASSET',
    'DEBIT',
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, account_code) DO NOTHING;

INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'VATC' || lpad(c.id::text, 6, '0') || '2300' AS uid,
    c.id,
    '2300',
    'VAT Due (Payable to TRA)',
    'LIABILITY',
    'CREDIT',
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, account_code) DO NOTHING;

INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'VATC' || lpad(c.id::text, 6, '0') || '2400' AS uid,
    c.id,
    '2400',
    'WHT Payable (to TRA)',
    'LIABILITY',
    'CREDIT',
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, account_code) DO NOTHING;

-- ============================================================================
-- (8) gl_configs CHECK constraint — widen to admit VAT_INPUT, VAT_DUE,
--     WHT_PAYABLE, WHT_RECEIVABLE (additive ALTER; V10/V11/V12/V13 DDL untouched).
-- ============================================================================
ALTER TABLE gl_configs
    DROP CONSTRAINT IF EXISTS chk_gl_config_key;

ALTER TABLE gl_configs
    ADD CONSTRAINT chk_gl_config_key CHECK (
        config_key IN (
            'SALES_REVENUE','VAT_PAYABLE','ACCOUNTS_RECEIVABLE','CASH',
            'INVENTORY','COGS','ACCOUNTS_PAYABLE',
            'BAD_DEBT_EXPENSE','OPENING_BALANCE_EQUITY',
            'PURCHASES',
            'VAT_INPUT','VAT_DUE','WHT_PAYABLE','WHT_RECEIVABLE'
        ));

-- Seed the 4 new gl_configs keys per company (joining the just-seeded CoA).
-- CRITICAL #12-safe seed-uid: 'VTC' || lpad(company_id,6,'0') || substr(md5(key),1,12) = 21 chars.
-- NEVER use || config_key (WHT_RECEIVABLE=14 chars would overflow with longer prefixes).
INSERT INTO gl_configs (uid, company_id, config_key, account_id, version, created_at)
SELECT
    'VTC' || lpad(coa.company_id::text, 6, '0') || substr(md5(m.config_key), 1, 12) AS uid,
    coa.company_id,
    m.config_key,
    coa.id,
    0,
    now()
FROM (VALUES
    ('VAT_INPUT',        '1400'),
    ('VAT_DUE',          '2300'),
    ('WHT_PAYABLE',      '2400'),
    ('WHT_RECEIVABLE',   '1500')
) AS m(config_key, account_code)
JOIN chart_of_accounts coa ON coa.account_code = m.account_code
ON CONFLICT (company_id, config_key) DO NOTHING;

-- ============================================================================
-- (9) journal source-type CHECK widen — add VAT_RETURN
-- (additive ALTER; V10/V11/V12/V13 DDL untouched; builds on V13's IN-list)
-- ============================================================================
ALTER TABLE journal_batches
    DROP CONSTRAINT IF EXISTS chk_journal_batch_source_type;

ALTER TABLE journal_batches
    ADD CONSTRAINT chk_journal_batch_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT',
            'VAT_RETURN'
        ));

ALTER TABLE journal_entries
    DROP CONSTRAINT IF EXISTS chk_journal_entry_source_type;

ALTER TABLE journal_entries
    ADD CONSTRAINT chk_journal_entry_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT',
            'VAT_RETURN'
        ));
