-- V1 baseline — IAM module, growing slice by slice.
--
-- PRE-STABLE SCHEMA RULE (PROJECT-CONVENTIONS §3.6): while the schema is unstable, EDIT this
-- baseline and recreate the DB (drop volume) rather than stacking corrective migrations. Freeze
-- and switch to additive V2, V3, ... only once IAM stabilises (after Slice 6).
--
-- Slice 1: organisations -> companies -> branches (the scoping tree). DATA-MODEL §1.1-1.3.

-- ---------------------------------------------------------------------------
-- organisations — top of the tree, one per deployment.
-- ---------------------------------------------------------------------------
CREATE TABLE organisations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    legal_name          VARCHAR(200),
    default_time_zone   VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_organisation_uid UNIQUE (uid)
);

-- ---------------------------------------------------------------------------
-- companies — a legal entity within the organisation; scoping parent of company-bound data.
-- ---------------------------------------------------------------------------
CREATE TABLE companies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    organisation_id     BIGINT       NOT NULL,
    code                VARCHAR(20)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    legal_name          VARCHAR(200),
    tax_id              VARCHAR(60),
    vrn                 VARCHAR(40),                 -- P2: VAT registration number (distinct from tax_id)
    logo_ref            VARCHAR(255),                -- P2: company-level branding logo reference
    fiscal_year_start_month SMALLINT,               -- P2: doc-default fiscal-year start month (1-12)
    time_zone           VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_company_uid UNIQUE (uid),
    CONSTRAINT uq_company_org_code UNIQUE (organisation_id, code),
    CONSTRAINT fk_company_organisation FOREIGN KEY (organisation_id) REFERENCES organisations (id)
);
CREATE INDEX ix_company_organisation ON companies (organisation_id);

-- ---------------------------------------------------------------------------
-- branches — a physical location under a company. At most one default per company.
-- ---------------------------------------------------------------------------
CREATE TABLE branches (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    company_id          BIGINT       NOT NULL,
    code                VARCHAR(20)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    time_zone           VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    is_default          BOOLEAN      NOT NULL DEFAULT false,
    manager_id          BIGINT,                      -- P2: soft-FK to app_users/employee (no DB FK — cross-module convention)
    branch_type         VARCHAR(20),                 -- P2: typed branch classification (enum-as-string)
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_branch_uid UNIQUE (uid),
    CONSTRAINT uq_branch_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_branch_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_branch_type CHECK (branch_type IS NULL OR branch_type IN ('HEAD_OFFICE','RETAIL','WAREHOUSE','SALES_OFFICE','FACTORY','OTHER'))
);
CREATE INDEX ix_branch_company ON branches (company_id);

-- BR-2: at most one default branch per company (ADR-0001 D-C). Partial unique index — the
-- Postgres-native enforcement that makes "one default" a DB fact, not a code hope.
CREATE UNIQUE INDEX uq_branch_company_default ON branches (company_id) WHERE is_default;

-- ---------------------------------------------------------------------------
-- permissions — org-wide catalogue (DATA-MODEL §1.5). Reference data, seeded here. The rest of
-- RBAC (roles, role_permission, user_role) and enforcement land in Slice 3; seeding the catalogue
-- early is harmless and lets controllers reference codes as they are built.
-- ---------------------------------------------------------------------------
CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(80)  NOT NULL,
    module      VARCHAR(40)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT uq_permission_code UNIQUE (code)
);
CREATE INDEX ix_permission_module ON permissions (module);

-- Seed the IAM permission catalogue (idempotent). Gates are enforced from Slice 3 (DATA-MODEL
-- "Seed data"). Every permission-gated endpoint must have its code here (PROJECT-CONVENTIONS §3.4).

-- ---------------------------------------------------------------------------
-- Slice 2: identity & authentication.
-- app_users — a login identity (DATA-MODEL §1.4). Org-wide; username org-unique. is_root marks the
-- super-admin that transcends company/branch scoping. No default_branch_id column: the user's
-- default branch is the single source of truth on user_branch.is_default (ADR-0001 D-B, Slice 4).
-- ---------------------------------------------------------------------------
CREATE TABLE app_users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)  NOT NULL,
    username             VARCHAR(80)  NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    display_name         VARCHAR(160) NOT NULL,
    email                VARCHAR(160),
    phone                VARCHAR(40),
    is_root              BOOLEAN      NOT NULL DEFAULT false,
    failed_login_count   INT          NOT NULL DEFAULT 0,
    locked_until         TIMESTAMPTZ,
    last_login_at        TIMESTAMPTZ,
    password_changed_at  TIMESTAMPTZ,
    must_change_password BOOLEAN      NOT NULL DEFAULT false,   -- P2: force password change on next login
    password_expires_at  TIMESTAMPTZ,                           -- P2: password expiry timestamp (nullable)
    last_login_ip        VARCHAR(45),                           -- P2: last successful login IP (IPv6-max length)
    employee_id          BIGINT,                                -- P2: soft-FK to HR employee master (no DB FK — cross-module)
    status               VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version              BIGINT       NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,
    CONSTRAINT uq_app_user_uid UNIQUE (uid),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

-- ---------------------------------------------------------------------------
-- Slice 4: user_branch — a user assigned to many branches, exactly one default (DATA-MODEL §1.9).
-- The user's default company is derived from the default branch's company (ADR-0001 D-B).
-- uq_user_branch_default partial unique index enforces BR-1 (at most one default per user, D-C).
-- assigned_at drives the earliest-assigned fallback (ADR-0001 D-D).
-- ---------------------------------------------------------------------------
CREATE TABLE user_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)  NOT NULL,
    user_id     BIGINT       NOT NULL,
    branch_id   BIGINT       NOT NULL,
    is_default  BOOLEAN      NOT NULL DEFAULT false,
    assigned_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    assigned_by BIGINT       NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_branch_uid        UNIQUE (uid),
    CONSTRAINT uq_user_branch_user_branch UNIQUE (user_id, branch_id),
    CONSTRAINT fk_user_branch_user        FOREIGN KEY (user_id)     REFERENCES app_users (id),
    CONSTRAINT fk_user_branch_branch      FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_user_branch_assigned_by FOREIGN KEY (assigned_by) REFERENCES app_users (id)
);
CREATE INDEX ix_user_branch_user   ON user_branch (user_id);
CREATE INDEX ix_user_branch_branch ON user_branch (branch_id);

-- BR-1: at most one default branch per user (ADR-0001 D-C). Partial unique index — Postgres
-- enforces the single-default invariant as a DB fact, not just a code hope.
CREATE UNIQUE INDEX uq_user_branch_default ON user_branch (user_id) WHERE is_default;

-- ---------------------------------------------------------------------------
-- refresh_tokens — hashed, single-use, rotated (DATA-MODEL §1.10). The raw token is never stored;
-- only its SHA-256 hash. A presented token whose rotated_at/revoked_at is set = reuse → revoke chain.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    token_hash          VARCHAR(64)  NOT NULL,
    issued_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ  NOT NULL,
    rotated_at          TIMESTAMPTZ,
    revoked_at          TIMESTAMPTZ,
    replaced_by_id      BIGINT,
    client_company_id   BIGINT,
    client_branch_id    BIGINT,
    device_info         VARCHAR(255),    -- P2: session/device-management label
    user_agent          VARCHAR(255),    -- P2: requesting client user-agent
    ip_address          VARCHAR(45),     -- P2: issuing/last IP (IPv6-max length)
    last_used_at        TIMESTAMPTZ,     -- P2: last time this token was presented
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_refresh_token_replaced FOREIGN KEY (replaced_by_id) REFERENCES refresh_tokens (id)
);
CREATE INDEX ix_refresh_token_user ON refresh_tokens (user_id);
CREATE INDEX ix_refresh_token_expiry ON refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- Slice 3: access control (RBAC). roles / role_permission / user_role + enforcement.
-- The atomic unit is the PERMISSION (already seeded above). A ROLE bundles permissions; a USER_ROLE
-- grants a role to a user scoped to a company (and optionally one branch). Effective permissions are
-- resolved per (user, company, branch) at request time, NOT embedded in the JWT (ADR-0001 D-E).
-- ---------------------------------------------------------------------------

-- roles — named, reusable permission bundle; org-wide (DATA-MODEL §1.6). is_system roles are
-- seeded and undeletable (BR-7).
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)  NOT NULL,
    code        VARCHAR(40)  NOT NULL,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    is_system   BOOLEAN      NOT NULL DEFAULT false,
    status      VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_role_uid UNIQUE (uid),
    CONSTRAINT uq_role_code UNIQUE (code)
);

-- role_permission — junction role <-> permission (DATA-MODEL §1.7).
CREATE TABLE role_permission (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);
CREATE INDEX ix_role_permission_permission ON role_permission (permission_id);

-- user_role — role assignment: binds a role to a user, scoped to a company, optionally one branch
-- (DATA-MODEL §1.8). branch_id NULL = all branches in the company (FR-IAM-13). revoked_at NULL =
-- active. BR-5 (branch belongs to the assignment's company) is enforced in the service.
CREATE TABLE user_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)  NOT NULL,
    user_id     BIGINT       NOT NULL,
    role_id     BIGINT       NOT NULL,
    company_id  BIGINT       NOT NULL,
    branch_id   BIGINT,
    granted_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    granted_by  BIGINT       NOT NULL,
    revoked_at  TIMESTAMPTZ,
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_role_uid UNIQUE (uid),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_user_role_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_user_role_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_user_role_granted_by FOREIGN KEY (granted_by) REFERENCES app_users (id)
);
CREATE INDEX ix_user_role_user ON user_role (user_id);
-- The resolve-per-scope hot path (ADR-0001 D-E): active grants for a user+company(+branch).
CREATE INDEX ix_user_role_lookup ON user_role (user_id, company_id, branch_id) WHERE revoked_at IS NULL;
-- No duplicate active grant. NULL branch_id is treated as distinct by Postgres, so the service also
-- guards the company-wide duplicate case (DATA-MODEL §1.8).
CREATE UNIQUE INDEX uq_user_role_active
    ON user_role (user_id, role_id, company_id, branch_id) WHERE revoked_at IS NULL;

-- Seed the ORG_ADMIN system role (DATA-MODEL "Seed data") and grant it every IAM permission.
-- SUPER_ADMIN is NOT a role — root is the app_users.is_root flag (ADR-0001). is_system => undeletable.
-- Fixed seed uid (zero timestamp marks it a seed; tail is a valid Crockford-base32 ULID).
INSERT INTO roles (uid, code, name, description, is_system) VALUES
    ('0000000000XVKF7J9FAGX51RMQ', 'ORG_ADMIN', 'Organisation Administrator',
     'Full IAM administration across the organisation.', true)
ON CONFLICT (code) DO NOTHING;


-- ---------------------------------------------------------------------------
-- Slice 6: audit_logs — append-only IAM (and later, global) action trail
-- (DATA-MODEL §1.11, ADR-0004 D-1). Internal table, no uid column (ADR-0001 D-G).
-- No version/updated_* columns — append-only (D-5). FK to app_users is SQL-only;
-- platform.audit depends on no module entity (D-1). NO trigger (owner ruling D-5).
-- ---------------------------------------------------------------------------
CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action        VARCHAR(80)  NOT NULL,
    target_type   VARCHAR(60)  NOT NULL,
    target_id     BIGINT,
    target_uid    VARCHAR(26),
    company_id    BIGINT,
    branch_id     BIGINT,
    detail        JSONB,
    at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ip            VARCHAR(45),
    CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_user_id) REFERENCES app_users (id)
);

-- Query patterns: history of a specific target entity; actions by a specific actor; action/time range.
CREATE INDEX ix_audit_log_target    ON audit_logs (target_type, target_id, at);
CREATE INDEX ix_audit_log_actor     ON audit_logs (actor_user_id, at);
CREATE INDEX ix_audit_log_action_at ON audit_logs (action, at);
