-- V1 baseline — IAM module, growing slice by slice.
--
-- PRE-STABLE SCHEMA RULE (PROJECT-CONVENTIONS §3.6): while the schema is unstable, EDIT this
-- baseline and recreate the DB (drop volume) rather than stacking corrective migrations. Freeze
-- and switch to additive V2, V3, ... only once IAM stabilises (after Slice 6).
--
-- Slice 1: organisation -> company -> branch (the scoping tree). DATA-MODEL §1.1-1.3.

-- ---------------------------------------------------------------------------
-- organisation — top of the tree, one per deployment.
-- ---------------------------------------------------------------------------
CREATE TABLE organisation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    legal_name          VARCHAR(200),
    default_time_zone   VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_organisation_uid UNIQUE (uid)
);

-- ---------------------------------------------------------------------------
-- company — a legal entity within the organisation; scoping parent of company-bound data.
-- ---------------------------------------------------------------------------
CREATE TABLE company (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    organisation_id     BIGINT       NOT NULL,
    code                VARCHAR(20)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    legal_name          VARCHAR(200),
    tax_id              VARCHAR(60),
    time_zone           VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_company_uid UNIQUE (uid),
    CONSTRAINT uq_company_org_code UNIQUE (organisation_id, code),
    CONSTRAINT fk_company_organisation FOREIGN KEY (organisation_id) REFERENCES organisation (id)
);
CREATE INDEX ix_company_organisation ON company (organisation_id);

-- ---------------------------------------------------------------------------
-- branch — a physical location under a company. At most one default per company.
-- ---------------------------------------------------------------------------
CREATE TABLE branch (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    company_id          BIGINT       NOT NULL,
    code                VARCHAR(20)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    time_zone           VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    is_default          BOOLEAN      NOT NULL DEFAULT false,
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_branch_uid UNIQUE (uid),
    CONSTRAINT uq_branch_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_branch_company FOREIGN KEY (company_id) REFERENCES company (id)
);
CREATE INDEX ix_branch_company ON branch (company_id);

-- BR-2: at most one default branch per company (ADR-0001 D-C). Partial unique index — the
-- Postgres-native enforcement that makes "one default" a DB fact, not a code hope.
CREATE UNIQUE INDEX uq_branch_company_default ON branch (company_id) WHERE is_default;

-- ---------------------------------------------------------------------------
-- permission — org-wide catalogue (DATA-MODEL §1.5). Reference data, seeded here. The rest of
-- RBAC (role, role_permission, user_role) and enforcement land in Slice 3; seeding the catalogue
-- early is harmless and lets controllers reference codes as they are built.
-- ---------------------------------------------------------------------------
CREATE TABLE permission (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(80)  NOT NULL,
    module      VARCHAR(40)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT uq_permission_code UNIQUE (code)
);
CREATE INDEX ix_permission_module ON permission (module);

-- Seed the IAM permission catalogue (idempotent). Gates become active in Slice 3.
INSERT INTO permission (code, module, description) VALUES
    ('COMPANY.VIEW',    'iam', 'View companies'),
    ('COMPANY.MANAGE',  'iam', 'Create, update and archive companies'),
    ('BRANCH.VIEW',     'iam', 'View branches'),
    ('BRANCH.MANAGE',   'iam', 'Create, update, set-default and archive branches'),
    ('USER.VIEW',       'iam', 'View users'),
    ('USER.MANAGE',     'iam', 'Create, update, disable and unlock users; set passwords')
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Slice 2: identity & authentication.
-- app_user — a login identity (DATA-MODEL §1.4). Org-wide; username org-unique. is_root marks the
-- super-admin that transcends company/branch scoping. default_branch_id is set in Slice 4 when
-- user_branch arrives; for now bootstrap sets it directly to the company's default branch.
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)  NOT NULL,
    username             VARCHAR(80)  NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    display_name         VARCHAR(160) NOT NULL,
    email                VARCHAR(160),
    phone                VARCHAR(40),
    is_root              BOOLEAN      NOT NULL DEFAULT false,
    default_branch_id    BIGINT,
    failed_login_count   INT          NOT NULL DEFAULT 0,
    locked_until         TIMESTAMPTZ,
    last_login_at        TIMESTAMPTZ,
    password_changed_at  TIMESTAMPTZ,
    status               VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version              BIGINT       NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,
    CONSTRAINT uq_app_user_uid UNIQUE (uid),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT fk_app_user_default_branch FOREIGN KEY (default_branch_id) REFERENCES branch (id)
);

-- ---------------------------------------------------------------------------
-- refresh_token — hashed, single-use, rotated (DATA-MODEL §1.10). The raw token is never stored;
-- only its SHA-256 hash. A presented token whose rotated_at/revoked_at is set = reuse → revoke chain.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_token (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    token_hash          VARCHAR(64)  NOT NULL,
    issued_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ  NOT NULL,
    rotated_at          TIMESTAMPTZ,
    revoked_at          TIMESTAMPTZ,
    replaced_by_id      BIGINT,
    client_company_id   BIGINT,
    client_branch_id    BIGINT,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_refresh_token_replaced FOREIGN KEY (replaced_by_id) REFERENCES refresh_token (id)
);
CREATE INDEX ix_refresh_token_user ON refresh_token (user_id);
CREATE INDEX ix_refresh_token_expiry ON refresh_token (expires_at);
