-- V1 baseline — IAM module, growing slice by slice.
--
-- PRE-STABLE SCHEMA RULE (PROJECT-CONVENTIONS §3.6): while the schema is unstable, EDIT this
-- baseline and recreate the DB (drop volume) rather than stacking corrective migrations. Freeze
-- and switch to additive V2, V3, ... only once IAM stabilises (after Slice 6).
--
-- Slice 1: organisation -> company -> branch (the scoping tree). DATA-MODEL §1.1-1.3.

-- ---------------------------------------------------------------------------
-- organisation — top of the tree, one per deployment.
-- ---------------------------------------------------------------------------
CREATE TABLE organisation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    legal_name          VARCHAR(200),
    default_time_zone   VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_organisation_uid UNIQUE (uid)
);

-- ---------------------------------------------------------------------------
-- company — a legal entity within the organisation; scoping parent of company-bound data.
-- ---------------------------------------------------------------------------
CREATE TABLE company (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    organisation_id     BIGINT       NOT NULL,
    code                VARCHAR(20)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    legal_name          VARCHAR(200),
    tax_id              VARCHAR(60),
    time_zone           VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_company_uid UNIQUE (uid),
    CONSTRAINT uq_company_org_code UNIQUE (organisation_id, code),
    CONSTRAINT fk_company_organisation FOREIGN KEY (organisation_id) REFERENCES organisation (id)
);
CREATE INDEX ix_company_organisation ON company (organisation_id);

-- ---------------------------------------------------------------------------
-- branch — a physical location under a company. At most one default per company.
-- ---------------------------------------------------------------------------
CREATE TABLE branch (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)  NOT NULL,
    company_id          BIGINT       NOT NULL,
    code                VARCHAR(20)  NOT NULL,
    name                VARCHAR(160) NOT NULL,
    time_zone           VARCHAR(64)  NOT NULL DEFAULT 'Africa/Dar_es_Salaam',
    is_default          BOOLEAN      NOT NULL DEFAULT false,
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_branch_uid UNIQUE (uid),
    CONSTRAINT uq_branch_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_branch_company FOREIGN KEY (company_id) REFERENCES company (id)
);
CREATE INDEX ix_branch_company ON branch (company_id);

-- BR-2: at most one default branch per company (ADR-0001 D-C). Partial unique index — the
-- Postgres-native enforcement that makes "one default" a DB fact, not a code hope.
CREATE UNIQUE INDEX uq_branch_company_default ON branch (company_id) WHERE is_default;

-- ---------------------------------------------------------------------------
-- permission — org-wide catalogue (DATA-MODEL §1.5). Reference data, seeded here. The rest of
-- RBAC (role, role_permission, user_role) and enforcement land in Slice 3; seeding the catalogue
-- early is harmless and lets controllers reference codes as they are built.
-- ---------------------------------------------------------------------------
CREATE TABLE permission (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(80)  NOT NULL,
    module      VARCHAR(40)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT uq_permission_code UNIQUE (code)
);
CREATE INDEX ix_permission_module ON permission (module);

-- Seed the IAM permission catalogue (idempotent). Gates are enforced from Slice 3 (DATA-MODEL
-- "Seed data"). Every permission-gated endpoint must have its code here (PROJECT-CONVENTIONS §3.4).
INSERT INTO permission (code, module, description) VALUES
    ('COMPANY.VIEW',    'iam', 'View companies'),
    ('COMPANY.MANAGE',  'iam', 'Create, update and archive companies'),
    ('BRANCH.VIEW',     'iam', 'View branches'),
    ('BRANCH.MANAGE',   'iam', 'Create, update, set-default and archive branches'),
    ('BRANCH.ASSIGN',   'iam', 'Assign users to branches and set their default branch'),
    ('USER.VIEW',       'iam', 'View users'),
    ('USER.MANAGE',     'iam', 'Create, update, disable and unlock users; set passwords'),
    ('ROLE.VIEW',       'iam', 'View roles and their permissions'),
    ('ROLE.MANAGE',     'iam', 'Create and update roles; grant and revoke role assignments'),
    ('PERMISSION.VIEW', 'iam', 'View the permission catalogue'),
    ('AUDIT.VIEW',      'iam', 'View the IAM audit trail')
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Slice 2: identity & authentication.
-- app_user — a login identity (DATA-MODEL §1.4). Org-wide; username org-unique. is_root marks the
-- super-admin that transcends company/branch scoping. default_branch_id is set in Slice 4 when
-- user_branch arrives; for now bootstrap sets it directly to the company's default branch.
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)  NOT NULL,
    username             VARCHAR(80)  NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    display_name         VARCHAR(160) NOT NULL,
    email                VARCHAR(160),
    phone                VARCHAR(40),
    is_root              BOOLEAN      NOT NULL DEFAULT false,
    default_branch_id    BIGINT,
    failed_login_count   INT          NOT NULL DEFAULT 0,
    locked_until         TIMESTAMPTZ,
    last_login_at        TIMESTAMPTZ,
    password_changed_at  TIMESTAMPTZ,
    status               VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version              BIGINT       NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,
    CONSTRAINT uq_app_user_uid UNIQUE (uid),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT fk_app_user_default_branch FOREIGN KEY (default_branch_id) REFERENCES branch (id)
);

-- ---------------------------------------------------------------------------
-- refresh_token — hashed, single-use, rotated (DATA-MODEL §1.10). The raw token is never stored;
-- only its SHA-256 hash. A presented token whose rotated_at/revoked_at is set = reuse → revoke chain.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_token (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    token_hash          VARCHAR(64)  NOT NULL,
    issued_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ  NOT NULL,
    rotated_at          TIMESTAMPTZ,
    revoked_at          TIMESTAMPTZ,
    replaced_by_id      BIGINT,
    client_company_id   BIGINT,
    client_branch_id    BIGINT,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_refresh_token_replaced FOREIGN KEY (replaced_by_id) REFERENCES refresh_token (id)
);
CREATE INDEX ix_refresh_token_user ON refresh_token (user_id);
CREATE INDEX ix_refresh_token_expiry ON refresh_token (expires_at);

-- ---------------------------------------------------------------------------
-- Slice 3: access control (RBAC). role / role_permission / user_role + enforcement.
-- The atomic unit is the PERMISSION (already seeded above). A ROLE bundles permissions; a USER_ROLE
-- grants a role to a user scoped to a company (and optionally one branch). Effective permissions are
-- resolved per (user, company, branch) at request time, NOT embedded in the JWT (ADR-0001 D-E).
-- ---------------------------------------------------------------------------

-- role — named, reusable permission bundle; org-wide (DATA-MODEL §1.6). is_system roles are
-- seeded and undeletable (BR-7).
CREATE TABLE role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)  NOT NULL,
    code        VARCHAR(40)  NOT NULL,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(255),
    is_system   BOOLEAN      NOT NULL DEFAULT false,
    status      VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_role_uid UNIQUE (uid),
    CONSTRAINT uq_role_code UNIQUE (code)
);

-- role_permission — junction role <-> permission (DATA-MODEL §1.7).
CREATE TABLE role_permission (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES permission (id)
);
CREATE INDEX ix_role_permission_permission ON role_permission (permission_id);

-- user_role — role assignment: binds a role to a user, scoped to a company, optionally one branch
-- (DATA-MODEL §1.8). branch_id NULL = all branches in the company (FR-IAM-13). revoked_at NULL =
-- active. BR-5 (branch belongs to the assignment's company) is enforced in the service.
CREATE TABLE user_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)  NOT NULL,
    user_id     BIGINT       NOT NULL,
    role_id     BIGINT       NOT NULL,
    company_id  BIGINT       NOT NULL,
    branch_id   BIGINT,
    granted_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    granted_by  BIGINT       NOT NULL,
    revoked_at  TIMESTAMPTZ,
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_role_uid UNIQUE (uid),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_user_role_company FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT fk_user_role_branch FOREIGN KEY (branch_id) REFERENCES branch (id),
    CONSTRAINT fk_user_role_granted_by FOREIGN KEY (granted_by) REFERENCES app_user (id)
);
CREATE INDEX ix_user_role_user ON user_role (user_id);
-- The resolve-per-scope hot path (ADR-0001 D-E): active grants for a user+company(+branch).
CREATE INDEX ix_user_role_lookup ON user_role (user_id, company_id, branch_id) WHERE revoked_at IS NULL;
-- No duplicate active grant. NULL branch_id is treated as distinct by Postgres, so the service also
-- guards the company-wide duplicate case (DATA-MODEL §1.8).
CREATE UNIQUE INDEX uq_user_role_active
    ON user_role (user_id, role_id, company_id, branch_id) WHERE revoked_at IS NULL;

-- Seed the ORG_ADMIN system role (DATA-MODEL "Seed data") and grant it every IAM permission.
-- SUPER_ADMIN is NOT a role — root is the app_user.is_root flag (ADR-0001). is_system => undeletable.
-- Fixed seed uid (zero timestamp marks it a seed; tail is a valid Crockford-base32 ULID).
INSERT INTO role (uid, code, name, description, is_system) VALUES
    ('0000000000XVKF7J9FAGX51RMQ', 'ORG_ADMIN', 'Organisation Administrator',
     'Full IAM administration across the organisation.', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM role r
CROSS JOIN permission p
WHERE r.code = 'ORG_ADMIN' AND p.module = 'iam'
ON CONFLICT DO NOTHING;
