-- V32 — Procurement depth: purchase_requisitions + purchase_requisition_lines,
--        purchase_settings (PO approval threshold config),
--        ALTER purchase_orders: add approval_status/approval_request_uid/source_quote_uid/source_requisition_uid,
--        permission seed + ORG_ADMIN grant.
-- Additive only. V1–V31 are FROZEN/in-flight. This file does NOT edit them.
-- ADR-0027 D-3 / D-6 / D-10 / D-12.
-- Order: (1) purchase_requisitions → (2) purchase_requisition_lines → (3) purchase_settings
--        → (4) ALTER purchase_orders → (5) indexes → (6) purchase_settings seed
--        → (7) permission seed + ORG_ADMIN grant.

-- ============================================================================
-- (1) purchase_requisitions — PR header
-- ============================================================================
CREATE TABLE purchase_requisitions (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    requisition_number      VARCHAR(30),                          -- PR-####; NULL while DRAFT
    status                  VARCHAR(20)      NOT NULL DEFAULT 'DRAFT',
    priority                VARCHAR(10),                          -- P2: LOW|NORMAL|HIGH|URGENT
    preferred_supplier_id   BIGINT,                               -- P2: soft-FK suppliers.id; requester's preferred source
    required_by_date        DATE,
    cost_centre_code        VARCHAR(40),                          -- free-text in v1 (OQ-PROC-06)
    approval_request_uid    VARCHAR(26),                          -- approvals-engine request (scalar, no FK)
    approval_status         VARCHAR(20),                          -- cached outcome; diagnostic mirror
    converted_to_type       VARCHAR(20),                          -- PURCHASE_ORDER | RFQ
    converted_to_uid        VARCHAR(26),                          -- the produced PO/RFQ uid
    notes                   VARCHAR(500),
    submitted_at            TIMESTAMPTZ,
    approved_at             TIMESTAMPTZ,
    rejected_at             TIMESTAMPTZ,
    converted_at            TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    submitted_by            BIGINT,
    approved_by             BIGINT,
    rejected_by             BIGINT,
    reject_reason           VARCHAR(255),
    cancel_reason           VARCHAR(255),
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_purchase_requisition_uid            UNIQUE (uid),
    CONSTRAINT uq_purchase_requisition_company_number UNIQUE (company_id, requisition_number), -- NULLs distinct
    CONSTRAINT fk_purchase_requisition_company        FOREIGN KEY (company_id)   REFERENCES companies (id),
    CONSTRAINT fk_purchase_requisition_branch         FOREIGN KEY (branch_id)    REFERENCES branches (id),
    CONSTRAINT fk_purchase_requisition_submitted_by   FOREIGN KEY (submitted_by) REFERENCES app_users (id),
    CONSTRAINT fk_purchase_requisition_approved_by    FOREIGN KEY (approved_by)  REFERENCES app_users (id),
    CONSTRAINT fk_purchase_requisition_rejected_by    FOREIGN KEY (rejected_by)  REFERENCES app_users (id),
    CONSTRAINT chk_purchase_requisition_status
        CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','CONVERTED','CANCELLED')),
    CONSTRAINT chk_purchase_requisition_number_when_submitted
        CHECK ((status = 'DRAFT' AND requisition_number IS NULL)
            OR (status <> 'DRAFT' AND requisition_number IS NOT NULL)),
    CONSTRAINT chk_purchase_requisition_priority                                                            -- P2
        CHECK (priority IS NULL OR priority IN ('LOW','NORMAL','HIGH','URGENT')),
    CONSTRAINT fk_purchase_requisition_pref_supplier                                                        -- P2
        FOREIGN KEY (preferred_supplier_id) REFERENCES suppliers (id)
);

-- ============================================================================
-- (2) purchase_requisition_lines — child of purchase_requisitions
-- ============================================================================
CREATE TABLE purchase_requisition_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    purchase_requisition_id BIGINT           NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    line_no                 SMALLINT         NOT NULL,
    product_id              BIGINT           NOT NULL,
    product_code            VARCHAR(60)      NOT NULL,            -- snapshot
    product_name            VARCHAR(200)     NOT NULL,            -- snapshot
    unit_id                 BIGINT           NOT NULL,
    unit_name               VARCHAR(60)      NOT NULL,            -- snapshot
    requested_qty           NUMERIC(19,6)    NOT NULL,
    requested_qty_in_base   NUMERIC(19,6)    NOT NULL,
    estimated_unit_cost     NUMERIC(19,4),                        -- optional; CHECK >= 0
    required_by_date        DATE,                                 -- P2: per-line required-by date
    suggested_supplier_id   BIGINT,                               -- P2: soft-FK suppliers.id; line-level suggested source
    converted_to_po_line_uid VARCHAR(26),                         -- P2: per-line traceability to the produced PO line
    note                    VARCHAR(255),
    currency                VARCHAR(3),
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_purchase_requisition_line_uid    UNIQUE (uid),
    CONSTRAINT uq_purchase_requisition_line_no     UNIQUE (purchase_requisition_id, line_no),
    CONSTRAINT fk_purchase_requisition_line_req    FOREIGN KEY (purchase_requisition_id) REFERENCES purchase_requisitions (id),
    CONSTRAINT fk_purchase_requisition_line_product FOREIGN KEY (product_id)   REFERENCES products (id),
    CONSTRAINT fk_purchase_requisition_line_unit   FOREIGN KEY (unit_id)       REFERENCES units_of_measure (id),
    CONSTRAINT fk_purchase_requisition_line_company FOREIGN KEY (company_id)   REFERENCES companies (id),
    CONSTRAINT fk_purchase_requisition_line_branch FOREIGN KEY (branch_id)     REFERENCES branches (id),
    CONSTRAINT chk_purchase_requisition_line_qty   CHECK (requested_qty > 0 AND requested_qty_in_base > 0),
    CONSTRAINT chk_purchase_requisition_line_cost  CHECK (estimated_unit_cost IS NULL OR estimated_unit_cost >= 0),
    CONSTRAINT fk_purchase_requisition_line_sugg_supplier                                                    -- P2
        FOREIGN KEY (suggested_supplier_id) REFERENCES suppliers (id)
);

-- ============================================================================
-- (3) purchase_settings — per-company PO approval threshold config (ADR-0027 D-6)
-- ============================================================================
CREATE TABLE purchase_settings (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)      NOT NULL,
    company_id                  BIGINT           NOT NULL,
    po_approval_threshold_amount NUMERIC(19,4),
    po_approval_enabled         BOOLEAN          NOT NULL DEFAULT false,
    currency                    VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    -- P2 D7: company-wide procurement policy defaults (one row/company)
    default_payment_terms_id    BIGINT,                          -- soft-FK → payment_terms (no DB FK — additive)
    default_location_id         BIGINT,                          -- soft-FK → stock_locations (default receiving location)
    match_tolerance_pct         NUMERIC(9,4),                    -- default 3-way price-match tolerance %
    match_tolerance_abs         NUMERIC(19,4),                   -- default absolute match tolerance
    auto_close_enabled          BOOLEAN          NOT NULL DEFAULT false,  -- auto-close fully-received/billed POs
    requisition_approval_enabled BOOLEAN         NOT NULL DEFAULT false,  -- require PR approval before RFQ/PO
    requisition_approval_threshold_amount NUMERIC(19,4),         -- PR value above which approval is required
    version                     BIGINT           NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,

    CONSTRAINT uq_purchase_settings_uid     UNIQUE (uid),
    CONSTRAINT uq_purchase_settings_company UNIQUE (company_id),
    CONSTRAINT fk_purchase_settings_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- ============================================================================
-- (4) ALTER purchase_orders — add 4 approval-gate + lineage columns (ADR-0027 D-6)
-- Existing rows back-fill approval_status = 'NOT_REQUIRED' via DEFAULT.
-- ============================================================================
ALTER TABLE purchase_orders
    ADD COLUMN approval_status       VARCHAR(20) NOT NULL DEFAULT 'NOT_REQUIRED',
    ADD COLUMN approval_request_uid  VARCHAR(26),
    ADD COLUMN source_quote_uid      VARCHAR(26),
    ADD COLUMN source_requisition_uid VARCHAR(26);

ALTER TABLE purchase_orders
    ADD CONSTRAINT chk_purchase_order_approval_status
        CHECK (approval_status IN ('NOT_REQUIRED','PENDING','APPROVED','REJECTED'));

-- ============================================================================
-- (5) Indexes (ADR-0027 D-11)
-- ============================================================================
CREATE INDEX ix_purchase_requisitions_company        ON purchase_requisitions (company_id);
CREATE INDEX ix_purchase_requisitions_company_status ON purchase_requisitions (company_id, status);
CREATE INDEX ix_purchase_requisitions_pending
    ON purchase_requisitions (company_id) WHERE status = 'SUBMITTED';

CREATE INDEX ix_purchase_requisition_lines_req ON purchase_requisition_lines (purchase_requisition_id);

-- ============================================================================
-- (6) purchase_settings seed — one row per existing company (#12-safe uid, gate disabled)
-- uid: 'PS' || lpad(company_id, 6, '0') || substr(md5('purchase_settings'), 1, 12)
--    = 2+6+12 = 20 chars (<=26). ON CONFLICT DO NOTHING — idempotent.
-- ============================================================================
INSERT INTO purchase_settings (uid, company_id, po_approval_enabled, currency, version, created_at)
SELECT
    'PS' || lpad(c.id::text, 6, '0') || substr(md5('purchase_settings'), 1, 12) AS uid,
    c.id,
    false,
    'TZS',
    0,
    now()
FROM companies c
ON CONFLICT (company_id) DO NOTHING;
