-- V33 — Procurement depth: rfqs + rfq_lines + rfq_suppliers + supplier_quotes + supplier_quote_lines
--        permission seed + ORG_ADMIN grant.
-- Additive only. V1–V32 are FROZEN/in-flight.
-- ADR-0027 D-4 / D-10 / D-11 / D-12.
-- Order: (1) rfqs → (2) rfq_lines → (3) rfq_suppliers
--        → (4) supplier_quotes → (5) supplier_quote_lines
--        → (6) indexes → (7) permission seed + ORG_ADMIN grant.

-- ============================================================================
-- (1) rfqs — RFQ header
-- ============================================================================
CREATE TABLE rfqs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    rfq_number              VARCHAR(30)      NOT NULL,            -- RFQ-####; assigned at create
    status                  VARCHAR(20)      NOT NULL DEFAULT 'DRAFT',
    source_requisition_uid  VARCHAR(26),                          -- the PR it seeded from (nullable)
    response_due_date       DATE,
    awarded_quote_uid       VARCHAR(26),                          -- set on award
    awarded_po_uid          VARCHAR(26),                          -- the PO generated on award
    notes                   VARCHAR(500),
    sent_at                 TIMESTAMPTZ,
    awarded_at              TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_rfq_uid              UNIQUE (uid),
    CONSTRAINT uq_rfq_company_number   UNIQUE (company_id, rfq_number),
    CONSTRAINT fk_rfq_company          FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_rfq_branch           FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT chk_rfq_status          CHECK (status IN ('DRAFT','SENT','QUOTES_RECEIVED','AWARDED','CANCELLED'))
);

-- ============================================================================
-- (2) rfq_lines — child of rfqs; the product+qty lines to solicit
-- ============================================================================
CREATE TABLE rfq_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    rfq_id                  BIGINT           NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    line_no                 SMALLINT         NOT NULL,
    product_id              BIGINT           NOT NULL,
    product_code            VARCHAR(60)      NOT NULL,            -- snapshot
    product_name            VARCHAR(200)     NOT NULL,            -- snapshot
    unit_id                 BIGINT           NOT NULL,
    unit_name               VARCHAR(60)      NOT NULL,            -- snapshot
    quantity                NUMERIC(19,6)    NOT NULL,
    quantity_in_base        NUMERIC(19,6)    NOT NULL,
    required_by_date        DATE,                                 -- P2: per-line required-by date
    specification           VARCHAR(2000),                        -- P2: free-text spec / notes solicited from suppliers
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_rfq_line_uid     UNIQUE (uid),
    CONSTRAINT uq_rfq_line_no      UNIQUE (rfq_id, line_no),
    CONSTRAINT fk_rfq_line_rfq     FOREIGN KEY (rfq_id)     REFERENCES rfqs (id),
    CONSTRAINT fk_rfq_line_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_rfq_line_unit    FOREIGN KEY (unit_id)    REFERENCES units_of_measure (id),
    CONSTRAINT fk_rfq_line_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_rfq_line_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT chk_rfq_line_qty    CHECK (quantity > 0 AND quantity_in_base > 0)
);

-- ============================================================================
-- (3) rfq_suppliers — junction: which suppliers this RFQ targets (singular table)
-- ============================================================================
CREATE TABLE rfq_supplier (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    rfq_id                  BIGINT           NOT NULL,
    supplier_id             BIGINT           NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    sent_at                 TIMESTAMPTZ,
    responded_at            TIMESTAMPTZ,                          -- P2: when this supplier responded
    response_status         VARCHAR(20),                          -- P2: PENDING|RESPONDED|DECLINED|NO_RESPONSE
    supplier_quote_uid      VARCHAR(26),                          -- P2: scalar link to the supplier_quotes uid they submitted
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,

    CONSTRAINT uq_rfq_supplier_uid UNIQUE (uid),
    CONSTRAINT uq_rfq_supplier     UNIQUE (rfq_id, supplier_id),
    CONSTRAINT chk_rfq_supplier_response_status                                                            -- P2
        CHECK (response_status IS NULL OR response_status IN ('PENDING','RESPONDED','DECLINED','NO_RESPONSE')),
    CONSTRAINT fk_rfq_supplier_rfq      FOREIGN KEY (rfq_id)      REFERENCES rfqs (id),
    CONSTRAINT fk_rfq_supplier_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_rfq_supplier_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_rfq_supplier_branch   FOREIGN KEY (branch_id)   REFERENCES branches (id)
);

-- ============================================================================
-- (4) supplier_quotes — one per responding supplier per RFQ
-- ============================================================================
CREATE TABLE supplier_quotes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    quote_number            VARCHAR(30)      NOT NULL,            -- SQ-####; assigned at capture
    rfq_id                  BIGINT           NOT NULL,
    rfq_uid                 VARCHAR(26)      NOT NULL,            -- scalar cross-doc ref
    supplier_id             BIGINT           NOT NULL,
    supplier_code           VARCHAR(20)      NOT NULL,            -- snapshot
    supplier_name           VARCHAR(200)     NOT NULL,            -- snapshot
    status                  VARCHAR(20)      NOT NULL DEFAULT 'RECEIVED',
    valid_until             DATE,
    lead_time_days          SMALLINT,
    quote_total_amount      NUMERIC(19,4)    NOT NULL DEFAULT 0,
    currency                VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    notes                   VARCHAR(500),
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_supplier_quote_uid            UNIQUE (uid),
    CONSTRAINT uq_supplier_quote_company_number UNIQUE (company_id, quote_number),
    CONSTRAINT fk_supplier_quote_rfq            FOREIGN KEY (rfq_id)      REFERENCES rfqs (id),
    CONSTRAINT fk_supplier_quote_supplier       FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_quote_company        FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_supplier_quote_branch         FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT chk_supplier_quote_status        CHECK (status IN ('RECEIVED','AWARDED','NOT_AWARDED')),
    CONSTRAINT chk_supplier_quote_lead_time     CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
    CONSTRAINT chk_supplier_quote_total         CHECK (quote_total_amount >= 0)
);

-- ============================================================================
-- (5) supplier_quote_lines — child of supplier_quotes; per-line pricing
-- ============================================================================
CREATE TABLE supplier_quote_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    supplier_quote_id       BIGINT           NOT NULL,
    rfq_line_id             BIGINT,                               -- nullable: the RFQ line this prices
    rfq_line_uid            VARCHAR(26),                          -- scalar cross-doc ref
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    line_no                 SMALLINT         NOT NULL,
    product_id              BIGINT           NOT NULL,
    product_code            VARCHAR(60)      NOT NULL,            -- snapshot
    product_name            VARCHAR(200)     NOT NULL,            -- snapshot
    unit_id                 BIGINT           NOT NULL,
    unit_name               VARCHAR(60)      NOT NULL,            -- snapshot
    quoted_qty              NUMERIC(19,6)    NOT NULL,
    quoted_qty_in_base      NUMERIC(19,6)    NOT NULL,
    unit_price_amount       NUMERIC(19,4)    NOT NULL,
    line_total_amount       NUMERIC(19,4)    NOT NULL,
    currency                VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_supplier_quote_line_uid     UNIQUE (uid),
    CONSTRAINT uq_supplier_quote_line_no      UNIQUE (supplier_quote_id, line_no),
    CONSTRAINT fk_supplier_quote_line_quote   FOREIGN KEY (supplier_quote_id) REFERENCES supplier_quotes (id),
    CONSTRAINT fk_supplier_quote_line_rfq_ln  FOREIGN KEY (rfq_line_id)       REFERENCES rfq_lines (id),
    CONSTRAINT fk_supplier_quote_line_product FOREIGN KEY (product_id)        REFERENCES products (id),
    CONSTRAINT fk_supplier_quote_line_unit    FOREIGN KEY (unit_id)           REFERENCES units_of_measure (id),
    CONSTRAINT fk_supplier_quote_line_company FOREIGN KEY (company_id)        REFERENCES companies (id),
    CONSTRAINT fk_supplier_quote_line_branch  FOREIGN KEY (branch_id)         REFERENCES branches (id),
    CONSTRAINT chk_supplier_quote_line_qty    CHECK (quoted_qty > 0 AND quoted_qty_in_base > 0),
    CONSTRAINT chk_supplier_quote_line_price  CHECK (unit_price_amount >= 0 AND line_total_amount >= 0)
);

-- ============================================================================
-- (6) Indexes (ADR-0027 D-11)
-- ============================================================================
CREATE INDEX ix_rfqs_company               ON rfqs (company_id);
CREATE INDEX ix_rfqs_company_status        ON rfqs (company_id, status);
CREATE INDEX ix_rfq_lines_rfq              ON rfq_lines (rfq_id);
CREATE INDEX ix_rfq_supplier_rfq           ON rfq_supplier (rfq_id);
CREATE INDEX ix_rfq_supplier_supplier      ON rfq_supplier (supplier_id);
CREATE INDEX ix_supplier_quotes_company    ON supplier_quotes (company_id);
CREATE INDEX ix_supplier_quotes_rfq        ON supplier_quotes (rfq_id);
CREATE INDEX ix_supplier_quote_lines_quote ON supplier_quote_lines (supplier_quote_id);
-- The last-quoted-price reader index (BR-PROC-09, D-4):
-- supplier_id is on supplier_quotes (parent), not on quote_lines — cannot index here.
-- Use a join-based query; index the quote lines with product_id for fast lookup:
CREATE INDEX ix_supplier_quote_lines_product ON supplier_quote_lines (product_id, company_id);
