-- V27 — Cost-centre / Accounting-dimension framework (ADR-0025):
-- CREATE dimensions (per-company dimension types, 4 bounded slots);
-- CREATE dimension_values (members — cost centres, departments — self-FK roll-up);
-- ALTER journal_lines — add 4 additive nullable dimension slot-columns + FKs + partial indexes;
-- permission seed + ORG_ADMIN grant: COSTING.VIEW, COSTING.MANAGE, COSTING.TAG;
-- dimension seed per existing company: COST_CENTRE + DEPARTMENT built-in rows (#12-safe uids).
-- Additive only. V1–V19 are FROZEN.
-- Order: dimensions → dimension_values → journal_lines ALTER → indexes →
--        permission seed + grant → dimension seed.

-- ============================================================================
-- (1) dimensions — the per-company dimension type definitions (ADR-0025 D-2)
-- ============================================================================
CREATE TABLE dimensions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid          VARCHAR(26)     NOT NULL,
    company_id   BIGINT          NOT NULL,
    slot         VARCHAR(20)     NOT NULL,
    code         VARCHAR(40)     NOT NULL,
    name         VARCHAR(120)    NOT NULL,
    is_built_in  BOOLEAN         NOT NULL DEFAULT false,
    is_mandatory BOOLEAN         NOT NULL DEFAULT false,
    status       VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version      BIGINT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT,

    CONSTRAINT uq_dimension_uid              UNIQUE (uid),
    CONSTRAINT uq_dimension_company_slot     UNIQUE (company_id, slot),
    CONSTRAINT uq_dimension_company_code     UNIQUE (company_id, code),
    CONSTRAINT fk_dimension_company          FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_dimension_slot            CHECK (
        slot IN ('COST_CENTRE', 'DEPARTMENT', 'DIMENSION_3', 'DIMENSION_4')),
    CONSTRAINT chk_dimension_status          CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);

CREATE INDEX ix_dimensions_company ON dimensions (company_id);

-- ============================================================================
-- (2) dimension_values — the members per company (cost centres, departments)
-- ============================================================================
CREATE TABLE dimension_values (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid          VARCHAR(26)     NOT NULL,
    company_id   BIGINT          NOT NULL,
    dimension_id BIGINT          NOT NULL,
    code         VARCHAR(40)     NOT NULL,
    name         VARCHAR(160)    NOT NULL,
    parent_id    BIGINT,
    is_active    BOOLEAN         NOT NULL DEFAULT true,
    status       VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version      BIGINT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ,
    updated_by   BIGINT,

    CONSTRAINT uq_dimension_value_uid       UNIQUE (uid),
    CONSTRAINT uq_dimension_value_dim_code  UNIQUE (dimension_id, code),
    CONSTRAINT fk_dimension_value_company   FOREIGN KEY (company_id)   REFERENCES companies (id),
    CONSTRAINT fk_dimension_value_dimension FOREIGN KEY (dimension_id) REFERENCES dimensions (id),
    CONSTRAINT fk_dimension_value_parent    FOREIGN KEY (parent_id)    REFERENCES dimension_values (id),
    CONSTRAINT chk_dimension_value_status   CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);

CREATE INDEX ix_dimension_values_company   ON dimension_values (company_id);
CREATE INDEX ix_dimension_values_dimension ON dimension_values (dimension_id);
-- Partial index: active-value picker working set (NFR-CC-02)
CREATE INDEX ix_dimension_values_active    ON dimension_values (dimension_id) WHERE is_active = true;
-- Partial index: roll-up parent chain navigation (FR-CC-16)
CREATE INDEX ix_dimension_values_parent    ON dimension_values (parent_id) WHERE parent_id IS NOT NULL;

-- ============================================================================
-- (3) ALTER journal_lines — add 4 nullable dimension slot-columns (ADR-0025 D-3)
-- All nullable: untagged lines are unchanged; no existing posting is affected (NFR-CC-01).
-- DB FKs provide the same-company backstop (the service validates before posting).
-- ============================================================================
ALTER TABLE journal_lines
    ADD COLUMN cost_centre_value_id BIGINT,
    ADD COLUMN department_value_id  BIGINT,
    ADD COLUMN dimension3_value_id  BIGINT,
    ADD COLUMN dimension4_value_id  BIGINT;

ALTER TABLE journal_lines
    ADD CONSTRAINT fk_journal_line_cost_centre
        FOREIGN KEY (cost_centre_value_id) REFERENCES dimension_values (id),
    ADD CONSTRAINT fk_journal_line_department
        FOREIGN KEY (department_value_id)  REFERENCES dimension_values (id),
    ADD CONSTRAINT fk_journal_line_dimension3
        FOREIGN KEY (dimension3_value_id)  REFERENCES dimension_values (id),
    ADD CONSTRAINT fk_journal_line_dimension4
        FOREIGN KEY (dimension4_value_id)  REFERENCES dimension_values (id);

-- Partial indexes for dimension-sliced TB reads (NFR-CC-02): only tagged lines indexed.
CREATE INDEX ix_journal_lines_cost_centre
    ON journal_lines (company_id, cost_centre_value_id)
    WHERE cost_centre_value_id IS NOT NULL;

CREATE INDEX ix_journal_lines_department
    ON journal_lines (company_id, department_value_id)
    WHERE department_value_id IS NOT NULL;

-- ============================================================================
-- (4) Permission seed + ORG_ADMIN grant (ADR-0025 D-10; V17 pattern)
-- ============================================================================
INSERT INTO permissions (code, module, description) VALUES
    ('COSTING.VIEW',   'costing',
     'View dimensions, dimension values (cost centres / departments), and the dimension-sliced trial balance'),
    ('COSTING.MANAGE', 'costing',
     'Maintain dimension values (create/edit/deactivate) and set a dimension mandatory/optional'),
    ('COSTING.TAG',    'costing',
     'Pick dimension values on a journal / invoice / bill / adjustment when posting')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM   roles r
CROSS JOIN permissions p
WHERE  r.code   = 'ORG_ADMIN'
  AND  p.code IN ('COSTING.VIEW', 'COSTING.MANAGE', 'COSTING.TAG')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- (5) Dimension seed per existing company — built-in COST_CENTRE + DEPARTMENT (ADR-0025 D-9)
-- CRITICAL #12-safe seed-uid: 'DIM' || lpad(company_id,6,'0') || substr(md5(slot),1,12)
--   = 3+6+12 = 21 chars (<=26). NEVER || slot directly (overflow risk, ISSUES-REGISTER #12).
-- is_built_in=true — cannot be deleted (FR-CC-01).
-- is_mandatory=false — opt-in governance, off by default (BR-CC-03, NFR-CC-01).
-- ON CONFLICT (company_id, slot) DO NOTHING — idempotent on keep-data re-deploy.
-- ============================================================================
INSERT INTO dimensions (uid, company_id, slot, code, name, is_built_in, is_mandatory, status, version, created_at)
SELECT
    'DIM' || lpad(c.id::text, 6, '0') || substr(md5(s.slot), 1, 12) AS uid,
    c.id,
    s.slot,
    s.code,
    s.name,
    true,
    false,
    'ACTIVE',
    0,
    now()
FROM companies c
CROSS JOIN (VALUES
    ('COST_CENTRE', 'COST_CENTRE', 'Cost Centre'),
    ('DEPARTMENT',  'DEPARTMENT',  'Department')
) AS s(slot, code, name)
ON CONFLICT (company_id, slot) DO NOTHING;
