-- V2 — Parties module: customers, suppliers, agents, other_parties
-- Additive only. V1 (IAM) is FROZEN — this file does not edit it.
-- Order per ADR-0006 D-13:
--   (1) master tables → (2) party_code_sequence → (3) link tables
--   → (4) indexes (partial / expression) → (5) permission seed + ORG_ADMIN grant.

-- ---------------------------------------------------------------------------
-- (1a) customers
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    country                 VARCHAR(2),                 -- P2: PartyBase country (ISO-3166 alpha-2)
    customer_kind           VARCHAR(20)     NOT NULL,
    credit_limit_amount     NUMERIC(19,4),
    credit_limit_currency   VARCHAR(3),
    payment_terms_days      INTEGER,
    tax_exempt              BOOLEAN         NOT NULL DEFAULT false,  -- P2: customer tax-exemption flag
    tax_exemption_ref       VARCHAR(80),                -- P2: tax-exemption certificate/reference
    default_currency        VARCHAR(3),                 -- P2: customer default transaction currency (CurrencyCode)
    default_price_list_id   BIGINT,                     -- P2 D5: soft-FK → price_lists(id) (no DB FK, cross-module)
    default_agent_id        BIGINT,                     -- P2 D5: soft-FK → agents(id) (no DB FK, cross-module)
    segment                 VARCHAR(20)     NOT NULL DEFAULT 'OTHER', -- P2 D5: CustomerSegment enum (Tier-2 deferred; simple enum only)
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_customer_uid          UNIQUE (uid),
    CONSTRAINT uq_customer_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_customer_company      FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_customer_party_type  CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_customer_kind        CHECK (customer_kind IN ('CASH_WALK_IN','CREDIT_ACCOUNT')),
    CONSTRAINT chk_customer_segment     CHECK (segment IN ('RETAIL','WHOLESALE','GOVERNMENT','OTHER')),
    CONSTRAINT chk_customer_vrn_vat     CHECK (vrn IS NULL OR vat_registered = true),
    CONSTRAINT chk_customer_credit_pair CHECK (
        (credit_limit_amount IS NULL AND credit_limit_currency IS NULL) OR
        (credit_limit_amount IS NOT NULL AND credit_limit_currency IS NOT NULL)
    )
);

-- ---------------------------------------------------------------------------
-- (1b) suppliers
-- ---------------------------------------------------------------------------
CREATE TABLE suppliers (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    country                 VARCHAR(2),                 -- P2: PartyBase country (ISO-3166 alpha-2)
    supplier_kind           VARCHAR(20)     NOT NULL,
    payment_terms_days      INTEGER,
    default_currency        VARCHAR(3),                 -- P2 D5: supplier default transaction currency (CurrencyCode)
    lead_time_days          INTEGER,                    -- P2 D5: typical procurement lead time in days
    min_order_value         NUMERIC(19,4),              -- P2 D5: minimum order value threshold
    default_wht_type_id     BIGINT,                     -- P2 D5: soft-FK → wht_types(id) (no DB FK, cross-module)
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_supplier_uid          UNIQUE (uid),
    CONSTRAINT uq_supplier_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_supplier_company      FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_supplier_party_type  CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_supplier_kind        CHECK (supplier_kind IN ('GOODS','SERVICE')),
    CONSTRAINT chk_supplier_lead_time   CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
    CONSTRAINT chk_supplier_min_order   CHECK (min_order_value IS NULL OR min_order_value >= 0),
    CONSTRAINT chk_supplier_vrn_vat     CHECK (vrn IS NULL OR vat_registered = true)
);

-- ---------------------------------------------------------------------------
-- (1c) agents
-- ---------------------------------------------------------------------------
CREATE TABLE agents (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    country                 VARCHAR(2),                 -- P2: PartyBase country (ISO-3166 alpha-2)
    agent_kind              VARCHAR(20)     NOT NULL,
    app_user_id             BIGINT,
    sales_target            NUMERIC(19,4),              -- P2 D5: periodic sales target value
    quota                   NUMERIC(19,4),              -- P2 D5: assigned quota value
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_agent_uid              UNIQUE (uid),
    CONSTRAINT uq_agent_company_code     UNIQUE (company_id, code),
    CONSTRAINT fk_agent_company          FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_agent_app_user         FOREIGN KEY (app_user_id) REFERENCES app_users (id),
    CONSTRAINT chk_agent_party_type      CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_agent_kind            CHECK (agent_kind IN ('INTERNAL','EXTERNAL')),
    CONSTRAINT chk_agent_vrn_vat         CHECK (vrn IS NULL OR vat_registered = true),
    CONSTRAINT chk_agent_sales_target    CHECK (sales_target IS NULL OR sales_target >= 0),
    CONSTRAINT chk_agent_quota           CHECK (quota IS NULL OR quota >= 0),
    CONSTRAINT chk_agent_user_kind       CHECK (
        (agent_kind = 'INTERNAL' AND app_user_id IS NOT NULL) OR
        (agent_kind = 'EXTERNAL' AND app_user_id IS NULL)
    )
);

-- ---------------------------------------------------------------------------
-- (1d) other_parties
-- ---------------------------------------------------------------------------
CREATE TABLE other_parties (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    country                 VARCHAR(2),                 -- P2: PartyBase country (ISO-3166 alpha-2)
    other_kind              VARCHAR(40),
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_other_party_uid          UNIQUE (uid),
    CONSTRAINT uq_other_party_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_other_party_company      FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_other_party_party_type  CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_other_party_vrn_vat     CHECK (vrn IS NULL OR vat_registered = true)
);

-- ---------------------------------------------------------------------------
-- (2) party_code_sequence — locked counter per (company, kind) (ADR-0006 D-7)
-- ---------------------------------------------------------------------------
CREATE TABLE party_code_sequence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT          NOT NULL,
    party_kind  VARCHAR(20)     NOT NULL,
    next_value  BIGINT          NOT NULL DEFAULT 1,
    version     BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_party_code_sequence UNIQUE (company_id, party_kind),
    CONSTRAINT fk_party_code_seq_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_party_code_kind CHECK (party_kind IN ('CUSTOMER','SUPPLIER','AGENT','OTHER'))
);

-- ---------------------------------------------------------------------------
-- (3) link tables (singular, no uid per DATA-MODEL convention for junctions)
-- ---------------------------------------------------------------------------

-- customer_branch
CREATE TABLE customer_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    CONSTRAINT uq_customer_branch_pair  UNIQUE (customer_id, branch_id),
    CONSTRAINT fk_customer_branch_cust  FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_customer_branch_br    FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_customer_branch_by    FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- supplier_branch
CREATE TABLE supplier_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    CONSTRAINT uq_supplier_branch_pair  UNIQUE (supplier_id, branch_id),
    CONSTRAINT fk_supplier_branch_supp  FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_branch_br    FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_supplier_branch_by    FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- agent_branch
CREATE TABLE agent_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    CONSTRAINT uq_agent_branch_pair     UNIQUE (agent_id, branch_id),
    CONSTRAINT fk_agent_branch_agent    FOREIGN KEY (agent_id)    REFERENCES agents (id),
    CONSTRAINT fk_agent_branch_br       FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_agent_branch_by       FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- other_party_branch
CREATE TABLE other_party_branch (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    other_party_id  BIGINT          NOT NULL,
    branch_id       BIGINT          NOT NULL,
    assigned_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by     BIGINT          NOT NULL,
    CONSTRAINT uq_other_party_branch_pair   UNIQUE (other_party_id, branch_id),
    CONSTRAINT fk_other_party_branch_op     FOREIGN KEY (other_party_id) REFERENCES other_parties (id),
    CONSTRAINT fk_other_party_branch_br     FOREIGN KEY (branch_id)      REFERENCES branches (id),
    CONSTRAINT fk_other_party_branch_by     FOREIGN KEY (assigned_by)     REFERENCES app_users (id)
);

-- ---------------------------------------------------------------------------
-- (3e) payment_terms master (D-2, shared across customers and suppliers)
-- ---------------------------------------------------------------------------
CREATE TABLE payment_terms (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    code                VARCHAR(30)     NOT NULL,
    name                VARCHAR(120)    NOT NULL,
    basis               VARCHAR(30)     NOT NULL,
    net_days            INTEGER         NOT NULL DEFAULT 0,
    discount_days       INTEGER,
    discount_percent    NUMERIC(5,2),
    status              VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_payment_terms_uid             UNIQUE (uid),
    CONSTRAINT uq_payment_term_company_code     UNIQUE (company_id, code),
    CONSTRAINT fk_payment_terms_company         FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_payment_terms_basis          CHECK (basis IN ('DAYS_AFTER_INVOICE','DAYS_AFTER_MONTH_END','DUE_ON_RECEIPT')),
    CONSTRAINT chk_payment_terms_net_days       CHECK (net_days >= 0),
    CONSTRAINT chk_payment_terms_discount_pair  CHECK (
        (discount_days IS NULL AND discount_percent IS NULL) OR
        (discount_days IS NOT NULL AND discount_percent IS NOT NULL)
    ),
    CONSTRAINT chk_payment_terms_discount_days  CHECK (discount_days IS NULL OR discount_days >= 0),
    CONSTRAINT chk_payment_terms_discount_pct   CHECK (discount_percent IS NULL OR discount_percent >= 0)
);

-- Add payment_terms_id soft-FK to customers (scalar, no DB FK — soft-FK cross-module convention)
ALTER TABLE customers ADD COLUMN payment_terms_id BIGINT;

-- Add payment_terms_id soft-FK to suppliers (scalar, no DB FK — soft-FK cross-module convention)
ALTER TABLE suppliers ADD COLUMN payment_terms_id BIGINT;

-- ---------------------------------------------------------------------------
-- (4) Indexes
-- ---------------------------------------------------------------------------

-- payment_terms
CREATE INDEX ix_payment_terms_company
    ON payment_terms (company_id);
CREATE INDEX ix_payment_terms_company_name
    ON payment_terms (company_id, lower(name));

-- ---------------------------------------------------------------------------
-- (3f) supplier_bank_accounts — addressable child sub-master (has uid, D-4)
-- ---------------------------------------------------------------------------
CREATE TABLE supplier_bank_accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)     NOT NULL,
    company_id      BIGINT          NOT NULL,
    supplier_id     BIGINT          NOT NULL,
    bank_name       VARCHAR(120)    NOT NULL,
    account_name    VARCHAR(120)    NOT NULL,
    account_no      VARCHAR(60),
    bank_branch     VARCHAR(120),
    iban            VARCHAR(34),
    swift_bic       VARCHAR(11),
    currency        VARCHAR(3),
    is_default      BOOLEAN         NOT NULL DEFAULT false,
    status          VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    CONSTRAINT uq_supplier_bank_account_uid     UNIQUE (uid),
    CONSTRAINT fk_sba_company                   FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_sba_supplier                  FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT chk_sba_account_or_iban          CHECK (account_no IS NOT NULL OR iban IS NOT NULL)
);

-- Partial unique index: at most one is_default per supplier
CREATE UNIQUE INDEX uq_supplier_bank_account_default
    ON supplier_bank_accounts (supplier_id)
    WHERE is_default = true;

CREATE INDEX ix_supplier_bank_accounts_supplier
    ON supplier_bank_accounts (supplier_id);
CREATE INDEX ix_supplier_bank_accounts_company
    ON supplier_bank_accounts (company_id);

-- customers: tenant, name (expression), tin, phone; link table pair/direction indexes
CREATE INDEX ix_customers_company
    ON customers (company_id);
CREATE INDEX ix_customers_company_name
    ON customers (company_id, lower(display_name));
CREATE INDEX ix_customers_company_tin
    ON customers (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_customers_company_phone
    ON customers (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_customer_company_vrn
    ON customers (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_customer_branch_customer ON customer_branch (customer_id);
CREATE INDEX ix_customer_branch_branch   ON customer_branch (branch_id);

-- suppliers
CREATE INDEX ix_suppliers_company
    ON suppliers (company_id);
CREATE INDEX ix_suppliers_company_name
    ON suppliers (company_id, lower(display_name));
CREATE INDEX ix_suppliers_company_tin
    ON suppliers (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_suppliers_company_phone
    ON suppliers (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_supplier_company_vrn
    ON suppliers (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_supplier_branch_supplier ON supplier_branch (supplier_id);
CREATE INDEX ix_supplier_branch_branch   ON supplier_branch (branch_id);

-- agents
CREATE INDEX ix_agents_company
    ON agents (company_id);
CREATE INDEX ix_agents_company_name
    ON agents (company_id, lower(display_name));
CREATE INDEX ix_agents_company_tin
    ON agents (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_agents_company_phone
    ON agents (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_agent_company_vrn
    ON agents (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_agent_branch_agent  ON agent_branch (agent_id);
CREATE INDEX ix_agent_branch_branch ON agent_branch (branch_id);

-- other_parties
CREATE INDEX ix_other_parties_company
    ON other_parties (company_id);
CREATE INDEX ix_other_parties_company_name
    ON other_parties (company_id, lower(display_name));
CREATE INDEX ix_other_parties_company_tin
    ON other_parties (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_other_parties_company_phone
    ON other_parties (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_other_party_company_vrn
    ON other_parties (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_other_party_branch_op     ON other_party_branch (other_party_id);
CREATE INDEX ix_other_party_branch_branch ON other_party_branch (branch_id);
