-- V2 — Parties module: customers, suppliers, agents, other_parties
-- Additive only. V1 (IAM) is FROZEN — this file does not edit it.
-- Order per ADR-0006 D-13:
--   (1) master tables → (2) party_code_sequence → (3) link tables
--   → (4) indexes (partial / expression) → (5) permission seed + ORG_ADMIN grant.

-- ---------------------------------------------------------------------------
-- (1a) customers
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    customer_kind           VARCHAR(20)     NOT NULL,
    credit_limit_amount     NUMERIC(19,4),
    credit_limit_currency   VARCHAR(3),
    payment_terms_days      INTEGER,
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_customer_uid          UNIQUE (uid),
    CONSTRAINT uq_customer_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_customer_company      FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_customer_party_type  CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_customer_kind        CHECK (customer_kind IN ('CASH_WALK_IN','CREDIT_ACCOUNT')),
    CONSTRAINT chk_customer_vrn_vat     CHECK (vrn IS NULL OR vat_registered = true),
    CONSTRAINT chk_customer_credit_pair CHECK (
        (credit_limit_amount IS NULL AND credit_limit_currency IS NULL) OR
        (credit_limit_amount IS NOT NULL AND credit_limit_currency IS NOT NULL)
    )
);

-- ---------------------------------------------------------------------------
-- (1b) suppliers
-- ---------------------------------------------------------------------------
CREATE TABLE suppliers (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    supplier_kind           VARCHAR(20)     NOT NULL,
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_supplier_uid          UNIQUE (uid),
    CONSTRAINT uq_supplier_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_supplier_company      FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_supplier_party_type  CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_supplier_kind        CHECK (supplier_kind IN ('GOODS','SERVICE')),
    CONSTRAINT chk_supplier_vrn_vat     CHECK (vrn IS NULL OR vat_registered = true)
);

-- ---------------------------------------------------------------------------
-- (1c) agents
-- ---------------------------------------------------------------------------
CREATE TABLE agents (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    agent_kind              VARCHAR(20)     NOT NULL,
    app_user_id             BIGINT,
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_agent_uid              UNIQUE (uid),
    CONSTRAINT uq_agent_company_code     UNIQUE (company_id, code),
    CONSTRAINT fk_agent_company          FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_agent_app_user         FOREIGN KEY (app_user_id) REFERENCES app_users (id),
    CONSTRAINT chk_agent_party_type      CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_agent_kind            CHECK (agent_kind IN ('INTERNAL','EXTERNAL')),
    CONSTRAINT chk_agent_vrn_vat         CHECK (vrn IS NULL OR vat_registered = true),
    CONSTRAINT chk_agent_user_kind       CHECK (
        (agent_kind = 'INTERNAL' AND app_user_id IS NOT NULL) OR
        (agent_kind = 'EXTERNAL' AND app_user_id IS NULL)
    )
);

-- ---------------------------------------------------------------------------
-- (1d) other_parties
-- ---------------------------------------------------------------------------
CREATE TABLE other_parties (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    company_id              BIGINT          NOT NULL,
    code                    VARCHAR(20)     NOT NULL,
    party_type              VARCHAR(20)     NOT NULL,
    display_name            VARCHAR(200)    NOT NULL,
    legal_name              VARCHAR(200),
    tin                     VARCHAR(20),
    vat_registered          BOOLEAN         NOT NULL DEFAULT false,
    vrn                     VARCHAR(20),
    business_reg_no         VARCHAR(40),
    mobile_money_no         VARCHAR(30),
    phone                   VARCHAR(40),
    email                   VARCHAR(160),
    physical_address        VARCHAR(255),
    postal_address          VARCHAR(255),
    region                  VARCHAR(80),
    district                VARCHAR(80),
    other_kind              VARCHAR(40),
    status                  VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT          NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    CONSTRAINT uq_other_party_uid          UNIQUE (uid),
    CONSTRAINT uq_other_party_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_other_party_company      FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_other_party_party_type  CHECK (party_type IN ('INDIVIDUAL','BUSINESS')),
    CONSTRAINT chk_other_party_vrn_vat     CHECK (vrn IS NULL OR vat_registered = true)
);

-- ---------------------------------------------------------------------------
-- (2) party_code_sequence — locked counter per (company, kind) (ADR-0006 D-7)
-- ---------------------------------------------------------------------------
CREATE TABLE party_code_sequence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT          NOT NULL,
    party_kind  VARCHAR(20)     NOT NULL,
    next_value  BIGINT          NOT NULL DEFAULT 1,
    version     BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_party_code_sequence UNIQUE (company_id, party_kind),
    CONSTRAINT fk_party_code_seq_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_party_code_kind CHECK (party_kind IN ('CUSTOMER','SUPPLIER','AGENT','OTHER'))
);

-- ---------------------------------------------------------------------------
-- (3) link tables (singular, no uid per DATA-MODEL convention for junctions)
-- ---------------------------------------------------------------------------

-- customer_branch
CREATE TABLE customer_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    CONSTRAINT uq_customer_branch_pair  UNIQUE (customer_id, branch_id),
    CONSTRAINT fk_customer_branch_cust  FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_customer_branch_br    FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_customer_branch_by    FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- supplier_branch
CREATE TABLE supplier_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    CONSTRAINT uq_supplier_branch_pair  UNIQUE (supplier_id, branch_id),
    CONSTRAINT fk_supplier_branch_supp  FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_branch_br    FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_supplier_branch_by    FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- agent_branch
CREATE TABLE agent_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    CONSTRAINT uq_agent_branch_pair     UNIQUE (agent_id, branch_id),
    CONSTRAINT fk_agent_branch_agent    FOREIGN KEY (agent_id)    REFERENCES agents (id),
    CONSTRAINT fk_agent_branch_br       FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_agent_branch_by       FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- other_party_branch
CREATE TABLE other_party_branch (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    other_party_id  BIGINT          NOT NULL,
    branch_id       BIGINT          NOT NULL,
    assigned_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by     BIGINT          NOT NULL,
    CONSTRAINT uq_other_party_branch_pair   UNIQUE (other_party_id, branch_id),
    CONSTRAINT fk_other_party_branch_op     FOREIGN KEY (other_party_id) REFERENCES other_parties (id),
    CONSTRAINT fk_other_party_branch_br     FOREIGN KEY (branch_id)      REFERENCES branches (id),
    CONSTRAINT fk_other_party_branch_by     FOREIGN KEY (assigned_by)     REFERENCES app_users (id)
);

-- ---------------------------------------------------------------------------
-- (4) Indexes
-- ---------------------------------------------------------------------------

-- customers: tenant, name (expression), tin, phone; link table pair/direction indexes
CREATE INDEX ix_customers_company
    ON customers (company_id);
CREATE INDEX ix_customers_company_name
    ON customers (company_id, lower(display_name));
CREATE INDEX ix_customers_company_tin
    ON customers (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_customers_company_phone
    ON customers (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_customer_company_vrn
    ON customers (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_customer_branch_customer ON customer_branch (customer_id);
CREATE INDEX ix_customer_branch_branch   ON customer_branch (branch_id);

-- suppliers
CREATE INDEX ix_suppliers_company
    ON suppliers (company_id);
CREATE INDEX ix_suppliers_company_name
    ON suppliers (company_id, lower(display_name));
CREATE INDEX ix_suppliers_company_tin
    ON suppliers (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_suppliers_company_phone
    ON suppliers (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_supplier_company_vrn
    ON suppliers (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_supplier_branch_supplier ON supplier_branch (supplier_id);
CREATE INDEX ix_supplier_branch_branch   ON supplier_branch (branch_id);

-- agents
CREATE INDEX ix_agents_company
    ON agents (company_id);
CREATE INDEX ix_agents_company_name
    ON agents (company_id, lower(display_name));
CREATE INDEX ix_agents_company_tin
    ON agents (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_agents_company_phone
    ON agents (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_agent_company_vrn
    ON agents (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_agent_branch_agent  ON agent_branch (agent_id);
CREATE INDEX ix_agent_branch_branch ON agent_branch (branch_id);

-- other_parties
CREATE INDEX ix_other_parties_company
    ON other_parties (company_id);
CREATE INDEX ix_other_parties_company_name
    ON other_parties (company_id, lower(display_name));
CREATE INDEX ix_other_parties_company_tin
    ON other_parties (company_id, tin) WHERE tin IS NOT NULL;
CREATE INDEX ix_other_parties_company_phone
    ON other_parties (company_id, phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX uq_other_party_company_vrn
    ON other_parties (company_id, vrn) WHERE vrn IS NOT NULL;

CREATE INDEX ix_other_party_branch_op     ON other_party_branch (other_party_id);
CREATE INDEX ix_other_party_branch_branch ON other_party_branch (branch_id);

-- ---------------------------------------------------------------------------
-- (5) Permission seed + additive ORG_ADMIN grant (ADR-0006 D-10)
-- ---------------------------------------------------------------------------
INSERT INTO permissions (code, module, description) VALUES
    ('CUSTOMER.VIEW',       'parties', 'View and select customers'),
    ('CUSTOMER.MANAGE',     'parties', 'Create, update and archive customers'),
    ('SUPPLIER.VIEW',       'parties', 'View and select suppliers'),
    ('SUPPLIER.MANAGE',     'parties', 'Create, update and archive suppliers'),
    ('AGENT.VIEW',          'parties', 'View and select sales agents'),
    ('AGENT.MANAGE',        'parties', 'Create, update and archive sales agents'),
    ('OTHERPARTY.VIEW',     'parties', 'View and select other/misc parties'),
    ('OTHERPARTY.MANAGE',   'parties', 'Create, update and archive other/misc parties'),
    ('PARTY.BRANCH.ASSIGN', 'parties', 'Associate/dissociate any party with branches of its company')
ON CONFLICT (code) DO NOTHING;

-- Additively grant all parties permissions to ORG_ADMIN (same INSERT-SELECT pattern as V1).
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'ORG_ADMIN' AND p.module = 'parties'
ON CONFLICT DO NOTHING;
