-- V30 — Multi-level Bill of Materials (ADR-0026):
-- boms header + bom_components child, partial-unique one-active index,
-- permission seed + ORG_ADMIN grant.
-- Additive only. V1–V19 are FROZEN — this file does not edit them.
-- product_components is LEFT INTACT (OQ-BOM-01, D-5 coexistence).
-- No GL config keys, no CoA accounts, no DomainEventType, no code_sequence (D-9/D-12).
-- Order: (1) boms → (2) bom_components → (3) partial-unique index
--        → (4) performance indexes → (5) permission seed + ORG_ADMIN grant.

-- ============================================================================
-- (1) boms — versioned BOM header per parent product (D-2)
-- ============================================================================
CREATE TABLE boms (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)         NOT NULL,
    company_id          BIGINT              NOT NULL,
    parent_product_id   BIGINT              NOT NULL,
    version_no          INTEGER             NOT NULL,
    status              VARCHAR(20)         NOT NULL DEFAULT 'DRAFT',
    output_qty          NUMERIC(19,6)       NOT NULL DEFAULT 1,
    yield_percent       NUMERIC(9,4)        NOT NULL DEFAULT 100,
    effective_from      DATE,
    effective_to        DATE,
    source_bom_uid      VARCHAR(26),
    notes               VARCHAR(500),
    activated_at        TIMESTAMPTZ,
    archived_at         TIMESTAMPTZ,
    version             BIGINT              NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ         NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_bom_uid
        UNIQUE (uid),
    CONSTRAINT uq_bom_parent_version
        UNIQUE (parent_product_id, version_no),
    CONSTRAINT fk_bom_company
        FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_bom_parent
        FOREIGN KEY (parent_product_id) REFERENCES products (id),
    CONSTRAINT chk_bom_status
        CHECK (status IN ('DRAFT','ACTIVE','ARCHIVED')),
    CONSTRAINT chk_bom_output_qty
        CHECK (output_qty > 0),
    CONSTRAINT chk_bom_yield
        CHECK (yield_percent > 0 AND yield_percent <= 100),
    CONSTRAINT chk_bom_effectivity
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from)
);

-- ============================================================================
-- (2) bom_components — child lines under a bom header (D-3)
-- ============================================================================
CREATE TABLE bom_components (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)         NOT NULL,
    bom_id                      BIGINT              NOT NULL,
    company_id                  BIGINT              NOT NULL,
    line_no                     SMALLINT            NOT NULL,
    component_product_id        BIGINT              NOT NULL,
    component_product_code      VARCHAR(20)         NOT NULL,
    component_product_name      VARCHAR(200)        NOT NULL,
    qty_per                     NUMERIC(19,6)       NOT NULL,
    sourcing                    VARCHAR(10)         NOT NULL DEFAULT 'BUY',
    scrap_percent               NUMERIC(9,4)        NOT NULL DEFAULT 0,
    reference                   VARCHAR(120),
    created_at                  TIMESTAMPTZ         NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,

    CONSTRAINT uq_bom_component_uid
        UNIQUE (uid),
    CONSTRAINT uq_bom_component_line_no
        UNIQUE (bom_id, line_no),
    CONSTRAINT uq_bom_component_child
        UNIQUE (bom_id, component_product_id),
    CONSTRAINT fk_bom_component_bom
        FOREIGN KEY (bom_id) REFERENCES boms (id),
    CONSTRAINT fk_bom_component_company
        FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_bom_component_product
        FOREIGN KEY (component_product_id) REFERENCES products (id),
    CONSTRAINT chk_bom_component_qty
        CHECK (qty_per > 0),
    CONSTRAINT chk_bom_component_sourcing
        CHECK (sourcing IN ('MAKE','BUY')),
    CONSTRAINT chk_bom_component_scrap
        CHECK (scrap_percent >= 0 AND scrap_percent < 100)
);

-- ============================================================================
-- (3) Partial-unique index — BR-BOM-04 backstop: at most one ACTIVE per parent (D-2)
-- A concurrent double-activate is rejected at the DB level by this index.
-- ============================================================================
CREATE UNIQUE INDEX uq_bom_one_active
    ON boms (parent_product_id)
    WHERE status = 'ACTIVE';

-- ============================================================================
-- (4) Performance indexes (D-2/D-3)
-- ============================================================================

-- boms
CREATE INDEX ix_boms_company
    ON boms (company_id);
CREATE INDEX ix_boms_parent
    ON boms (parent_product_id);
CREATE INDEX ix_boms_parent_status
    ON boms (parent_product_id, status);

-- bom_components
CREATE INDEX ix_bom_components_bom
    ON bom_components (bom_id);
CREATE INDEX ix_bom_components_child
    ON bom_components (component_product_id);
CREATE INDEX ix_bom_components_company
    ON bom_components (company_id);

-- ============================================================================
-- (5) Permission seed + ORG_ADMIN grant (D-11 / V3/V7/V17 pattern)
-- No uid column on permissions — #12 N/A.
-- ============================================================================
INSERT INTO permissions (code, module, description) VALUES
    ('BOM.VIEW',   'products', 'View, list, explode, where-used and cost-roll-up for Bills of Materials'),
    ('BOM.MANAGE', 'products', 'Create, edit drafts, add/remove components, activate, archive and clone BOMs')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM   roles r
CROSS JOIN permissions p
WHERE  r.code   = 'ORG_ADMIN'
  AND  p.code IN ('BOM.VIEW', 'BOM.MANAGE')
ON CONFLICT DO NOTHING;
