-- V37 — Inventory Depth (ADR-0028, D-4/D-13): stock_locations master + default-location backfill.
-- Creates the location master BEFORE the on-hand re-grain (load-bearing order, D-13).
-- Seeds one ACTIVE WAREHOUSE default location per existing branch (#12-safe uid).
-- Seeds one in-transit OTHER location per branch for in-transit holding (D-5).
-- Additive only. V1–V36 are FROZEN.

-- ============================================================================
-- (1) CREATE stock_locations
-- ============================================================================
CREATE TABLE stock_locations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           VARCHAR(26)     NOT NULL,
    company_id    BIGINT          NOT NULL,
    branch_id     BIGINT          NOT NULL,
    code          VARCHAR(30)     NOT NULL,
    name          VARCHAR(120)    NOT NULL,
    location_type VARCHAR(20)     NOT NULL,
    is_default    BOOLEAN         NOT NULL DEFAULT false,
    parent_location_id BIGINT,                              -- P2 D7: self soft-FK — location hierarchy (no DB FK)
    allow_negative BOOLEAN        NOT NULL DEFAULT false,   -- P2 D7: permit negative on-hand at this location
    pickable      BOOLEAN         NOT NULL DEFAULT true,    -- P2 D7: stock here is available for picking
    sellable      BOOLEAN         NOT NULL DEFAULT true,    -- P2 D7: stock here is available to sell
    gl_account_id BIGINT,                                   -- P2 D7: per-location inventory GL account override (soft-FK)
    status        VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    version       BIGINT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT,
    CONSTRAINT uq_stock_location_uid          UNIQUE (uid),
    CONSTRAINT uq_stock_location_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_stock_location_company      FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_stock_location_branch       FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT chk_stock_location_type   CHECK (location_type IN ('WAREHOUSE','STORE','VAN','QUARANTINE','OTHER')),
    CONSTRAINT chk_stock_location_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'))
);

-- Partial-unique: exactly one default per branch (D-4, BR-INVD-01)
CREATE UNIQUE INDEX uq_stock_location_one_default
    ON stock_locations (company_id, branch_id)
    WHERE is_default = true;

-- Support index for per-branch list
CREATE INDEX ix_stock_locations_branch
    ON stock_locations (company_id, branch_id);

-- ============================================================================
-- (2) Backfill — seed one WAREHOUSE default location per existing branch
--     uid: 'SLC' || lpad(company_id, 6, '0') || substr(md5(branch_id::text), 1, 12)
--       = 3+6+12 = 21 chars (<= 26). NEVER raw-key concat (#12 rule).
--     code: 'MAIN-' || b.code (deterministic, OQ-INVD-09, D-13).
--     ON CONFLICT DO NOTHING — idempotent on keep-data re-deploy.
-- ============================================================================
INSERT INTO stock_locations (
    uid, company_id, branch_id, code, name,
    location_type, is_default, status, version, created_at
)
SELECT
    'SLC' || lpad(b.company_id::text, 6, '0') || substr(md5(b.id::text), 1, 12) AS uid,
    b.company_id,
    b.id          AS branch_id,
    'MAIN-' || b.code                                                              AS code,
    'Main Store — ' || b.name                                                      AS name,
    'WAREHOUSE',
    true,
    'ACTIVE',
    0,
    now()
FROM branches b
ON CONFLICT (company_id, code) DO NOTHING;

-- ============================================================================
-- (3) Backfill — seed one in-transit OTHER location per existing branch (D-5)
--     Used as the in-transit holding location for IN_TRANSIT mode transfers.
--     uid: 'SLT' || lpad(company_id, 6, '0') || substr(md5(branch_id::text), 1, 12)
--       = 3+6+12 = 21 chars (<= 26).
--     is_default = false; name = 'In-Transit — <branch>'.
-- ============================================================================
INSERT INTO stock_locations (
    uid, company_id, branch_id, code, name,
    location_type, is_default, status, version, created_at
)
SELECT
    'SLT' || lpad(b.company_id::text, 6, '0') || substr(md5(b.id::text), 1, 12) AS uid,
    b.company_id,
    b.id          AS branch_id,
    'TRANSIT-' || b.code                                                           AS code,
    'In-Transit — ' || b.name                                                      AS name,
    'OTHER',
    false,
    'ACTIVE',
    0,
    now()
FROM branches b
ON CONFLICT (company_id, code) DO NOTHING;
