-- V39 — Inventory Depth (ADR-0028, D-5/D-13): stock_transfers + stock_transfer_lines.
-- In-transit TRANSFER_OUT / TRANSFER_IN document, no GL (value-preserving, single avg).
-- Additive only. V1–V38 are FROZEN.

-- ============================================================================
-- (1) CREATE stock_transfers (header)
-- ============================================================================
CREATE TABLE stock_transfers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    transfer_number     VARCHAR(30)     NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    transfer_mode       VARCHAR(12)     NOT NULL,
    source_branch_id    BIGINT          NOT NULL,
    source_location_id  BIGINT          NOT NULL,
    dest_branch_id      BIGINT          NOT NULL,
    dest_location_id    BIGINT          NOT NULL,
    transfer_date       DATE            NOT NULL,
    dispatched_at       TIMESTAMPTZ,
    received_at         TIMESTAMPTZ,
    notes               VARCHAR(500),
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_stock_transfer_uid            UNIQUE (uid),
    CONSTRAINT uq_stock_transfer_company_number UNIQUE (company_id, transfer_number),
    CONSTRAINT fk_stock_transfer_company        FOREIGN KEY (company_id)         REFERENCES companies (id),
    CONSTRAINT fk_stock_transfer_src_branch     FOREIGN KEY (source_branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_stock_transfer_src_location   FOREIGN KEY (source_location_id) REFERENCES stock_locations (id),
    CONSTRAINT fk_stock_transfer_dst_branch     FOREIGN KEY (dest_branch_id)     REFERENCES branches (id),
    CONSTRAINT fk_stock_transfer_dst_location   FOREIGN KEY (dest_location_id)   REFERENCES stock_locations (id),
    CONSTRAINT chk_stock_transfer_status   CHECK (status IN ('DRAFT','DISPATCHED','RECEIVED','COMPLETED','CANCELLED')),
    CONSTRAINT chk_stock_transfer_mode     CHECK (transfer_mode IN ('INSTANT','IN_TRANSIT')),
    CONSTRAINT chk_stock_transfer_distinct CHECK (source_location_id <> dest_location_id)
);

CREATE INDEX ix_stock_transfers_company
    ON stock_transfers (company_id, status, transfer_date DESC);

CREATE INDEX ix_stock_transfers_src_location
    ON stock_transfers (source_location_id);

CREATE INDEX ix_stock_transfers_dst_location
    ON stock_transfers (dest_location_id);

-- ============================================================================
-- (2) CREATE stock_transfer_lines (child rows)
-- ============================================================================
CREATE TABLE stock_transfer_lines (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)     NOT NULL,
    stock_transfer_id    BIGINT          NOT NULL,
    company_id           BIGINT          NOT NULL,
    line_no              SMALLINT        NOT NULL,
    product_id           BIGINT          NOT NULL,
    product_code         VARCHAR(50)     NOT NULL,
    product_name         VARCHAR(255)    NOT NULL,
    unit_id              BIGINT,
    unit_name            VARCHAR(50),
    qty_transferred      NUMERIC(19,6)   NOT NULL,
    qty_transferred_base NUMERIC(19,6)   NOT NULL,
    value_amount         NUMERIC(19,4),
    currency             VARCHAR(3)      NOT NULL DEFAULT 'TZS',
    version              BIGINT          NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,
    CONSTRAINT uq_stock_transfer_line_uid    UNIQUE (uid),
    CONSTRAINT uq_stock_transfer_line_no     UNIQUE (stock_transfer_id, line_no),
    CONSTRAINT fk_stock_transfer_line_header FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfers (id),
    CONSTRAINT fk_stock_transfer_line_product FOREIGN KEY (product_id)       REFERENCES products (id),
    CONSTRAINT chk_stock_transfer_line_qty   CHECK (qty_transferred > 0),
    CONSTRAINT chk_stock_transfer_line_base  CHECK (qty_transferred_base > 0)
);

CREATE INDEX ix_stock_transfer_lines_transfer
    ON stock_transfer_lines (stock_transfer_id);
