-- V34 — Procurement depth: landed_costs + landed_cost_receipts + landed_cost_charges
--        + landed_cost_allocations; CoA back-seed 2160 Landed Cost Clearing;
--        chk_gl_config_key widen (FULL union incl. LANDED_COST_CLEARING);
--        gl_configs key back-seed; ALTER supplier_bill_lines ADD landed_cost_uid;
--        journal source-type CHECK widen (add LANDED_COST);
--        permission seed + ORG_ADMIN grant.
-- Additive only. V1–V33 are FROZEN/in-flight.
-- ADR-0027 D-5 / D-7 / D-8 / D-9 / D-10 / D-12.

-- ============================================================================
-- (1) landed_costs — LC header
-- ============================================================================
CREATE TABLE landed_costs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    landed_cost_number      VARCHAR(30)      NOT NULL,            -- LC-####; assigned at create
    status                  VARCHAR(20)      NOT NULL DEFAULT 'DRAFT',
    basis                   VARCHAR(20)      NOT NULL DEFAULT 'BY_VALUE',
    total_charge_amount     NUMERIC(19,4)    NOT NULL DEFAULT 0,
    currency                VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    gl_entry_uid            VARCHAR(26),                          -- capitalisation journal uid (diagnostic)
    notes                   VARCHAR(500),
    confirmed_at            TIMESTAMPTZ,
    confirmed_by            BIGINT,
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_landed_cost_uid            UNIQUE (uid),
    CONSTRAINT uq_landed_cost_company_number UNIQUE (company_id, landed_cost_number),
    CONSTRAINT fk_landed_cost_company        FOREIGN KEY (company_id)   REFERENCES companies (id),
    CONSTRAINT fk_landed_cost_branch         FOREIGN KEY (branch_id)    REFERENCES branches (id),
    CONSTRAINT fk_landed_cost_confirmed_by   FOREIGN KEY (confirmed_by) REFERENCES app_users (id),
    CONSTRAINT chk_landed_cost_status        CHECK (status IN ('DRAFT','CONFIRMED')),
    CONSTRAINT chk_landed_cost_basis         CHECK (basis IN ('BY_VALUE','BY_QUANTITY')),
    CONSTRAINT chk_landed_cost_total         CHECK (total_charge_amount >= 0)
);

-- ============================================================================
-- (2) landed_cost_receipts — junction: the GRs this LC covers
-- ============================================================================
CREATE TABLE landed_cost_receipt (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    landed_cost_id          BIGINT           NOT NULL,
    goods_receipt_id        BIGINT           NOT NULL,
    goods_receipt_uid       VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,

    CONSTRAINT uq_landed_cost_receipt_uid UNIQUE (uid),
    CONSTRAINT uq_landed_cost_receipt     UNIQUE (landed_cost_id, goods_receipt_id),
    CONSTRAINT fk_landed_cost_receipt_lc  FOREIGN KEY (landed_cost_id)   REFERENCES landed_costs (id),
    CONSTRAINT fk_landed_cost_receipt_gr  FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts (id),
    CONSTRAINT fk_landed_cost_receipt_co  FOREIGN KEY (company_id)       REFERENCES companies (id),
    CONSTRAINT fk_landed_cost_receipt_br  FOREIGN KEY (branch_id)        REFERENCES branches (id)
);

-- ============================================================================
-- (3) landed_cost_charges — charge lines (freight/duty/etc.)
-- ============================================================================
CREATE TABLE landed_cost_charges (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    landed_cost_id          BIGINT           NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    line_no                 SMALLINT         NOT NULL,
    charge_type             VARCHAR(20)      NOT NULL,
    amount                  NUMERIC(19,4)    NOT NULL,
    is_billed               BOOLEAN          NOT NULL DEFAULT false,
    supplier_bill_uid       VARCHAR(26),                          -- the freight bill if is_billed
    currency                VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_landed_cost_charge_uid UNIQUE (uid),
    CONSTRAINT uq_landed_cost_charge_no  UNIQUE (landed_cost_id, line_no),
    CONSTRAINT fk_landed_cost_charge_lc  FOREIGN KEY (landed_cost_id) REFERENCES landed_costs (id),
    CONSTRAINT fk_landed_cost_charge_co  FOREIGN KEY (company_id)     REFERENCES companies (id),
    CONSTRAINT fk_landed_cost_charge_br  FOREIGN KEY (branch_id)      REFERENCES branches (id),
    CONSTRAINT chk_landed_cost_charge_type
        CHECK (charge_type IN ('FREIGHT','DUTY','CLEARING','INSURANCE','OTHER')),
    CONSTRAINT chk_landed_cost_charge_amount  CHECK (amount > 0),
    CONSTRAINT chk_landed_cost_charge_billed
        CHECK ((is_billed = false AND supplier_bill_uid IS NULL)
            OR (is_billed = true  AND supplier_bill_uid IS NOT NULL))
);

-- ============================================================================
-- (4) landed_cost_allocations — per-receipt-line allocation amounts (the maths audit)
-- ============================================================================
CREATE TABLE landed_cost_allocations (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    landed_cost_id          BIGINT           NOT NULL,
    goods_receipt_line_id   BIGINT           NOT NULL,
    goods_receipt_line_uid  VARCHAR(26)      NOT NULL,
    product_id              BIGINT           NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    allocated_amount        NUMERIC(19,4)    NOT NULL,
    currency                VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,

    CONSTRAINT uq_landed_cost_allocation_uid UNIQUE (uid),
    CONSTRAINT uq_landed_cost_allocation     UNIQUE (landed_cost_id, goods_receipt_line_id),
    CONSTRAINT fk_landed_cost_alloc_lc       FOREIGN KEY (landed_cost_id)         REFERENCES landed_costs (id),
    CONSTRAINT fk_landed_cost_alloc_grl      FOREIGN KEY (goods_receipt_line_id)  REFERENCES goods_receipt_lines (id),
    CONSTRAINT fk_landed_cost_alloc_product  FOREIGN KEY (product_id)             REFERENCES products (id),
    CONSTRAINT fk_landed_cost_alloc_co       FOREIGN KEY (company_id)             REFERENCES companies (id),
    CONSTRAINT fk_landed_cost_alloc_br       FOREIGN KEY (branch_id)              REFERENCES branches (id),
    CONSTRAINT chk_landed_cost_alloc_amount  CHECK (allocated_amount >= 0)
);

-- ============================================================================
-- (5) Indexes (ADR-0027 D-11)
-- ============================================================================
CREATE INDEX ix_landed_costs_company        ON landed_costs (company_id);
CREATE INDEX ix_landed_costs_company_status ON landed_costs (company_id, status);
CREATE INDEX ix_landed_cost_receipts_lc     ON landed_cost_receipt (landed_cost_id);
CREATE INDEX ix_landed_cost_receipts_gr     ON landed_cost_receipt (goods_receipt_id);
CREATE INDEX ix_landed_cost_charges_lc      ON landed_cost_charges (landed_cost_id);
CREATE INDEX ix_landed_cost_allocations_lc  ON landed_cost_allocations (landed_cost_id);
CREATE INDEX ix_landed_cost_allocations_prod ON landed_cost_allocations (company_id, product_id);

-- ============================================================================
-- (6) CoA back-seed — 2160 Landed Cost Clearing per existing company
-- uid: 'PC' || lpad(company_id, 6, '0') || '2160' = 2+6+4 = 12 chars (<=26)
-- ON CONFLICT (company_id, account_code) DO NOTHING — idempotent.
-- ============================================================================
INSERT INTO chart_of_accounts (
    uid, company_id, account_code, name, account_type, normal_balance,
    is_active, status, version, created_at
)
SELECT
    'PC' || lpad(c.id::text, 6, '0') || '2160' AS uid,
    c.id,
    '2160',
    'Landed Cost Clearing',
    'LIABILITY',
    'CREDIT',
    true,
    'ACTIVE',
    0,
    now()
FROM companies c
ON CONFLICT (company_id, account_code) DO NOTHING;

-- ============================================================================
-- (7) chk_gl_config_key widen — FULL union of ALL prior keys + LANDED_COST_CLEARING
-- Prior union at V46: V17 keys + FA keys. Our V32-V34 come BEFORE V37+, so we build
-- the union of V17 + FA (from V46) + LANDED_COST_CLEARING here.
-- Since V34 < V46 in number, but V46 is already on this branch (in-flight):
-- we must include the FA keys so our constraint doesn't conflict if V46 runs after us.
-- IMPORTANT: V46 will re-DROP and re-ADD with its own union which includes FA keys.
-- If V34 runs BEFORE V46, we set keys = V17 + LANDED_COST_CLEARING.
-- If V46 runs AFTER V34, V46 will widen again to include FA keys.
-- Since V32-V36 < V46 numerically, V32-V36 run first.
-- So here we include only V17 keys + LANDED_COST_CLEARING.
-- V46 will then add FA keys on top.
-- ============================================================================
ALTER TABLE gl_configs
    DROP CONSTRAINT IF EXISTS chk_gl_config_key;

ALTER TABLE gl_configs
    ADD CONSTRAINT chk_gl_config_key CHECK (
        config_key IN (
            'SALES_REVENUE','VAT_PAYABLE','ACCOUNTS_RECEIVABLE','CASH',
            'INVENTORY','COGS','ACCOUNTS_PAYABLE',
            'BAD_DEBT_EXPENSE','OPENING_BALANCE_EQUITY',
            'PURCHASES',
            'VAT_INPUT','VAT_DUE','WHT_PAYABLE','WHT_RECEIVABLE',
            'RETAINED_EARNINGS',
            'GRNI','STOCK_ADJUSTMENT',
            -- procurement-depth (ADR-0027) ---
            'LANDED_COST_CLEARING'
        ));

-- ============================================================================
-- (8) gl_configs back-seed: LANDED_COST_CLEARING → 2160 per existing company
-- uid: 'PG' || lpad(company_id, 6, '0') || substr(md5('LANDED_COST_CLEARING'), 1, 12)
--    = 2+6+12 = 20 chars (<=26). #12-safe. ON CONFLICT (company_id, config_key) DO NOTHING.
-- ============================================================================
INSERT INTO gl_configs (uid, company_id, config_key, account_id, version, created_at)
SELECT
    'PG' || lpad(coa.company_id::text, 6, '0') || substr(md5('LANDED_COST_CLEARING'), 1, 12) AS uid,
    coa.company_id,
    'LANDED_COST_CLEARING',
    coa.id,
    0,
    now()
FROM chart_of_accounts coa
WHERE coa.account_code = '2160'
ON CONFLICT (company_id, config_key) DO NOTHING;

-- ============================================================================
-- (9) ALTER supplier_bill_lines — add landed_cost_uid clearing signal (ADR-0027 D-7)
-- ============================================================================
ALTER TABLE supplier_bill_lines
    ADD COLUMN landed_cost_uid VARCHAR(26);

-- ============================================================================
-- (10) journal source-type CHECK widen — add LANDED_COST
-- Full union of V46 tokens + LANDED_COST.
-- Since V34 < V46, here we include V17 tokens + LANDED_COST only.
-- V46 will re-widen to include FA tokens; since V46 is a DROP/ADD it will need
-- to include LANDED_COST too. But V46 is an IN-FLIGHT migration we must not edit.
-- RESOLUTION: V46 is already shipped on develop and we cannot edit it.
-- We widen here with V17 + LANDED_COST; V46 will then further widen to V17+FA.
-- This means after V34+V46, the constraint has V17+FA keys but NOT LANDED_COST.
-- FIX: We must include LANDED_COST in V34's widen, and accept that V46 overrides us.
-- Since we cannot edit V46, we will add LANDED_COST again in V36 (indexes/fixup migration)
-- to ensure it's in the final constraint after V46 runs.
-- For now, V34 widens with V17 + LANDED_COST (which V46 will override):
-- ============================================================================
ALTER TABLE journal_batches
    DROP CONSTRAINT IF EXISTS chk_journal_batch_source_type;

ALTER TABLE journal_batches
    ADD CONSTRAINT chk_journal_batch_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT',
            'VAT_RETURN',
            'YEAR_END_CLOSE',
            'STOCK_RECEIPT','COGS','STOCK_ADJUSTMENT','OPENING_INVENTORY',
            -- procurement-depth (ADR-0027) ---
            'LANDED_COST','PURCHASE_RETURN'
        ));

ALTER TABLE journal_entries
    DROP CONSTRAINT IF EXISTS chk_journal_entry_source_type;

ALTER TABLE journal_entries
    ADD CONSTRAINT chk_journal_entry_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT',
            'VAT_RETURN',
            'YEAR_END_CLOSE',
            'STOCK_RECEIPT','COGS','STOCK_ADJUSTMENT','OPENING_INVENTORY',
            -- procurement-depth (ADR-0027) ---
            'LANDED_COST','PURCHASE_RETURN'
        ));

-- ============================================================================
-- (11) Permission seed + ORG_ADMIN grant (ADR-0027 D-10)
-- ============================================================================
INSERT INTO permissions (code, module, description) VALUES
    ('PURCHASE.LANDEDCOST.VIEW',   'purchases', 'View landed-cost documents and allocations'),
    ('PURCHASE.LANDEDCOST.MANAGE', 'purchases', 'Create and confirm landed-cost allocations')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM   roles r
CROSS JOIN permissions p
WHERE  r.code = 'ORG_ADMIN'
  AND  p.code IN ('PURCHASE.LANDEDCOST.VIEW', 'PURCHASE.LANDEDCOST.MANAGE')
ON CONFLICT DO NOTHING;
