-- V40 — Inventory Depth (ADR-0028, D-6/D-13): stock_counts + stock_count_lines.
-- Count lifecycle DRAFT → COUNTING → POSTED; posts variance via ADR-0020 revalueAdjustment.
-- No new movement type — reuses ADJUSTMENT with source_document_type='STOCK_COUNT' (OQ-INVD-07).
-- Additive only. V1–V39 are FROZEN.

-- ============================================================================
-- (1) CREATE stock_counts (header)
-- ============================================================================
CREATE TABLE stock_counts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)     NOT NULL,
    company_id           BIGINT          NOT NULL,
    branch_id            BIGINT          NOT NULL,
    count_number         VARCHAR(30)     NOT NULL,
    status               VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    count_type           VARCHAR(12)     NOT NULL DEFAULT 'FULL',
    location_id          BIGINT          NOT NULL,
    count_date           DATE            NOT NULL,
    frozen_at            TIMESTAMPTZ,
    posted_at            TIMESTAMPTZ,
    cancelled_at         TIMESTAMPTZ,
    variance_gl_entry_uid VARCHAR(26),
    notes                VARCHAR(500),
    version              BIGINT          NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,
    CONSTRAINT uq_stock_count_uid            UNIQUE (uid),
    CONSTRAINT uq_stock_count_company_number UNIQUE (company_id, count_number),
    CONSTRAINT fk_stock_count_company        FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_stock_count_branch         FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_stock_count_location       FOREIGN KEY (location_id) REFERENCES stock_locations (id),
    CONSTRAINT chk_stock_count_status  CHECK (status IN ('DRAFT','COUNTING','POSTED','CANCELLED')),
    CONSTRAINT chk_stock_count_type    CHECK (count_type IN ('FULL','CYCLE'))
);

CREATE INDEX ix_stock_counts_company
    ON stock_counts (company_id, branch_id, status, count_date DESC);

CREATE INDEX ix_stock_counts_location
    ON stock_counts (location_id);

-- ============================================================================
-- (2) CREATE stock_count_lines (child rows)
-- ============================================================================
CREATE TABLE stock_count_lines (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)     NOT NULL,
    stock_count_id   BIGINT          NOT NULL,
    company_id       BIGINT          NOT NULL,
    branch_id        BIGINT          NOT NULL,
    line_no          SMALLINT        NOT NULL,
    product_id       BIGINT          NOT NULL,
    product_code     VARCHAR(50)     NOT NULL,
    product_name     VARCHAR(255)    NOT NULL,
    unit_id          BIGINT,
    unit_name        VARCHAR(50),
    system_qty       NUMERIC(19,6)   NOT NULL,
    counted_qty      NUMERIC(19,6),
    variance_qty     NUMERIC(19,6),
    unit_cost_amount NUMERIC(19,4),
    variance_value   NUMERIC(19,4),
    reason_code      VARCHAR(40),
    movement_uid     VARCHAR(26),
    currency         VARCHAR(10)     NOT NULL DEFAULT 'TZS',
    version          BIGINT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_stock_count_line_uid   UNIQUE (uid),
    CONSTRAINT uq_stock_count_line_no    UNIQUE (stock_count_id, line_no),
    CONSTRAINT fk_stock_count_line_count FOREIGN KEY (stock_count_id) REFERENCES stock_counts (id),
    CONSTRAINT fk_stock_count_line_product FOREIGN KEY (product_id)   REFERENCES products (id)
);

CREATE INDEX ix_stock_count_lines_count
    ON stock_count_lines (stock_count_id);
