-- V35 — Procurement depth: purchase_returns + purchase_return_lines;
--        ALTER goods_receipt_lines ADD returned_qty_in_base;
--        ALTER ap_debit_notes ADD origin column + chk_ap_debit_note_origin widen;
--        permission seed + ORG_ADMIN grant.
-- Additive only. V1–V34 are FROZEN/in-flight.
-- ADR-0027 D-7 / D-10 / D-12.
-- Order: (1) purchase_returns → (2) purchase_return_lines
--        → (3) ALTER goods_receipt_lines → (4) ALTER ap_debit_notes
--        → (5) indexes → (6) permission seed + ORG_ADMIN grant.

-- ============================================================================
-- (1) purchase_returns — purchase return / RMA header
-- ============================================================================
CREATE TABLE purchase_returns (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    return_number           VARCHAR(30)      NOT NULL,            -- PRET-####; assigned at create
    status                  VARCHAR(20)      NOT NULL DEFAULT 'DRAFT',
    goods_receipt_id        BIGINT           NOT NULL,
    goods_receipt_uid       VARCHAR(26)      NOT NULL,
    supplier_id             BIGINT           NOT NULL,
    supplier_code           VARCHAR(20)      NOT NULL,            -- snapshot
    supplier_name           VARCHAR(200)     NOT NULL,            -- snapshot
    reason                  VARCHAR(255)     NOT NULL,
    net_amount              NUMERIC(19,4)    NOT NULL DEFAULT 0,
    vat_amount              NUMERIC(19,4)    NOT NULL DEFAULT 0,
    gross_amount            NUMERIC(19,4)    NOT NULL DEFAULT 0,
    currency                VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    debit_note_uid          VARCHAR(26),                          -- set on confirm
    gl_entry_uid            VARCHAR(26),                          -- stock-out reversal journal (diagnostic)
    confirmed_at            TIMESTAMPTZ,
    confirmed_by            BIGINT,
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_purchase_return_uid            UNIQUE (uid),
    CONSTRAINT uq_purchase_return_company_number UNIQUE (company_id, return_number),
    CONSTRAINT fk_purchase_return_company        FOREIGN KEY (company_id)       REFERENCES companies (id),
    CONSTRAINT fk_purchase_return_branch         FOREIGN KEY (branch_id)        REFERENCES branches (id),
    CONSTRAINT fk_purchase_return_gr             FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts (id),
    CONSTRAINT fk_purchase_return_supplier       FOREIGN KEY (supplier_id)      REFERENCES suppliers (id),
    CONSTRAINT fk_purchase_return_confirmed_by   FOREIGN KEY (confirmed_by)     REFERENCES app_users (id),
    CONSTRAINT chk_purchase_return_status        CHECK (status IN ('DRAFT','CONFIRMED')),
    CONSTRAINT chk_purchase_return_amounts       CHECK (net_amount >= 0 AND vat_amount >= 0 AND gross_amount >= 0)
);

-- ============================================================================
-- (2) purchase_return_lines — child of purchase_returns
-- ============================================================================
CREATE TABLE purchase_return_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    purchase_return_id      BIGINT           NOT NULL,
    goods_receipt_line_id   BIGINT           NOT NULL,
    goods_receipt_line_uid  VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    line_no                 SMALLINT         NOT NULL,
    product_id              BIGINT           NOT NULL,
    product_code            VARCHAR(60)      NOT NULL,            -- snapshot
    product_name            VARCHAR(200)     NOT NULL,            -- snapshot
    unit_id                 BIGINT           NOT NULL,
    unit_name               VARCHAR(60)      NOT NULL,            -- snapshot
    returned_qty            NUMERIC(19,6)    NOT NULL,
    returned_qty_in_base    NUMERIC(19,6)    NOT NULL,
    unit_cost_amount        NUMERIC(19,4)    NOT NULL,            -- original receipt cost
    line_value_amount       NUMERIC(19,4)    NOT NULL,            -- original-cost value reversed
    currency                VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_purchase_return_line_uid     UNIQUE (uid),
    CONSTRAINT uq_purchase_return_line_no      UNIQUE (purchase_return_id, line_no),
    CONSTRAINT fk_purchase_return_line_return  FOREIGN KEY (purchase_return_id)    REFERENCES purchase_returns (id),
    CONSTRAINT fk_purchase_return_line_grl     FOREIGN KEY (goods_receipt_line_id) REFERENCES goods_receipt_lines (id),
    CONSTRAINT fk_purchase_return_line_product FOREIGN KEY (product_id)            REFERENCES products (id),
    CONSTRAINT fk_purchase_return_line_unit    FOREIGN KEY (unit_id)               REFERENCES units_of_measure (id),
    CONSTRAINT fk_purchase_return_line_company FOREIGN KEY (company_id)            REFERENCES companies (id),
    CONSTRAINT fk_purchase_return_line_branch  FOREIGN KEY (branch_id)             REFERENCES branches (id),
    CONSTRAINT chk_purchase_return_line_qty    CHECK (returned_qty > 0 AND returned_qty_in_base > 0),
    CONSTRAINT chk_purchase_return_line_cost   CHECK (unit_cost_amount >= 0 AND line_value_amount >= 0)
);

-- ============================================================================
-- (3) ALTER goods_receipt_lines — add returned_qty_in_base (ADR-0027 D-7)
-- ============================================================================
ALTER TABLE goods_receipt_lines
    ADD COLUMN returned_qty_in_base NUMERIC(19,6) NOT NULL DEFAULT 0;

ALTER TABLE goods_receipt_lines
    ADD CONSTRAINT chk_goods_receipt_line_returned
        CHECK (returned_qty_in_base >= 0 AND returned_qty_in_base <= qty_in_base);

-- ============================================================================
-- (4) ALTER ap_debit_notes — add origin column (ADR-0027 D-7; existing rows = STANDALONE)
-- ============================================================================
ALTER TABLE ap_debit_notes
    ADD COLUMN origin VARCHAR(20) NOT NULL DEFAULT 'STANDALONE';

ALTER TABLE ap_debit_notes
    ADD CONSTRAINT chk_ap_debit_note_origin
        CHECK (origin IN ('STANDALONE','PURCHASE_RETURN'));

-- ============================================================================
-- (5) Indexes (ADR-0027 D-11)
-- ============================================================================
CREATE INDEX ix_purchase_returns_company        ON purchase_returns (company_id);
CREATE INDEX ix_purchase_returns_company_status ON purchase_returns (company_id, status);
CREATE INDEX ix_purchase_returns_receipt        ON purchase_returns (goods_receipt_id);
CREATE INDEX ix_purchase_return_lines_return    ON purchase_return_lines (purchase_return_id);
CREATE INDEX ix_purchase_return_lines_gr_line   ON purchase_return_lines (goods_receipt_line_id);

-- ============================================================================
-- (6) Permission seed + ORG_ADMIN grant (ADR-0027 D-10)
-- ============================================================================
INSERT INTO permissions (code, module, description) VALUES
    ('PURCHASE.RETURN.VIEW',   'purchases', 'View and list purchase returns'),
    ('PURCHASE.RETURN.CREATE', 'purchases', 'Create and confirm a purchase return')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM   roles r
CROSS JOIN permissions p
WHERE  r.code = 'ORG_ADMIN'
  AND  p.code IN ('PURCHASE.RETURN.VIEW', 'PURCHASE.RETURN.CREATE')
ON CONFLICT DO NOTHING;
