-- V41 — Inventory Depth (ADR-0028, D-7/D-11/D-13):
-- ALTER products: ADD lot_tracked + serial_tracked flags + tracking-exclusivity CHECK.
-- CREATE stock_batches (lot/expiry, FEFO, per-location lot on-hand).
-- CREATE stock_serials (per-unit identity, IN_STOCK/ISSUED/RETURNED).
-- Permission seed (11 new codes) + ORG_ADMIN grant.
-- Additive only. V1–V40 are FROZEN.

-- ============================================================================
-- (1) ALTER products — add tracking flags (D-7)
-- ============================================================================
ALTER TABLE products
    ADD COLUMN lot_tracked    BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN serial_tracked BOOLEAN NOT NULL DEFAULT false;

-- Mutual exclusivity: a product is lot-tracked OR serial-tracked OR neither (D-7, OQ-INVD-05)
ALTER TABLE products
    ADD CONSTRAINT chk_product_tracking_exclusive
        CHECK (NOT (lot_tracked AND serial_tracked));

-- ============================================================================
-- (2) CREATE stock_batches (lot/expiry/FEFO, per (location, product, lot))
-- ============================================================================
CREATE TABLE stock_batches (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)     NOT NULL,
    company_id       BIGINT          NOT NULL,
    branch_id        BIGINT          NOT NULL,
    location_id      BIGINT          NOT NULL,
    product_id       BIGINT          NOT NULL,
    lot_number       VARCHAR(60)     NOT NULL,
    manufacture_date DATE,
    expiry_date      DATE,
    qty_on_hand      NUMERIC(19,6)   NOT NULL DEFAULT 0,
    version          BIGINT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_stock_batch_uid    UNIQUE (uid),
    -- Per-location on-hand row per (company, branch, location, product, lot)
    CONSTRAINT uq_stock_batch_scope  UNIQUE (company_id, branch_id, location_id, product_id, lot_number),
    CONSTRAINT fk_stock_batch_company   FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_stock_batch_branch    FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_stock_batch_location  FOREIGN KEY (location_id) REFERENCES stock_locations (id),
    CONSTRAINT fk_stock_batch_product   FOREIGN KEY (product_id)  REFERENCES products (id)
);

-- FEFO order query index: expiry_date ASC NULLS LAST per (location, product)
CREATE INDEX ix_stock_batches_fefo
    ON stock_batches (company_id, location_id, product_id, expiry_date NULLS LAST, id);

-- Expiry report: lots by expiry date per company
CREATE INDEX ix_stock_batches_expiry
    ON stock_batches (company_id, expiry_date)
    WHERE expiry_date IS NOT NULL AND qty_on_hand > 0;

-- ============================================================================
-- (3) CREATE stock_serials (per-unit identity, SerialStatus)
-- ============================================================================
CREATE TABLE stock_serials (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                   VARCHAR(26)     NOT NULL,
    company_id            BIGINT          NOT NULL,
    branch_id             BIGINT          NOT NULL,
    location_id           BIGINT,                       -- NULL when ISSUED (out of stock)
    product_id            BIGINT          NOT NULL,
    serial_number         VARCHAR(80)     NOT NULL,
    serial_status         VARCHAR(12)     NOT NULL DEFAULT 'IN_STOCK',
    received_document_uid VARCHAR(26),
    issued_document_uid   VARCHAR(26),
    version               BIGINT          NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ,
    updated_by            BIGINT,
    CONSTRAINT uq_stock_serial_uid            UNIQUE (uid),
    -- Serial numbers unique per product company-wide (BR-INVD-11)
    CONSTRAINT uq_stock_serial_product_serial UNIQUE (company_id, product_id, serial_number),
    CONSTRAINT fk_stock_serial_company   FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_stock_serial_branch    FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_stock_serial_location  FOREIGN KEY (location_id) REFERENCES stock_locations (id),
    CONSTRAINT fk_stock_serial_product   FOREIGN KEY (product_id)  REFERENCES products (id),
    CONSTRAINT chk_stock_serial_status   CHECK (serial_status IN ('IN_STOCK','ISSUED','RETURNED'))
);

-- Fast lookup: IN_STOCK count per (location, product) — integrity invariant check
CREATE INDEX ix_stock_serials_location_product
    ON stock_serials (company_id, location_id, product_id, serial_status)
    WHERE serial_status = 'IN_STOCK';

-- Serial lookup by number
CREATE INDEX ix_stock_serials_number
    ON stock_serials (company_id, product_id, serial_number);
