-- V3 — Products module: products, code_sequence, price_lists, and child/link tables
-- Additive only. V1 (IAM) and V2 (Parties) are FROZEN — this file does not edit them.
-- Order per ADR-0007 D-14:
--   (1) products master → (2) code_sequence → (3) price_lists master
--   → (4) child/link tables → (5) indexes → (6) permission seed + ORG_ADMIN grant.

-- ---------------------------------------------------------------------------
-- (1) products
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)         NOT NULL,
    company_id      BIGINT              NOT NULL,
    code            VARCHAR(20)         NOT NULL,
    name            VARCHAR(200)        NOT NULL,
    description     VARCHAR(500),
    type            VARCHAR(20)         NOT NULL,
    sellable        BOOLEAN             NOT NULL DEFAULT true,
    stockable       BOOLEAN             NOT NULL DEFAULT true,
    base_unit       VARCHAR(40)         NOT NULL,
    cost_amount     NUMERIC(19,4),
    cost_currency   VARCHAR(3),
    status          VARCHAR(32)         NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT              NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    CONSTRAINT uq_product_uid               UNIQUE (uid),
    CONSTRAINT uq_product_company_code      UNIQUE (company_id, code),
    CONSTRAINT fk_product_company           FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_product_type             CHECK (type IN ('GOODS','SERVICE')),
    CONSTRAINT chk_product_service_stockable
        CHECK (NOT (type = 'SERVICE' AND stockable = true)),
    CONSTRAINT chk_product_cost_pair
        CHECK (
            (cost_amount IS NULL AND cost_currency IS NULL) OR
            (cost_amount IS NOT NULL AND cost_currency IS NOT NULL)
        ),
    -- D-10: product planning + sourcing (ADR-0040)
    reorder_level           NUMERIC(19,6),
    reorder_qty             NUMERIC(19,6),
    min_stock               NUMERIC(19,6),
    max_stock               NUMERIC(19,6),
    safety_stock            NUMERIC(19,6),
    lead_time_days          INTEGER,
    purchasable             BOOLEAN             NOT NULL DEFAULT true,
    preferred_supplier_id   BIGINT,
    CONSTRAINT chk_product_reorder_level    CHECK (reorder_level   IS NULL OR reorder_level   >= 0),
    CONSTRAINT chk_product_reorder_qty      CHECK (reorder_qty     IS NULL OR reorder_qty     >= 0),
    CONSTRAINT chk_product_min_stock        CHECK (min_stock       IS NULL OR min_stock       >= 0),
    CONSTRAINT chk_product_max_stock        CHECK (max_stock       IS NULL OR max_stock       >= 0),
    CONSTRAINT chk_product_safety_stock     CHECK (safety_stock    IS NULL OR safety_stock    >= 0),
    CONSTRAINT chk_product_lead_time        CHECK (lead_time_days  IS NULL OR lead_time_days  >= 0),
    CONSTRAINT chk_product_stock_range
        CHECK (min_stock IS NULL OR max_stock IS NULL OR max_stock >= min_stock),
    CONSTRAINT fk_product_preferred_supplier
        FOREIGN KEY (preferred_supplier_id) REFERENCES suppliers (id)
);

-- ---------------------------------------------------------------------------
-- (2) code_sequence — generic locked counter per (company, entity_kind) (ADR-0007 D-6)
-- ---------------------------------------------------------------------------
CREATE TABLE code_sequence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT          NOT NULL,
    entity_kind VARCHAR(30)     NOT NULL,
    next_value  BIGINT          NOT NULL DEFAULT 1,
    version     BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_code_sequence            UNIQUE (company_id, entity_kind),
    CONSTRAINT fk_code_sequence_company    FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- ---------------------------------------------------------------------------
-- (3) price_lists
-- ---------------------------------------------------------------------------
CREATE TABLE price_lists (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)     NOT NULL,
    company_id  BIGINT          NOT NULL,
    code        VARCHAR(20)     NOT NULL,
    name        VARCHAR(120)    NOT NULL,
    status      VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version     BIGINT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_price_list_uid            UNIQUE (uid),
    CONSTRAINT uq_price_list_company_code   UNIQUE (company_id, code),
    CONSTRAINT fk_price_list_company        FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- ---------------------------------------------------------------------------
-- (4) Child / link tables
-- ---------------------------------------------------------------------------

-- product_bulk_packs
CREATE TABLE product_bulk_packs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)         NOT NULL,
    product_id      BIGINT              NOT NULL,
    name            VARCHAR(40)         NOT NULL,
    factor_to_base  NUMERIC(19,6)       NOT NULL,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    CONSTRAINT uq_product_bulk_pack_uid     UNIQUE (uid),
    CONSTRAINT uq_product_bulk_pack_name    UNIQUE (product_id, name),
    CONSTRAINT fk_product_bulk_pack_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_product_bulk_pack_factor CHECK (factor_to_base > 0)
);

-- product_barcodes (company_id denormalised — BR-PROD-07, NFR-PROD-01)
CREATE TABLE product_barcodes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)     NOT NULL,
    product_id  BIGINT          NOT NULL,
    company_id  BIGINT          NOT NULL,
    barcode     VARCHAR(64)     NOT NULL,
    is_primary  BOOLEAN         NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by  BIGINT,
    CONSTRAINT uq_product_barcode_uid           UNIQUE (uid),
    CONSTRAINT uq_product_barcode_company_value UNIQUE (company_id, barcode),
    CONSTRAINT fk_product_barcode_product       FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_barcode_company       FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- product_prices (company_id denormalised; bare amount/currency — no @AttributeOverride)
CREATE TABLE product_prices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT          NOT NULL,
    price_list_id   BIGINT          NOT NULL,
    company_id      BIGINT          NOT NULL,
    amount          NUMERIC(19,4)   NOT NULL,
    currency        VARCHAR(3)      NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    CONSTRAINT uq_product_price             UNIQUE (product_id, price_list_id),
    CONSTRAINT fk_product_price_product     FOREIGN KEY (product_id)    REFERENCES products (id),
    CONSTRAINT fk_product_price_pricelist   FOREIGN KEY (price_list_id) REFERENCES price_lists (id),
    CONSTRAINT fk_product_price_company     FOREIGN KEY (company_id)    REFERENCES companies (id)
);

-- product_components (self-referential, single-level BOM)
CREATE TABLE product_components (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    composed_product_id BIGINT          NOT NULL,
    component_product_id BIGINT         NOT NULL,
    quantity            NUMERIC(19,6)   NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    CONSTRAINT uq_product_component        UNIQUE (composed_product_id, component_product_id),
    CONSTRAINT fk_product_component_composed
        FOREIGN KEY (composed_product_id)  REFERENCES products (id),
    CONSTRAINT fk_product_component_component
        FOREIGN KEY (component_product_id) REFERENCES products (id),
    CONSTRAINT chk_product_component_not_self
        CHECK (composed_product_id <> component_product_id),
    CONSTRAINT chk_product_component_qty   CHECK (quantity > 0)
);

-- product_branch (singular junction, no uid/status/version per DATA-MODEL convention)
CREATE TABLE product_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    CONSTRAINT uq_product_branch_pair   UNIQUE (product_id, branch_id),
    CONSTRAINT fk_product_branch_product FOREIGN KEY (product_id)  REFERENCES products (id),
    CONSTRAINT fk_product_branch_br      FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_product_branch_by      FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- ---------------------------------------------------------------------------
-- (5) Indexes
-- ---------------------------------------------------------------------------

-- products: tenant + name expression, and the partial primary-barcode unique
CREATE INDEX ix_products_company
    ON products (company_id);
CREATE INDEX ix_products_company_name
    ON products (company_id, lower(name));

-- product_bulk_packs
CREATE INDEX ix_product_bulk_packs_product
    ON product_bulk_packs (product_id);

-- product_barcodes: one-primary partial unique + lookup + product list
CREATE UNIQUE INDEX uq_product_barcode_primary
    ON product_barcodes (product_id) WHERE is_primary;
CREATE INDEX ix_product_barcodes_product
    ON product_barcodes (product_id);

-- product_prices: product / list / company scoped reads
CREATE INDEX ix_product_prices_product
    ON product_prices (product_id);
CREATE INDEX ix_product_prices_list
    ON product_prices (price_list_id);
CREATE INDEX ix_product_prices_company
    ON product_prices (company_id);

-- product_components: recipe read + reverse impact
CREATE INDEX ix_product_components_composed
    ON product_components (composed_product_id);
CREATE INDEX ix_product_components_component
    ON product_components (component_product_id);

-- product_branch: both directions
CREATE INDEX ix_product_branch_product
    ON product_branch (product_id);
CREATE INDEX ix_product_branch_branch
    ON product_branch (branch_id);

-- price_lists: tenant read
CREATE INDEX ix_price_lists_company
    ON price_lists (company_id);
