-- V47 — Fixed Assets: asset_categories table (ADR-0030, D-2)
-- FKs to chart_of_accounts(id) reference the V46 seed.
-- version column present (UidEntity/@Version requirement).
-- Additive only. V1–V46 are FROZEN.

CREATE TABLE asset_categories (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)         NOT NULL,
    company_id              BIGINT              NOT NULL,
    code                    VARCHAR(30)         NOT NULL,
    name                    VARCHAR(160)        NOT NULL,
    default_method          VARCHAR(20)         NOT NULL,
    default_life_periods    INTEGER             NOT NULL,
    default_reducing_rate   NUMERIC(9,4),
    asset_account_id        BIGINT              NOT NULL,
    accum_dep_account_id    BIGINT              NOT NULL,
    dep_expense_account_id  BIGINT              NOT NULL,
    parent_category_id      BIGINT,             -- P3: self soft-FK for category hierarchy (flat in v1)
    status                  VARCHAR(32)         NOT NULL DEFAULT 'ACTIVE',
    version                 BIGINT              NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ         NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_asset_category_uid            UNIQUE (uid),
    CONSTRAINT uq_asset_category_company_code   UNIQUE (company_id, code),
    CONSTRAINT fk_asset_category_company        FOREIGN KEY (company_id)
                                                REFERENCES companies(id),
    CONSTRAINT fk_asset_category_asset_acct     FOREIGN KEY (asset_account_id)
                                                REFERENCES chart_of_accounts(id),
    CONSTRAINT fk_asset_category_accum_acct     FOREIGN KEY (accum_dep_account_id)
                                                REFERENCES chart_of_accounts(id),
    CONSTRAINT fk_asset_category_expense_acct   FOREIGN KEY (dep_expense_account_id)
                                                REFERENCES chart_of_accounts(id),
    CONSTRAINT chk_asset_category_method        CHECK (default_method IN ('STRAIGHT_LINE','REDUCING_BALANCE')),
    CONSTRAINT chk_asset_category_life          CHECK (default_life_periods > 0),
    CONSTRAINT chk_asset_category_rate          CHECK (
        default_reducing_rate IS NULL
        OR (default_reducing_rate > 0 AND default_reducing_rate <= 100)
    ),
    CONSTRAINT chk_asset_category_status        CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')),
    CONSTRAINT fk_asset_category_parent         FOREIGN KEY (parent_category_id)
                                                REFERENCES asset_categories(id)
);

CREATE INDEX ix_asset_categories_company ON asset_categories (company_id);
