-- V50 — Fixed Assets: asset_disposals + asset_revaluations + permission seed (ADR-0030, D-6/D-14)
-- version columns present on both tables (UidEntity/@Version requirement).
-- Permissions seeded + granted to ORG_ADMIN (V7/V12/V14/V17 pattern).
-- Additive only. V1–V49 are FROZEN.

-- ============================================================================
-- (1) asset_disposals — one disposal per asset (terminal event)
-- ============================================================================
CREATE TABLE asset_disposals (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT          NOT NULL,
    fixed_asset_id      BIGINT          NOT NULL,
    disposal_type       VARCHAR(20)     NOT NULL,
    disposal_date       DATE            NOT NULL,
    fiscal_period_id    BIGINT          NOT NULL,
    proceeds_amount     NUMERIC(19,4)   NOT NULL,
    nbv_at_disposal     NUMERIC(19,4)   NOT NULL,
    gain_loss_amount    NUMERIC(19,4)   NOT NULL,
    gl_entry_uid        VARCHAR(26),
    currency            VARCHAR(3)      NOT NULL,
    reason              VARCHAR(255),
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_asset_disposal_uid        UNIQUE (uid),
    CONSTRAINT uq_asset_disposal_asset      UNIQUE (fixed_asset_id),
    CONSTRAINT fk_asset_disposal_company    FOREIGN KEY (company_id)
                                            REFERENCES companies(id),
    CONSTRAINT fk_asset_disposal_branch     FOREIGN KEY (branch_id)
                                            REFERENCES branches(id),
    CONSTRAINT fk_asset_disposal_asset      FOREIGN KEY (fixed_asset_id)
                                            REFERENCES fixed_assets(id),
    CONSTRAINT fk_asset_disposal_period     FOREIGN KEY (fiscal_period_id)
                                            REFERENCES fiscal_periods(id),
    CONSTRAINT chk_asset_disposal_type      CHECK (disposal_type IN ('SALE','WRITE_OFF')),
    CONSTRAINT chk_asset_disposal_proceeds  CHECK (proceeds_amount >= 0)
);

CREATE INDEX ix_asset_disposals_company ON asset_disposals (company_id);

-- ============================================================================
-- (2) asset_revaluations — multiple revaluations per asset over its life
-- ============================================================================
CREATE TABLE asset_revaluations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT          NOT NULL,
    fixed_asset_id      BIGINT          NOT NULL,
    revaluation_date    DATE            NOT NULL,
    fiscal_period_id    BIGINT          NOT NULL,
    direction           VARCHAR(10)     NOT NULL,
    delta_amount        NUMERIC(19,4)   NOT NULL,
    carrying_before     NUMERIC(19,4)   NOT NULL,
    carrying_after      NUMERIC(19,4)   NOT NULL,
    gl_entry_uid        VARCHAR(26),
    currency            VARCHAR(3)      NOT NULL,
    reason              VARCHAR(255),
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_asset_revaluation_uid         UNIQUE (uid),
    CONSTRAINT fk_asset_revaluation_company     FOREIGN KEY (company_id)
                                                REFERENCES companies(id),
    CONSTRAINT fk_asset_revaluation_branch      FOREIGN KEY (branch_id)
                                                REFERENCES branches(id),
    CONSTRAINT fk_asset_revaluation_asset       FOREIGN KEY (fixed_asset_id)
                                                REFERENCES fixed_assets(id),
    CONSTRAINT fk_asset_revaluation_period      FOREIGN KEY (fiscal_period_id)
                                                REFERENCES fiscal_periods(id),
    CONSTRAINT chk_asset_revaluation_direction  CHECK (direction IN ('UP','DOWN')),
    CONSTRAINT chk_asset_revaluation_delta      CHECK (delta_amount > 0)
);

CREATE INDEX ix_asset_revaluations_company ON asset_revaluations (company_id);
CREATE INDEX ix_asset_revaluations_asset   ON asset_revaluations (fixed_asset_id);
