-- V48 — Fixed Assets: fixed_assets + depreciation_schedule_lines (ADR-0030, D-2/D-5)
-- version columns present on both tables (UidEntity/@Version requirement).
-- Additive only. V1–V47 are FROZEN.

-- ============================================================================
-- (1) fixed_assets — the asset register (master, per company/branch)
-- ============================================================================
CREATE TABLE fixed_assets (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)     NOT NULL,
    company_id                  BIGINT          NOT NULL,
    branch_id                   BIGINT          NOT NULL,
    asset_number                VARCHAR(30)     NOT NULL,
    category_id                 BIGINT          NOT NULL,
    name                        VARCHAR(200)    NOT NULL,
    status                      VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    acquisition_cost            NUMERIC(19,4)   NOT NULL,
    salvage_value               NUMERIC(19,4)   NOT NULL DEFAULT 0,
    depreciation_method         VARCHAR(20)     NOT NULL,
    life_periods                INTEGER         NOT NULL,
    reducing_rate               NUMERIC(9,4),
    acquisition_date            DATE            NOT NULL,
    depreciation_start_date     DATE            NOT NULL,
    carrying_cost               NUMERIC(19,4)   NOT NULL,
    accumulated_depreciation    NUMERIC(19,4)   NOT NULL DEFAULT 0,
    revaluation_reserve_balance NUMERIC(19,4)   NOT NULL DEFAULT 0,
    supplier_id                 BIGINT,
    source_bill_uid             VARCHAR(26),
    location                    VARCHAR(200),
    cost_centre_id              BIGINT,
    asset_tag                   VARCHAR(100),
    capitalised_gl_entry_uid    VARCHAR(26),
    disposed_at                 DATE,
    version                     BIGINT          NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,

    CONSTRAINT uq_fixed_asset_uid               UNIQUE (uid),
    CONSTRAINT uq_fixed_asset_company_number    UNIQUE (company_id, asset_number),
    CONSTRAINT fk_fixed_asset_company           FOREIGN KEY (company_id)
                                                REFERENCES companies(id),
    CONSTRAINT fk_fixed_asset_branch            FOREIGN KEY (branch_id)
                                                REFERENCES branches(id),
    CONSTRAINT fk_fixed_asset_category         FOREIGN KEY (category_id)
                                                REFERENCES asset_categories(id),
    CONSTRAINT chk_fixed_asset_status          CHECK (status IN ('DRAFT','IN_SERVICE','DISPOSED','WRITTEN_OFF')),
    CONSTRAINT chk_fixed_asset_cost            CHECK (acquisition_cost > 0),
    CONSTRAINT chk_fixed_asset_salvage         CHECK (salvage_value >= 0 AND salvage_value < acquisition_cost),
    CONSTRAINT chk_fixed_asset_method          CHECK (depreciation_method IN ('STRAIGHT_LINE','REDUCING_BALANCE')),
    CONSTRAINT chk_fixed_asset_life            CHECK (life_periods > 0),
    CONSTRAINT chk_fixed_asset_rate            CHECK (
        (depreciation_method = 'STRAIGHT_LINE' AND reducing_rate IS NULL)
        OR (depreciation_method = 'REDUCING_BALANCE' AND reducing_rate IS NOT NULL
            AND reducing_rate > 0 AND reducing_rate <= 100)
    ),
    CONSTRAINT chk_fixed_asset_start           CHECK (depreciation_start_date >= acquisition_date),
    CONSTRAINT chk_fixed_asset_accum           CHECK (accumulated_depreciation >= 0)
);

CREATE INDEX ix_fixed_assets_company          ON fixed_assets (company_id);
CREATE INDEX ix_fixed_assets_company_status   ON fixed_assets (company_id, status);
CREATE INDEX ix_fixed_assets_company_category ON fixed_assets (company_id, category_id);

-- ============================================================================
-- (2) depreciation_schedule_lines — generated schedule for each asset (D-5)
-- ============================================================================
CREATE TABLE depreciation_schedule_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    fixed_asset_id      BIGINT          NOT NULL,
    company_id          BIGINT          NOT NULL,
    period_seq          INTEGER         NOT NULL,
    schedule_version    INTEGER         NOT NULL DEFAULT 1,
    period_date         DATE            NOT NULL,
    planned_charge      NUMERIC(19,4)   NOT NULL,
    accumulated_after   NUMERIC(19,4)   NOT NULL,
    nbv_after           NUMERIC(19,4)   NOT NULL,
    posted              BOOLEAN         NOT NULL DEFAULT false,
    depreciation_run_id BIGINT,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_depreciation_schedule_line_uid    UNIQUE (uid),
    CONSTRAINT uq_depreciation_schedule_line_seq    UNIQUE (fixed_asset_id, period_seq, schedule_version),
    CONSTRAINT fk_depreciation_schedule_line_asset  FOREIGN KEY (fixed_asset_id)
                                                    REFERENCES fixed_assets(id),
    CONSTRAINT chk_depreciation_schedule_line_charge CHECK (planned_charge >= 0)
);

CREATE INDEX ix_depreciation_schedule_lines_asset
    ON depreciation_schedule_lines (fixed_asset_id, schedule_version, posted);
