-- V49 — Fixed Assets: depreciation_runs + depreciation_run_lines (ADR-0030, D-4)
-- The idempotency anchor: uq_depreciation_run_company_period on (company_id, fiscal_period_id).
-- version columns present on both tables (UidEntity/@Version requirement).
-- Additive only. V1–V48 are FROZEN.

-- ============================================================================
-- (1) depreciation_runs — run header (the idempotency anchor)
-- ============================================================================
CREATE TABLE depreciation_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    run_number          VARCHAR(30)     NOT NULL,
    fiscal_period_id    BIGINT          NOT NULL,
    posting_date        DATE            NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'POSTED',
    total_charge_amount NUMERIC(19,4)   NOT NULL,
    asset_count         INTEGER         NOT NULL,
    gl_entry_uid        VARCHAR(26)     NOT NULL,
    currency            VARCHAR(3)      NOT NULL,
    executed_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_depreciation_run_uid              UNIQUE (uid),
    CONSTRAINT uq_depreciation_run_company_number   UNIQUE (company_id, run_number),
    CONSTRAINT uq_depreciation_run_company_period   UNIQUE (company_id, fiscal_period_id),
    CONSTRAINT fk_depreciation_run_company          FOREIGN KEY (company_id)
                                                    REFERENCES companies(id),
    CONSTRAINT fk_depreciation_run_period           FOREIGN KEY (fiscal_period_id)
                                                    REFERENCES fiscal_periods(id),
    CONSTRAINT chk_depreciation_run_status          CHECK (status IN ('POSTED'))
);

CREATE INDEX ix_depreciation_runs_company ON depreciation_runs (company_id);

-- ============================================================================
-- (2) depreciation_run_lines — per-asset charge in each run
-- Note: FK to depreciation_schedule_lines added after FK to depreciation_runs.
-- ============================================================================
CREATE TABLE depreciation_run_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)     NOT NULL,
    depreciation_run_id     BIGINT          NOT NULL,
    company_id              BIGINT          NOT NULL,
    fixed_asset_id          BIGINT          NOT NULL,
    schedule_line_id        BIGINT          NOT NULL,
    charge_amount           NUMERIC(19,4)   NOT NULL,
    accum_dep_after         NUMERIC(19,4)   NOT NULL,
    nbv_after               NUMERIC(19,4)   NOT NULL,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_depreciation_run_line_uid     UNIQUE (uid),
    CONSTRAINT uq_depreciation_run_line_asset   UNIQUE (depreciation_run_id, fixed_asset_id),
    CONSTRAINT fk_depreciation_run_line_run     FOREIGN KEY (depreciation_run_id)
                                                REFERENCES depreciation_runs(id),
    CONSTRAINT fk_depreciation_run_line_asset   FOREIGN KEY (fixed_asset_id)
                                                REFERENCES fixed_assets(id),
    CONSTRAINT fk_depreciation_run_line_schedule FOREIGN KEY (schedule_line_id)
                                                REFERENCES depreciation_schedule_lines(id),
    CONSTRAINT chk_depreciation_run_line_charge CHECK (charge_amount >= 0)
);

-- Also add the back-FK from depreciation_schedule_lines to depreciation_runs
-- (defined here after depreciation_runs exists — the FK cannot be added in V48)
ALTER TABLE depreciation_schedule_lines
    ADD CONSTRAINT fk_depreciation_schedule_line_run
        FOREIGN KEY (depreciation_run_id) REFERENCES depreciation_runs(id);

CREATE INDEX ix_depreciation_run_lines_run ON depreciation_run_lines (depreciation_run_id);
