-- V4 — Units of Measure master + products/product_bulk_packs hard cutover.
-- V1/V2/V3 are FROZEN. This migration is additive and extends V3 schema.
-- Order: (1) create units_of_measure → (2) seed defaults for existing companies
--       → (3) products hard cutover → (4) product_bulk_packs hard cutover
--       → (5) permission seed + ORG_ADMIN grant.
--
-- ASSUMPTION: Target DBs (dev/verify) have zero product rows and zero product_bulk_pack rows.
-- The DB is effectively empty of transactional data (fresh bootstrap only). Therefore the
-- hard-cutover steps add the NOT NULL FK columns without row backfill. If any product rows
-- existed, the migration would fail at the NOT NULL constraint — reset the DB before running.
-- This is acceptable because the branch is unmerged and the owner has confirmed the assumption.

-- ---------------------------------------------------------------------------
-- (1) units_of_measure master table
-- ---------------------------------------------------------------------------
CREATE TABLE units_of_measure (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)     NOT NULL,
    company_id  BIGINT          NOT NULL,
    code        VARCHAR(20)     NOT NULL,
    name        VARCHAR(60)     NOT NULL,
    symbol      VARCHAR(20),                              -- P3: display symbol (e.g. "kg", "L", "pcs")
    dimension_type VARCHAR(20)  NOT NULL DEFAULT 'COUNT', -- P2 D5: UoM dimension family (COUNT/WEIGHT/VOLUME/LENGTH/TIME)
    decimal_places SMALLINT     NOT NULL DEFAULT 0,        -- P2 D5: display/rounding scale for quantities
    is_fractional  BOOLEAN      NOT NULL DEFAULT true,     -- P2 D5: whether fractional quantities are allowed
    status      VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version     BIGINT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_unit_of_measure_uid           UNIQUE (uid),
    CONSTRAINT uq_unit_of_measure_company_code  UNIQUE (company_id, code),
    CONSTRAINT fk_unit_of_measure_company       FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_unit_of_measure_dimension    CHECK (dimension_type IN ('COUNT','WEIGHT','VOLUME','LENGTH','TIME')),
    CONSTRAINT chk_unit_of_measure_decimals     CHECK (decimal_places >= 0 AND decimal_places <= 6)
);

CREATE INDEX ix_units_of_measure_company
    ON units_of_measure (company_id);

-- ---------------------------------------------------------------------------
-- (2) Seed default units for every existing company.
-- ULIDs cannot be generated portably in pure SQL, so we use a deterministic
-- 26-char string: 'SEED' + zero-padded company_id (10 chars) + code padded to
-- 12 chars, totalling 26. This is unique per (company, code) and is replaced
-- by a real ULID the first time the unit is touched by the application code.
-- New companies created after migration get their units seeded in Java by
-- UnitOfMeasureSeeder (called from BootstrapRunner and CompanyService.create).
-- ---------------------------------------------------------------------------
INSERT INTO units_of_measure (uid, company_id, code, name, status, version, created_at)
SELECT
    'SEED' || lpad(c.id::text, 10, '0') || rpad(u.code, 12, '_') AS uid,
    c.id,
    u.code,
    u.name,
    'ACTIVE',
    0,
    now()
FROM companies c
CROSS JOIN (VALUES
    ('PCS',    'Pieces'),
    ('BOX',    'Box'),
    ('CARTON', 'Carton'),
    ('CRATE',  'Crate'),
    ('PACK',   'Pack'),
    ('KG',     'Kilogram'),
    ('GRAM',   'Gram'),
    ('LITRE',  'Litre'),
    ('ML',     'Millilitre'),
    ('DOZEN',  'Dozen'),
    ('PAIR',   'Pair'),
    ('SET',    'Set'),
    ('ROLL',   'Roll'),
    ('BAG',    'Bag'),
    ('BOTTLE', 'Bottle')
) AS u(code, name);

-- ---------------------------------------------------------------------------
-- (3) products hard cutover: drop base_unit (text) → base_unit_id (FK).
-- ASSUMPTION: no product rows exist (see header note).
-- ---------------------------------------------------------------------------

-- 3a. Add nullable FK column first, then tighten to NOT NULL.
ALTER TABLE products ADD COLUMN base_unit_id BIGINT;

-- 3b. No backfill needed (assumption: zero product rows).

-- 3c. Set NOT NULL.
ALTER TABLE products ALTER COLUMN base_unit_id SET NOT NULL;

-- 3d. Add FK constraint.
ALTER TABLE products ADD CONSTRAINT fk_product_base_unit
    FOREIGN KEY (base_unit_id) REFERENCES units_of_measure (id);

-- 3e. Drop the old text column.
ALTER TABLE products DROP COLUMN base_unit;

CREATE INDEX ix_products_base_unit
    ON products (base_unit_id);

-- ---------------------------------------------------------------------------
-- (4) product_bulk_packs hard cutover: drop name (text) → unit_id (FK) + swap unique.
-- ASSUMPTION: no product_bulk_pack rows exist (see header note).
-- ---------------------------------------------------------------------------

-- 4a. Add nullable FK column.
ALTER TABLE product_bulk_packs ADD COLUMN unit_id BIGINT;

-- 4b. No backfill needed.

-- 4c. Set NOT NULL.
ALTER TABLE product_bulk_packs ALTER COLUMN unit_id SET NOT NULL;

-- 4d. Add FK constraint.
ALTER TABLE product_bulk_packs ADD CONSTRAINT fk_product_bulk_pack_unit
    FOREIGN KEY (unit_id) REFERENCES units_of_measure (id);

-- 4e. Drop old name column and its unique constraint.
ALTER TABLE product_bulk_packs DROP CONSTRAINT uq_product_bulk_pack_name;
ALTER TABLE product_bulk_packs DROP COLUMN name;

-- 4f. Add new unique constraint (product_id, unit_id) — one unit per product per bulk pack.
ALTER TABLE product_bulk_packs ADD CONSTRAINT uq_product_bulk_pack_unit
    UNIQUE (product_id, unit_id);

CREATE INDEX ix_product_bulk_packs_unit
    ON product_bulk_packs (unit_id);
