-- V64 — Projects / Job Costing module (ADR-0033):
-- CREATE projects, project_tasks, project_timesheets (ADR-0033 D-2);
-- ALTER journal_lines — add project_id, project_task_id, project_cost_type (ADR-0033 D-3/D-6);
-- Indexes for partial roll-up working set (NFR-PROJ-02).
-- Additive only. V1–V63 are FROZEN.
-- Order: projects → project_tasks → project_timesheets →
--        journal_lines ALTER → indexes.

-- ============================================================================
-- (1) projects — master (ADR-0033 D-2)
-- ============================================================================
CREATE TABLE projects (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT          NOT NULL,
    project_number      VARCHAR(30)     NOT NULL,
    name                VARCHAR(160)    NOT NULL,
    customer_id         BIGINT,
    manager_user_id     BIGINT,
    project_status      VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    planned_start_date  DATE,
    planned_end_date    DATE,
    budget_amount       NUMERIC(19,4),
    currency            VARCHAR(3)      NOT NULL DEFAULT 'TZS',
    notes               VARCHAR(500),
    status              VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    activated_at        TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    cancelled_at        TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_project_uid            UNIQUE (uid),
    CONSTRAINT uq_project_company_number UNIQUE (company_id, project_number),
    CONSTRAINT fk_project_company        FOREIGN KEY (company_id)      REFERENCES companies (id),
    CONSTRAINT fk_project_branch         FOREIGN KEY (branch_id)       REFERENCES branches (id),
    CONSTRAINT fk_project_customer       FOREIGN KEY (customer_id)     REFERENCES customers (id),
    CONSTRAINT fk_project_manager        FOREIGN KEY (manager_user_id) REFERENCES app_users (id),
    CONSTRAINT chk_project_status        CHECK (project_status IN (
        'DRAFT','ACTIVE','ON_HOLD','COMPLETED','CANCELLED')),
    CONSTRAINT chk_project_master_status CHECK (status IN (
        'ACTIVE','INACTIVE','ARCHIVED')),
    CONSTRAINT chk_project_dates         CHECK (
        planned_end_date IS NULL OR planned_start_date IS NULL
        OR planned_end_date >= planned_start_date)
);

-- ============================================================================
-- (2) project_tasks — child of project; one level in v1 (ADR-0033 D-2)
-- ============================================================================
CREATE TABLE project_tasks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)     NOT NULL,
    project_id      BIGINT          NOT NULL,
    company_id      BIGINT          NOT NULL,
    branch_id       BIGINT          NOT NULL,
    task_code       VARCHAR(30)     NOT NULL,
    name            VARCHAR(160)    NOT NULL,
    parent_id       BIGINT,
    planned_hours   NUMERIC(9,2),
    is_billable     BOOLEAN         NOT NULL DEFAULT true,
    status          VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_project_task_uid        UNIQUE (uid),
    CONSTRAINT uq_project_task_code       UNIQUE (project_id, task_code),
    CONSTRAINT fk_project_task_project    FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_project_task_company    FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_project_task_parent     FOREIGN KEY (parent_id)  REFERENCES project_tasks (id),
    CONSTRAINT chk_project_task_status    CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'))
);

-- ============================================================================
-- (3) project_timesheets — informational labour estimate (ADR-0033 D-2; posts no GL in v1)
-- ============================================================================
CREATE TABLE project_timesheets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    project_id          BIGINT          NOT NULL,
    project_task_id     BIGINT,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT          NOT NULL,
    user_id             BIGINT          NOT NULL,
    work_date           DATE            NOT NULL,
    hours               NUMERIC(9,2)    NOT NULL,
    is_billable         BOOLEAN         NOT NULL DEFAULT true,
    planned_rate_amount NUMERIC(19,4),
    notes               VARCHAR(255),
    status              VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_project_timesheet_uid      UNIQUE (uid),
    CONSTRAINT fk_project_timesheet_project  FOREIGN KEY (project_id)      REFERENCES projects (id),
    CONSTRAINT fk_project_timesheet_task     FOREIGN KEY (project_task_id) REFERENCES project_tasks (id),
    CONSTRAINT fk_project_timesheet_company  FOREIGN KEY (company_id)      REFERENCES companies (id),
    CONSTRAINT fk_project_timesheet_user     FOREIGN KEY (user_id)         REFERENCES app_users (id),
    CONSTRAINT chk_project_timesheet_hours   CHECK (hours > 0),
    CONSTRAINT chk_project_timesheet_status  CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'))
);

-- ============================================================================
-- (4) ALTER journal_lines — add project_id, project_task_id, project_cost_type (ADR-0033 D-3/D-6)
-- The authoritative project tag — the P&L roll-up reads these (BR-PROJ-03).
-- All nullable: untagged postings are byte-identical to today (NFR-PROJ-04).
-- ============================================================================
ALTER TABLE journal_lines
    ADD COLUMN project_id        BIGINT,
    ADD COLUMN project_task_id   BIGINT,
    ADD COLUMN project_cost_type VARCHAR(20);

ALTER TABLE journal_lines
    ADD CONSTRAINT fk_journal_line_project      FOREIGN KEY (project_id)      REFERENCES projects (id),
    ADD CONSTRAINT fk_journal_line_project_task FOREIGN KEY (project_task_id) REFERENCES project_tasks (id),
    ADD CONSTRAINT chk_journal_line_project_cost_type CHECK (
        project_cost_type IS NULL OR project_cost_type IN (
            'MATERIAL','SUBCONTRACT','LABOUR','OVERHEAD','OTHER'));

-- ============================================================================
-- (5) Indexes (NFR-PROJ-02)
-- ============================================================================

-- projects
CREATE INDEX ix_projects_company
    ON projects (company_id);
CREATE INDEX ix_projects_company_status
    ON projects (company_id, project_status);

-- project_tasks
CREATE INDEX ix_project_tasks_project
    ON project_tasks (project_id);

-- project_timesheets
CREATE INDEX ix_project_timesheets_project
    ON project_timesheets (project_id);
CREATE INDEX ix_project_timesheets_project_task
    ON project_timesheets (project_task_id)
    WHERE project_task_id IS NOT NULL;

-- journal_lines — partial index for the roll-up working set (NFR-PROJ-02)
CREATE INDEX ix_journal_lines_company_project
    ON journal_lines (company_id, project_id)
    WHERE project_id IS NOT NULL;
