-- V74 — Manufacturing / Production module (ADR-0035):
-- (1) CREATE work_orders, work_order_components, work_order_operations
-- (2) Indexes per D-2/D-3
-- (3) chk_stock_movement_type widen (FULL union + 4 new PRODUCTION_* types)
-- (4) chk_gl_config_key widen (FULL union + 5 new manufacturing keys)
-- (5) chk_journal_batch_source_type + chk_journal_entry_source_type widen (+ 4 new tokens)
-- (6) Permission seed + ORG_ADMIN grant
-- Additive only. V1–V19 FROZEN; V20–V73 are in-flight range — never edited.
-- EVERY table that is a UidEntity carries: version BIGINT NOT NULL DEFAULT 0

-- ============================================================================
-- (1a) work_orders — header (D-2)
-- ============================================================================
CREATE TABLE work_orders (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)      NOT NULL,
    wo_number                   VARCHAR(30)      NOT NULL,
    company_id                  BIGINT           NOT NULL,
    branch_id                   BIGINT           NOT NULL,
    finished_product_id         BIGINT           NOT NULL,
    finished_product_code       VARCHAR(20)      NOT NULL,
    finished_product_name       VARCHAR(200)     NOT NULL,
    bom_id                      BIGINT,
    bom_uid                     VARCHAR(26),
    planned_qty                 NUMERIC(19,6)    NOT NULL,
    good_qty                    NUMERIC(19,6)    NOT NULL DEFAULT 0,
    scrap_qty                   NUMERIC(19,6)    NOT NULL DEFAULT 0,
    status                      VARCHAR(20)      NOT NULL DEFAULT 'PLANNED',
    wip_debit_total             NUMERIC(19,4)    NOT NULL DEFAULT 0,
    wip_credit_total            NUMERIC(19,4)    NOT NULL DEFAULT 0,
    labour_applied_total        NUMERIC(19,4)    NOT NULL DEFAULT 0,
    overhead_applied_total      NUMERIC(19,4)    NOT NULL DEFAULT 0,
    computed_unit_cost          NUMERIC(19,4),
    variance_amount             NUMERIC(19,4)    NOT NULL DEFAULT 0,
    incomplete_cost             BOOLEAN          NOT NULL DEFAULT false,
    cost_centre_value_id        BIGINT,
    planned_date                DATE,
    released_at                 TIMESTAMPTZ,
    completed_at                TIMESTAMPTZ,
    closed_at                   TIMESTAMPTZ,
    cancelled_at                TIMESTAMPTZ,
    notes                       VARCHAR(500),
    version                     BIGINT           NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,
    CONSTRAINT uq_work_order_uid                UNIQUE (uid),
    CONSTRAINT uq_work_order_company_number     UNIQUE (company_id, wo_number),
    CONSTRAINT fk_work_order_company            FOREIGN KEY (company_id)           REFERENCES companies (id),
    CONSTRAINT fk_work_order_branch             FOREIGN KEY (branch_id)            REFERENCES branches (id),
    CONSTRAINT fk_work_order_product            FOREIGN KEY (finished_product_id)  REFERENCES products (id),
    CONSTRAINT fk_work_order_bom                FOREIGN KEY (bom_id)               REFERENCES boms (id),
    CONSTRAINT fk_work_order_cost_centre        FOREIGN KEY (cost_centre_value_id) REFERENCES dimension_values (id),
    CONSTRAINT chk_work_order_planned_qty       CHECK (planned_qty > 0),
    CONSTRAINT chk_work_order_good_qty          CHECK (good_qty >= 0),
    CONSTRAINT chk_work_order_scrap_qty         CHECK (scrap_qty >= 0),
    CONSTRAINT chk_work_order_status            CHECK (status IN (
        'PLANNED','RELEASED','IN_PROGRESS','COMPLETED','CLOSED','CANCELLED'
    ))
);

-- ============================================================================
-- (1b) work_order_components — planned + actual per-leaf consumption (D-3)
-- ============================================================================
CREATE TABLE work_order_components (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)      NOT NULL,
    work_order_id               BIGINT           NOT NULL,
    company_id                  BIGINT           NOT NULL,
    line_no                     SMALLINT         NOT NULL,
    component_product_id        BIGINT           NOT NULL,
    component_product_code      VARCHAR(20)      NOT NULL,
    component_product_name      VARCHAR(200)     NOT NULL,
    planned_qty                 NUMERIC(19,6)    NOT NULL DEFAULT 0,
    issued_qty                  NUMERIC(19,6)    NOT NULL DEFAULT 0,
    issued_value                NUMERIC(19,4)    NOT NULL DEFAULT 0,
    unit_cost_at_issue          NUMERIC(19,4),
    cost_skipped                BOOLEAN          NOT NULL DEFAULT false,
    status                      VARCHAR(12)      NOT NULL DEFAULT 'PLANNED',
    version                     BIGINT           NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,
    CONSTRAINT uq_work_order_component_uid      UNIQUE (uid),
    CONSTRAINT uq_work_order_component_line_no  UNIQUE (work_order_id, line_no),
    CONSTRAINT uq_work_order_component_leaf     UNIQUE (work_order_id, component_product_id),
    CONSTRAINT fk_work_order_component_wo       FOREIGN KEY (work_order_id)        REFERENCES work_orders (id),
    CONSTRAINT fk_work_order_component_company  FOREIGN KEY (company_id)           REFERENCES companies (id),
    CONSTRAINT fk_work_order_component_product  FOREIGN KEY (component_product_id) REFERENCES products (id),
    CONSTRAINT chk_work_order_component_planned CHECK (planned_qty >= 0),
    CONSTRAINT chk_work_order_component_issued  CHECK (issued_qty >= 0),
    CONSTRAINT chk_work_order_component_status  CHECK (status IN ('PLANNED','PARTIAL','ISSUED'))
);

-- ============================================================================
-- (1c) work_order_operations — optional routing (D-3)
-- ============================================================================
CREATE TABLE work_order_operations (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                         VARCHAR(26)      NOT NULL,
    work_order_id               BIGINT           NOT NULL,
    company_id                  BIGINT           NOT NULL,
    seq_no                      SMALLINT         NOT NULL,
    description                 VARCHAR(200)     NOT NULL,
    work_centre                 VARCHAR(80),
    labour_amount               NUMERIC(19,4)    NOT NULL DEFAULT 0,
    overhead_amount             NUMERIC(19,4)    NOT NULL DEFAULT 0,
    applied                     BOOLEAN          NOT NULL DEFAULT false,
    version                     BIGINT           NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by                  BIGINT,
    updated_at                  TIMESTAMPTZ,
    updated_by                  BIGINT,
    CONSTRAINT uq_work_order_operation_uid      UNIQUE (uid),
    CONSTRAINT uq_work_order_operation_seq      UNIQUE (work_order_id, seq_no),
    CONSTRAINT fk_work_order_operation_wo       FOREIGN KEY (work_order_id)  REFERENCES work_orders (id),
    CONSTRAINT fk_work_order_operation_company  FOREIGN KEY (company_id)     REFERENCES companies (id),
    CONSTRAINT chk_work_order_operation_labour  CHECK (labour_amount >= 0),
    CONSTRAINT chk_work_order_operation_overhead CHECK (overhead_amount >= 0)
);

-- ============================================================================
-- (2) Indexes (D-2/D-3)
-- ============================================================================
CREATE INDEX ix_work_orders_company   ON work_orders (company_id);
CREATE INDEX ix_work_orders_branch    ON work_orders (branch_id);
CREATE INDEX ix_work_orders_product   ON work_orders (finished_product_id);
CREATE INDEX ix_work_orders_status    ON work_orders (company_id, status);
-- Partial index for WIP recon — open-order working set (D-6)
CREATE INDEX ix_work_orders_open
    ON work_orders (company_id)
    WHERE status IN ('RELEASED','IN_PROGRESS','COMPLETED');

CREATE INDEX ix_work_order_components_wo      ON work_order_components (work_order_id);
CREATE INDEX ix_work_order_components_company ON work_order_components (company_id);
CREATE INDEX ix_work_order_components_product ON work_order_components (component_product_id);

CREATE INDEX ix_work_order_operations_wo      ON work_order_operations (work_order_id);
CREATE INDEX ix_work_order_operations_company ON work_order_operations (company_id);

-- ============================================================================
-- (3) chk_stock_movement_type widen — FULL union of ALL prior types + 4 new PRODUCTION_* types
-- Prior types through V41: V7 base + PURCHASE_RETURN (V36) + TRANSFER_OUT/IN (V39/V41)
-- New: PRODUCTION_ISSUE, PRODUCTION_RECEIPT, PRODUCTION_ISSUE_REVERSAL, PRODUCTION_RECEIPT_REVERSAL
-- ============================================================================
ALTER TABLE stock_movements
    DROP CONSTRAINT IF EXISTS chk_stock_movement_type;

ALTER TABLE stock_movements
    ADD CONSTRAINT chk_stock_movement_type CHECK (
        movement_type IN (
            -- V7 base
            'GOODS_RECEIPT','SALE_ISSUE','SALE_REVERSAL',
            'GOODS_RECEIPT_REVERSAL','ADJUSTMENT','OPENING_BALANCE',
            -- procurement-depth (ADR-0027, V36)
            'PURCHASE_RETURN',
            -- inventory-depth (ADR-0028, V39/V41): TRANSFER_OUT/IN admitted
            'TRANSFER_OUT','TRANSFER_IN',
            -- manufacturing (ADR-0035, this migration)
            'PRODUCTION_ISSUE','PRODUCTION_RECEIPT',
            'PRODUCTION_ISSUE_REVERSAL','PRODUCTION_RECEIPT_REVERSAL'
        )
    );

-- ============================================================================
-- (4) chk_gl_config_key widen — FULL union of ALL prior keys + 5 new manufacturing keys
-- Prior keys through V56: V10..V17 base + LANDED_COST_CLEARING (V34) +
--   POS_CASH_OVER/SHORT (V43) + FA keys (V46) + HR keys (V56)
-- New: WIP_INVENTORY, FINISHED_GOODS, LABOUR_APPLIED, OVERHEAD_APPLIED, MANUFACTURING_VARIANCE
-- ============================================================================
ALTER TABLE gl_configs
    DROP CONSTRAINT IF EXISTS chk_gl_config_key;

ALTER TABLE gl_configs
    ADD CONSTRAINT chk_gl_config_key CHECK (
        config_key IN (
            -- V10..V17 (base)
            'SALES_REVENUE','VAT_PAYABLE','ACCOUNTS_RECEIVABLE','CASH',
            'INVENTORY','COGS','ACCOUNTS_PAYABLE',
            'BAD_DEBT_EXPENSE','OPENING_BALANCE_EQUITY',
            'PURCHASES',
            'VAT_INPUT','VAT_DUE','WHT_PAYABLE','WHT_RECEIVABLE',
            'RETAINED_EARNINGS',
            'GRNI','STOCK_ADJUSTMENT',
            -- procurement-depth (ADR-0027, V34/V36)
            'LANDED_COST_CLEARING',
            -- sales-depth (ADR-0029, V43)
            'POS_CASH_OVER','POS_CASH_SHORT',
            -- fixed-assets (ADR-0030, V46)
            'FIXED_ASSETS','FIXED_ASSET_CLEARING','ACCUMULATED_DEPRECIATION',
            'DEPRECIATION_EXPENSE','GAIN_LOSS_ON_DISPOSAL','REVALUATION_RESERVE',
            -- HR payroll (ADR-0032, V56)
            'SALARY_EXPENSE','EMPLOYER_STATUTORY_EXPENSE',
            'PAYE_PAYABLE','NSSF_PAYABLE','WCF_PAYABLE','SDL_PAYABLE','HESLB_PAYABLE',
            'NET_WAGES_PAYABLE','EMPLOYEE_LOAN_RECEIVABLE',
            -- manufacturing (ADR-0035, this migration)
            'WIP_INVENTORY','FINISHED_GOODS',
            'LABOUR_APPLIED','OVERHEAD_APPLIED','MANUFACTURING_VARIANCE'
        )
    );

-- ============================================================================
-- (5) chk_journal_batch_source_type + chk_journal_entry_source_type widen
-- FULL union of ALL prior tokens + 4 new PRODUCTION_* tokens
-- Prior tokens through V56: V10..V17 base + AR/AP/Cash + VAT + YearEnd + Stock +
--   procurement (V34/V36) + POS_VARIANCE (V43) + FA (V46) + PAYROLL (V56)
-- New: PRODUCTION_ISSUE, PRODUCTION_RECEIPT, PRODUCTION_LABOUR, PRODUCTION_VARIANCE
-- ============================================================================
ALTER TABLE journal_batches
    DROP CONSTRAINT IF EXISTS chk_journal_batch_source_type;

ALTER TABLE journal_batches
    ADD CONSTRAINT chk_journal_batch_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT',
            'VAT_RETURN',
            'YEAR_END_CLOSE',
            'STOCK_RECEIPT','COGS','STOCK_ADJUSTMENT','OPENING_INVENTORY',
            -- procurement-depth (ADR-0027)
            'LANDED_COST','PURCHASE_RETURN',
            -- sales-depth (ADR-0029)
            'POS_VARIANCE',
            -- fixed-assets (ADR-0030)
            'FA_ACQUISITION','DEPRECIATION','FA_DISPOSAL','FA_REVALUATION',
            -- HR payroll (ADR-0032)
            'PAYROLL',
            -- manufacturing (ADR-0035)
            'PRODUCTION_ISSUE','PRODUCTION_RECEIPT','PRODUCTION_LABOUR','PRODUCTION_VARIANCE'
        )
    );

ALTER TABLE journal_entries
    DROP CONSTRAINT IF EXISTS chk_journal_entry_source_type;

ALTER TABLE journal_entries
    ADD CONSTRAINT chk_journal_entry_source_type CHECK (
        source_type IN (
            'MANUAL','SALES','SALES_REVERSAL','OPENING_BALANCE',
            'AR_RECEIPT','AR_WRITEOFF','AR_CREDIT_NOTE',
            'AP_BILL','AP_PAYMENT','AP_DEBIT_NOTE',
            'CASH_TRANSFER','CASH_DIRECT',
            'VAT_RETURN',
            'YEAR_END_CLOSE',
            'STOCK_RECEIPT','COGS','STOCK_ADJUSTMENT','OPENING_INVENTORY',
            -- procurement-depth (ADR-0027)
            'LANDED_COST','PURCHASE_RETURN',
            -- sales-depth (ADR-0029)
            'POS_VARIANCE',
            -- fixed-assets (ADR-0030)
            'FA_ACQUISITION','DEPRECIATION','FA_DISPOSAL','FA_REVALUATION',
            -- HR payroll (ADR-0032)
            'PAYROLL',
            -- manufacturing (ADR-0035)
            'PRODUCTION_ISSUE','PRODUCTION_RECEIPT','PRODUCTION_LABOUR','PRODUCTION_VARIANCE'
        )
    );
