-- V5 — Sales module: products.vat_status ALTER + tax_rates + 3 sales tables + perms.
-- Additive only. V1 (IAM) / V2 (Parties) / V3 (Products) / V4 (Units) are FROZEN.
-- Order per ADR-0008 D-14.

-- (1) Additive product VAT-status column (the one cross-module touch; safe default).
ALTER TABLE products
    ADD COLUMN vat_status VARCHAR(20) NOT NULL DEFAULT 'STANDARD';
ALTER TABLE products
    ADD CONSTRAINT chk_product_vat_status
    CHECK (vat_status IN ('STANDARD','ZERO_RATED','EXEMPT'));

-- (2) tax_rates master (D-5b)
CREATE TABLE tax_rates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)     NOT NULL,
    company_id  BIGINT          NOT NULL,
    vat_status  VARCHAR(20)     NOT NULL,
    rate        NUMERIC(9,4)    NOT NULL,
    status      VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version     BIGINT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_tax_rate_uid             UNIQUE (uid),
    CONSTRAINT uq_tax_rate_company_status  UNIQUE (company_id, vat_status),
    CONSTRAINT fk_tax_rate_company         FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_tax_rate_vat_status     CHECK (vat_status IN ('STANDARD','ZERO_RATED','EXEMPT')),
    CONSTRAINT chk_tax_rate_value          CHECK (rate >= 0 AND rate < 1)
);

-- (3) Seed tax_rates for every existing company (CROSS JOIN, deterministic seed-uid; V4 §2 pattern).
INSERT INTO tax_rates (uid, company_id, vat_status, rate, status, version, created_at)
SELECT
    'SEED' || lpad(c.id::text, 10, '0') || rpad(t.vat_status, 12, '_') AS uid,
    c.id, t.vat_status, t.rate, 'ACTIVE', 0, now()
FROM companies c
CROSS JOIN (VALUES
    ('STANDARD',   0.1800),
    ('ZERO_RATED', 0.0000),
    ('EXEMPT',     0.0000)
) AS t(vat_status, rate);

-- (4) sales_invoices (header)
CREATE TABLE sales_invoices (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    branch_id           BIGINT          NOT NULL,
    document_type       VARCHAR(20)     NOT NULL DEFAULT 'INVOICE',
    invoice_number      VARCHAR(30),
    status              VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    customer_id         BIGINT          NOT NULL,
    agent_id            BIGINT          NOT NULL,
    currency            VARCHAR(3)      NOT NULL,
    doc_discount_amount  NUMERIC(19,4),
    doc_discount_percent NUMERIC(9,4),
    net_total_amount    NUMERIC(19,4)   NOT NULL DEFAULT 0,
    vat_total_amount    NUMERIC(19,4)   NOT NULL DEFAULT 0,
    gross_total_amount  NUMERIC(19,4)   NOT NULL DEFAULT 0,
    tax_summary         JSONB,
    finalised_at        TIMESTAMPTZ,
    finalised_by        BIGINT,
    voided_at           TIMESTAMPTZ,
    voided_by           BIGINT,
    void_reason         VARCHAR(255),
    notes               VARCHAR(500),
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,
    CONSTRAINT uq_sales_invoice_uid             UNIQUE (uid),
    CONSTRAINT uq_sales_invoice_company_number  UNIQUE (company_id, invoice_number),
    CONSTRAINT fk_sales_invoice_company         FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_sales_invoice_branch          FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_sales_invoice_customer        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_sales_invoice_agent           FOREIGN KEY (agent_id)    REFERENCES agents (id),
    CONSTRAINT fk_sales_invoice_finalised_by    FOREIGN KEY (finalised_by) REFERENCES app_users (id),
    CONSTRAINT fk_sales_invoice_voided_by       FOREIGN KEY (voided_by)    REFERENCES app_users (id),
    CONSTRAINT chk_sales_invoice_doc_type       CHECK (document_type IN ('INVOICE')),
    CONSTRAINT chk_sales_invoice_status         CHECK (status IN ('DRAFT','FINALISED','VOID')),
    CONSTRAINT chk_sales_invoice_number_when_finalised
        CHECK ((status = 'DRAFT' AND invoice_number IS NULL)
            OR (status IN ('FINALISED','VOID') AND invoice_number IS NOT NULL)),
    CONSTRAINT chk_sales_invoice_doc_discount
        CHECK (doc_discount_percent IS NULL OR (doc_discount_percent >= 0 AND doc_discount_percent <= 100)),
    CONSTRAINT chk_sales_invoice_totals_nonneg
        CHECK (net_total_amount >= 0 AND vat_total_amount >= 0 AND gross_total_amount >= 0)
);

-- (5) sales_invoice_lines (child)
CREATE TABLE sales_invoice_lines (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)     NOT NULL,
    invoice_id           BIGINT          NOT NULL,
    company_id           BIGINT          NOT NULL,
    branch_id            BIGINT          NOT NULL,
    line_no              SMALLINT        NOT NULL,
    product_id           BIGINT          NOT NULL,
    product_code         VARCHAR(20)     NOT NULL,
    product_name         VARCHAR(200)    NOT NULL,
    unit_id              BIGINT          NOT NULL,
    unit_name            VARCHAR(60)     NOT NULL,
    quantity             NUMERIC(19,6)   NOT NULL,
    qty_in_base          NUMERIC(19,6)   NOT NULL,
    list_price_amount    NUMERIC(19,4)   NOT NULL,
    unit_price_amount    NUMERIC(19,4)   NOT NULL,
    price_overridden     BOOLEAN         NOT NULL DEFAULT false,
    overridden_by        BIGINT,
    line_discount_amount  NUMERIC(19,4),
    line_discount_percent NUMERIC(9,4),
    vat_status           VARCHAR(20)     NOT NULL,
    vat_rate             NUMERIC(9,4)    NOT NULL,
    net_amount           NUMERIC(19,4)   NOT NULL DEFAULT 0,
    vat_amount           NUMERIC(19,4)   NOT NULL DEFAULT 0,
    gross_amount         NUMERIC(19,4)   NOT NULL DEFAULT 0,
    currency             VARCHAR(3)      NOT NULL,
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,
    CONSTRAINT uq_sales_invoice_line_uid     UNIQUE (uid),
    CONSTRAINT uq_sales_invoice_line_no      UNIQUE (invoice_id, line_no),
    CONSTRAINT fk_sales_invoice_line_invoice FOREIGN KEY (invoice_id)    REFERENCES sales_invoices (id),
    CONSTRAINT fk_sales_invoice_line_product FOREIGN KEY (product_id)    REFERENCES products (id),
    CONSTRAINT fk_sales_invoice_line_unit    FOREIGN KEY (unit_id)       REFERENCES units_of_measure (id),
    CONSTRAINT fk_sales_invoice_line_overridden_by FOREIGN KEY (overridden_by) REFERENCES app_users (id),
    CONSTRAINT fk_sales_invoice_line_company FOREIGN KEY (company_id)    REFERENCES companies (id),
    CONSTRAINT fk_sales_invoice_line_branch  FOREIGN KEY (branch_id)     REFERENCES branches (id),
    CONSTRAINT chk_sales_invoice_line_vat_status CHECK (vat_status IN ('STANDARD','ZERO_RATED','EXEMPT')),
    CONSTRAINT chk_sales_invoice_line_qty        CHECK (quantity > 0 AND qty_in_base > 0),
    CONSTRAINT chk_sales_invoice_line_amounts    CHECK (net_amount >= 0 AND vat_amount >= 0 AND gross_amount >= 0),
    CONSTRAINT chk_sales_invoice_line_disc_pct
        CHECK (line_discount_percent IS NULL OR (line_discount_percent >= 0 AND line_discount_percent <= 100))
);

-- (6) sales_invoice_payments (child)
CREATE TABLE sales_invoice_payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           VARCHAR(26)     NOT NULL,
    invoice_id    BIGINT          NOT NULL,
    company_id    BIGINT          NOT NULL,
    branch_id     BIGINT          NOT NULL,
    tender_type   VARCHAR(20)     NOT NULL,
    amount        NUMERIC(19,4)   NOT NULL,
    currency      VARCHAR(3)      NOT NULL,
    change_amount NUMERIC(19,4),
    reference     VARCHAR(80),
    received_at   TIMESTAMPTZ     NOT NULL DEFAULT now(),
    received_by   BIGINT          NOT NULL,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by    BIGINT,
    CONSTRAINT uq_sales_invoice_payment_uid     UNIQUE (uid),
    CONSTRAINT fk_sales_invoice_payment_invoice FOREIGN KEY (invoice_id) REFERENCES sales_invoices (id),
    CONSTRAINT fk_sales_invoice_payment_by      FOREIGN KEY (received_by) REFERENCES app_users (id),
    CONSTRAINT fk_sales_invoice_payment_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_sales_invoice_payment_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT chk_sales_invoice_payment_tender CHECK (tender_type IN ('CASH','MOBILE_MONEY')),
    CONSTRAINT chk_sales_invoice_payment_amount CHECK (amount > 0),
    CONSTRAINT chk_sales_invoice_payment_change CHECK (change_amount IS NULL OR change_amount >= 0)
);

-- (7) Indexes (ADR-0008 D-15)
CREATE INDEX ix_sales_invoices_company         ON sales_invoices (company_id);
CREATE INDEX ix_sales_invoices_company_branch  ON sales_invoices (company_id, branch_id);
CREATE INDEX ix_sales_invoices_customer        ON sales_invoices (customer_id);
CREATE INDEX ix_sales_invoices_agent           ON sales_invoices (agent_id);
CREATE INDEX ix_sales_invoices_status          ON sales_invoices (company_id, status);
CREATE INDEX ix_sales_invoices_created_at      ON sales_invoices (company_id, created_at);
CREATE INDEX ix_sales_invoice_lines_invoice    ON sales_invoice_lines (invoice_id);
CREATE INDEX ix_sales_invoice_lines_product    ON sales_invoice_lines (product_id);
CREATE INDEX ix_sales_invoice_lines_company    ON sales_invoice_lines (company_id);
CREATE INDEX ix_sales_invoice_payments_invoice ON sales_invoice_payments (invoice_id);
CREATE INDEX ix_sales_invoice_payments_company ON sales_invoice_payments (company_id);
CREATE INDEX ix_tax_rates_company              ON tax_rates (company_id);

-- (8) Permission seed + additive ORG_ADMIN grant (V3 lines 208-222 pattern)
INSERT INTO permissions (code, module, description) VALUES
    ('SALES.INVOICE.VIEW',     'sales', 'View and list/search sales invoices'),
    ('SALES.INVOICE.CREATE',   'sales', 'Create and edit draft invoices; add/edit/remove lines; finalise'),
    ('SALES.INVOICE.SETTLE',   'sales', 'Take payment / record tenders against an invoice'),
    ('SALES.INVOICE.OVERRIDE', 'sales', 'Override a line unit price / non-default discount / default agent'),
    ('SALES.INVOICE.VOID',     'sales', 'Void a finalised invoice'),
    ('TAXRATE.VIEW',           'sales', 'View company VAT rates'),
    ('TAXRATE.MANAGE',         'sales', 'Maintain company VAT rates')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'ORG_ADMIN' AND p.module = 'sales'
ON CONFLICT DO NOTHING;
