-- V77 — FX/Multi-currency: currencies master + currency_rates + permissions (ADR-0036, D-1/D-2/D-7)
--
-- TRANCHE 1 — the shared foundation for all FX tranches.
--
-- (1) CREATE currencies  (global reference, NO company_id — explicitly declared stance, D-2)
-- (2) CREATE currency_rates (per-company, effective-dated, D-2)
-- (3) SEED currencies: TZS, USD, EUR, KES, GBP (OQ-FX-05 default set)
-- (4) SEED permissions: CURRENCY.MANAGE, CURRENCY.VIEW + grant to ORG_ADMIN
--
-- Rate direction (fixed convention — apply everywhere):
--   rate = units of to_currency (base) per ONE unit of from_currency (foreign)
--   base_amount = face_amount × rate
--   Example: USD→TZS rate 2500.00000000 means 1 USD = 2500 TZS.
--   NEVER invert. CurrencyConversionService is the ONLY code that applies this.
--
-- uid patterns (#12-safe, ISSUES-REGISTER #12):
--   currencies: 'CUR' || lpad(id::text, 6, '0') || code  = 3+6+3 = 12 chars (<=26), set post-insert via CTE trick
--   (currencies has NO company_id so we use the row serial id padded)
--   currency_rates: seeded by app at runtime; no migration seeds rate rows.
--   permission seeds reuse code itself (code is already <=40, uid uses substr pattern).
--
-- Additive only. V1–V76 are FROZEN. No edit to any prior migration.
-- EVERY UidEntity table carries: version BIGINT NOT NULL DEFAULT 0

-- ============================================================================
-- (1) currencies — global reference data; deliberately NO company_id (ADR-0036 D-2)
-- ============================================================================
CREATE TABLE currencies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)      NOT NULL,
    code            VARCHAR(3)       NOT NULL,
    name            VARCHAR(60)      NOT NULL,
    symbol          VARCHAR(8),
    minor_units     SMALLINT         NOT NULL,
    active          BOOLEAN          NOT NULL DEFAULT true,
    status          VARCHAR(20)      NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT           NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    CONSTRAINT uq_currency_uid     UNIQUE (uid),
    CONSTRAINT uq_currency_code    UNIQUE (code),
    CONSTRAINT chk_currency_minor_units CHECK (minor_units IN (0, 2, 3)),
    CONSTRAINT chk_currency_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- No company_id index needed (global table, lookups by code only).
CREATE INDEX ix_currencies_active ON currencies (active);

-- ============================================================================
-- (2) currency_rates — per-company, effective-dated (ADR-0036 D-2)
--
-- RATE DIRECTION: rate = units of to_currency per ONE unit of from_currency.
--   base_amount = face_amount × rate  (multiply, never divide).
--   from_currency = the foreign currency (face denomination).
--   to_currency   = company base currency in v1; stored explicitly to allow cross-rates.
-- ============================================================================
CREATE TABLE currency_rates (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)      NOT NULL,
    company_id      BIGINT           NOT NULL,
    branch_id       BIGINT,
    from_currency   VARCHAR(3)       NOT NULL,
    to_currency     VARCHAR(3)       NOT NULL,
    rate            NUMERIC(19,8)    NOT NULL,
    effective_date  DATE             NOT NULL,
    rate_type       VARCHAR(20)      NOT NULL DEFAULT 'SPOT',
    source          VARCHAR(40),
    active          BOOLEAN          NOT NULL DEFAULT true,
    version         BIGINT           NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    CONSTRAINT uq_currency_rate_uid     UNIQUE (uid),
    CONSTRAINT fk_currency_rate_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_currency_rate_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT chk_currency_rate_positive CHECK (rate > 0),
    CONSTRAINT chk_currency_rate_type    CHECK (rate_type IN ('SPOT', 'CLOSING', 'AVERAGE', 'BUDGET')),
    CONSTRAINT uq_currency_rate         UNIQUE (company_id, from_currency, to_currency, effective_date, rate_type)
);

-- Primary lookup index: as-of effective-dated lookup (ORDER BY effective_date DESC, LIMIT 1)
CREATE INDEX ix_currency_rates_lookup
    ON currency_rates (company_id, from_currency, to_currency, effective_date DESC)
    WHERE active = true;

-- ============================================================================
-- (3) SEED currencies (TZS/USD/EUR/KES/GBP per OQ-FX-05)
--   uid: 'CUR' || lpad(id::text,6,'0') || code  = 12 chars (#12-safe, no company_id component)
--   TZS minor_units=0 (ISO 4217 — TZS has no subunit in practice)
--   USD/EUR/KES/GBP minor_units=2 (cents/pence)
-- We INSERT first without uid, then UPDATE uid using the assigned id — safe #12 pattern
-- since the id is IDENTITY-generated and we need it to build the uid.
-- ============================================================================
INSERT INTO currencies (uid, code, name, symbol, minor_units, active, status, version, created_at)
VALUES
    ('CUR_PLACEHOLDER_TZS', 'TZS', 'Tanzanian Shilling',    'TSh', 0, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_USD', 'USD', 'US Dollar',              '$',   2, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_EUR', 'EUR', 'Euro',                   '€',   2, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_KES', 'KES', 'Kenyan Shilling',        'KSh', 2, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_GBP', 'GBP', 'Pound Sterling',         '£',   2, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_UGX', 'UGX', 'Ugandan Shilling',       'USh', 0, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_RWF', 'RWF', 'Rwandan Franc',          'RF',  0, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_BIF', 'BIF', 'Burundian Franc',        'Fr',  0, true, 'ACTIVE', 0, now()),
    ('CUR_PLACEHOLDER_SSP', 'SSP', 'South Sudanese Pound',   '£',   2, true, 'ACTIVE', 0, now())
ON CONFLICT (code) DO NOTHING;

-- Fix uid to the #12-safe pattern: 'CUR' || lpad(id,6,'0') || code = 3+6+3 = 12 chars
UPDATE currencies
SET    uid = 'CUR' || lpad(id::text, 6, '0') || code
WHERE  uid LIKE 'CUR_PLACEHOLDER_%';
