-- V65 — Currency enablement allow-lists: company_currency + branch_currency (ADR-0039 D-7/D-8)
--
-- Tranche 1 of ADR-0039.
--
-- (1) CREATE company_currency  — per-company enabled-currency allow-list; the default doc-currency
-- (2) CREATE branch_currency   — optional per-branch subset + branch-level default
-- (3) No back-fill of existing companies: the bootstrap seeder handles the bootstrap company
--     at startup (from BootstrapProperties); any pre-existing companies in a production upgrade
--     would be back-filled here, but this DB is dev-phase ephemeral (ADR-0039 D-10).
--
-- Invariants (service-enforced; see CurrencyEnablementServiceImpl):
--   - base_currency of the company MUST be present, active, and cannot be deactivated.
--   - is_default row must be active.
--   - branch_currency.currency_code must be in company_currency (active) for same company.
--   - currency_code must be globally currencies.active to be enabled.
--
-- uid patterns (#12-safe, ISSUES-REGISTER #12):
--   company_currency: set by @PrePersist in UidEntity (ULID — no migration seed rows).
--   branch_currency:  set by @PrePersist in UidEntity (ULID — no migration seed rows).
--
-- Dev-phase: no ADD-nullable→backfill ceremony (DB is ephemeral, ADR-0039 D-10).

-- ============================================================================
-- (1) company_currency — per-company enabled-currency allow-list (ADR-0039 D-7)
-- ============================================================================
CREATE TABLE company_currency (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)     NOT NULL,
    company_id      BIGINT          NOT NULL,
    currency_code   VARCHAR(3)      NOT NULL,
    is_default      BOOLEAN         NOT NULL DEFAULT false,
    active          BOOLEAN         NOT NULL DEFAULT true,
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_company_currency_uid      UNIQUE (uid),
    CONSTRAINT uq_company_currency          UNIQUE (company_id, currency_code),
    CONSTRAINT fk_company_currency_company  FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- Partial unique index: exactly one is_default per company (ADR-0039 D-7)
CREATE UNIQUE INDEX uq_company_currency_default
    ON company_currency (company_id)
    WHERE is_default = true;

-- Lookup indexes
CREATE INDEX ix_company_currency_company
    ON company_currency (company_id)
    WHERE active = true;

-- ============================================================================
-- (2) branch_currency — optional per-branch subset + branch default (ADR-0039 D-7)
-- ============================================================================
CREATE TABLE branch_currency (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)     NOT NULL,
    company_id      BIGINT          NOT NULL,
    branch_id       BIGINT          NOT NULL,
    currency_code   VARCHAR(3)      NOT NULL,
    is_default      BOOLEAN         NOT NULL DEFAULT false,
    active          BOOLEAN         NOT NULL DEFAULT true,
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_branch_currency_uid       UNIQUE (uid),
    CONSTRAINT uq_branch_currency           UNIQUE (branch_id, currency_code),
    CONSTRAINT fk_branch_currency_company   FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_branch_currency_branch    FOREIGN KEY (branch_id)   REFERENCES branches (id)
);

-- Partial unique index: exactly one is_default per branch (ADR-0039 D-7)
CREATE UNIQUE INDEX uq_branch_currency_default
    ON branch_currency (branch_id)
    WHERE is_default = true;

-- Lookup indexes
CREATE INDEX ix_branch_currency_branch
    ON branch_currency (branch_id)
    WHERE active = true;

CREATE INDEX ix_branch_currency_company
    ON branch_currency (company_id);
