-- V67 — D-3: Party contacts & addresses (8 child tables, uid sub-masters) +
--            sales ship-to / bill-to fields (ADR-0040 D-3).
--
-- Tables: customer_contacts, supplier_contacts, agent_contacts, other_party_contacts,
--         customer_addresses, supplier_addresses, agent_addresses, other_party_addresses
-- Alters: sales_orders, sales_invoices, deliveries

-- =============================================================================
-- CONTACTS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- customer_contacts
-- ---------------------------------------------------------------------------
CREATE TABLE customer_contacts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    customer_id      BIGINT           NOT NULL,
    contact_person   VARCHAR(160),
    phone            VARCHAR(40),
    email            VARCHAR(160),
    is_primary       BOOLEAN          NOT NULL DEFAULT false,
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_customer_contact_uid      UNIQUE (uid),
    CONSTRAINT fk_customer_contact_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_customer_contact_company  FOREIGN KEY (company_id)  REFERENCES companies (id)
);

CREATE UNIQUE INDEX uq_customer_contacts_primary
    ON customer_contacts (customer_id) WHERE is_primary;
CREATE INDEX ix_customer_contacts_customer
    ON customer_contacts (customer_id);

-- ---------------------------------------------------------------------------
-- supplier_contacts
-- ---------------------------------------------------------------------------
CREATE TABLE supplier_contacts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    supplier_id      BIGINT           NOT NULL,
    contact_person   VARCHAR(160),
    phone            VARCHAR(40),
    email            VARCHAR(160),
    is_primary       BOOLEAN          NOT NULL DEFAULT false,
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_supplier_contact_uid      UNIQUE (uid),
    CONSTRAINT fk_supplier_contact_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_contact_company  FOREIGN KEY (company_id)  REFERENCES companies (id)
);

CREATE UNIQUE INDEX uq_supplier_contacts_primary
    ON supplier_contacts (supplier_id) WHERE is_primary;
CREATE INDEX ix_supplier_contacts_supplier
    ON supplier_contacts (supplier_id);

-- ---------------------------------------------------------------------------
-- agent_contacts
-- ---------------------------------------------------------------------------
CREATE TABLE agent_contacts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    agent_id         BIGINT           NOT NULL,
    contact_person   VARCHAR(160),
    phone            VARCHAR(40),
    email            VARCHAR(160),
    is_primary       BOOLEAN          NOT NULL DEFAULT false,
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_agent_contact_uid      UNIQUE (uid),
    CONSTRAINT fk_agent_contact_agent    FOREIGN KEY (agent_id)    REFERENCES agents (id),
    CONSTRAINT fk_agent_contact_company  FOREIGN KEY (company_id)  REFERENCES companies (id)
);

CREATE UNIQUE INDEX uq_agent_contacts_primary
    ON agent_contacts (agent_id) WHERE is_primary;
CREATE INDEX ix_agent_contacts_agent
    ON agent_contacts (agent_id);

-- ---------------------------------------------------------------------------
-- other_party_contacts
-- ---------------------------------------------------------------------------
CREATE TABLE other_party_contacts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    other_party_id   BIGINT           NOT NULL,
    contact_person   VARCHAR(160),
    phone            VARCHAR(40),
    email            VARCHAR(160),
    is_primary       BOOLEAN          NOT NULL DEFAULT false,
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_other_party_contact_uid         UNIQUE (uid),
    CONSTRAINT fk_other_party_contact_op          FOREIGN KEY (other_party_id) REFERENCES other_parties (id),
    CONSTRAINT fk_other_party_contact_company     FOREIGN KEY (company_id)     REFERENCES companies (id)
);

CREATE UNIQUE INDEX uq_other_party_contacts_primary
    ON other_party_contacts (other_party_id) WHERE is_primary;
CREATE INDEX ix_other_party_contacts_op
    ON other_party_contacts (other_party_id);

-- =============================================================================
-- ADDRESSES
-- =============================================================================

-- ---------------------------------------------------------------------------
-- customer_addresses
-- ---------------------------------------------------------------------------
CREATE TABLE customer_addresses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    customer_id      BIGINT           NOT NULL,
    address_role     VARCHAR(20)      NOT NULL,
    is_default       BOOLEAN          NOT NULL DEFAULT false,
    country          VARCHAR(2),
    address_line1    VARCHAR(200),
    address_line2    VARCHAR(200),
    city             VARCHAR(100),
    region           VARCHAR(80),
    postal_code      VARCHAR(20),
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_customer_address_uid      UNIQUE (uid),
    CONSTRAINT fk_customer_address_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_customer_address_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT chk_customer_address_role    CHECK (address_role IN ('BILL_TO','SHIP_TO','GENERAL'))
);

CREATE UNIQUE INDEX uq_customer_addresses_default
    ON customer_addresses (customer_id, address_role) WHERE is_default;
CREATE INDEX ix_customer_addresses_customer
    ON customer_addresses (customer_id);

-- ---------------------------------------------------------------------------
-- supplier_addresses
-- ---------------------------------------------------------------------------
CREATE TABLE supplier_addresses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    supplier_id      BIGINT           NOT NULL,
    address_role     VARCHAR(20)      NOT NULL,
    is_default       BOOLEAN          NOT NULL DEFAULT false,
    country          VARCHAR(2),
    address_line1    VARCHAR(200),
    address_line2    VARCHAR(200),
    city             VARCHAR(100),
    region           VARCHAR(80),
    postal_code      VARCHAR(20),
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_supplier_address_uid      UNIQUE (uid),
    CONSTRAINT fk_supplier_address_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_address_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT chk_supplier_address_role    CHECK (address_role IN ('BILL_TO','SHIP_TO','GENERAL'))
);

CREATE UNIQUE INDEX uq_supplier_addresses_default
    ON supplier_addresses (supplier_id, address_role) WHERE is_default;
CREATE INDEX ix_supplier_addresses_supplier
    ON supplier_addresses (supplier_id);

-- ---------------------------------------------------------------------------
-- agent_addresses
-- ---------------------------------------------------------------------------
CREATE TABLE agent_addresses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    agent_id         BIGINT           NOT NULL,
    address_role     VARCHAR(20)      NOT NULL,
    is_default       BOOLEAN          NOT NULL DEFAULT false,
    country          VARCHAR(2),
    address_line1    VARCHAR(200),
    address_line2    VARCHAR(200),
    city             VARCHAR(100),
    region           VARCHAR(80),
    postal_code      VARCHAR(20),
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_agent_address_uid      UNIQUE (uid),
    CONSTRAINT fk_agent_address_agent    FOREIGN KEY (agent_id)    REFERENCES agents (id),
    CONSTRAINT fk_agent_address_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT chk_agent_address_role    CHECK (address_role IN ('BILL_TO','SHIP_TO','GENERAL'))
);

CREATE UNIQUE INDEX uq_agent_addresses_default
    ON agent_addresses (agent_id, address_role) WHERE is_default;
CREATE INDEX ix_agent_addresses_agent
    ON agent_addresses (agent_id);

-- ---------------------------------------------------------------------------
-- other_party_addresses
-- ---------------------------------------------------------------------------
CREATE TABLE other_party_addresses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)      NOT NULL,
    company_id       BIGINT           NOT NULL,
    other_party_id   BIGINT           NOT NULL,
    address_role     VARCHAR(20)      NOT NULL,
    is_default       BOOLEAN          NOT NULL DEFAULT false,
    country          VARCHAR(2),
    address_line1    VARCHAR(200),
    address_line2    VARCHAR(200),
    city             VARCHAR(100),
    region           VARCHAR(80),
    postal_code      VARCHAR(20),
    status           VARCHAR(32)      NOT NULL DEFAULT 'ACTIVE',
    version          BIGINT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_other_party_address_uid     UNIQUE (uid),
    CONSTRAINT fk_other_party_address_op      FOREIGN KEY (other_party_id) REFERENCES other_parties (id),
    CONSTRAINT fk_other_party_address_company FOREIGN KEY (company_id)     REFERENCES companies (id),
    CONSTRAINT chk_other_party_address_role   CHECK (address_role IN ('BILL_TO','SHIP_TO','GENERAL'))
);

CREATE UNIQUE INDEX uq_other_party_addresses_default
    ON other_party_addresses (other_party_id, address_role) WHERE is_default;
CREATE INDEX ix_other_party_addresses_op
    ON other_party_addresses (other_party_id);

-- =============================================================================
-- ALTER sales_orders — ship-to / bill-to fields
-- =============================================================================
ALTER TABLE sales_orders
    ADD COLUMN ship_to_address_id   BIGINT,
    ADD COLUMN bill_to_address_id   BIGINT,
    ADD COLUMN ship_to_address_text VARCHAR(500),
    ADD COLUMN bill_to_address_text VARCHAR(500);

-- =============================================================================
-- ALTER sales_invoices — ship-to / bill-to fields
-- =============================================================================
ALTER TABLE sales_invoices
    ADD COLUMN ship_to_address_id   BIGINT,
    ADD COLUMN bill_to_address_id   BIGINT,
    ADD COLUMN ship_to_address_text VARCHAR(500),
    ADD COLUMN bill_to_address_text VARCHAR(500);

-- =============================================================================
-- ALTER deliveries — ship-to fields
-- =============================================================================
ALTER TABLE deliveries
    ADD COLUMN ship_to_address_id   BIGINT,
    ADD COLUMN ship_to_address_text VARCHAR(500);
