-- V69 — Budgeting & Management Accounting (ADR-0034):
-- CREATE budgets (header), budget_versions (lifecycle), budget_lines (period lines).
-- Budgets CONSUME ADR-0025 dimension_values (cost_centre_value_id) — NO cost_centres table,
-- NO journal_lines change (both are ADR-0025's V27).
-- Gated by ADR-0025 V27 (dimension_values must exist before FK below).
-- All tables carry version BIGINT NOT NULL DEFAULT 0 for @Version / ddl-validate.
-- CRITICAL: budget_lines has version too (Hibernate ddl-validate requires it on UidEntity children).

-- ============================================================================
-- (1) budgets — budget header, per (company, fiscal_year, [cost_centre_value])
-- ============================================================================
CREATE TABLE budgets (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)      NOT NULL,
    company_id           BIGINT           NOT NULL,
    budget_number        VARCHAR(30)      NOT NULL,
    name                 VARCHAR(160)     NOT NULL,
    fiscal_year_id       BIGINT           NOT NULL,
    -- NULL = company-wide budget (ADR-0034 D-4a); references ADR-0025 dimension_values
    cost_centre_value_id BIGINT,
    notes                VARCHAR(500),
    version              BIGINT           NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,

    CONSTRAINT uq_budget_uid                      UNIQUE (uid),
    CONSTRAINT uq_budget_company_number           UNIQUE (company_id, budget_number),
    -- At most one budget per (company, FY, cost centre) for cost-centre-scoped budgets
    CONSTRAINT uq_budget_company_year_cc          UNIQUE (company_id, fiscal_year_id, cost_centre_value_id),
    CONSTRAINT fk_budget_company                  FOREIGN KEY (company_id)           REFERENCES companies (id),
    CONSTRAINT fk_budget_fiscal_year              FOREIGN KEY (fiscal_year_id)        REFERENCES fiscal_years (id),
    CONSTRAINT fk_budget_cost_centre_value        FOREIGN KEY (cost_centre_value_id)  REFERENCES dimension_values (id)
);

-- Partial unique: at most ONE company-wide budget per (company, FY) — Postgres NULLs are
-- distinct so the UNIQUE above doesn't guard the NULL case (ADR-0034 D-4a).
CREATE UNIQUE INDEX uq_budget_company_year_companywide
    ON budgets (company_id, fiscal_year_id)
    WHERE cost_centre_value_id IS NULL;

CREATE INDEX ix_budgets_company_year ON budgets (company_id, fiscal_year_id);

-- ============================================================================
-- (2) budget_versions — one revision, carries the lifecycle (ADR-0034 D-4b/D-5)
-- ============================================================================
CREATE TABLE budget_versions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)      NOT NULL,
    budget_id            BIGINT           NOT NULL,
    company_id           BIGINT           NOT NULL,
    fiscal_year_id       BIGINT           NOT NULL,
    -- Denormalised for the single-active-version partial unique; NULL = company-wide
    cost_centre_value_id BIGINT,
    version_no           SMALLINT         NOT NULL,
    status               VARCHAR(20)      NOT NULL DEFAULT 'DRAFT',
    label                VARCHAR(120),
    -- Self-FK: the version whose lines were copied as a seed (FR-BUD-08c)
    seeded_from_version_id BIGINT,
    submitted_at         TIMESTAMPTZ,
    submitted_by         BIGINT,
    approved_at          TIMESTAMPTZ,
    approved_by          BIGINT,
    rejected_at          TIMESTAMPTZ,
    rejected_by          BIGINT,
    superseded_at        TIMESTAMPTZ,
    decision_reason      VARCHAR(500),
    version              BIGINT           NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by           BIGINT,
    updated_at           TIMESTAMPTZ,
    updated_by           BIGINT,

    CONSTRAINT uq_budget_version_uid           UNIQUE (uid),
    CONSTRAINT uq_budget_version_no            UNIQUE (budget_id, version_no),
    CONSTRAINT chk_budget_version_status       CHECK (
        status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED','SUPERSEDED')),
    CONSTRAINT fk_budget_version_budget        FOREIGN KEY (budget_id)              REFERENCES budgets (id),
    CONSTRAINT fk_budget_version_company       FOREIGN KEY (company_id)             REFERENCES companies (id),
    CONSTRAINT fk_budget_version_fy            FOREIGN KEY (fiscal_year_id)         REFERENCES fiscal_years (id),
    CONSTRAINT fk_budget_version_cc_value      FOREIGN KEY (cost_centre_value_id)   REFERENCES dimension_values (id),
    CONSTRAINT fk_budget_version_seeded_from   FOREIGN KEY (seeded_from_version_id) REFERENCES budget_versions (id),
    CONSTRAINT fk_budget_version_submitted_by  FOREIGN KEY (submitted_by)           REFERENCES app_users (id),
    CONSTRAINT fk_budget_version_approved_by   FOREIGN KEY (approved_by)            REFERENCES app_users (id),
    CONSTRAINT fk_budget_version_rejected_by   FOREIGN KEY (rejected_by)            REFERENCES app_users (id)
);

-- THE SINGLE-ACTIVE-VERSION INVARIANT (BR-BUD-12): at most one APPROVED version per scope (ADR-0034 D-4b)
CREATE UNIQUE INDEX uq_budget_version_one_approved
    ON budget_versions (company_id, fiscal_year_id, cost_centre_value_id)
    WHERE status = 'APPROVED';

-- Guarding company-wide (cost_centre_value_id IS NULL) separately — Postgres treats NULLs as distinct
-- so the partial unique above does NOT cover the NULL case for company-wide budgets (ADR-0034 D-4b caveat)
CREATE UNIQUE INDEX uq_budget_version_one_approved_companywide
    ON budget_versions (company_id, fiscal_year_id)
    WHERE status = 'APPROVED' AND cost_centre_value_id IS NULL;

CREATE INDEX ix_budget_versions_budget     ON budget_versions (budget_id);
CREATE INDEX ix_budget_versions_active     ON budget_versions (company_id, fiscal_year_id, cost_centre_value_id)
    WHERE status = 'APPROVED';

-- ============================================================================
-- (3) budget_lines — (version, account, period, amount) per line (ADR-0034 D-4c)
-- CRITICAL: version BIGINT NOT NULL DEFAULT 0 — required by UidEntity @Version / ddl-validate.
-- The ADR notes "no @Version — lines replaced wholesale"; however UidEntity inherits @Version,
-- so the column is REQUIRED for Hibernate ddl-validate to pass.
-- ============================================================================
CREATE TABLE budget_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)      NOT NULL,
    budget_version_id   BIGINT           NOT NULL,
    company_id          BIGINT           NOT NULL,
    account_id          BIGINT           NOT NULL,
    fiscal_period_id    BIGINT           NOT NULL,
    amount              NUMERIC(19,4)    NOT NULL,
    currency            VARCHAR(3)       NOT NULL DEFAULT 'TZS',
    line_memo           VARCHAR(255),
    version             BIGINT           NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by          BIGINT,

    CONSTRAINT uq_budget_line_uid                    UNIQUE (uid),
    -- One amount per (account, period) per version (BR-BUD-04)
    CONSTRAINT uq_budget_line_version_account_period UNIQUE (budget_version_id, account_id, fiscal_period_id),
    CONSTRAINT chk_budget_line_amount                CHECK (amount >= 0),
    CONSTRAINT fk_budget_line_version                FOREIGN KEY (budget_version_id) REFERENCES budget_versions (id),
    CONSTRAINT fk_budget_line_company                FOREIGN KEY (company_id)        REFERENCES companies (id),
    CONSTRAINT fk_budget_line_account                FOREIGN KEY (account_id)        REFERENCES chart_of_accounts (id),
    CONSTRAINT fk_budget_line_period                 FOREIGN KEY (fiscal_period_id)  REFERENCES fiscal_periods (id)
);

CREATE INDEX ix_budget_lines_version         ON budget_lines (budget_version_id);
CREATE INDEX ix_budget_lines_version_account ON budget_lines (budget_version_id, account_id);
