-- V6 — Transactional outbox: domain_events + processed_events platform tables.
-- Additive only. V1 (IAM) / V2 (Parties) / V3 (Products) / V4 (Units) / V5 (Sales) are FROZEN.
-- Order per ADR-0009 D-10: domain_events → processed_events → indexes.
-- No permission seed, no code_sequence row, no data seed (ADR-0009 D-9 / D-10).

-- (1) domain_events — append-only outbox table (ADR-0009 D-2)
--     FKs to companies/branches (frozen V1). No FK to aggregate tables (cross-module scalar refs).
CREATE TABLE domain_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)     NOT NULL,
    event_type      VARCHAR(60)     NOT NULL,
    aggregate_type  VARCHAR(40)     NOT NULL,
    aggregate_id    BIGINT          NOT NULL,
    aggregate_uid   VARCHAR(26)     NOT NULL,
    company_id      BIGINT          NOT NULL,
    branch_id       BIGINT,                          -- NULLable: future company-level events
    payload         JSONB           NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    occurred_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    dispatched_at   TIMESTAMPTZ,
    attempt_count   INTEGER         NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000),
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_domain_event_uid      UNIQUE (uid),
    CONSTRAINT fk_domain_event_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_domain_event_branch   FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT chk_domain_event_status  CHECK (status IN ('PENDING','DISPATCHED','FAILED')),
    CONSTRAINT chk_domain_event_attempt CHECK (attempt_count >= 0)
);

-- (2) processed_events — consumer-side idempotency dedup marker (ADR-0009 D-6a)
--     Written in the SAME TX as the consumer's effect; uq on (consumer, event_uid) is the dedup key.
CREATE TABLE processed_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer     VARCHAR(80)     NOT NULL,
    event_uid    VARCHAR(26)     NOT NULL,
    processed_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT uq_processed_event UNIQUE (consumer, event_uid)
);

-- (3) Indexes on domain_events (ADR-0009 D-2 / D-10)
-- THE poller hot path: PENDING oldest-first. Partial keeps the index tiny as DISPATCHED rows grow.
CREATE INDEX ix_domain_events_pending
    ON domain_events (occurred_at)
    WHERE status = 'PENDING';

-- FAILED triage / dead-letter review.
CREATE INDEX ix_domain_events_failed
    ON domain_events (occurred_at)
    WHERE status = 'FAILED';

-- Replay / diagnostics by aggregate (e.g. "all events for invoice 42").
CREATE INDEX ix_domain_events_aggregate
    ON domain_events (aggregate_type, aggregate_id);

-- Tenant-scoped diagnostics.
CREATE INDEX ix_domain_events_company
    ON domain_events (company_id);
