-- V70 — POS sale idempotency (ADR-0042 D-1). Additive; no change to existing tables.
--
-- Dedup POST /api/v1/pos/sales by a client-supplied Idempotency-Key, per company.
-- RESERVE-BEFORE-PROCESS: the marker is inserted (INSERT ... ON CONFLICT DO NOTHING) inside the
-- sale's transaction BEFORE the invoice is created, so a duplicate/retry blocks on the in-flight
-- winner and then returns the original invoice — it never creates a second finalised sale.
-- invoice_uid is stamped after the invoice is created (same TX). A failed sale rolls the marker back,
-- freeing the key for a clean retry.
CREATE TABLE pos_sale_idempotency (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id   BIGINT       NOT NULL,
    idem_key     VARCHAR(80)  NOT NULL,
    invoice_uid  VARCHAR(26),                       -- the created invoice; NULL only mid-flight
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_pos_sale_idem            UNIQUE (company_id, idem_key),
    CONSTRAINT fk_pos_sale_idem_company    FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- Tenant-scoped diagnostics / retention purge.
CREATE INDEX ix_pos_sale_idem_company ON pos_sale_idempotency (company_id);
