-- ============================================================================
-- V73 — embedded weight/price barcode support (ADR-0044 D-1a / BR-9)
-- ============================================================================
-- Deli/produce/butchery scale labels are EAN-13 "type-2" barcodes whose trailing
-- digits carry an embedded WEIGHT or PRICE — so the full string varies per package
-- and never matches a stored barcode (the exact-match lookup 404s). This adds:
--   (a) two new barcode_type values for such labels;
--   (b) per-company symbology rules describing how to decode them (prefix, item-code
--       offset, embedded-value offset/decimals).
-- Both changes are additive (a superset CHECK widen + a new empty table), so they
-- apply cleanly onto populated tables (ADR-0043).

-- (a) widen product_barcodes types — superset of the V3 constraint (existing rows pass)
ALTER TABLE product_barcodes
    DROP CONSTRAINT IF EXISTS chk_product_barcode_type;

ALTER TABLE product_barcodes
    ADD CONSTRAINT chk_product_barcode_type
        CHECK (barcode_type IN ('EAN','UPC','CODE128','OTHER','EMBEDDED_WEIGHT','EMBEDDED_PRICE'));

-- (b) per-company rules for decoding variable-digit (type-2) labels
CREATE TABLE barcode_symbology_rules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)  NOT NULL,
    company_id       BIGINT       NOT NULL,
    code             VARCHAR(40)  NOT NULL,
    name             VARCHAR(120) NOT NULL,
    prefix           VARCHAR(8)   NOT NULL,                   -- leading digits selecting this rule (e.g. '21','02')
    value_kind       VARCHAR(10)  NOT NULL,                   -- WEIGHT | PRICE (what the embedded field encodes)
    item_code_start  SMALLINT     NOT NULL,                   -- 0-based offset of the item code within the barcode
    item_code_length SMALLINT     NOT NULL,
    value_start      SMALLINT     NOT NULL,                   -- 0-based offset of the embedded value
    value_length     SMALLINT     NOT NULL,
    value_decimals   SMALLINT     NOT NULL DEFAULT 0,         -- implied decimals (weight grams->3, price->2)
    item_match       VARCHAR(16)  NOT NULL DEFAULT 'BARCODE', -- BARCODE | PRODUCT_CODE (how the item code resolves)
    check_digit_mode VARCHAR(16),                             -- NULL = none (v1); reserved for label check-digit variants
    priority         INT          NOT NULL DEFAULT 100,       -- lower = higher precedence on overlapping prefixes
    status           VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_barcode_symbology_rule_uid     UNIQUE (uid),
    CONSTRAINT uq_barcode_symbology_rule_code    UNIQUE (company_id, code),
    CONSTRAINT fk_barcode_symbology_rule_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT chk_barcode_symbology_value_kind  CHECK (value_kind IN ('WEIGHT','PRICE')),
    CONSTRAINT chk_barcode_symbology_item_match  CHECK (item_match IN ('BARCODE','PRODUCT_CODE')),
    CONSTRAINT chk_barcode_symbology_status      CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')),
    CONSTRAINT chk_barcode_symbology_offsets     CHECK (item_code_length > 0 AND value_length > 0
                                                        AND item_code_start >= 0 AND value_start >= 0)
);

CREATE INDEX ix_barcode_symbology_rules_company ON barcode_symbology_rules (company_id);
