-- V77: explicit, non-authoritative user↔company membership.
-- A user_company row ADDS membership (used by the additive oracle in CompanyServiceImpl and
-- AppUserRepository) — it never blocks a role/branch grant and never strips access.
-- Root users bypass the oracle entirely.
--
-- Table is created empty so inline constraints are safe (no backfill required here; app-layer
-- backfill runs once on boot when the table is empty — see UserCompanyBackfill).
-- uid is assigned by UidEntity @PrePersist, never seeded in SQL.

CREATE TABLE user_company (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(26)  NOT NULL,
    user_id     BIGINT       NOT NULL  REFERENCES app_users (id),
    company_id  BIGINT       NOT NULL  REFERENCES companies (id),
    assigned_at TIMESTAMPTZ  NOT NULL  DEFAULT now(),
    assigned_by BIGINT                 REFERENCES app_users (id),
    revoked_at  TIMESTAMPTZ,           -- NULL = active (mirrors user_role)
    version     BIGINT       NOT NULL  DEFAULT 0,
    CONSTRAINT uq_user_company_uid UNIQUE (uid)
);

-- One active row per (user, company) at most.
CREATE UNIQUE INDEX uq_user_company_active
    ON user_company (user_id, company_id) WHERE revoked_at IS NULL;

CREATE INDEX ix_user_company_company ON user_company (company_id);
CREATE INDEX ix_user_company_user    ON user_company (user_id);
