-- ============================================================================
-- DEFERRED ITEM D-4: sales_settings (SO automatic approval threshold).
-- Extends the sales-order approval flow shipped in PR #189 (engine-derived,
-- no schema) with an amount-threshold gate — mirrors purchase_settings
-- (V26__purchase_requisitions.sql) / PoApprovalGate for sales orders.
-- Additive only. Depends on: companies (V1).
--
-- One row per company, created lazily by SalesSettingsServiceImpl on first
-- read/update (mirrors PurchaseSettingsServiceImpl) — NOT backfilled here
-- (owner decision 2026-06-25: provisioning over data migrations).
-- New endpoints seed SALES.SETTINGS.MANAGE in R__seed_permissions.sql
-- (+ automatic ORG_ADMIN grant via its CROSS JOIN).
-- ============================================================================

CREATE TABLE sales_settings (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                          VARCHAR(26)   NOT NULL,
    company_id                   BIGINT        NOT NULL,
    so_approval_enabled          BOOLEAN       NOT NULL DEFAULT false,
    so_approval_threshold_amount NUMERIC(19,4),                     -- SO value at/above which approval is required
    currency                     VARCHAR(3)    NOT NULL DEFAULT 'TZS',
    version                      BIGINT        NOT NULL DEFAULT 0,
    created_at                   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by                   BIGINT,
    updated_at                   TIMESTAMPTZ,
    updated_by                   BIGINT,

    CONSTRAINT uq_sales_settings_uid     UNIQUE (uid),
    CONSTRAINT uq_sales_settings_company UNIQUE (company_id),
    CONSTRAINT fk_sales_settings_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
