-- V7 — Stock module: stock_on_hand + stock_movements + permissions.
-- Additive only. V1–V6 are FROZEN (IAM/Parties/Products/Units/Sales/Outbox).
-- Order per ADR-0010 D-14: stock_on_hand → stock_movements → indexes → permission seed.
-- No code_sequence row, no data seed, no trigger, no FK into domain_events/processed_events.

-- (1) stock_on_hand — maintained current level per (company, branch, product) (ADR-0010 D-2)
--     Signed quantity; NO >= 0 CHECK (overselling allowed, BR-STOCK-03).
--     uid-addressed for the reorder-level edit (D-11); natural key = uq_stock_on_hand_scope.
CREATE TABLE stock_on_hand (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           VARCHAR(26)     NOT NULL,
    company_id    BIGINT          NOT NULL,
    branch_id     BIGINT          NOT NULL,
    product_id    BIGINT          NOT NULL,
    quantity      NUMERIC(19,6)   NOT NULL DEFAULT 0,   -- signed; NO >= 0 CHECK
    reorder_level NUMERIC(19,6),                         -- optional indicator threshold; nullable
    max_qty       NUMERIC(19,6),                         -- P2-M5: optional max-stock indicator threshold
    last_movement_at TIMESTAMPTZ,                        -- P2-M5: timestamp of last applied movement (snapshot)
    last_counted_at  TIMESTAMPTZ,                        -- P2-M5: timestamp of last physical count (snapshot)
    version       BIGINT          NOT NULL DEFAULT 0,   -- optimistic lock (NFR-STOCK-04)
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ,
    updated_by    BIGINT,
    CONSTRAINT uq_stock_on_hand_uid      UNIQUE (uid),
    CONSTRAINT uq_stock_on_hand_scope    UNIQUE (company_id, branch_id, product_id),
    CONSTRAINT fk_stock_on_hand_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_stock_on_hand_branch   FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_stock_on_hand_product  FOREIGN KEY (product_id)  REFERENCES products (id),
    -- No FK to app_users for created_by/updated_by (nullable system writes; mirrors sales pattern)
    CONSTRAINT chk_stock_on_hand_reorder CHECK (reorder_level IS NULL OR reorder_level >= 0)
    -- Deliberately NO CHECK (quantity >= 0) — overselling is allowed and flagged, never blocked
);

-- (2) stock_movements — append-only signed ledger (ADR-0010 D-4)
--     No updated_* columns (BR-STOCK-06: movements are immutable).
--     source_event_uid + source_document_* are scalar cross-module references (no FK — D-4/D-9).
CREATE TABLE stock_movements (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                  VARCHAR(26)     NOT NULL,
    company_id           BIGINT          NOT NULL,
    branch_id            BIGINT          NOT NULL,
    product_id           BIGINT          NOT NULL,
    movement_type        VARCHAR(25)     NOT NULL,
    quantity             NUMERIC(19,6)   NOT NULL,   -- signed delta; CHECK <> 0
    source_event_uid     VARCHAR(26),                -- event-driven: the domain_events.uid; NULL for manual
    source_document_type VARCHAR(40),                -- e.g. SALES_INVOICE, GOODS_RECEIPT; NULL for manual
    source_document_uid  VARCHAR(26),                -- invoice uid / receipt uid; NULL for manual
    reason_code          VARCHAR(40),                -- mandatory for ADJUSTMENT (D-7); NULL otherwise
    note                 VARCHAR(500),               -- optional free-text or anomaly note
    occurred_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by           BIGINT,                     -- operator (manual) or NULL (system/event-driven)
    CONSTRAINT uq_stock_movement_uid          UNIQUE (uid),
    -- Idempotency backstop: one (event, product) movement at most — NULLs are distinct in Postgres
    -- so the many manual movements (NULL source_event_uid) coexist; only event-driven rows are deduped.
    CONSTRAINT uq_stock_movement_source_event UNIQUE (source_event_uid, product_id),
    CONSTRAINT fk_stock_movement_company      FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_stock_movement_branch       FOREIGN KEY (branch_id)   REFERENCES branches (id),
    CONSTRAINT fk_stock_movement_product      FOREIGN KEY (product_id)  REFERENCES products (id),
    -- v1 admits the 6 built types; TRANSFER_* reserved in Java but NOT in this CHECK (OQ-STOCK-08).
    CONSTRAINT chk_stock_movement_type CHECK (
        movement_type IN (
            'GOODS_RECEIPT','SALE_ISSUE','SALE_REVERSAL',
            'GOODS_RECEIPT_REVERSAL','ADJUSTMENT','OPENING_BALANCE'
        )
    ),
    CONSTRAINT chk_stock_movement_qty CHECK (quantity <> 0),
    -- ADJUSTMENT must have a reason; no other type carries one (BR-STOCK-05, D-7)
    CONSTRAINT chk_stock_movement_reason CHECK (
        (movement_type = 'ADJUSTMENT' AND reason_code IS NOT NULL)
        OR (movement_type <> 'ADJUSTMENT' AND reason_code IS NULL)
    )
);

-- (3) Indexes on stock_on_hand (ADR-0010 D-2 / D-14)
-- The uq_stock_on_hand_scope UNIQUE already covers the (company, branch, product) upsert probe.
CREATE INDEX ix_stock_on_hand_company_branch
    ON stock_on_hand (company_id, branch_id);

CREATE INDEX ix_stock_on_hand_product
    ON stock_on_hand (product_id);

-- Partial index for fast negative-stock flag surfacing (FR-STOCK-04, D-2)
CREATE INDEX ix_stock_on_hand_negative
    ON stock_on_hand (company_id, branch_id)
    WHERE quantity < 0;

-- (4) Indexes on stock_movements (ADR-0010 D-4 / D-14)
-- THE drill-down: a product's history at a branch, chronological (FR-STOCK-11)
CREATE INDEX ix_stock_movements_product_branch
    ON stock_movements (company_id, branch_id, product_id, occurred_at);

-- Branch movement feed
CREATE INDEX ix_stock_movements_company_branch
    ON stock_movements (company_id, branch_id, occurred_at);

-- Reversal lookup: "all movements for this invoice/receipt" (OQ-STOCK-10, D-5)
CREATE INDEX ix_stock_movements_source_doc
    ON stock_movements (source_document_type, source_document_uid);
