-- ADR-0049 (D-6): EFD / fiscal-receipt persistence spine.
--
-- One row per FINALISED sales invoice, created/retried by the manual "Issue EFD receipt" action
-- (FiscalReceiptServiceImpl.issue) — decoupled from SalesInvoiceServiceImpl.finalise, which is
-- untouched. The default FiscalisationProvider (NotConfiguredFiscalisationProvider) NEVER
-- fabricates a fiscal_number; a NOT_CONFIGURED row simply records that fiscalisation was attempted
-- with no device configured. See ADR-0049 §5 for the full rationale.
--
-- Plain transactional migration — no CREATE INDEX CONCURRENTLY (this repo has no non-transactional
-- migration mode; see V78/V81 headers). fiscal_receipts is a new/empty table so the constraints +
-- index build instantly. Additive only. Depends on: companies (V1), branches (V1), sales_invoices (V5).

CREATE TABLE fiscal_receipts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)   NOT NULL,
    company_id       BIGINT        NOT NULL,
    branch_id        BIGINT        NOT NULL,
    sales_invoice_id BIGINT        NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING',   -- PENDING|ISSUED|FAILED|NOT_CONFIGURED|VOID
    provider_code    VARCHAR(30),                                -- NOT_CONFIGURED | SIMULATED | TRA_VFD (which provider produced this row)
    fiscal_number    VARCHAR(60),                                -- device receipt / verification number (ISSUED only)
    verification_url VARCHAR(500),                               -- TRA verification / QR URL (ISSUED only)
    signature        VARCHAR(512),                               -- device signature (ISSUED only)
    device_serial    VARCHAR(60),                                -- issuing device serial (ISSUED only)
    issued_at        TIMESTAMPTZ,                                -- device-reported issue time (ISSUED only)
    attempt_count    INT           NOT NULL DEFAULT 0,           -- retry diagnostics
    last_attempt_at  TIMESTAMPTZ,
    error_detail     VARCHAR(500),                               -- last failure/not-configured reason (bounded, non-leaky)
    version          BIGINT        NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,

    CONSTRAINT uq_fiscal_receipt_uid     UNIQUE (uid),
    CONSTRAINT uq_fiscal_receipt_invoice UNIQUE (sales_invoice_id),   -- one fiscal receipt per invoice
    CONSTRAINT fk_fiscal_receipt_company FOREIGN KEY (company_id)       REFERENCES companies (id),
    CONSTRAINT fk_fiscal_receipt_branch  FOREIGN KEY (branch_id)        REFERENCES branches (id),
    CONSTRAINT fk_fiscal_receipt_invoice FOREIGN KEY (sales_invoice_id) REFERENCES sales_invoices (id),
    CONSTRAINT chk_fiscal_receipt_status CHECK (status IN ('PENDING','ISSUED','FAILED','NOT_CONFIGURED','VOID'))
);

CREATE INDEX ix_fiscal_receipt_company_status ON fiscal_receipts (company_id, status);
