-- ADR-0050 (D-7 PR-A / D-7.5): end-of-day cash count against a CASH till.
--
-- Lifecycle: OPEN (expected derived from the till's book balance as-of business_date) ->
-- COUNTED (denominations recorded; counted/variance computed) -> RECONCILED (variance auto-posted
-- to GL via the existing POS_CASH_OVER/POS_CASH_SHORT accounts + a linked DIRECT_ENTRY cash_transaction
-- so the cash-book and GL move together). See ADR-0050 for the full rationale.
--
-- Plain transactional migration — no CREATE INDEX CONCURRENTLY (this repo has no non-transactional
-- migration mode; see V78/V81/V82 headers). Both tables are new/empty so constraints + indexes build
-- instantly. Additive only. Depends on: companies (V1), branches (V1), cash_bank_accounts (V13),
-- app_users (V1).

CREATE TABLE cash_counts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                VARCHAR(26)   NOT NULL,
    company_id         BIGINT        NOT NULL,
    branch_id          BIGINT        NOT NULL,
    cash_account_id    BIGINT        NOT NULL,                 -- the till (cash_bank_accounts, type CASH)
    count_number       VARCHAR(30)   NOT NULL,                 -- CC-#### per company
    counted_by         BIGINT        NOT NULL,                 -- app_users.id
    business_date      DATE          NOT NULL,
    expected_amount    NUMERIC(19,4) NOT NULL DEFAULT 0,       -- derived: till book balance as-of business_date
    counted_amount     NUMERIC(19,4) NOT NULL DEFAULT 0,       -- Σ denomination lines
    variance_amount    NUMERIC(19,4) NOT NULL DEFAULT 0,       -- counted - expected (over>0 / short<0)
    currency           VARCHAR(3)    NOT NULL DEFAULT 'TZS',
    status             VARCHAR(20)   NOT NULL DEFAULT 'OPEN',  -- OPEN|COUNTED|RECONCILED
    journal_entry_ref  VARCHAR(26),                            -- GL variance entry uid (set on RECONCILE)
    notes              VARCHAR(500),
    counted_at         TIMESTAMPTZ,
    reconciled_at      TIMESTAMPTZ,
    reconciled_by      BIGINT,
    version            BIGINT        NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by         BIGINT,
    updated_at         TIMESTAMPTZ,
    updated_by         BIGINT,

    CONSTRAINT uq_cash_count_uid        UNIQUE (uid),
    CONSTRAINT uq_cash_count_number     UNIQUE (company_id, count_number),
    CONSTRAINT fk_cash_count_company    FOREIGN KEY (company_id)      REFERENCES companies (id),
    CONSTRAINT fk_cash_count_branch     FOREIGN KEY (branch_id)       REFERENCES branches (id),
    CONSTRAINT fk_cash_count_account    FOREIGN KEY (cash_account_id) REFERENCES cash_bank_accounts (id),
    CONSTRAINT fk_cash_count_counted_by FOREIGN KEY (counted_by)      REFERENCES app_users (id),
    CONSTRAINT chk_cash_count_status    CHECK (status IN ('OPEN','COUNTED','RECONCILED'))
);
CREATE INDEX ix_cash_count_company_date ON cash_counts (company_id, branch_id, business_date);
CREATE INDEX ix_cash_count_account_date ON cash_counts (cash_account_id, business_date);
-- At most one LIVE (non-reconciled) count per till/day — a DB backstop for the service guard so a
-- variance can never post to GL/cash-book twice (D-7 review). RECONCILED counts are exempt, so a
-- corrective re-count is allowed after the first one reconciles (its expected re-derives to net 0).
CREATE UNIQUE INDEX uq_cash_count_open_per_till_date
    ON cash_counts (cash_account_id, business_date)
    WHERE status IN ('OPEN','COUNTED');

CREATE TABLE cash_count_denominations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_count_id  BIGINT        NOT NULL,
    denomination   NUMERIC(19,4) NOT NULL,
    quantity       INTEGER       NOT NULL DEFAULT 0,
    line_amount    NUMERIC(19,4) NOT NULL DEFAULT 0,           -- denomination * quantity
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by     BIGINT,

    CONSTRAINT fk_cash_count_denom_count FOREIGN KEY (cash_count_id) REFERENCES cash_counts (id),
    CONSTRAINT uq_cash_count_denom       UNIQUE (cash_count_id, denomination),
    CONSTRAINT chk_cash_count_denom_qty  CHECK (quantity >= 0),
    CONSTRAINT chk_cash_count_denom_face CHECK (denomination > 0)
);
