-- ADR-0050 (D-7 PR-B / D-7.5): petty cash imprest funds + their movements.
--
-- RECORD-ONLY this slice (D-7.1): a fund holds a float/balance; DISBURSEMENT decrements it,
-- REPLENISHMENT increments it, ADJUSTMENT applies a signed correction. Every transaction stamps
-- balance_after. NO GL leg is posted — gl_account_id captures the intended expense/funding account
-- for a manual journal (or the fast-follow ADR); journal_entry_ref is reserved and always NULL this
-- slice. See ADR-0050 for the full rationale.
--
-- amount is the SIGNED transaction amount for ADJUSTMENT (may be negative to decrease the balance,
-- must be non-zero) and a positive magnitude for DISBURSEMENT/REPLENISHMENT (direction implied by
-- txn_type) — chk_petty_cash_txn_amount enforces exactly that.
--
-- Plain transactional migration — no CREATE INDEX CONCURRENTLY (this repo has no non-transactional
-- migration mode; see V78/V81/V82/V83 headers). Both tables are new/empty so constraints + indexes
-- build instantly. Additive only. Depends on: companies (V1), branches (V1).

CREATE TABLE petty_cash_funds (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)   NOT NULL,
    company_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    code            VARCHAR(30)   NOT NULL,                    -- PCF-#### per company
    name            VARCHAR(120)  NOT NULL,
    custodian_id    BIGINT,                                    -- app_users.id (soft-FK)
    float_amount    NUMERIC(19,4) NOT NULL DEFAULT 0,          -- authorised imprest ceiling
    balance_amount  NUMERIC(19,4) NOT NULL DEFAULT 0,          -- current cash on hand
    currency        VARCHAR(3)    NOT NULL DEFAULT 'TZS',
    status          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE|INACTIVE|ARCHIVED
    version         BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_petty_cash_fund_uid     UNIQUE (uid),
    CONSTRAINT uq_petty_cash_fund_code    UNIQUE (company_id, code),
    CONSTRAINT uq_petty_cash_fund_name    UNIQUE (company_id, branch_id, name),
    CONSTRAINT fk_petty_cash_fund_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_petty_cash_fund_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT chk_petty_cash_fund_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')),
    CONSTRAINT chk_petty_cash_fund_float  CHECK (float_amount >= 0)
);

CREATE TABLE petty_cash_transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                VARCHAR(26)   NOT NULL,
    petty_cash_fund_id BIGINT        NOT NULL,
    company_id         BIGINT        NOT NULL,
    branch_id          BIGINT        NOT NULL,
    txn_number         VARCHAR(30)   NOT NULL,                 -- PC-#### per company
    txn_type           VARCHAR(20)   NOT NULL,                 -- DISBURSEMENT|REPLENISHMENT|ADJUSTMENT
    txn_date           DATE          NOT NULL,
    amount             NUMERIC(19,4) NOT NULL,                 -- signed for ADJUSTMENT; positive magnitude otherwise
    balance_after      NUMERIC(19,4) NOT NULL DEFAULT 0,       -- fund balance after this txn
    gl_account_id      BIGINT,                                 -- expense acct for a disbursement (captured; soft-FK)
    journal_entry_ref  VARCHAR(26),                            -- reserved; NULL in the record-only slice
    reference          VARCHAR(120),
    description        VARCHAR(500),
    version            BIGINT        NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by         BIGINT,
    updated_at         TIMESTAMPTZ,
    updated_by         BIGINT,

    CONSTRAINT uq_petty_cash_txn_uid     UNIQUE (uid),
    CONSTRAINT uq_petty_cash_txn_number  UNIQUE (company_id, txn_number),
    CONSTRAINT fk_petty_cash_txn_fund    FOREIGN KEY (petty_cash_fund_id) REFERENCES petty_cash_funds (id),
    CONSTRAINT fk_petty_cash_txn_company FOREIGN KEY (company_id)         REFERENCES companies (id),
    CONSTRAINT fk_petty_cash_txn_branch  FOREIGN KEY (branch_id)          REFERENCES branches (id),
    CONSTRAINT chk_petty_cash_txn_type   CHECK (txn_type IN ('DISBURSEMENT','REPLENISHMENT','ADJUSTMENT')),
    CONSTRAINT chk_petty_cash_txn_amount CHECK (amount <> 0 AND (txn_type = 'ADJUSTMENT' OR amount > 0))
);
CREATE INDEX ix_petty_cash_txn_fund_date ON petty_cash_transactions (petty_cash_fund_id, txn_date);
