-- ============================================================================
-- V85 — Deferred item D-8: van-stock reconciliation (route sales day-end worksheet).
-- ADR-0051. Additive only. LocationType.VAN already exists (no type migration).
-- Depends on: companies, branches (V1); stock_locations (V31); agents (V2); products (V3).
-- RECORD-ONLY: no GL / no stock posting (ADR-0051 D-8.2) — reconcile() only flips status and
-- emits an informational VAN.RECONCILED outbox event. New endpoints seed
-- STOCK.VAN_RECON.MANAGE/.VIEW in R__seed_permissions.sql.
-- Plain transactional — no CREATE INDEX CONCURRENTLY (agent_id add is nullable-additive on a
-- populated stock_locations table; the two new tables start empty).
-- ============================================================================

-- ============================================================================
-- (1) Bind a VAN stock-location to the route agent that runs it (nullable additive).
-- ============================================================================
ALTER TABLE stock_locations
    ADD COLUMN agent_id BIGINT NULL;
ALTER TABLE stock_locations
    ADD CONSTRAINT fk_stock_location_agent
        FOREIGN KEY (agent_id) REFERENCES agents (id);

-- At most one ACTIVE van per agent (reassignment allowed after deactivation).
CREATE UNIQUE INDEX uq_stock_location_agent_active
    ON stock_locations (agent_id)
    WHERE agent_id IS NOT NULL AND status = 'ACTIVE' AND location_type = 'VAN';

-- ============================================================================
-- (2) Day-end reconciliation worksheet for a van (header).
-- ============================================================================
CREATE TABLE van_reconciliations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)   NOT NULL,
    company_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    recon_number    VARCHAR(30)   NOT NULL,                 -- VR-#### per company
    van_location_id BIGINT        NOT NULL,                 -- stock_locations.id (VAN type)
    agent_id        BIGINT,                                 -- agents.id (route agent), nullable
    business_date   DATE          NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'OPEN',  -- OPEN|RECONCILED|CANCELLED
    notes           VARCHAR(500),
    reconciled_at   TIMESTAMPTZ,
    reconciled_by   BIGINT,
    cancelled_at    TIMESTAMPTZ,
    cancelled_by    BIGINT,
    version         BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_van_reconciliation_uid      UNIQUE (uid),
    CONSTRAINT uq_van_reconciliation_number   UNIQUE (company_id, recon_number),
    CONSTRAINT fk_van_reconciliation_company  FOREIGN KEY (company_id)      REFERENCES companies (id),
    CONSTRAINT fk_van_reconciliation_branch   FOREIGN KEY (branch_id)       REFERENCES branches (id),
    CONSTRAINT fk_van_reconciliation_location FOREIGN KEY (van_location_id) REFERENCES stock_locations (id),
    CONSTRAINT fk_van_reconciliation_agent    FOREIGN KEY (agent_id)        REFERENCES agents (id),
    CONSTRAINT chk_van_reconciliation_status  CHECK (status IN ('OPEN','RECONCILED','CANCELLED'))
);

-- One live (non-cancelled) worksheet per van per day; a fresh one is allowed after cancel.
CREATE UNIQUE INDEX uq_van_reconciliation_van_date
    ON van_reconciliations (van_location_id, business_date)
    WHERE status <> 'CANCELLED';

-- Reporting index: list/filter by company+branch+date.
CREATE INDEX ix_van_reconciliation_company_date
    ON van_reconciliations (company_id, branch_id, business_date);

-- ============================================================================
-- (3) Per-product reconciliation line.
-- expected_qty / physical_qty / variance_qty are kept as SEPARATE columns:
--   expected_qty = loaded_qty - sold_qty - returned_qty (computed, stored snapshot)
--   physical_qty = entered day-end count (NULL until entered)
--   variance_qty = physical_qty - expected_qty (computed once physical_qty is entered)
-- ============================================================================
CREATE TABLE van_reconciliation_lines (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    van_reconciliation_id BIGINT        NOT NULL,
    line_no               SMALLINT      NOT NULL,
    product_id            BIGINT        NOT NULL,
    product_code          VARCHAR(60),                       -- denormalised snapshot (immutability)
    product_name          VARCHAR(200),
    loaded_qty            NUMERIC(19,6) NOT NULL DEFAULT 0,   -- derived (TRANSFER_IN), editable
    sold_qty              NUMERIC(19,6) NOT NULL DEFAULT 0,   -- entered
    returned_qty          NUMERIC(19,6) NOT NULL DEFAULT 0,   -- derived (-TRANSFER_OUT), editable
    expected_qty          NUMERIC(19,6) NOT NULL DEFAULT 0,   -- loaded - sold - returned
    physical_qty          NUMERIC(19,6),                      -- entered day-end count (NULL until entered)
    variance_qty          NUMERIC(19,6) NOT NULL DEFAULT 0,   -- physical - expected
    unit_cost_amount      NUMERIC(19,4),                      -- snapshot avg (report only; no GL)
    variance_value        NUMERIC(19,4),                      -- variance_qty * unit_cost (report only)
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ,
    updated_by            BIGINT,

    CONSTRAINT fk_van_recon_line_recon   FOREIGN KEY (van_reconciliation_id) REFERENCES van_reconciliations (id),
    CONSTRAINT fk_van_recon_line_product FOREIGN KEY (product_id)            REFERENCES products (id),
    CONSTRAINT uq_van_recon_line         UNIQUE (van_reconciliation_id, product_id)
);

CREATE INDEX ix_van_recon_lines_recon
    ON van_reconciliation_lines (van_reconciliation_id);
