-- V8 — Purchases module: purchase_orders + purchase_order_lines + goods_receipts + goods_receipt_lines + permissions.
-- Additive only. V1–V7 are FROZEN (IAM/Parties/Products/Units/Sales/Outbox/Stock).
-- Order per ADR-0011 D-14: PO header → PO lines → GR header → GR lines → indexes → permissions.
-- No new numbering table (code_sequence entity_kinds PURCHASE_ORDER/GOODS_RECEIPT added at runtime).
-- No outbox table (V6 owns it). No FK into domain_events. No trigger. No data seed.

-- (1) purchase_orders — PO header
CREATE TABLE purchase_orders (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    order_number            VARCHAR(30),                          -- PO-####; NULL while DRAFT (ADR-0011 D-6)
    status                  VARCHAR(25)      NOT NULL DEFAULT 'DRAFT',
    supplier_id             BIGINT           NOT NULL,
    supplier_code           VARCHAR(20)      NOT NULL,            -- snapshot at order-placement
    supplier_name           VARCHAR(200)     NOT NULL,            -- snapshot at order-placement
    currency                VARCHAR(3)       NOT NULL,
    order_total_amount      NUMERIC(19,4)    NOT NULL DEFAULT 0,
    expected_date           DATE,
    notes                   VARCHAR(500),
    ordered_at              TIMESTAMPTZ,
    ordered_by              BIGINT,
    closed_at               TIMESTAMPTZ,
    closed_by               BIGINT,
    voided_at               TIMESTAMPTZ,
    voided_by               BIGINT,
    void_reason             VARCHAR(255),
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_purchase_order_uid              UNIQUE (uid),
    CONSTRAINT uq_purchase_order_company_number   UNIQUE (company_id, order_number),  -- NULLs distinct → DRAFTs coexist
    CONSTRAINT fk_purchase_order_company          FOREIGN KEY (company_id)   REFERENCES companies (id),
    CONSTRAINT fk_purchase_order_branch           FOREIGN KEY (branch_id)    REFERENCES branches (id),
    CONSTRAINT fk_purchase_order_supplier         FOREIGN KEY (supplier_id)  REFERENCES suppliers (id),
    CONSTRAINT fk_purchase_order_ordered_by       FOREIGN KEY (ordered_by)   REFERENCES app_users (id),
    CONSTRAINT fk_purchase_order_closed_by        FOREIGN KEY (closed_by)    REFERENCES app_users (id),
    CONSTRAINT fk_purchase_order_voided_by        FOREIGN KEY (voided_by)    REFERENCES app_users (id),
    CONSTRAINT chk_purchase_order_status          CHECK (status IN ('DRAFT','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CLOSED','VOID')),
    CONSTRAINT chk_purchase_order_number_when_ordered
        CHECK ((status = 'DRAFT' AND order_number IS NULL)
            OR (status <> 'DRAFT' AND order_number IS NOT NULL)),
    CONSTRAINT chk_purchase_order_total_nonneg    CHECK (order_total_amount >= 0)
);

-- (2) purchase_order_lines — child of purchase_orders
CREATE TABLE purchase_order_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    purchase_order_id       BIGINT           NOT NULL,
    company_id              BIGINT           NOT NULL,            -- denormalised from header (tenant predicate)
    branch_id               BIGINT           NOT NULL,            -- denormalised from header
    line_no                 SMALLINT         NOT NULL,
    product_id              BIGINT           NOT NULL,
    product_code            VARCHAR(20)      NOT NULL,            -- snapshot at order-placement
    product_name            VARCHAR(200)     NOT NULL,            -- snapshot at order-placement
    unit_id                 BIGINT           NOT NULL,
    unit_name               VARCHAR(60)      NOT NULL,            -- snapshot at order-placement
    ordered_qty             NUMERIC(19,6)    NOT NULL,
    ordered_qty_in_base     NUMERIC(19,6)    NOT NULL,            -- snapshot: ordered_qty × factor_to_base
    received_qty_in_base    NUMERIC(19,6)    NOT NULL DEFAULT 0, -- maintained cumulative received (ADR-0011 D-3)
    unit_cost_amount        NUMERIC(19,4)    NOT NULL,
    line_total_amount       NUMERIC(19,4)    NOT NULL,
    currency                VARCHAR(3)       NOT NULL,            -- denormalised document currency
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_purchase_order_line_uid     UNIQUE (uid),
    CONSTRAINT uq_purchase_order_line_no      UNIQUE (purchase_order_id, line_no),
    CONSTRAINT fk_purchase_order_line_order   FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id),
    CONSTRAINT fk_purchase_order_line_product FOREIGN KEY (product_id)        REFERENCES products (id),
    CONSTRAINT fk_purchase_order_line_unit    FOREIGN KEY (unit_id)           REFERENCES units_of_measure (id),
    CONSTRAINT fk_purchase_order_line_company FOREIGN KEY (company_id)        REFERENCES companies (id),
    CONSTRAINT fk_purchase_order_line_branch  FOREIGN KEY (branch_id)         REFERENCES branches (id),
    CONSTRAINT chk_purchase_order_line_qty    CHECK (ordered_qty > 0 AND ordered_qty_in_base > 0),
    CONSTRAINT chk_purchase_order_line_received
        CHECK (received_qty_in_base >= 0 AND received_qty_in_base <= ordered_qty_in_base),
    CONSTRAINT chk_purchase_order_line_cost   CHECK (unit_cost_amount >= 0 AND line_total_amount >= 0)
);

-- (3) goods_receipts — GR header; FK → purchase_orders
CREATE TABLE goods_receipts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    company_id              BIGINT           NOT NULL,
    branch_id               BIGINT           NOT NULL,
    purchase_order_id       BIGINT           NOT NULL,
    receipt_number          VARCHAR(30),                          -- GRN-####; NULL while DRAFT (ADR-0011 D-6)
    status                  VARCHAR(20)      NOT NULL DEFAULT 'DRAFT',
    supplier_id             BIGINT           NOT NULL,            -- inherited from PO (denormalised)
    received_at             TIMESTAMPTZ,
    received_by             BIGINT,
    voided_at               TIMESTAMPTZ,
    voided_by               BIGINT,
    void_reason             VARCHAR(255),
    notes                   VARCHAR(500),
    version                 BIGINT           NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,

    CONSTRAINT uq_goods_receipt_uid             UNIQUE (uid),
    CONSTRAINT uq_goods_receipt_company_number  UNIQUE (company_id, receipt_number),  -- NULLs distinct
    CONSTRAINT fk_goods_receipt_company         FOREIGN KEY (company_id)        REFERENCES companies (id),
    CONSTRAINT fk_goods_receipt_branch          FOREIGN KEY (branch_id)         REFERENCES branches (id),
    CONSTRAINT fk_goods_receipt_order           FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id),
    CONSTRAINT fk_goods_receipt_supplier        FOREIGN KEY (supplier_id)       REFERENCES suppliers (id),
    CONSTRAINT fk_goods_receipt_received_by     FOREIGN KEY (received_by)       REFERENCES app_users (id),
    CONSTRAINT fk_goods_receipt_voided_by       FOREIGN KEY (voided_by)         REFERENCES app_users (id),
    CONSTRAINT chk_goods_receipt_status         CHECK (status IN ('DRAFT','RECEIVED','VOID')),
    CONSTRAINT chk_goods_receipt_number_when_received
        CHECK ((status = 'DRAFT' AND receipt_number IS NULL)
            OR (status IN ('RECEIVED','VOID') AND receipt_number IS NOT NULL))
);

-- (4) goods_receipt_lines — child of goods_receipts; FK → purchase_order_lines
CREATE TABLE goods_receipt_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                     VARCHAR(26)      NOT NULL,
    goods_receipt_id        BIGINT           NOT NULL,
    purchase_order_line_id  BIGINT           NOT NULL,            -- the PO line this draws down (ADR-0011 D-2)
    company_id              BIGINT           NOT NULL,            -- denormalised from header
    branch_id               BIGINT           NOT NULL,            -- denormalised from header
    line_no                 SMALLINT         NOT NULL,
    product_id              BIGINT           NOT NULL,
    product_code            VARCHAR(20)      NOT NULL,            -- snapshot (from PO line)
    product_name            VARCHAR(200)     NOT NULL,            -- snapshot
    unit_id                 BIGINT           NOT NULL,
    unit_name               VARCHAR(60)      NOT NULL,            -- snapshot
    received_qty            NUMERIC(19,6)    NOT NULL,
    qty_in_base             NUMERIC(19,6)    NOT NULL,            -- snapshot: received × factor_to_base
    unit_cost_amount        NUMERIC(19,4)    NOT NULL,            -- inherited from PO line
    line_cost_amount        NUMERIC(19,4)    NOT NULL,            -- received_qty × unit_cost
    currency                VARCHAR(3)       NOT NULL,            -- denormalised from PO/GR header
    created_at              TIMESTAMPTZ      NOT NULL DEFAULT now(),
    created_by              BIGINT,

    CONSTRAINT uq_goods_receipt_line_uid      UNIQUE (uid),
    CONSTRAINT uq_goods_receipt_line_no       UNIQUE (goods_receipt_id, line_no),
    CONSTRAINT fk_goods_receipt_line_receipt  FOREIGN KEY (goods_receipt_id)       REFERENCES goods_receipts (id),
    CONSTRAINT fk_goods_receipt_line_po_line  FOREIGN KEY (purchase_order_line_id) REFERENCES purchase_order_lines (id),
    CONSTRAINT fk_goods_receipt_line_product  FOREIGN KEY (product_id)             REFERENCES products (id),
    CONSTRAINT fk_goods_receipt_line_unit     FOREIGN KEY (unit_id)                REFERENCES units_of_measure (id),
    CONSTRAINT fk_goods_receipt_line_company  FOREIGN KEY (company_id)             REFERENCES companies (id),
    CONSTRAINT fk_goods_receipt_line_branch   FOREIGN KEY (branch_id)              REFERENCES branches (id),
    CONSTRAINT chk_goods_receipt_line_qty     CHECK (received_qty > 0 AND qty_in_base > 0),
    CONSTRAINT chk_goods_receipt_line_cost    CHECK (unit_cost_amount >= 0 AND line_cost_amount >= 0)
);

-- (5) Indexes (ADR-0011 D-15)

-- purchase_orders
CREATE INDEX ix_purchase_orders_company        ON purchase_orders (company_id);
CREATE INDEX ix_purchase_orders_company_branch ON purchase_orders (company_id, branch_id);
CREATE INDEX ix_purchase_orders_supplier       ON purchase_orders (supplier_id);
CREATE INDEX ix_purchase_orders_status         ON purchase_orders (company_id, status);
CREATE INDEX ix_purchase_orders_created_at     ON purchase_orders (company_id, created_at);

-- purchase_order_lines
CREATE INDEX ix_purchase_order_lines_order     ON purchase_order_lines (purchase_order_id);
CREATE INDEX ix_purchase_order_lines_product   ON purchase_order_lines (product_id);
CREATE INDEX ix_purchase_order_lines_company   ON purchase_order_lines (company_id);
-- partial index over lines still outstanding (the receive-screen "what's left" probe, ADR-0011 D-3)
CREATE INDEX ix_purchase_order_lines_outstanding ON purchase_order_lines (purchase_order_id)
    WHERE received_qty_in_base < ordered_qty_in_base;

-- goods_receipts
CREATE INDEX ix_goods_receipts_company         ON goods_receipts (company_id);
CREATE INDEX ix_goods_receipts_company_branch  ON goods_receipts (company_id, branch_id);
CREATE INDEX ix_goods_receipts_order           ON goods_receipts (purchase_order_id);
CREATE INDEX ix_goods_receipts_supplier        ON goods_receipts (supplier_id);

-- goods_receipt_lines
CREATE INDEX ix_goods_receipt_lines_receipt    ON goods_receipt_lines (goods_receipt_id);
CREATE INDEX ix_goods_receipt_lines_po_line    ON goods_receipt_lines (purchase_order_line_id);
CREATE INDEX ix_goods_receipt_lines_product    ON goods_receipt_lines (product_id);
CREATE INDEX ix_goods_receipt_lines_company    ON goods_receipt_lines (company_id);
