-- ============================================================================
-- V98 — POS till-expense idempotency (product-wide defect, surfaced at Kilimanjaro 2026-08-08).
--
-- WHY: two byte-identical POSTs to /pos/sessions/uid/{uid}/expenses created TWO payout rows and
-- TWO GL journals — real money counted twice in the ledger and in the till-expense report for
-- cash that left the drawer once. Verified live during UAT (payout rows 17 and 18, 2,468 TZS
-- posted for a single 1,234 expense). The POS SALE endpoint has had an Idempotency-Key since V70;
-- the expense endpoint never did.
--
-- An interim guard already refuses a same-session repeat matched on (amount, category, reason)
-- within a short window. That closes the common double-tap but cannot close two TRULY simultaneous
-- requests, and it has to answer a legitimate retry-after-lost-response with a refusal. This table
-- closes both: the unique constraint makes the loser's insert fail deterministically, and the
-- endpoint then REPLAYS the winner's payout (200 with the original) instead of writing a second
-- one or rejecting a caller who did nothing wrong.
--
-- Mirrors V70__pos_sale_idempotency.sql exactly, including RESERVE-BEFORE-PROCESS: the marker is
-- inserted (INSERT ... ON CONFLICT DO NOTHING) inside the expense transaction BEFORE the payout is
-- written, so a duplicate blocks on the in-flight winner and then returns the original payout.
-- payout_uid is stamped after the payout is created, in the same transaction. A failed expense
-- rolls the marker back, freeing the key for a clean retry.
--
-- pos_session_id is carried (V70 has no equivalent) because a till expense is only ever meaningful
-- within a session — it makes retention purging and per-shift diagnostics possible without a join
-- through the payout.
--
-- ADDITIVE: a new table only. No existing table is altered, no backfill, no rewrite, nothing to
-- validate against existing rows. Safe on a populated database. V1..V97 remain frozen.
--
-- FOLLOW-UP (code, not schema): the endpoint must accept an Idempotency-Key header and the
-- OrbixPOS client must send a stable one per expense entry — a key regenerated on each retry
-- defeats the whole mechanism.
-- ============================================================================

CREATE TABLE pos_expense_idempotency (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT       NOT NULL,
    pos_session_id BIGINT       NOT NULL,
    idem_key       VARCHAR(80)  NOT NULL,
    payout_uid     VARCHAR(26),                      -- the recorded payout; NULL only mid-flight
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_pos_expense_idem         UNIQUE (company_id, idem_key),
    CONSTRAINT fk_pos_expense_idem_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_pos_expense_idem_session FOREIGN KEY (pos_session_id) REFERENCES pos_sessions (id)
);

-- Tenant-scoped diagnostics / retention purge (mirrors ix_pos_sale_idem_company).
CREATE INDEX ix_pos_expense_idem_company ON pos_expense_idempotency (company_id);
