-- V9 — Routes module: routes master + 3 junction tables + additive sales_invoices.route_id + permissions.
-- Additive only. V1–V8 are FROZEN (IAM/Parties/Products/Units/Sales/Outbox/Stock/Purchases).
-- Order per ADR-0012 D-13:
--   (1) routes master → (2) route_customer → (3) route_agent → (4) route_branch
--   → (5) ALTER sales_invoices → (6) indexes + partial unique → (7) permission seed + ORG_ADMIN grant.
-- No new numbering table (code_sequence entity_kind 'ROUTE' added at runtime, ADR-0012 D-7).
-- No outbox table (V6 owns it). No trigger. No data seed.

-- ---------------------------------------------------------------------------
-- (1) routes — master table
-- ---------------------------------------------------------------------------
CREATE TABLE routes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                 VARCHAR(26)     NOT NULL,
    company_id          BIGINT          NOT NULL,
    code                VARCHAR(20)     NOT NULL,
    name                VARCHAR(200)    NOT NULL,
    location_identifier VARCHAR(500),
    status              VARCHAR(32)     NOT NULL DEFAULT 'ACTIVE',
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ,
    updated_by          BIGINT,

    CONSTRAINT uq_route_uid             UNIQUE (uid),
    CONSTRAINT uq_route_company_code    UNIQUE (company_id, code),
    CONSTRAINT fk_route_company         FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_route_created_by      FOREIGN KEY (created_by) REFERENCES app_users (id),
    CONSTRAINT fk_route_updated_by      FOREIGN KEY (updated_by) REFERENCES app_users (id),
    CONSTRAINT chk_route_status         CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'))
);

-- ---------------------------------------------------------------------------
-- (2) route_customer — N:M junction (FR-ROUTE-04, ADR-0012 D-3)
-- No uid; no status/version — same-shape as customer_branch.
-- ---------------------------------------------------------------------------
CREATE TABLE route_customer (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id    BIGINT          NOT NULL,
    customer_id BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT true,  -- P3: soft-unassign flag
    unassigned_at TIMESTAMPTZ,                          -- P3: unassignment timestamp

    -- Uniqueness scoped to active rows (partial unique index below) so a soft-unassigned
    -- pair can be re-added later (P3 re-add support).
    CONSTRAINT fk_route_customer_route      FOREIGN KEY (route_id)    REFERENCES routes (id),
    CONSTRAINT fk_route_customer_customer   FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_route_customer_by         FOREIGN KEY (assigned_by)  REFERENCES app_users (id)
);

-- ** partial unique: at most one ACTIVE link per (route, customer); re-add allowed after unassign **
CREATE UNIQUE INDEX uq_route_customer_pair
    ON route_customer (route_id, customer_id) WHERE active;

-- ---------------------------------------------------------------------------
-- (3) route_agent — N:M junction, EXTERNAL agents only (FR-ROUTE-07, ADR-0012 D-4)
-- is_primary: at-most-one-primary-per-agent enforced by partial unique below.
-- ---------------------------------------------------------------------------
CREATE TABLE route_agent (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id    BIGINT          NOT NULL,
    agent_id    BIGINT          NOT NULL,
    is_primary  BOOLEAN         NOT NULL DEFAULT false,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT true,  -- P3: soft-unassign flag
    unassigned_at TIMESTAMPTZ,                          -- P3: unassignment timestamp

    -- Uniqueness scoped to active rows (partial unique index below) so a soft-unassigned
    -- pair can be re-added later (P3 re-add support).
    CONSTRAINT fk_route_agent_route     FOREIGN KEY (route_id)   REFERENCES routes (id),
    CONSTRAINT fk_route_agent_agent     FOREIGN KEY (agent_id)   REFERENCES agents (id),
    CONSTRAINT fk_route_agent_by        FOREIGN KEY (assigned_by) REFERENCES app_users (id)
);

-- ** partial unique: at most one ACTIVE link per (route, agent); re-add allowed after unassign **
CREATE UNIQUE INDEX uq_route_agent_pair
    ON route_agent (route_id, agent_id) WHERE active;

-- ---------------------------------------------------------------------------
-- (4) route_branch — N:M junction, mirrors customer_branch exactly (FR-ROUTE-11, ADR-0012 D-5)
-- ---------------------------------------------------------------------------
CREATE TABLE route_branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id    BIGINT          NOT NULL,
    branch_id   BIGINT          NOT NULL,
    assigned_at TIMESTAMPTZ     NOT NULL DEFAULT now(),
    assigned_by BIGINT          NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT true,  -- P3: soft-unassign flag
    unassigned_at TIMESTAMPTZ,                          -- P3: unassignment timestamp

    -- Uniqueness scoped to active rows (partial unique index below) so a soft-unassigned
    -- pair can be re-added later (P3 re-add support).
    CONSTRAINT fk_route_branch_route    FOREIGN KEY (route_id)   REFERENCES routes (id),
    CONSTRAINT fk_route_branch_br       FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT fk_route_branch_by       FOREIGN KEY (assigned_by) REFERENCES app_users (id)
);

-- ** partial unique: at most one ACTIVE link per (route, branch); re-add allowed after unassign **
CREATE UNIQUE INDEX uq_route_branch_pair
    ON route_branch (route_id, branch_id) WHERE active;

-- ---------------------------------------------------------------------------
-- (5) ALTER sales_invoices — additive nullable route_id (ADR-0012 D-6a)
-- Cross-module touch: placed AFTER routes exists so the FK target is present.
-- Does NOT break V5; existing rows keep route_id = NULL, which is correct.
-- ---------------------------------------------------------------------------
ALTER TABLE sales_invoices
    ADD COLUMN route_id BIGINT;

ALTER TABLE sales_invoices
    ADD CONSTRAINT fk_sales_invoice_route
    FOREIGN KEY (route_id) REFERENCES routes (id);

-- ---------------------------------------------------------------------------
-- (6) Indexes
-- ---------------------------------------------------------------------------

-- routes master: tenant + search
CREATE INDEX ix_routes_company
    ON routes (company_id);
CREATE INDEX ix_routes_company_name
    ON routes (company_id, lower(name));

-- route_customer: two-direction lookup
CREATE INDEX ix_route_customer_route    ON route_customer (route_id);
CREATE INDEX ix_route_customer_customer ON route_customer (customer_id);

-- route_agent: two-direction lookup + invoice-default lookup
CREATE INDEX ix_route_agent_route   ON route_agent (route_id);
CREATE INDEX ix_route_agent_agent   ON route_agent (agent_id);

-- ** partial unique: at-most-one primary route per agent (BR-ROUTE-04, ADR-0012 D-4) **
-- Mirrors uq_product_barcode_primary (V3) and uq_user_branch_default (V1).
CREATE UNIQUE INDEX uq_route_agent_primary
    ON route_agent (agent_id) WHERE is_primary AND active;

-- route_branch: two-direction lookup
CREATE INDEX ix_route_branch_route  ON route_branch (route_id);
CREATE INDEX ix_route_branch_branch ON route_branch (branch_id);

-- sales_invoices.route_id: partial index for future sales-by-route reporting (NFR-ROUTE-04)
CREATE INDEX ix_sales_invoices_route
    ON sales_invoices (route_id) WHERE route_id IS NOT NULL;
