import { HttpErrorResponse } from '@angular/common/http';
import { DecimalPipe } from '@angular/common';
import { Component, computed, inject, input, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AlertService } from '../../../../core/feedback/alert.service';
import { SessionStore } from '../../../../core/auth/session.store';
import { StandingOrderDto, StandingStatus } from './standing-order.model';
import { StandingOrderService } from './standing-order.service';

type LoadState = 'loading' | 'idle' | 'error';

/**
 * Standing order detail + lifecycle screen.
 * Route: /admin/standing-orders/uid/:uid
 * Guard: SALES.STANDING.VIEW
 *
 * Actions (require SALES.STANDING.MANAGE):
 *   ACTIVE  → Pause, Cancel, Trigger Now
 *   PAUSED  → Resume, Cancel
 *   CANCELLED → (read-only)
 *
 * Trigger Now generates a sales order immediately; the returned dto carries
 * the latest nextRunDate so we refresh after triggering.
 */
@Component({
  selector: 'app-standing-order-detail',
  imports: [RouterLink, DecimalPipe],
  templateUrl: './standing-order-detail.component.html',
  styleUrl: './standing-order-detail.component.scss',
})
export class StandingOrderDetailComponent {
  private readonly standingService = inject(StandingOrderService);
  private readonly alerts = inject(AlertService);
  protected readonly session = inject(SessionStore);

  readonly uid = input.required<string>();

  // ── Entity state ─────────────────────────────────────────────────────────────
  readonly entity = signal<StandingOrderDto | null>(null);
  readonly state = signal<LoadState>('loading');

  // ── Action busy / error signals ───────────────────────────────────────────────
  readonly pausing = signal(false);
  readonly pauseError = signal<string | null>(null);

  readonly resuming = signal(false);
  readonly resumeError = signal<string | null>(null);

  readonly cancelling = signal(false);
  readonly cancelError = signal<string | null>(null);

  readonly triggering = signal(false);
  readonly triggerError = signal<string | null>(null);
  /** uid of the sales order generated by the most-recent trigger. */
  readonly generatedOrderUid = signal<string | null>(null);

  // ── Permissions ──────────────────────────────────────────────────────────────
  readonly canManage = computed(() => this.session.hasPermission('SALES.STANDING.MANAGE'));

  // ── Derived status helpers ────────────────────────────────────────────────────
  readonly isActive = computed(() => this.entity()?.status === 'ACTIVE');
  readonly isPaused = computed(() => this.entity()?.status === 'PAUSED');
  readonly isCancelled = computed(() => this.entity()?.status === 'CANCELLED');

  readonly orderLabel = computed(() => this.entity()?.orderNumber ?? this.uid());

  constructor() {
    queueMicrotask(() => this.init());
  }

  private init(): void {
    this.load();
  }

  private load(): void {
    this.state.set('loading');
    this.standingService.getByUid(this.uid()).subscribe({
      next: (so) => {
        this.entity.set(so);
        this.state.set('idle');
      },
      error: () => this.state.set('error'),
    });
  }

  // ── Pause ─────────────────────────────────────────────────────────────────────

  pause(): void {
    if (this.pausing()) return;
    this.pausing.set(true);
    this.pauseError.set(null);
    this.standingService.pause(this.uid()).subscribe({
      next: () => {
        this.pausing.set(false);
        this.alerts.success('Standing order paused');
        this.load();
      },
      error: (err: unknown) => {
        this.pauseError.set(this.messageFrom(err, 'Could not pause standing order.'));
        this.pausing.set(false);
      },
    });
  }

  // ── Resume ────────────────────────────────────────────────────────────────────

  resume(): void {
    if (this.resuming()) return;
    this.resuming.set(true);
    this.resumeError.set(null);
    this.standingService.resume(this.uid()).subscribe({
      next: () => {
        this.resuming.set(false);
        this.alerts.success('Standing order resumed');
        this.load();
      },
      error: (err: unknown) => {
        this.resumeError.set(this.messageFrom(err, 'Could not resume standing order.'));
        this.resuming.set(false);
      },
    });
  }

  // ── Cancel ────────────────────────────────────────────────────────────────────

  cancel(): void {
    if (this.cancelling()) return;
    this.cancelling.set(true);
    this.cancelError.set(null);
    this.standingService.cancel(this.uid()).subscribe({
      next: () => {
        this.cancelling.set(false);
        this.alerts.success('Standing order cancelled');
        this.load();
      },
      error: (err: unknown) => {
        this.cancelError.set(this.messageFrom(err, 'Could not cancel standing order.'));
        this.cancelling.set(false);
      },
    });
  }

  // ── Trigger Now ───────────────────────────────────────────────────────────────

  triggerNow(): void {
    if (this.triggering()) return;
    this.triggering.set(true);
    this.triggerError.set(null);
    this.generatedOrderUid.set(null);
    this.standingService.triggerNow(this.uid()).subscribe({
      next: (updated) => {
        this.triggering.set(false);
        this.entity.set(updated);
        // triggerNow returns the updated StandingOrderDto; extract generated order uid from notes
        // as a hint if needed. The UI shows a success toast and the updated nextRunDate.
        this.alerts.success('Order generated — check Sales Orders for the new order');
      },
      error: (err: unknown) => {
        this.triggerError.set(this.messageFrom(err, 'Could not trigger standing order.'));
        this.triggering.set(false);
      },
    });
  }

  // ── Display helpers ───────────────────────────────────────────────────────────

  statusBadgeClass(status: StandingStatus): string {
    switch (status) {
      case 'ACTIVE': return 'text-bg-success';
      case 'PAUSED': return 'text-bg-warning';
      case 'CANCELLED': return 'text-bg-danger';
      default: return 'text-bg-secondary';
    }
  }

  private messageFrom(err: unknown, fallback: string): string {
    if (err instanceof HttpErrorResponse) {
      const errors = (err.error as { errors?: string[] })?.errors;
      if (errors?.length) return errors[0];
    }
    return fallback;
  }
}
