-- ============================================================================
-- PROPOSED — DEFERRED ITEM D-6: fiscal (EFD/VFD) receipts.
-- Assign the real V<n> (next free vs origin/develop) when this ships with the
-- fiscalisation service + device/API integration. Additive only. ADR: to be written.
-- Depends on: companies, branches (V1), sales_invoices.
--
-- The persistence spine only — the external TRA VFD/EFD device/API integration
-- is the bulk of D-6 and lives in app code. New endpoints need FISCAL.MANAGE/.VIEW
-- seeded in R__seed_permissions.sql (+ ORG_ADMIN grant).
-- ============================================================================

CREATE TABLE fiscal_receipts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid              VARCHAR(26)   NOT NULL,
    company_id       BIGINT        NOT NULL,
    branch_id        BIGINT        NOT NULL,
    sales_invoice_id BIGINT        NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING',     -- PENDING|ISSUED|FAILED|VOID
    fiscal_number    VARCHAR(60),                                  -- device receipt / verification number
    verification_url VARCHAR(500),                                 -- TRA verification / QR URL
    signature        VARCHAR(512),                                 -- device signature
    device_serial    VARCHAR(60),
    issued_at        TIMESTAMPTZ,
    error_detail     VARCHAR(500),                                 -- last failure (retry diagnostics)
    version          BIGINT        NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,

    CONSTRAINT uq_fiscal_receipt_uid     UNIQUE (uid),
    CONSTRAINT uq_fiscal_receipt_invoice UNIQUE (sales_invoice_id),   -- one fiscal receipt per invoice
    CONSTRAINT fk_fiscal_receipt_company FOREIGN KEY (company_id)       REFERENCES companies (id),
    CONSTRAINT fk_fiscal_receipt_branch  FOREIGN KEY (branch_id)        REFERENCES branches (id),
    CONSTRAINT fk_fiscal_receipt_invoice FOREIGN KEY (sales_invoice_id) REFERENCES sales_invoices (id),
    CONSTRAINT chk_fiscal_receipt_status CHECK (status IN ('PENDING','ISSUED','FAILED','VOID'))
);
