-- ============================================================================
-- PROPOSED — DEFERRED ITEM D-7 (1 of 2): end-of-day cash count.
-- Assign the real V<n> (next free vs origin/develop) when this ships with the
-- cash-count service + UI. Additive only. ADR: to be written.
-- Depends on: companies, branches, app_users (V1); cash_bank_accounts (V13, soft link).
-- New endpoints need CASH_COUNT.MANAGE/.VIEW seeded in R__seed_permissions.sql.
-- ============================================================================

-- Session header: counted vs expected, over/short variance.
CREATE TABLE cash_counts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)   NOT NULL,
    company_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    cash_account_id BIGINT,                                    -- soft-FK → cash_bank_accounts (the till); no DB FK
    counted_by      BIGINT        NOT NULL,                    -- app_users.id
    business_date   DATE          NOT NULL,
    expected_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    counted_amount  NUMERIC(19,4) NOT NULL DEFAULT 0,
    variance_amount NUMERIC(19,4) NOT NULL DEFAULT 0,          -- counted - expected (over/short)
    currency        VARCHAR(3)    NOT NULL DEFAULT 'TZS',
    status          VARCHAR(20)   NOT NULL DEFAULT 'OPEN',     -- OPEN|COUNTED|RECONCILED
    notes           VARCHAR(500),
    counted_at      TIMESTAMPTZ,
    version         BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_cash_count_uid        UNIQUE (uid),
    CONSTRAINT fk_cash_count_company    FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_cash_count_branch     FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT fk_cash_count_counted_by FOREIGN KEY (counted_by) REFERENCES app_users (id),
    CONSTRAINT chk_cash_count_status    CHECK (status IN ('OPEN','COUNTED','RECONCILED'))
);

-- Denomination breakdown (note/coin face value * quantity).
CREATE TABLE cash_count_denominations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_count_id BIGINT        NOT NULL,
    denomination  NUMERIC(19,4) NOT NULL,
    quantity      INTEGER       NOT NULL DEFAULT 0,
    line_amount   NUMERIC(19,4) NOT NULL DEFAULT 0,            -- denomination * quantity
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by    BIGINT,

    CONSTRAINT fk_cash_count_denom_count FOREIGN KEY (cash_count_id) REFERENCES cash_counts (id),
    CONSTRAINT uq_cash_count_denom       UNIQUE (cash_count_id, denomination),
    CONSTRAINT chk_cash_count_denom_qty  CHECK (quantity >= 0)
);
