-- ============================================================================
-- PROPOSED — DEFERRED ITEM D-7 (2 of 2): petty cash (float + transactions).
-- Assign the real V<n> immediately AFTER D7a. Additive only. ADR: to be written.
-- Depends on: companies, branches (V1). New endpoints need PETTY_CASH.MANAGE/.VIEW
-- seeded in R__seed_permissions.sql. Funds provisioned in app code, not Flyway.
-- ============================================================================

-- The float / imprest fund (one per branch till or purpose).
CREATE TABLE petty_cash_funds (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid            VARCHAR(26)   NOT NULL,
    company_id     BIGINT        NOT NULL,
    branch_id      BIGINT        NOT NULL,
    name           VARCHAR(120)  NOT NULL,
    custodian_id   BIGINT,                                    -- app_users.id (soft-FK)
    float_amount   NUMERIC(19,4) NOT NULL DEFAULT 0,          -- authorised imprest ceiling
    balance_amount NUMERIC(19,4) NOT NULL DEFAULT 0,          -- current cash on hand
    currency       VARCHAR(3)    NOT NULL DEFAULT 'TZS',
    status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE|INACTIVE|ARCHIVED
    version        BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,

    CONSTRAINT uq_petty_cash_fund_uid     UNIQUE (uid),
    CONSTRAINT uq_petty_cash_fund_name    UNIQUE (company_id, branch_id, name),
    CONSTRAINT fk_petty_cash_fund_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_petty_cash_fund_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT chk_petty_cash_fund_status CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'))
);

-- Disbursements / replenishments / adjustments against a fund.
CREATE TABLE petty_cash_transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid                VARCHAR(26)   NOT NULL,
    petty_cash_fund_id BIGINT        NOT NULL,
    company_id         BIGINT        NOT NULL,
    txn_type           VARCHAR(20)   NOT NULL,                -- DISBURSEMENT|REPLENISHMENT|ADJUSTMENT
    txn_date           DATE          NOT NULL,
    amount             NUMERIC(19,4) NOT NULL,
    gl_account_id      BIGINT,                                -- expense account for a disbursement (soft-FK)
    reference          VARCHAR(120),
    description        VARCHAR(500),
    version            BIGINT        NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by         BIGINT,
    updated_at         TIMESTAMPTZ,
    updated_by         BIGINT,

    CONSTRAINT uq_petty_cash_txn_uid     UNIQUE (uid),
    CONSTRAINT fk_petty_cash_txn_fund    FOREIGN KEY (petty_cash_fund_id) REFERENCES petty_cash_funds (id),
    CONSTRAINT fk_petty_cash_txn_company FOREIGN KEY (company_id)         REFERENCES companies (id),
    CONSTRAINT chk_petty_cash_txn_type   CHECK (txn_type IN ('DISBURSEMENT','REPLENISHMENT','ADJUSTMENT')),
    CONSTRAINT chk_petty_cash_txn_amount CHECK (amount > 0)
);
