-- ============================================================================
-- PROPOSED — DEFERRED ITEM D-8: van-stock reconciliation.
-- Assign the real V<n> (next free vs origin/develop) when this ships with the
-- van-reconciliation service + UI. Additive only. ADR: to be written.
-- Depends on: companies, branches (V1); stock_locations, agents, products.
--
-- The 'VAN' location_type ALREADY exists on stock_locations, so this only adds
-- the day-end reconciliation session (+lines) and an optional agent<->van link.
-- New endpoints need VAN_RECON.MANAGE/.VIEW seeded in R__seed_permissions.sql.
-- ============================================================================

-- Optional: bind a VAN stock-location to the route agent that runs it.
ALTER TABLE stock_locations
    ADD COLUMN agent_id BIGINT NULL;                          -- route agent (NULL for fixed locations)
ALTER TABLE stock_locations
    ADD CONSTRAINT fk_stock_location_agent FOREIGN KEY (agent_id) REFERENCES agents (id);

-- Day-end reconciliation session for a van.
CREATE TABLE van_reconciliations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(26)   NOT NULL,
    company_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    van_location_id BIGINT        NOT NULL,                   -- stock_locations.id (VAN type)
    agent_id        BIGINT,                                   -- agents.id (route agent)
    business_date   DATE          NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'OPEN',    -- OPEN|RECONCILED
    notes           VARCHAR(500),
    reconciled_at   TIMESTAMPTZ,
    version         BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,

    CONSTRAINT uq_van_reconciliation_uid      UNIQUE (uid),
    CONSTRAINT fk_van_reconciliation_company  FOREIGN KEY (company_id)      REFERENCES companies (id),
    CONSTRAINT fk_van_reconciliation_branch   FOREIGN KEY (branch_id)       REFERENCES branches (id),
    CONSTRAINT fk_van_reconciliation_location FOREIGN KEY (van_location_id) REFERENCES stock_locations (id),
    CONSTRAINT fk_van_reconciliation_agent    FOREIGN KEY (agent_id)        REFERENCES agents (id),
    CONSTRAINT chk_van_reconciliation_status  CHECK (status IN ('OPEN','RECONCILED'))
);

-- Per-product: loaded - sold - returned = variance.
CREATE TABLE van_reconciliation_lines (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    van_reconciliation_id BIGINT        NOT NULL,
    product_id            BIGINT        NOT NULL,
    loaded_qty            NUMERIC(19,6) NOT NULL DEFAULT 0,
    sold_qty              NUMERIC(19,6) NOT NULL DEFAULT 0,
    returned_qty          NUMERIC(19,6) NOT NULL DEFAULT 0,
    variance_qty          NUMERIC(19,6) NOT NULL DEFAULT 0,   -- loaded - sold - returned
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by            BIGINT,

    CONSTRAINT fk_van_recon_line_recon   FOREIGN KEY (van_reconciliation_id) REFERENCES van_reconciliations (id),
    CONSTRAINT fk_van_recon_line_product FOREIGN KEY (product_id)            REFERENCES products (id),
    CONSTRAINT uq_van_recon_line         UNIQUE (van_reconciliation_id, product_id)
);
